### ISSUE TITLE
glade - big sur

### ISSUE THREAD

**Issue by mumin16** [Homebrew/brew#10086]
GladeUI-Message: 20:21:44.021: Glade needs artwork; a default icon will be used for the following classes:
	GFileIcon	needs an icon named 'widget-gtk-fileicon'
	GladeInstantiableGtkBin	needs an icon named 'widget-gtk-bin'
	GtkApplicationWindow	needs an icon named 'widget-gtk-applicationwindow'
	GtkFileChooserNative	needs an icon named 'widget-gtk-filechoosernative'
	GThemedIcon	needs an icon named 'widget-gtk-themedicon'
GladeUI-Message: 20:21:44.048: No DevHelp installed on your system, devhelp feature will be disabled.
** Message: 20:21:44.555: No TLS support in GIO, Registration & User Survey disabled. (missing glib-networking package)
Assertion failed: (!surface->finished), function _cairo_surface_release_source_image, file cairo-surface.c, line 2092.
zsh: abort      glade

**Comment by vitorgalvao** [comment]
This seems to be related to the `glade` formula, so the correct repo to open a report is https://github.com/Homebrew/homebrew-core. I’ll point out three important things:

1. Use proper [code blocks](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks) when reporting issues. As it is, your issue is hard to read, parse, and understand.
2. This seems to be related to *using* the software, so a better place to complain about this [might be upstream](https://glade.gnome.org/).
3. If you do open another issue on Homebrew, please **do not ignore the template**; we need the information asked there to be able to assist. If you do not do so, your issue will likely be closed without review (as the template warns).
