### ISSUE TITLE
brew taps homebrew/cask on user typos

### ISSUE THREAD

**Issue by telemachus** [Homebrew/brew#10303]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ NA] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [NA] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install or remove a package, but I made a typo. For example:

```shell
brew install mpmtp # typo: this should be msmtp
brew rm mpmtp # same typo
```

## What happened (include command output)

<summary>Homebrew started to tap `homebrew/cask`.</summary>

<pre>

 Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'
…
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "nobodyhome".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
  </pre>

</details>

## What you expected to happen

I would expect Homebrew to say "Can't install mpmtp because there is no such formula" or "Can't remove mpmtp because it is not currently installed."

## Clarification and expansion

After seeing the questions below and doing some more experimentation, I see that there are two (probably related) issues here:

1. If you ask `brew` to install a package that does not exist (perhaps because you make a typo), `brew` will tap `homebrew/cask`. This seems to be by design: it's part of the process where `brew` goes looking for what the user asked for in other places (cask, recently deleted formulas, etc.). I don't think that this should be the default. (I'd rather be told "Did you mean a cask? If so, tap that repo, etc.") But this may be bikeshedding.
2. If you ask `brew` to remove a package that does not exist (perhaps because you make a typo) *or even a package that does exist but that you don't have installed*, `brew` will tap `homebrew/cask`. This  doesn't make sense to me: it takes a significant amount of time to tap `homebrew/cask`, but it's pointless in this case. If I run `brew remove newt`, `brew` taps `homebrew/cask` only to tell me `Error: No available formula or cask with the name "newt".` But `newt` is a formula in `homebrew-core`. There was no need to tap `homebrew/cask` in this case at all. I wonder if `brew remove` shares too much code or logic with `brew install`.
3. On my machine, `brew remove <typo>` takes a minute and a half because of the addition of `brew tap homebrew/cask`. So, I hope that it doesn't seem to be bikeshedding to want to change the default behavior for `brew remove` even if not for `brew install`.

**Comment by telemachus** [comment]
@SMillerDev Thanks for moving this, and sorry for putting it in the wrong place.

**Comment by MikeMcQuaid** [comment]
Is `mpmtp` a cask?

**Comment by carlocab** [comment]
Doesn't look like it's a cask. I think it's meant to be a typo for the formula `msmtp`? (I had to read that thrice to make sure it wasn't also a typo...)

**Comment by telemachus** [comment]
Sorry, yes: mpmtp is a typo. `brew` seems to do this if you try to install or remove a "non-existent" package via typo (or for whatever other reason).

```shell
brew rm nobodyhome
```
This has the same effect.

**Comment by fxcoudert** [comment]
I strongly second this report: I don't have the casks repo tapped, and every time I make a typo in a formula name, it wants to tap homebrew-casks. I always thought it was on purpose, but found it bad user experience.

**Comment by Rylan12** [comment]
For the sake of adding another maintainer's opinion, here are my thoughts:

> 1. If you ask `brew` to install a package that does not exist (perhaps because you make a typo), `brew` will tap `homebrew/cask`. This seems to be by design: it's part of the process where `brew` goes looking for what the user asked for in other places (cask, recently deleted formulas, etc.). I don't think that this should be the default. (I'd rather be told "Did you mean a cask? If so, tap that repo, etc.") But this may be bikeshedding.

Does the Homebrew installer tap homebrew/cask automatically?

If so, I fully agree. The fact that a user has taken the time to untap homebrew/cask shows that they don't want the repo around (and are able to add it back if needed).

If not, I think I would disagree. Casks are a full part of the Homebrew ecosystem. A user should not have to do any extra work to install a cask from a new Homebrew install. I do think it makes sense that they would be installed automatically on all mac installations (although this should probably be done in the installer rather than on a failed install). Assuming, though, that the installer doesn't tap the repo, I think this functionality is useful in that it makes installing casks a one-command process (`brew install`) rather than a two-command process (`brew tap` and `brew install`).

My opinion is that the first option (having the installer tap homebrew/cask and not having the tap be tapped on a failed install like reported here) is the better user experience. That being said, I'm sure there are more reasons explaining why things are the way they are so I can be easily persuaded that the current way is optimal.

---

That being said, an alternative solution that I wouldn't mind seeing is to have something like a `HOMEBREW_NO_TAP_CASK` environment variable. A user who really doesn't want the cask repo tapped can set this and we will never attempt to re-tap the cask repo. That gives flexibility and easy-of-use to most users while allowing those who are a little more comfortable with Homebrew to have a better experience as well.

---

> 2. If you ask `brew` to remove a package that does not exist (perhaps because you make a typo) _or even a package that does exist but that you don't have installed_, `brew` will tap `homebrew/cask`. This  doesn't make sense to me: it takes a significant amount of time to tap `homebrew/cask`, but it's pointless in this case. If I run `brew remove newt`, `brew` taps `homebrew/cask` only to tell me `Error: No available formula or cask with the name "newt".` But `newt` is a formula in *homebrew-core`. There was no need to tap `homebrew/cask`in this case at all. I wonder if`brew remove`shares too much code or logic with`brew install`.
> 3. On my machine, `brew remove <typo>` takes a minute and a half because of the addition of `brew tap homebrew/cask`. So, I hope that it doesn't seem to be bikeshedding to want to change the default behavior for `brew remove` even if not for `brew install`.

I agree, this seems rather odd. My inital reaction is to say "absolutely. uninstalling should never tap the cask repo." Again, though, I'd like to hear from someone (maybe it's @MikeMcQuaid , not sure) who knows a little bit more about why that functionality was added. It would be nice if whatever issue is solved by tapping the repo can be solved (to some extent) in a more user-friendly manner.

If not, I would again suggest having an environment variable that would have an effect here as well.

**Comment by jonchang** [comment]
I believe the idea is to automatically tap repositories in the Homebrew organization if it's required. So running `brew bundle` will automatically tap `homebrew/bundle`. The same was true for running `brew cask` but now that `brew cask` is going away in favor of `brew install --cask` and friends the behavior was preserved. I don't know whether that's a good thing or not. I personally have pretty much everything tapped so it never comes up for me, but the typo behavior does sound pretty unfriendly.

**Comment by Rylan12** [comment]
So hearing that, I think this functionality should be kept. I agree that it's important for the internal functions to Just Work when called, and it makes sense that the cask repo would be tapped when running `brew install` on something that is not a formula.

However, that doesn't really explain the issue of the cask repo being tapped on `brew uninstall`.

So maybe a better solution is an environment variable like `HOMEBREW_NO_AUTO_TAP_INTERNAL_TAPS` (that's kinda long) that, if enabled, will stop this for users who have specifically indicated that they do not want to use the other Homebrew org functionality (e.g. services, bundle, casks, etc.)

**Comment by fxcoudert** [comment]
@Rylan12 haven't they already indicated that by untapping?

**Comment by Rylan12** [comment]
> @Rylan12 haven't they already indicated that by untapping?

Oh, you know what, you're right. I guess the tricky part is differentiating between the repo not being tapped because it was never tapped vs. not being tapped because it was actively untapped.

Okay, new suggestion: if a user untaps a Homebrew org tap, we write a setting (e.g. `homebrew.caskrepountapped` to `.git/config`. Then, instead of always re-tapping in these cases, we only tap the missing taps if the setting has not been set. That also gives more flexibility if for example the user _does_ want homebrew/cask but not homebrew/services.

**Comment by carlocab** [comment]
How about `homebrew.untapped` as a `;`-separated list of repos that `brew` isn't supposed to tap automatically?

**Comment by Rylan12** [comment]
I've opened #10366 to implement the settings suggestion. Feedback is welcome!

**Comment by Rylan12** [comment]
From now on, running `brew untap homebrew/cask` (you will need to re-tap) will write the repo to a setting and we will never try to automatically install again (unless you specifically request a cask).

**Comment by telemachus** [comment]
@Rylan12 Thanks so much for taking this on and solving the issue.
