### ISSUE TITLE
Error: Failed to download resource "openjdk@11--patch"

### ISSUE THREAD

**Issue by ZhangQiJin** [Homebrew/brew#10437]
3teedeMacBook-Pro:~ 3tee$ brew install jenkins
Updating Homebrew...
Warning: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/autoconf-2.
Already downloaded: /Users/3tee/Library/Caches/Homebrew/downloads/f601e9d801a5ceb7e536b720e8e57d74e3bae6fb99f0e0c163c1f78b4b92e404--autoconf-2.69.sierra.bottle.4.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/2087f

curl: (35) Server aborted the SSL handshake
Error: Failed to download resource "openjdk@11--patch"
Download failed: https://raw.githubusercontent.com/Homebrew/formula-patches/2087f9d0/openjdk%4011/xcode12.diff

**Comment by carlocab** [comment]
Sorry, but this issue tracker is for bugs in `brew`, and this doesn't look like one. Also:

>Warning: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
