### ISSUE TITLE
`brew bump-formula-pr --write` without a valid tap

### ISSUE THREAD

**Issue by jjergus** [Homebrew/brew#10492]
**`brew config` output**

HOMEBREW_VERSION: 2.7.7-120-gd2430bc
ORIGIN: https://github.com/Homebrew/brew
HEAD: d2430bcf50d513807ab62320ff966d569afc40dc
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e4e6dc6e2b80759bcee5267ca44645eb297d88b7
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

**`brew doctor` output**

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Run a `brew bump-formula-pr` operation with the `--write` argument, which should prevent any Git operations from happening:

```
brew bump-formula-pr --write --no-audit \
  --url=https://dl.hhvm.com/source/nightlies/hhvm-nightly-2021.02.02.tar.gz \
  --sha256=ee1f6561fd453e6f50abf36591b9ec70aaa7ac11541876a8bb48af54a0470cbd \
  Formula/hhvm-nightly.rb
```

Formula file: https://github.com/hhvm/homebrew-hhvm/blob/master/Formula/hhvm-nightly.rb

**What happened (include all command output)?**

```
Error: This formula is not in a tap!
```

I think this is because of https://github.com/Homebrew/brew/commit/2901d2058aabe3610438ee4f2705a72f9b311142

I'm not sure if the change is intentional, or just forgot to account for the possible `--write` argument. If intentional, then I apologize and please close the issue, I'll find a way to work around it in our CI.

**What did you expect to happen?**

I expected the command to succeed without a valid tap, due to the `--write` argument.

It should produce a change like the first 2 lines in https://github.com/hhvm/homebrew-hhvm/commit/40bb313baf371f0344f6d7db1b46cb8a80d94df6

**Step-by-step reproduction instructions (by running `brew` commands)**

Exact command is above.

**Comment by Rylan12** [comment]
Try running with just `hhvm-nightly` (or that's an ambiguous formula name you can use `hhvm/hhvm/hhvm-nightly`) instead of a path:

```
brew bump-formula-pr --write --no-audit \
  --url=https://dl.hhvm.com/source/nightlies/hhvm-nightly-2021.02.02.tar.gz \
  --sha256=ee1f6561fd453e6f50abf36591b9ec70aaa7ac11541876a8bb48af54a0470cbd \
 hhvm-nightly
```

That being said, I think this _is_ a bug. I'll take a look.

**Comment by Rylan12** [comment]
Okay, I took some time to look it over. I think I feel okay saying that this _is_ intentional. `bump-formula-pr` is designed to be run on a formula in a tap. Part of this has to do with the checks it does about duplicate PRs and making sure it's finding the latest version. It would take some work to allow this to work on non-tap formulae, and I'm just not sure it's worth the effort as almost all cases use a tap. And, in the few cases where it doesn't, I don't think the extra features that `bump-formula-pr` provides are really that useful.

The easy solution to this is simply to run `bump-formula-pr` on a formula in a tap. If that's not an option, you're probably better off just replacing the old lines using a custom script.
