### ISSUE TITLE
Add `BOTTLE_DEFAULT_DOMAIN` to downloader mirror list if `BOTTLE_DOMAIN` is other than the default

### ISSUE THREAD

**Issue by XuehaiPan** [Homebrew/brew#10660]
**Provide a detailed description of the proposed feature**

Add `HOMEBREW_BOTTLE_DEFAULT_DOMAIN` to downloader mirror list if `HOMEBREW_BOTTLE_DOMAIN` is other than the default. The downloader may use the `HOMEBREW_BOTTLE_DEFAULT_DOMAIN` as a fallback option.

**What is the motivation for the feature?**

The `CurlDownloadStrategy` downloader downloads bottles from `HOMEBREW_BOTTLE_DOMAIN` if it is set. In order to speed up downloading, I have set `HOMEBREW_BOTTLE_DOMAIN` to `"https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles"` ([TUNA](https://mirrors.tuna.tsinghua.edu.cn/) is an open source mirror in China) in my shell profile.

A `404 not found` error occurs if the bottle is unavailable on `HOMEBREW_BOTTLE_DOMAIN`. Then `brew` tries to build formula from source and that costs a lot of time. I have to press `Ctrl+C` to stop the formula building process, then unset `HOMEBREW_BOTTLE_DOMAIN` and run `brew install` again manually.

Sometimes the bottle may be unavailable on `HOMEBREW_BOTTLE_DOMAIN`, but available on `HOMEBREW_BOTTLE_DOMAIN`. I wish to make `HOMEBREW_BOTTLE_DEFAULT_DOMAIN` as a fallback option when the resource is unavailable on `HOMEBREW_BOTTLE_DOMAIN`.

My implementation of this feature here:
```diff
diff --git a/Library/Homebrew/software_spec.rb b/Library/Homebrew/software_spec.rb
index 491eef049..4ef5510b1 100644
--- a/Library/Homebrew/software_spec.rb
+++ b/Library/Homebrew/software_spec.rb
@@ -1,15 +1,16 @@
 # typed: false
 # frozen_string_literal: true

 require "resource"
+require "download_strategy"
 require "checksum"
 require "version"
 require "options"
 require "build_options"
 require "dependency_collector"
 require "utils/bottles"
 require "patch"
 require "compilers"
 require "global"
 require "os/mac/version"
 require "extend/on_os"
@@ -291,29 +292,39 @@ class Bottle
   extend Forwardable

   attr_reader :name, :resource, :prefix, :cellar, :rebuild

-  def_delegators :resource, :url, :fetch, :verify_download_integrity
+  def_delegators :resource, :url, :verify_download_integrity
   def_delegators :resource, :cached_download, :clear_cache

   def initialize(formula, spec)
     @name = formula.name
     @resource = Resource.new
     @resource.owner = formula
     @resource.specs[:bottle] = true
     @spec = spec

     checksum, tag, cellar = spec.checksum_for(Utils::Bottles.tag)

     filename = Filename.create(formula, tag, spec.rebuild)
     @resource.url("#{spec.root_url}/#{filename.bintray}",
                   select_download_strategy(spec.root_url_specs))
+    if @resource.download_strategy == CurlDownloadStrategy && !spec.default_root_url.nil?
+      @default_url = "#{spec.default_root_url}/#{filename.bintray}"
+    end
     @resource.version = formula.pkg_version
     @resource.checksum = checksum
     @prefix = spec.prefix
     @cellar = cellar
     @rebuild = spec.rebuild
   end

+  def fetch(verify_download_integrity: true)
+    if !@default_url.nil? && !@spec.default_root_url.nil? && @resource.mirrors.exclude?(@default_url)
+      @resource.mirror(@default_url)
+    end
+    @resource.fetch(verify_download_integrity: verify_download_integrity)
+  end
+
   def compatible_locations?
     @spec.compatible_locations?
   end
@@ -339,15 +350,18 @@ class BottleSpecification
   extend T::Sig

   attr_rw :prefix, :rebuild
   attr_accessor :tap
-  attr_reader :all_tags_cellar, :checksum, :collector, :root_url_specs, :repository
+  attr_reader :all_tags_cellar, :checksum, :collector, :root_url_specs, :default_root_url, :repository

   sig { void }
   def initialize
     @rebuild = 0
     @prefix = Homebrew::DEFAULT_PREFIX
     @all_tags_cellar = Homebrew::DEFAULT_CELLAR
     @repository = Homebrew::DEFAULT_REPOSITORY
     @collector = Utils::Bottles::Collector.new
     @root_url_specs = {}
+    return if Homebrew::EnvConfig.bottle_domain == HOMEBREW_BOTTLE_DEFAULT_DOMAIN
+
+    @default_root_url = "#{HOMEBREW_BOTTLE_DEFAULT_DOMAIN}/#{Utils::Bottles::Bintray.repository(tap)}"
   end
@@ -364,9 +378,10 @@ class BottleSpecification
   def root_url(var = nil, specs = {})
     if var.nil?
       @root_url ||= "#{Homebrew::EnvConfig.bottle_domain}/#{Utils::Bottles::Bintray.repository(tap)}"
     else
       @root_url = var
       @root_url_specs.merge!(specs)
+      @default_root_url = nil
     end
   end
```

**How will the feature be relevant to at least 90% of Homebrew users?**

No. I think most Homebrew users do not set `HOMEBREW_BOTTLE_DOMAIN` (`brew` will set this variable to default if not set). This feature should only take effect when `HOMEBREW_BOTTLE_DOMAIN` is set to a value other than the default.

Many Homebrew users in China will set mirrors to speed up downloading. But sometimes, bottles, especially bottles of linuxbrew-core formulae, on these mirrors are unavailable. Becauce these mirrors are during a sync process. I think this feature will reduce a lot of troubles.

**What alternatives to the feature have been considered?**

None. Unset `HOMEBREW_BOTTLE_DOMAIN` and try again manually by user.

**Comment by Abo3zma** [comment]
‫في 20‏/02‏/2021 الساعة 12:49 م، كتب/كتبت ‏Xuehai Pan ‏<notifications@github.com>:‬

﻿
Provide a detailed description of the proposed feature

Add HOMEBREW_BOTTLE_DEFAULT_DOMAIN to downloader mirror list if HOMEBREW_BOTTLE_DOMAIN is other than the default. The downloader may use the HOMEBREW_BOTTLE_DEFAULT_DOMAIN as a fallback option.

What is the motivation for the feature?

The CurlDownloadStrategy downloader downloads bottles from HOMEBREW_BOTTLE_DOMAIN if it is set. In order to speed up downloading, I have set HOMEBREW_BOTTLE_DOMAIN to "https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles" (TUNA is an open source mirror in China) in my shell profile.
A 404 not found error occurs if the bottle is unavailable on HOMEBREW_BOTTLE_DOMAIN. Then brew tries to build formula from source and that cost a lot of time. I have to press Ctrl+C to stop the formula building process, then unset HOMEBREW_BOTTLE_DOMAIN and run brew install again manually.
Sometimes the bottle may be unavailable on HOMEBREW_BOTTLE_DOMAIN, but available on HOMEBREW_BOTTLE_DOMAIN. I wish to make HOMEBREW_BOTTLE_DEFAULT_DOMAIN as a fallback option when the resource is unavailable on HOMEBREW_BOTTLE_DOMAIN.

My implementation of this feature:

diff --git a/Library/Homebrew/software_spec.rb b/Library/Homebrew/software_spec.rb
index 491eef049..89307743f 100644
--- a/Library/Homebrew/software_spec.rb
+++ b/Library/Homebrew/software_spec.rb
@@ -2,6 +2,7 @@
 # frozen_string_literal: true
 
 require "resource"
+require "download_strategy"
 require "checksum"
 require "version"
 require "options"
@@ -307,6 +308,9 @@ class Bottle
     filename = Filename.create(formula, tag, spec.rebuild)
     @resource.url("#{spec.root_url}/#{filename.bintray}",
                   select_download_strategy(spec.root_url_specs))
+    if @resource.download_strategy == CurlDownloadStrategy && !spec.default_root_url.nil?
+      @resource.mirror(spec.default_root_url) unless @resource.mirrors.include? spec.default_root_url
+    end
     @resource.version = formula.pkg_version
     @resource.checksum = checksum
     @prefix = spec.prefix
@@ -362,8 +366,12 @@ class BottleSpecification
   end
 
   def root_url(var = nil, specs = {})
+    @default_root_url = nil
     if var.nil?
       @root_url ||= "#{Homebrew::EnvConfig.bottle_domain}/#{Utils::Bottles::Bintray.repository(tap)}"
+      if Homebrew::EnvConfig.bottle_domain != Homebrew::EnvConfig.bottle_default_domain
+        @default_root_url = "#{Homebrew::EnvConfig.bottle_default_domain}/#{Utils::Bottles::Bintray.repository(tap)}"
+      end
     else
       @root_url = var
       @root_url_specs.merge!(specs)
How will the feature be relevant to at least 90% of Homebrew users?

No. I think most Homebrew users do not set HOMEBREW_BOTTLE_DOMAIN (brew will set this variable to default if not set). This feature should only have an effect when HOMEBREW_BOTTLE_DOMAIN is set to a value other than the default.
Many Homebrew users in China will set mirrors to speed up downloading. But sometimes, bottles, especially bottles of linuxbrew-core formulae, on these mirrors are unavailable. Becauce these mirrors are during a sync process. I think this feature will reduce a lot of troubles.

What alternatives to the feature have been considered?

None. Unset HOMEBREW_BOTTLE_DOMAIN and try again manually by user.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!
