### ISSUE TITLE
Third-party tap always attempts to use master instead of default branch

### ISSUE THREAD

**Issue by strafe** [Homebrew/brew#10766]
### `brew config` output

```
HOMEBREW_VERSION: 3.0.4-8-gb024954
ORIGIN: https://github.com/Homebrew/brew
HEAD: b024954a0f203a4f439cc95eefb1180c96e943ce
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7254d2fa9b1b01351be360ed99c57e1158f7b53f
Core tap last commit: 32 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I am trying to install a formula from a third-party tap:
https://github.com/strafe/homebrew-tap/blob/master/Formula/hjkl.rb

### What happened (include all command output)?

```
$ brew install hjkl
==> Installing hjkl from strafe/tap
==> Cloning https://github.com/strafe/hjkl.git
Cloning into '/Users/adam/Library/Caches/Homebrew/hjkl--git'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
Error: Failed to download resource "hjkl"
Failure while executing; `git clone --depth 1 --branch master -c advice.detachedHead=false https://github.com/strafe/hjkl.git /Users/adam/Library/Caches/Homebrew/hjkl--git` exited with 128. Here's the output:
Cloning into '/Users/adam/Library/Caches/Homebrew/hjkl--git'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```

### What did you expect to happen?

The formula to use the default branch (main in this case).

### Step-by-step reproduction instructions (by running `brew` commands)

```
brew install strafe/tap/hjkl
```

**Comment by carlocab** [comment]
At the moment, the `url` in the formula needs to specify the branch to clone if it's not `master`. You might get a quicker fix for this particular problem if you report this issue to `strafe/tap`.

**Comment by strafe** [comment]
> At the moment, the `url` in the formula needs to specify the branch to clone if it's not `master`. You might get a quicker fix for this particular problem if you report this issue to `strafe/tap`.

Interesting... thank you! Is this a limitation of git or Homebrew? I assume it's possible git-wise, since if I do a naive `git clone` on the repository locally it has no issues.

**Comment by slhck** [comment]
Same issue here: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/74

**Comment by carlocab** [comment]
@slhck not quite the same, I think. The original issue is about cloning the correct branch when installing from a formula. The fix for that is fairly natural: the formula just needs to specify the branch.

The issue you link to is about taps renaming their default branch. This shouldn't be a problem if you tap something for the first time (this just does `git clone`, which knows how to fetch the default branch). However, it could be an issue when something you've already tapped renames their default branch.

One workaround is to do `brew untap` (you may need to pass `-f` if you have anything installed from that tap), then `brew tap` the tap again.

**Comment by carlocab** [comment]
I think the issue is that `git` doesn't quite support branch renaming fully yet.

See https://github.com/Homebrew/brew/issues/10424 for a related discussion.

**Comment by slhck** [comment]
Thanks. I see now. The discussion is open but locked and limited to collaborators? Should we file a bug report here? I don't think this issue belongs in our tap.

**Comment by carlocab** [comment]
It probably does, actually, since there's nothing `brew` can do about the fact that you've renamed your default branch. (This is for the same reason that `git` can't do anything about local clones when you've renamed your default branch.) You'll need to inform your users that they need to follow these instructions:

https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

They can find their local copy of your repo at `$(brew --repo homebrew-ffmpeg/ffmpeg)`, so they probably need to just do

```
cd $(brew --repo homebrew-ffmpeg/ffmpeg)
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by slhck** [comment]
> there's nothing brew can do about the fact that you've renamed your default branch

*I* did not rename the default branch. GitHub forced it. This is terribly bad UX. All taps will break eventually. We cannot reasonably expect users to perform these manual steps. Couldn't `brew` just check the remote branches and switch automatically if `master` is no longer there but `main` is present?

**Comment by carlocab** [comment]
How did GitHub force you to rename your default branch?

**Comment by slhck** [comment]
<img width="649" alt="Screen Shot 2021-03-20 at 08 39 29" src="https://user-images.githubusercontent.com/582444/111862793-deea7700-8957-11eb-975f-02f4919faac4.png">

It just did it without asking or notifying me.

**Comment by carlocab** [comment]
You should probably file a bug report with GitHub, then, because it shouldn't be doing that.

As for `brew` automatically switching branches: maybe. I suspect if you want that behaviour, you'll have to open a PR that implements this. I'm also inclined to think that the correct move is to wait for this to be supported in `git`, rather than jumping the gun on them, however.

**Comment by slhck** [comment]
> I'm also inclined to think that the correct move is to wait for this to be supported in git

I agree. We've reverted to `master` in the meantime until end-user facing tools support this in a transparent manner.

**Comment by strafe** [comment]
Based on this new-ish message from `git init`:
```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
```

I'd say it's no longer sufficient to Homebrew to just assume `master` is the default branch. `git clone` is able to pull the default branch without it being specified, so this behaviour should be possible in Homebrew too? Unless of course `branch:` has been used to override it.

**Comment by carlocab** [comment]
This is in progress, though it's stalled a bit recently. See #10424. `brew tap` will tap repositories whose default branches are not named master just fine.

**Comment by strafe** [comment]
> This is in progress, though it's stalled a bit recently. See #10424. `brew tap` will tap repositories whose default branches are not named master just fine, so I think it is not entirely correct to say Homebrew assumes `master` is the default branch. (It's not entirely wrong either.)

The issue states
> It's important to note that even though GitHub added the ability for users to rename branches, git still does not support this.

but `git branch -m` exists and is definitely not new? Technically `-m` is _move_ but the Git documentation refers to this as "Move/rename".

**Comment by strafe** [comment]
> This is in progress, though it's stalled a bit recently. See #10424. `brew tap` will tap repositories whose default branches are not named master just fine, so I think it is not entirely correct to say Homebrew assumes `master` is the default branch. (It's not entirely wrong either.)

This issue is actually regarding formulae inside a third party tap, not the tap itself.

**Comment by carlocab** [comment]
Yes. See:

>(It's not entirely wrong either.)

**Comment by Rylan12** [comment]
If you run `brew update` and have a tap whose upstream default branch has been renamed, you will see an error that will prompt you to run `brew tap --repair`. That command will fix the tap so that it points to the correct remote branch. You shouldn't need to un-tap and re-tap. This was added in https://github.com/Homebrew/brew/pull/10423so check there for some more discussion about that.

> I'd say it's no longer sufficient for Homebrew to just assume `master` is the default branch.

I'm not sure I agree. Currently, out of the 774 formulae that use a `*.git` stable URL in homebrew/core, there are only 21 formulae that use a non-standard branch name. Even out of these, only two are actually pointing to `main`. The rest are pointing to names such as `development`, `v1.x`, etc. Similarly, there are 2,926 formulae that define a `head` block, only 91 of which use a different branch (again, mostly not `main`).

I think the numbers here are pretty clearly saying that changing the default isn't right for Homebrew right now. In the future, I would love to see the `main` branch take precedence, but I don't think it's very likely to happen.

While not really related to this issue, I would point out that we have changed the `brew tap-new` command to use `main` by default. We'll continue to make changes like these when we can.

> `git clone` is able to pull the default branch without it being specified, so this behaviour should be possible in Homebrew too? Unless of course `branch:` has been used to override it.

I agree this would be quite helpful. I haven't looked at the code that handles this in quite a while so I don't remember off the top of my head whether this would be an easy change or not.

**Comment by slhck** [comment]
> If you run brew update and have a tap whose upstream default branch has been renamed, you will see an error that will prompt you

It doesn't seem like this was the case for what was reported in https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/74 — or is there something I'm missing?

**Comment by strafe** [comment]
> If you run `brew update` and have a tap whose upstream default branch has been renamed, you will see an error that will prompt you to run `brew tap --repair`. That command will fix the tap so that it points to the correct remote branch. You shouldn't need to un-tap and re-tap. This was added in #10423, so check there for some more discussion about that.
> 

Again this issue is not about taps themselves, but the formulae within them. I realise you may be responding to @slhck but that might fit better in an entirely new issue.
> > I'd say it's no longer sufficient for Homebrew to just assume `master` is the default branch.
> 
> I'm not sure I agree. Currently, out of the 774 formulae that use a `*.git` stable URL in homebrew/core, there are only 21 formulae that use a non-standard branch name. Even out of these, only two are actually pointing to `main`. The rest are pointing to names such as `development`, `v1.x`, etc. Similarly, there are 2,926 formulae that define a `head` block, only 91 of which use a different branch (again, mostly not `main`).
> 
> I think the numbers here are pretty clearly saying that changing the default isn't right for Homebrew right now. In the future, I would love to see the `main` branch take precedence, but I don't think it's very likely to happen.
> 
> While not really related to this issue, I would point out that we have changed the `brew tap-new` command to use `main` by default. We'll continue to make changes like these when we can.
> 

I'm not suggesting a change to `main`. Just stating it's clear that `git` is moving away from the default `master` branch and giving developers a bit more freedom when it comes to default branch naming. The numbers are small because we're so early on in this process and `master` is deeply rooted at this point. Looking to the future though, this is only going to become more of a hindrance as times goes on and people ditch `master` for `main`, `dev` or whatever else.
> > `git clone` is able to pull the default branch without it being specified, so this behaviour should be possible in Homebrew too? Unless of course `branch:` has been used to override it.
> 
> I agree this would be quite helpful. I haven't looked at the code that handles this in quite a while so I don't remember off the top of my head whether this would be an easy change or not.
> 
> The place to look is probably the [`GitDownloadStrategy`](https://github.com/Homebrew/brew/blob/7e2ba95169593366565e84bce44da28a5aefe62c/Library/Homebrew/download_strategy.rb#L756-L974) class.

That'd be great, thanks.

**Comment by Rylan12** [comment]
> It doesn't seem like this was the case for what was reported in [homebrew-ffmpeg/homebrew-ffmpeg#74](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/74) — or is there something I'm missing?

Not sure. I haven't looked at that issue closely. It's possible that it doesn't work right. If you have a specific reproducible example where it doesn't work I can take a look.

> Looking to the future though, this is only going to become more of a hindrance as times goes on and people ditch `master` for `main`, `dev` or whatever else.

It's quite a hindrance to change though. Keep in mind that making a change means we need to deprecate using `master` which will be a hindrance to any third-party tap that doesn't specify a branch. Also, I think you're overestimating the number of projects that will change to use `main`. I'd like you to be right, but I just don't see it.

Maybe the right solution is to require a branch name in all cases. That way there's never any ambiguity.

**Comment by slhck** [comment]
> Also, I think you're overestimating the number of projects that will change to use `main`.

Please note that the branch was changed for us automatically. I saw some other projects where this has happened. I assume this will be done to every repository eventually.

**Comment by carlocab** [comment]
GitHub definitely isn't, and shouldn't be doing that. Who has write access to your repo? Are you sure they didn't change the default branch name by mistake?

**Comment by Rylan12** [comment]
Agreed. I find it highly unusual and un-GitHub-like to change branch names without warning. We've double-checked with maintainers who work at GitHub and they've confirmed that GitHub is not currently doing this.

**Comment by Rylan12** [comment]
Before I spend too much time looking into this, I'd like to get some other opinions from @Homebrew/maintainers about what the right path forward here is.

For context (so reading the whole thread isn't necessary), we're discussing what the default branch name for the [`GitDownloadStrategy`](https://github.com/Homebrew/brew/blob/7e2ba95169593366565e84bce44da28a5aefe62c/Library/Homebrew/download_strategy.rb#L756-L974) class should be. Currently, the default is `master`. If a repository doesn't have a `master` branch, the clone will fail. The branch name can be overridden using a `branch` argument for repositories with another branch name in these cases. Since GitHub has changed the default branch name to `main`, there is a question about whether `master` should remain the default for this download strategy.

Here are the options I have in my head:

1. Continue to use `master` as the default
    - Pros: doesn't require deprecations/changing lots of formulae, most software in Homebrew uses `master` as the branch name.
    - Cons: this doesn't match the default GitHub branch name, so we may find that lots of new formulae need to manually specify a branch.
2. Switch to using `main` as the default
    - Pros: new software may be more likely to use `main` as the branch name, so this would allow the `url` method to work without needing to specify a branch for new formulae.
    - Cons: we'll need to deprecate using `master` and have to change lots of formulae in homebrew/core (although the change is relatively trivial).
3. Automatically detect the default branch if no branch is specified
    - Pros: it doesn't matter what the branch name is so it's the best of both worlds, handles renaming branched without needing to change the branch name in the formula.
    - Cons: more complexity behind the scenes
4. Require a branch to be specified in all cases.
    - Pros: we don't need to worry about defaults, it's always clear which branch we're trying to use
    - Cons: we need to add branch names to formulae in homebrew/core, arguably makes the formula code a little less clean

This may be an issue that makes more sense to discuss in a few years when we have a better sense of the lay of the land and whether `main` is really used more often. Changing the default now assumes that lots of repos will change and new repos will continue to use `main`, but that may not be the case. As we're seeing, changing the branch name can cause problems, so I wouldn't be surprised if it's not a change that's made very quickly.

**Comment by MikeMcQuaid** [comment]
> Since GitHub has changed the default branch name to `main`

(for new repositories)

> Automatically detect the default branch if no branch is specified
> * Pros: it doesn't matter what the branch name is so it's the best of both worlds, handles renamed branches without needing to edit the formula, this is what `git clone` does by default unless you add the `--branch` flag.

This makes sense to me. We could make the local branch if specified default to `main` and use `origin/HEAD` where available.

**Comment by slhck** [comment]
> GitHub definitely isn't, and shouldn't be doing that. Who has write access to your repo? Are you sure they didn't change the default branch name by mistake?

Hmm. I will check again. It could be a communication issue on the maintainers' part. It's definitely not something you can do as a *mistake*, as the setting is buried somewhere. If it was a manual switch, apologies for the wrong information I would have given here.
