### ISSUE TITLE
Homebrew install not working with my M1 silicon chip

### ISSUE THREAD

**Issue by MatthwFrost** [Homebrew/brew#10773]
### `brew config` output

fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core failed!
fatal: invalid upstream 'origin/master'
Failed during: /opt/homebrew/bin/brew update --force --quiet

### `brew doctor` output

Not able to use 'Brew doctor' as install won't work

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Install Homebrew on my Macbook Pro M1 silicon chip.

### What happened (include all command output)?

After using the Homebrew formulae in terminal i get a few fatal errors that rise:

command output:
HEAD is now at 9d62a13a3 Merge pull request #10700 from appropriate/docs-homebrew-and-java
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core failed!
fatal: invalid upstream 'origin/master'
Failed during: /opt/homebrew/bin/brew update --force --quiet

### What did you expect to happen?

For homebrew to install

### Step-by-step reproduction instructions (by running `brew` commands)

Terminal input:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by Bo98** [comment]
This is usually caused by something breaking the connection, such as security software. You can try temporarily disabling anything like that you may have installed. [I also hear that Big Sur 11.3 will help a bit here.](https://github.com/Homebrew/discussions/discussions/666#discussioncomment-427191)

Either way, this is unfortunately something disrupting a regular `git` fetch and not a `brew` bug. You can open a [discussion](https://github.com/Homebrew/discussions/discussions), or reply to an existing one, for additional help.
