### ISSUE TITLE
C++ standard library warning is useless

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#10830]
### Provide a detailed description of the proposed feature

Remove the warning:

> "Warning: X dependency Y was built with a different C++ standard library (libstdc++ from clang). This may cause problems at runtime.”

that occurs for example when installing root: https://github.com/Homebrew/homebrew-core/issues/72879

### What is the motivation for the feature?

We have a lot of software that builds with dependencies with mixed clang/gcc. It does not actually mean it uses mixed C++ shared libraries: we typically depend on GCC for the Fortran runtime, which is C-only. While the warning has good intentions, it is too crude and therefore useless.

### How will the feature be relevant to at least 90% of Homebrew users?

I've been a maintainer with Homebrew for 4 years now, and dealing with most of the GCC-related issues during that time. I have never seen an actual case where the warning is correct.

### What alternatives to the feature have been considered?

Ignoring the problem because it's a warning and not an error, and because it says "may cause problems" which, strictly speaking, could be true.

**Comment by carlocab** [comment]
Could it be a useful warning on Linux? CC @Homebrew/linux

**Comment by MikeMcQuaid** [comment]
I'm 👍🏻 on just removing this.

**Comment by iMichka** [comment]
I've never seen anything break due to this in 3 years, and heard no complaints from users.

**Comment by fxcoudert** [comment]
The reason I opened an issue rather than a PR is because the code doing this is very extensive and has ramifications in several files. There is also stdlib information stored in install receipts, and I'm not sure whether it's used for some other purpose, or if it makes sense to remove it root and stem.

**Comment by Bo98** [comment]
Tab is just another name for install receipts really.

**Comment by Bo98** [comment]
This will probably involve deprecations considering we have the `cxxstdlib_check` formula DSL.

**Comment by sjackman** [comment]
I agree this warning is not useful in its current form. Whether a formula depends on C++ and what version of C++ (C++11 or C++17) is actually quite useful information to Homebrew on Linux. I'd like to retain that aspect, and I may take a stab at improving it. The warning can likely go away. It hasn't been useful since the ABI migration from `libstdc++` to `libc++` on macOS, and from GCC 4 to GCC 5 on Linux, from reference counted `std::string` to small-string-optimization (SSO) `std::string`.

**Comment by MikeMcQuaid** [comment]
> Whether a formula depends on C++ and what version of C++ (C++11 or C++17) is actually quite useful information to Homebrew on Linux.

@sjackman how and where is that information used already? If this is a "we'd like to use this information in future": I'd prefer we removed it.

**Comment by sjackman** [comment]
> how and where is that information used already? If this is a "we'd like to use this information in future": I'd prefer we removed it.

Homebrew on Linux uses very few dependencies provided by the host system. Two key dependencies that it does use are:
1. `libc.so.6` provided by Glibc
2. `libstdc++.so.6` provided by GCC

The way we know that a particular bottle depends on `libstdc++.so.6` is `"stdlib": "libstdcxx"` in `INSTALL_RECEIPT.json`. Homebrew/brew does not currently use this information. If the host's `libstdc++.so.6` is too old or missing, it installs the brewed `gcc@5` the very first time `brew install` is run. A modest improvement would be to install `gcc@5` the first time that a formula that depends on `libstdc++.so.6` is installed (if the host's `libstdc++.so.6` is too old or missing). A further improvement would be to do the same thing for `libc.so.6`.

We previously used this information when migrated the default compiler used by Linuxbrew from GCC 4.8 (provided by Ubuntu 14) to GCC 5.4 (provided by Ubuntu 16), which included a `libstdc++.so.6` ABI change. We're planning to migrate this year from GCC 5.4 (provided by Ubuntu 16) to GCC 7.3 (provided by Ubuntu 18). There is no ABI change this time, so I don't expect similar challenges. It would however be useful to know which formula depend on `libstdc++.so.6`, so that we can test those formulae for regressions.

**Comment by MikeMcQuaid** [comment]
@sjackman Ok, thanks for explaining. I'd propose:
- we/someone removes all storage of this in the INSTALL_RECEIPT/Tab on macOS
- we/someone removes all error messaging related to this on macOS and Linux
- @sjackman writes up a "help wanted" issue describing the behaviour he would like to see above

How's that sound?

**Comment by sjackman** [comment]
Sounds good to me!

**Comment by Bo98** [comment]
The warning has been removed in #11004.
