### ISSUE TITLE
Random Permission Failures @ Build.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#1094]
```
cp: /usr/local/Cellar/openssl@1.1/1.1.0a/lib/pkgconfig/libcrypto.pc: Permission denied
```

Also: https://github.com/Homebrew/homebrew-core/issues/5074

Seems to have started since we returned `/usr/local` to the default permissions. Doesn't consistently reproduce, which is frankly puzzling.

**Comment by DomT4** [comment]
I can get my particular one to reproduce by doing:
```
brew install openssl@1.1
brew upgrade openssl@1.1 -s -v
```
Which is just great, because it's blocking me from properly investigating https://github.com/Homebrew/homebrew-core/issues/5126. *Throws MacBook into the ocean*.

**Comment by zmwangx** [comment]
Yeah, I can reproduce, but I don't plan to throw a 2.5 grand MacBook into the ocean, plus there's no ocean around me. 😌

**Comment by ilovezfs** [comment]
This is just a Makefile bug

**Comment by ilovezfs** [comment]
But the underlying cause is that the same prefix is being reused due to Homebrew/homebrew-core#5126, so the file is already there. The Makefile doesn't handle that situation correctly, but it ordinarily never would have to because we start out with an empty `prefix`. In this case it's starting out with a fully occupied prefix, and the problematic files have mode 444.
