### ISSUE TITLE
Add option to disable “Checking for dependents of upgraded formulae”

### ISSUE THREAD

**Issue by NightMachinary** [Homebrew/brew#10986]
### Provide a detailed description of the proposed feature

“Checking for dependents of upgraded formulae” completely clogs up my 1GB vps. I do a “brew upgrade” every midnight anyway, so I don’t want these upgrades to happen in my daily usage.

### What is the motivation for the feature?

The upgrades are almost always superfluous and not needed. The default behavior is a bad tradeoff on constrained systems. The bottleneck can even be the network. The ability to do the upgrades on the admin’s schedule is very helpful in various scenarios.

### How will the feature be relevant to at least 90% of Homebrew users?

Most users will want to run Homebrew on a constrained environment, I assume. 

### What alternatives to the feature have been considered?

I haven’t heard of any.

**Comment by carlocab** [comment]
>The upgrades are almost always superfluous and not needed.

What makes you say that? I actually think that these upgrades only happen (in the majority of instances) when they're needed.

In any case, the feature you're requesting leads to software configurations that aren't tested in our CI, so it's unlikely that this is something we'd want to implement. See also [this FAQ](https://docs.brew.sh/FAQ#why-does-brew-upgrade-formula-also-upgrade-a-bunch-of-other-stuff).

**Comment by NightMachinary** [comment]
> > The upgrades are almost always superfluous and not needed.
> 
> What makes you say that? I actually think that these upgrades only happen (in the majority of instances) when they're needed.

They happen for every single dependent of a package, as far as I understand. Usually dependents can work just fine with newer versions, can’t they? Anyhow, the point isn’t to not upgrade, but to postpone the upgrades to some suitable time.

> In any case, the feature you're requesting leads to software configurations that aren't tested in our CI, so it's unlikely that this is something we'd want to implement. See also [this FAQ](https://docs.brew.sh/FAQ#why-does-brew-upgrade-formula-also-upgrade-a-bunch-of-other-stuff).

How does it matter that it is not tested on the CI? You can ask everyone opening an issue to first do a thorough “brew upgrade”, so their potential issues won’t spam here anyway. I don’t see why every configuration should be supported to such high degrees.

**Comment by carlocab** [comment]
> They happen for every single dependent of a package, as far as I understand.

I think you're mistaken.

> Usually dependents can work just fine with newer versions, can’t they?

Usually, yes. Those dependents should not and are almost never upgraded, so they should be unaffected by the check for dependents of upgraded formulae.

Except sometimes, some very minimal tests reveal that these dependents are actually broken when used with the new version of a dependency, so they need to be rebuilt against the new version. So actually what you're asking is to skip out on updates that are meant to fix formulae that are _known_ to have been broken by a version bump to another formula.

>How does it matter that it is not tested on the CI? You can ask everyone opening an issue to first do a thorough “brew upgrade”, so their potential issues won’t spam here anyway. 

Sorry, but I'm really not interested in triaging issues that could've been fixed by a user doing `brew update && brew upgrade`. I don't think other maintainers are interested in doing that either.

It might seem as simple as including some messages that ask users to do `brew update && brew upgrade` before filing an issue, but the unfortunate truth is that we still get quite a large number of issues and support requests from users that could've been avoided if they just read the warning messages from `brew`.

>I don’t see why every configuration should be supported to such high degrees.

I agree. That's why we only support one configuration: doing `brew upgrade $formula` will make sure everything connected to `$formula` via its dependency graph should also be at its latest version.

**Comment by carlocab** [comment]
Here's an example: https://github.com/Homebrew/homebrew-core/pull/74289

`rav1e` was bumped to to `0.4.1`. However, this broke `ffmpeg` (see CI run [here](https://github.com/Homebrew/homebrew-core/runs/2241799598)), which, in turn, broke a whole bunch of things that depend (perhaps indirectly) on `ffmpeg`.

The solution is to bump the `revision` of `ffmpeg` (but _not_ all the other formulae that depend on `ffmpeg`) in order to rebuild `ffmpeg` against the new version of `rav1e`. Then, doing `brew upgrade rav1e` should upgrade `ffmpeg` (if you have it installed), but not all these other formulae that also depend on `ffmpeg`.

**Comment by NightMachinary** [comment]
@carlocab Thank you, it seems my understanding was wrong, and the packages are not upgraded for no reason. How are these lists of packages that need to be upgraded determined? The contributor manually specifies them till the CI passes?

**Comment by carlocab** [comment]
> How are these lists of packages that need to be upgraded determined? The contributor manually specifies them till the CI passes?

Roughly, yes. We currently don't have an automated way to identify which other packages need to be updated because of a change to another formula, so one has to check the CI output first then decide. Typically, one starts with formulae that fail a linkage test (as `ffmpeg` did in the linked PR), because those are definitely broken, and rebuilding them often resolves many of the other CI failures.

We try to keep an eye on things to make sure that things like `revision` bumps are applied only to the smallest set of formulae required to keep things working, but there are a lot of formulae in homebrew/core, and this is all done in the time of a handful of volunteers.
