### ISSUE TITLE
Upgrade Sorbet

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11207]
### What were you trying to do (and why)?

Let @dependabot-bot upgrade Sorbet (e.g. https://github.com/Homebrew/brew/pull/11195)

### What happened (include all command output)?

```
Option ‘dsl-plugins’ does not exist. To see all available options pass `--help`.
```

### What did you expect to happen?

Sorbet could be upgraded.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
gh pr checkout https://github.com/Homebrew/brew/pull/11195
brew typecheck
...
Option ‘dsl-plugins’ does not exist. To see all available options pass `--help`.
```

**Comment by issyl0** [comment]
I'll figure this out later today! 🍨

**Comment by issyl0** [comment]
Figuring it out today was too ambitious. We relied on this "experimental" feature a lot.

Context for its removal (and some alternatives) are at https://github.com/sorbet/sorbet/pull/3983. I looked into the Tapioca DSL generator, but I couldn't find any docs for how to write new ones (thinking I could repurpose our `sorbet/plugins` code). Also, a bunch of other things I Googled assume that `sorbet-rails` is a thing you're using, which it isn't.

The Sorbet docs for `attr_reader`, `attr_writer`, `attr_accessor` (a lot of the current "method does not exist" problems once I'd removed the flag and `brew typecheck` could run again) say ["put a method signature above the declaration"](https://sorbet.org/docs/faq#how-should-i-add-types-to-methods-defined-with-attr_reader), but that's not going to be sustainable I don't think with how many we have and how they're [sometimes different types](https://stackoverflow.com/questions/56844571/adding-sorbet-type-signatures-to-attr-reader-attr-writer-with-multiple-variables). Not to mention the ~100 other errors across `brew typecheck`!

I've now realised why we used the plugins to [define the same signature for _every one_ of these automatically](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/sorbet/plugins/) as per [this](https://stackoverflow.com/a/57149310) sadly outdated StackOverflow answer. 😱

I deactivated my account on the Sorbet Slack because I hadn't looked there in a while, and now I can't reactivate it without finding a workspace admin. Given that I can't ask what other folks have done for this, combined with my relatively poor knowledge of this kind of stuff, I'm (disappointingly) going to leave this for someone else.

**Comment by MikeMcQuaid** [comment]
@reitermarkus @vidusheeamoli Would one of you be able to look into this? I don't think it's sustainable for us to sit on an old version of Sorbet indefinitely, [particularly given it's broken on M1 Macs](https://github.com/Homebrew/brew/issues/10210).

**Comment by Bo98** [comment]
I was looking at Tapioca RBI generators for this. Turns out Tapioca RBI generation is broken because of https://github.com/rails/rails/pull/41610.

So it seems like we're waiting for ActiveSupport 6.1.4 now :~)

I can continue to look into this with a locally-patched ActiveSupport.

**Comment by MikeMcQuaid** [comment]
> I can continue to look into this with a locally-patched ActiveSupport.

That'd be great, thanks @Bo98!

**Comment by Bo98** [comment]
Going through the plugins we were using:

* `def_delegator` - no longer necessary since 0.5.6104, which we already use.
* `def_delegators` - no longer necessary since 0.5.6408, released a few hours ago.
* `delegate` - I'm working on a patch to submit upstream.
* `attr_rw` - I've written an RBI generator for this.
* `attr_predicate` - `attr_rw` code can be generalised to cover this too.
* `using` - this is all trying to cover refinements, which Sorbet does not support. This is probably a case of more RBI generation but I haven't properly investigated yet.

**Comment by MikeMcQuaid** [comment]
I think we should consider just upgrading and disabling checks on any files that require plugins at this point.

**Comment by Bo98** [comment]
I'll give an update here later this week and show what I have done. iirc I had managed to cover most things

**Comment by MikeMcQuaid** [comment]
@Bo98 Thanks! Could you consider opening a draft PR (or pointing to your current WIP PR if there is one)? This is getting to the point I'm tempted to just disable type-checking on the relevant files. I hope this isn't too rude but I don't want this effort to be blocked on a couple of individuals.

**Comment by Bo98** [comment]
Yes, expect a draft PR - likely on Thursday!

If it spawns any bigger questions on direction, I'm happy to talk about it in more depth at the meeting next week if there is one. Otherwise, I'll be around as usual from Monday likely.

**Comment by MikeMcQuaid** [comment]
Done in https://github.com/Homebrew/brew/pull/11771 by @Bo98 🎉
