### ISSUE TITLE
Speed up `brew bottle` "Determining ... bottle rebuild..."

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11281]
### Provide a detailed description of the proposed feature

This is _really_ slow. I have a fast machine with a SSD and it takes multiple seconds. [`FormulaVersions#bottle_version_map`](https://github.com/Homebrew/brew/blob/32fe482a4c9517482db447874354d9366cfa7534/Library/Homebrew/formula_versions.rb#L60-L76) should be sped up to speed up both our CI and those for anyone who bottles things.

### What is the motivation for the feature?

Slow things are bad.

### How will the feature be relevant to at least 90% of Homebrew users?

Increased CI throughput.

### What alternatives to the feature have been considered?

Doing nothing.

**Comment by cwegrzyn** [comment]
Hoping I can help out here, since I was just running into a problem related to this where an ancient version of our (newly bottled) formula was causing an error on load. I scratched my head about that, because all `brew bottle` seemed to need was the most recent rebuild number for the current package version, so why is it going into the ancient past, long long before we first bottled this?

From what I can tell, the logic in `bottle_version_map` currently stops only after it has found TWO distinct `pkg_version`s each with at least ONE bottle checksum and THEN  one more `pkg_version` (with or without a bottle) after that.

Since the only current usage of `bottle_version_map` is in `brew bottle` and it only ever looks at the current `pkg_version`, could this stop after finding ONE pkg_version after the current bottled version? A `brew tests` with that change succeeded, but I'm not sure that guarantees that this doesn't break something.

Even more aggressively, it could just stop looking after it finds a single rebuild number for the current version.

Fwiw, it looks like the behavior of limiting after two was introduced here https://github.com/Homebrew/brew/pull/2109. Do you recall how that number was chosen? The current behavior seems to protect against the possibility that the pair (pkg_version, rebuild number) is not monotonically increasing with git commit as one would expect. Unfortunately, I don't have the context to know how much of a concern that really is. I think the `git rev-list` call might need a tweak to not walk each commit included in a merge, otherwise maybe that could mess with the ordering. I think `--first-parent` does that, but somebody with more git knowledge may need to weigh in.

**Comment by MikeMcQuaid** [comment]
Fixed by @cwegrzyn, nice work!
