### ISSUE TITLE
Don't unexpectedly read all casks/formulae

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11292]
### Provide a detailed description of the proposed feature

There's certain commands (e.g. `brew update`, `brew doctor`) that will read/evaluate all formulae and all casks from all tapped taps.

### What is the motivation for the feature?

The current behaviour is unexpected and (I'd argue) undesirable. I consider it expected behaviour to read the formula/casks that are already installed with commands such as `brew update`/`brew doctor` but not every formula/cask in every tap.

`HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED` already does some of this for `brew update`. I use it and it improves the output (and potentially speed).

### How will the feature be relevant to at least 90% of Homebrew users?

Improved security and speed of those commands.

### What alternatives to the feature have been considered?

- The status quo
- Sandboxing (with blocked network access?) all reads (only available on macOS) to improve security

**Comment by lionellloh** [comment]
Thinking of working this later in this week or early next week. Will get some context and follow up with questions!

**Comment by MikeMcQuaid** [comment]
@lionellloh That'd be great!

**Comment by SkittishSloth** [comment]
I see that the setting is now defaulted to on; how can I change it to get back the previous behavior? I completely understand the reasoning behind the update, but I personally loved seeing the report - I've come across a ton of programs that I never would have even thought I needed because of it. It's part of my daily routine: run brew update, see some random name in the list, run brew info on it, see what it's about. I've even spent more time than I care to admit trying to implement something similar for apt on my Termux installation, or trying to get brew installed there just so I can have that report.

The past few days I've been trying to figure out what I broke on my mac because I'd recently cleaned out my profile/rc scripts due to some other issues; while I'm relieved that my comp isn't busted, I didn't see anything in the merged PR that makes it obvious what I need to do to re-enable the feature - am I just missing something?

**Comment by RandomDSdevel** [comment]
@SkittishSloth:&nbsp;&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I also asked for such a toggle switch for this option in Homebrew/discussions#3008, but, per [Mr. McQuaid's answer there](https://github.com/Homebrew/discussions/discussions/3008#discussioncomment-2236350):  

> I'd consider adding this if I see lots of people (10+) requesting this behaviour.

'`brew`' won't have one after this change just yet.  Further conversation surrounding this can and should happen over on that other thread.

**Comment by MikeMcQuaid** [comment]
@SkittishSloth Yup, as @RandomDSdevel said: there's no flag to bring back this behaviour, I'm afraid.

**Comment by SkittishSloth** [comment]
I completely forgot about GitHub Discussions - moved over there. Thanks!

**Comment by MikeMcQuaid** [comment]
> `HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED` already does some of this for `brew update`. I use it and it improves the output (and potentially speed).

This doesn't actually read formulae so I've reverted the change to make this default.

---

We've now deprecated the use of `Enumerable` in `Formula` and `Cask::Cask` so this can be closed. Thanks everyone!
