### ISSUE TITLE
Make bottle relocation more specific 

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11302]
### Provide a detailed description of the proposed feature

Don't rewrite paths such as e.g. `$foo/build/usr/local/bin`. For example, see `objc-run`: https://github.com/iljaiwas/objc-run/blob/55f257300154201a40f3631b06d8131dfe47a5a2/objc-run#L110 

See discussion in https://github.com/Homebrew/homebrew-core/issues/75943#issuecomment-830718892

This would require changing  at least `replace_text_in_files` (https://github.com/Homebrew/brew/blob/eae355810873ceb6972f14f7f46c508a7e0309d5/Library/Homebrew/keg_relocate.rb#L69) and `each_unique_file_matching` (https://github.com/Homebrew/brew/blob/eae355810873ceb6972f14f7f46c508a7e0309d5/Library/Homebrew/keg_relocate.rb#L112) in `keg_relocate.rb`.

### What is the motivation for the feature?

Improve the number of bottles that are relocated and `all:`.

### How will the feature be relevant to at least 90% of Homebrew users?

Reduce the need to redownload bottles.

### What alternatives to the feature have been considered?

The status quo.

**Comment by Rylan12** [comment]
Is this just to protect against cases where one of the relocation path regexes matches in the middle of a path or are there more cases that need fixing?

If so, can we just add `\b` to the beginning of the `old_*` relocation strings in `replace_locations_with_placeholders`

https://github.com/Homebrew/brew/blob/eae355810873ceb6972f14f7f46c508a7e0309d5/Library/Homebrew/keg_relocate.rb#L39-L52

**Comment by MikeMcQuaid** [comment]
> Is this just to protect against cases where one of the relocation path regexes matches in the middle of a path

Yes, I think so for now.

> or are there more cases that need fixing?

Probably but: we don't know what they are yet 😁 

> If so, can we just add `\b` to the beginning of the `old_*` relocation strings in `replace_locations_with_placeholders`

Something like that makes sense to me. I'm not sure I fully understand what `\b` does and whether it would handle `/`, `"`, or the beginning of line like we'd expect?

**Comment by Rylan12** [comment]
> I'm not sure I fully understand what `\b` does and whether it would handle `/`, `"`, or the beginning of line like we'd expect?

Good point. it don't think it will match `"` but I'm pretty sure it _does_ match `/` so probably best to go with your suggestion from https://github.com/Homebrew/homebrew-core/pull/76394#discussion_r624676949:

```ruby
/[^a-z]?#{HOMEBREW_PREFIX}/
```

**Comment by MikeMcQuaid** [comment]
It's worth noting e.g. https://github.com/Homebrew/homebrew-core/blob/a32f8fd08629a24537a01af1e57556007a5fbc29/Formula/fontconfig.rb#L23-L28

(and similar cases in other formulae)

Arguably any/all of these are a sign that the bottle relocation logic needs fixed.

**Comment by Rylan12** [comment]
Now that #11332 has been merged, I've opened https://github.com/Homebrew/homebrew-core/pull/77187 and https://github.com/Homebrew/homebrew-core/pull/77188 to remove the `pour_bottle?` blocks from `objc-run` and `pkg-config`.

There are still 20 other formulae in homebrew/core that have `pour_bottle?` blocks but these fall into four categories:
1. [`ocaml`](https://github.com/Homebrew/homebrew-core/blob/483437c30369bbfb0c35b55b760ae9cff3551668/Formula/ocaml.rb#L33-L38): I'm currently investigating why this is needs the `pour_bottle?` block and will hopefully soon know whether it's solved by #11332 as well or not (looks like it isn't)
2. [`percona-server`](https://github.com/Homebrew/homebrew-core/blob/483437c30369bbfb0c35b55b760ae9cff3551668/Formula/percona-server.rb#L19-L22) needs `datadir == var/"mysql"`
3. [`gcc`](https://github.com/Homebrew/homebrew-core/blob/483437c30369bbfb0c35b55b760ae9cff3551668/Formula/gcc.rb#L34-L41) and [`llvm`](https://github.com/Homebrew/homebrew-core/blob/483437c30369bbfb0c35b55b760ae9cff3551668/Formula/llvm.rb#L22-L28) formulae require the Xcode CLT to be installed on macOS:
    ```ruby
    pour_bottle? do
      on_macos do
        reason "The bottle needs the Xcode CLT to be installed."
        satisfy { MacOS::CLT.installed? }
      end
    end
    ```
4. [`python`](https://github.com/Homebrew/homebrew-core/blob/483437c30369bbfb0c35b55b760ae9cff3551668/Formula/python%403.9.rb#L21-L32) formulae require the Apple Command Line Tools to be installed on macOS:
    ```ruby
    pour_bottle? do
      on_macos do
        reason <<~EOS
          The bottle needs the Apple Command Line Tools to be installed.
            You can install them, if desired, with:
              xcode-select --install
        EOS
        satisfy { MacOS::CLT.installed? }
      end
    end
    ```
5. [`libgccjit`](https://github.com/Homebrew/homebrew-core/blob/483437c30369bbfb0c35b55b760ae9cff3551668/Formula/libgccjit.rb#L22-L27) and [`swift-format`](https://github.com/Homebrew/homebrew-core/blob/483437c30369bbfb0c35b55b760ae9cff3551668/Formula/swift-format.rb#L22-L27) both also need the CLT but its not restricted to just on macOS

First of all, is there really a difference between 3 and 4? I think 4 gives better messaging so it should probably be used consistently (see my suggestion below).

Second, for number 5, _should_ these be enclosed in `on_macos` blocks? You can't install the CLT on Linux (at least I assume) so I wonder if they work on Linux or not.

I don't think we can really avoid the CLT requirement but I wonder if we should add a shortcut to require the CLT because it seems that the same `pour_bottle?` block is used in a bunch of places.

Maybe one of these could be a shortcut (obviously allowing existing `pour_bottle?` syntax to continue:

```ruby
pour_bottle? :require_clt
pour_bottle? :if_clt_installed
pour_bottle? if: :clt_installed
```

**Comment by carlocab** [comment]
I'd been contemplating making `MacOS::CLT.installed?` return true on anything that's not macOS, but I suspect your suggestion of a `pour_bottle?` DSL might be better.

**Comment by MikeMcQuaid** [comment]
> Now that #11332 has been merged, I've opened [Homebrew/homebrew-core#77187](https://github.com/Homebrew/homebrew-core/pull/77187) and [Homebrew/homebrew-core#77188](https://github.com/Homebrew/homebrew-core/pull/77188) to remove the `pour_bottle?` blocks from `objc-run` and `pkg-config`.

🎉 



> * [`ocaml`](https://github.com/Homebrew/homebrew-core/blob/483437c30369bbfb0c35b55b760ae9cff3551668/Formula/ocaml.rb#L33-L38): I'm currently investigating why this is needs the `pour_bottle?` block and will hopefully soon know whether it's solved by #11332 as well or not (looks like it isn't)

😭 but thanks for checking

> First of all, is there really a difference between 3 and 4? I think 4 gives better messaging so it should probably be used consistently (see my suggestion below).

Agreed!

> I don't think we can really avoid the CLT requirement but I wonder if we should add a shortcut to require the CLT because it seems that the same `pour_bottle?` block is used in a bunch of places.
> 
> Maybe one of these could be a shortcut (obviously allowing existing `pour_bottle?` syntax to continue:

I like this! Maybe `pour_bottle? :clt_required` or `pour_bottle? if: :clt_installed`?

**Comment by MikeMcQuaid** [comment]
> I'd been contemplating making `MacOS::CLT.installed?` return true on anything that's not macOS, but I suspect your suggestion of a `pour_bottle?` DSL might be better.

I'd like (eventually) to get to a point where `MacOS` and `MacOS::CLT` classes aren't even defined on Linux (as they aren't in the "generic OS" layer).

**Comment by Rylan12** [comment]
Okay, here's an update on `ocaml`. The `pour_bottle?` block was added in 2016 in https://github.com/Homebrew/homebrew-core/pull/586 (specifically https://github.com/Homebrew/homebrew-core/commit/a995aa20ef603d389ec95fb0256891f7fd0ba79a).

Looking at the contents of the `bin` directory, it seems that there are several references to `/usr/local/lib`. It looks to me like we intentionally don't search for references to `/usr/local/lib` because it's not a Homebrew-only directory (is that correct?).

There are also references to `/usr/local/bin`, many (but not all) through shebangs: `#!/usr/local/bin/ocamlrun`. We also don't check for `/usr/local/bin` (for what I presume is the same reason). I do know, though, that we have some handling of shebangs (I know that @Bo98 did some work on them in #11286). I don't know much about how what we do with shebangs in terms of relocation. Is this soemthing that should be looked into (i.e. a shebang is found pointing to `HOMEBREW_PREFIX/bin/foo` where `foo` belongs to a formula)?

**Comment by Rylan12** [comment]
> I like this! Maybe `pour_bottle? :clt_required` or `pour_bottle? if: :clt_installed`?

I like these. No real preference from me; I think they're both very clear. I'll spend some time soon working on this

**Comment by MikeMcQuaid** [comment]
> Looking at the contents of the `bin` directory, it seems that there are several references to `/usr/local/lib`. It looks to me like we intentionally don't search for references to `/usr/local/lib` because it's not a Homebrew-only directory (is that correct?).
> We also don't check for `/usr/local/bin` (for what I presume is the same reason).

Correct!

> There are also references to `/usr/local/bin`, many (but not all) through shebangs: `#!/usr/local/bin/ocamlrun`.

We should probably rewrite these so it works when unlinked.

> Is this soemthing that should be looked into (i.e. a shebang is found pointing to `HOMEBREW_PREFIX/bin/foo` where `foo` belongs to a formula)?

Yes, that would make sense to do I think 👍🏻. Should be relatively easy to look at bottle time whether it's a symlink into a cellar and, if so, replace it with a `opt` path.

**Comment by MikeMcQuaid** [comment]
Closing this as considering it mostly done.
