### ISSUE TITLE
If the latest version of a formula is not supported on the installed OS, Homebrew should install the most recent compatible version

### ISSUE THREAD

**Issue by unikitty37** [Homebrew/brew#11304]
### Provide a detailed description of the proposed feature

When typing `brew install --cask mkvtoolnix` on a Mac running Mojave, the message `mkvtoolnix: macOS Catalina or newer is required for this software.` is returned and mkvtoolnix is not installed.

As mkvtoolnix v53 and earlier are compatible with Mojave, rather than completely refusing to install the formula because v56 is not compatible, Homebrew should install v53 and warn that upgrades will not be possible without upgrading the OS.

### What is the motivation for the feature?

I am using a 2010 Mac Pro; Catalina is not supported on this machine. I cannot afford to buy a new Mac, especially since there is nothing comparable running Apple Silicon and an Intel Mac would have a very short useful lifetime.

Even though there are versions (v53 and earlier) of mkvtoolnix that are compatible with Mojave, I now have to install it manually rather than use Homebrew. At least for cask installs where previous versions are still available, such as with mkvtoolnix, Homebrew should be able to do something more useful than it does here.

### How will the feature be relevant to at least 90% of Homebrew users?

Unless 90% of Homebrew users are on the latest version of macOS, they will get hit by this at some point. 

Apple does periodically block installation of new versions of macOS even when the hardware is capable of running it, and Homebrew really shouldn't be helping them say "just throw it away and buy a new one"…

### What alternatives to the feature have been considered?

As I mentioned above, manual installation is the only workaround I can think of. That's not too bad for cask installs, like mkvtoolnix, but it becomes very painful for packages that need to be compiled from source.

**Comment by carlocab** [comment]
We only support the installation of the latest version [*] of any formulae in Homebrew/core, I'm afraid. We very much sympathise with users who aren't on the latest version of macOS for reasons not in their control, but our resources are too limited to extend support even further.

The feature you are looking for requires a significant amount of work to be put into changing `brew` internals in order to support a very small number of formulae (less than 50).

>Unless 90% of Homebrew users are on the latest version of macOS, they will get hit by this at some point.

That's different from this feature being relevant to 90+% of Homebrew users. Even if 90% of Homebrew users are not running Big Sur, I would say that the users affected by this are a minority (and certainly nowhere near 90% of users).

>As I mentioned above, manual installation is the only workaround I can think of. 

You can host earlier versions of the formulae you need in your own tap. Doing so will also allow you to build them on GitHub CI. Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

[*] There are a handful of exceptions that exist as versioned formulae, but there are some [requirements](https://docs.brew.sh/Versions) for versioned formulae in Homebrew/core.

**Comment by unikitty37** [comment]
Thanks — I think in this case simply installing from the .dmg is the easier option, but I'll look into that for source builds :)
