### ISSUE TITLE
Homebrew/.github dependabot update handling

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#11401]
PRs such as e.g. https://github.com/Homebrew/homebrew-test-bot/pull/612 should be handled by updating Homebrew/.github which in turn then submits the PRs to sync the configuration with all other repositories.

This could/should also be done by syncing https://github.com/Homebrew/brew/blob/master/.github/dependabot.yml between all repositories and ensuring that the Homebrew/.github one is setup to update that repository but all other repositories dependabot ignores actions updates (because our tooling will do them for us).

**Comment by Rylan12** [comment]
🎉 I was just thinking about this.

I think the update frequency for Homebrew/.github can be switched to daily (it was set to weekly to avoid constantly opening 22 PRs for version bumps, but this hasn't happened that often and when it does it can be more disruptive because it adds double the number of PRs.

I think the way to do it is to add `ignore` entries for the dessant/lock-threads and actions/stale dependencies. That way, they'll only be updated in the Homebrew/.github repo.

> This could/should also be done by syncing https://github.com/Homebrew/brew/blob/master/.github/dependabot.yml between all repositories and ensuring that the Homebrew/.github one is setup to update that repository but all other repositories dependabot ignores actions updates (because our tooling will do them for us).

I'm not sure that we can sync this file, though, as each repo has different dependency structures (or none at all), right? For example, [Homebrew/brew](https://github.com/Homebrew/brew/blob/master/.github/dependabot.yml) has GitHub actions and two Gemfiles (each located in a specific directory) whereas [Homebrew/brew.sh](https://github.com/Homebrew/brew.sh/blob/master/.github/dependabot.yml) has GitHub actions and a Gemfile in the root directory with a handful of other settings.

**Comment by MikeMcQuaid** [comment]
> I think the way to do it is to add `ignore` entries for the dessant/lock-threads and actions/stale dependencies. That way, they'll only be updated in the Homebrew/.github repo.
> 
> I'm not sure that we can sync this file, though, as each repo has different dependency structures (or none at all), right? For example, [Homebrew/brew](https://github.com/Homebrew/brew/blob/master/.github/dependabot.yml) has GitHub actions and two Gemfiles (each located in a specific directory) whereas [Homebrew/brew.sh](https://github.com/Homebrew/brew.sh/blob/master/.github/dependabot.yml) has GitHub actions and a Gemfile in the root directory with a handful of other settings.

👍🏻 sounds good, thanks.

**Comment by MikeMcQuaid** [comment]
Thanks @Rylan12!
