### ISSUE TITLE
Documentation doesn't say how to do silent install

### ISSUE THREAD

**Issue by winternet-studio** [Homebrew/brew#11435]
### Provide a detailed description of the proposed feature

Document how to do a silent install (I still don't know how to do it)

### What is the motivation for the feature?

I need to install this in a docker environment without user needed to do anything - so that I can install mkcert for having https working in my application.

### How will the feature be relevant to at least 90% of Homebrew users?

N/A

### What alternatives to the feature have been considered?

There are no alternatives.

**Comment by winternet-studio** [comment]
Not true:

![image](https://user-images.githubusercontent.com/5200270/119368917-deea5880-bcb3-11eb-9301-6cc350b596c6.png)

**Comment by gromgit** [comment]
You're talking about installing _Homebrew itself_, for which the appropriate repo to file an issue against is https://github.com/Homebrew/install, not here.

In any case, if you want a "lights-out" Homebrew installation, you can simply untar the Homebrew software in a directory of your choice (https://docs.brew.sh/Installation#untar-anywhere). You may just find yourself spending _hours_ building the formulae you want from scratch, instead of getting near-instant installs from precompiled bottles, when your chosen software can't be automatically relocated from a `/home/linuxbrew/.linuxbrew` root prefix.

**Comment by Bo98** [comment]
The install script automatically detects whether it is being run in a full terminal (via a `-t 0` check), so interactive prompts shouldn't happen in a Dockerfile unless you are starting some interactive terminal session.

If this is not possible to avoid, then you can prepend the install command with `echo | ` which should shut off stdin from the TTY (and thus make it run non-interactively).

**Comment by winternet-studio** [comment]
> The install script automatically detects whether it is being run in a full terminal (via a `-t 0` check), so interactive prompts shouldn't happen in a Dockerfile unless you are starting some interactive terminal session.

I noticed that in the script and tried it in the Dockerfile - but it didn't detect it for some reason.

> If this is not possible to avoid, then you can prepend the install command with `echo | ` which should shut off stdin from the TTY (and thus make it run non-interactively).

Will try that if I ever need it again.
