### ISSUE TITLE
Document supported macOS versions for pre-built binary bottles

### ISSUE THREAD

**Issue by GottemHams** [Homebrew/brew#11688]
### Provide a detailed description of the proposed feature

Not sure if this is the right place because there are many issue trackers/categories and discussions forums.

I cannot find a clear list of the supported macOS versions for pre-built binary bottles. The [FAQ](https://docs.brew.sh/FAQ) would be the expected place for this, but it merely says `bottled builds are generated only for supported macOS versions`. All other semi-relevant pages I could find mention something similar. The [Installation](https://docs.brew.sh/Installation) page says `10.14 or higher is recommended. 10.9–10.13 are supported on a best-effort basis. For 10.4-10.6 see Tigerbrew.` but it doesn't clarify what `best-effort` entails.

### What is the motivation for the feature?

I don't want `brew` to spend many hours "manually" compiling stuff, so if I can determine if there are binary bottles __before doing anything with `brew`__ that would help a lot. I do realise that some packages might always need local compilation, but even then a general guideline would still be helpful.

Like in my specific case, I've upgraded from El Cap to Mojave and it would likely need to upgrade hundreds of packages. If 5-10 of those need to be locally compiled that's fine, but at the moment I simply don't have the information to make an educated guess.

### How will the feature be relevant to at least 90% of Homebrew users?

Everyone should be able to tell if __any__ package will need to be compiled locally, as this will be quite inconvenient and is probably not even expected behaviour for many users.

### What alternatives to the feature have been considered?

There are none.

**Comment by carlocab** [comment]
The documentation could probably be improved here (pull requests welcome).

If you're running Mojave, you shouldn't need to compile anything (unless you pass `--HEAD` to `brew install`). We bottle everything that can be built on the three latest major versions of macOS.

**Comment by gromgit** [comment]
And if you want to verify it locally:
```
brew update   # to make sure you have the latest formulae
brew info $(brew outdated) | grep stable
```
will give you a list of all the outdated formulae on your system, and show you which of them have bottles prepared. On my Linux box, for example, I get this:
```
$ brew info $(brew outdated) | grep stable
harfbuzz: stable 2.8.2 (bottled), HEAD
libomp: stable 12.0.1 (bottled) [keg-only]
pcre2: stable 10.37 (bottled), HEAD
ruby: stable 3.0.2 (bottled), HEAD
vim: stable 8.2.3125 (bottled), HEAD
zimg: stable 3.0.2 (bottled), HEAD
```
If you want to survey everything you've installed, and show only those that don't have bottles:
```
brew info $(brew ls) | grep stable | grep -v bottled
```
The general pattern:
1. Make a list of formulae you're interested in checking
2. Feed them to `brew info`
3. Feed the output of [2] to `grep stable` and/or whatever filters you desire

**Comment by Rylan12** [comment]
I agree the documentation can be improved, but we do clearly state which versions are supported [here](https://docs.brew.sh/Installation#macos-requirements) (also take a look at [the footnotes](https://docs.brew.sh/Installation#2) on that page). Maybe all that's needed is a direct link to that on the homepage?

If you just want to check for a certain package, you can visit `formulae.brew.sh/formula/$NAME` to view a table with each bottled OS. While we only create new bottles for the three latest OS versions, that doesn't mean there aren't currently older bottles available. These are, generally, only removed when formulae are updated to new versions so some old formulae still have old bottles. For example, [`python@3.9`](https://formulae.brew.sh/formula/python@3.9) only have bottles since Mojave while [`hello`](https://formulae.brew.sh/formula/hello) has bottles since Yosemite.

**Comment by GottemHams** [comment]
> I agree the documentation can be improved, but we do clearly state which versions are supported [here](https://docs.brew.sh/Installation#macos-requirements) (also take a look at [the footnotes](https://docs.brew.sh/Installation#2) on that page). Maybe all that's needed is a direct link to that on the homepage?

Yeah I mentioned that page myself but it's still unclear what "supported" means in the context of pre-built packages. The information I was looking for is basically `we only create new bottles for the three latest OS versions`. The commands outlined by @gromgit are certainly helpful to narrow it down for everyone's specific environments, even if you're on e.g. Yosemite.

I think it would be sufficient if the last 3 comments before this one were summarised/condensed into its own section in the FAQ, then maybe reference that from the installation page to be sure. Perhaps I might open a PR in the coming days. :>

**Comment by Rylan12** [comment]
> Yeah I mentioned that page myself but it's still unclear what "supported" means in the context of pre-built packages. The information I was looking for is basically `we only create new bottles for the three latest OS versions`.

While this is certainly a part of "support", it's not the only part. The more traditional definition of "support" also applies here (i.e. we won't provide help if you run into issues on an unsupported version, you'll see warnings letting you know that the version you're using is not supported, things may unexpectedly break without a normal deprecation/disable path, bugs may not be fixed unless they are trivial, etc.). So, I'm just a bit hesitant to scrap the word "supported" because I think that for many people, "support" implies different things than "creating bottles" and we want to be clear that both apply, if that makes sense.

> The commands outlined by @gromgit are certainly helpful to narrow it down for everyone's specific environments, even if you're on e.g. Yosemite.

I think if you want these added, they should go in the FAQ rather than on the installation page. Since this technically is not "supported" (see my definition above, mainly the part about giving help), we don't really want to advertise it more than we need to so that we don't give the impression that it's still supported. But, I think it's not a bad idea to have some info somewhere in the docs.

> Perhaps I might open a PR in the coming days. :>

That would be great!

**Comment by MikeMcQuaid** [comment]
> 10.9–10.13 are supported on a best-effort basis.

In the context of this issue this means: we are not generating new bottles/binary packages for these.

**Comment by rubyFeedback** [comment]
> I think if you want these added, they should go in the FAQ rather than on the installation page.

This is all fine; the problem may be for new users to find content, so when the main entry point (as the README) mention this, e. g. to visit the FAQ and the FAQ then covers this, then this seems fine. Personally I much prefer HTML tables for quick overviews similar to how wikipedia uses that on various pages.

New users tend to like documentation that is quickly useful without drowning in information and details.

**Comment by GuillaumeDIDIER** [comment]
Speaking of the policy, Mojave was the last version to support 32 bit applications. Some people are sometime stuck due to legacy applications that have not been updated for 64 bits. Would it be unreasonable for it to have a special support policy ?
(If a new issue should be opened I'll be glad to do it)

**Comment by iMichka** [comment]
Probably not. But some community members (and maybe even some maintainers) might be interest to create a fork of Homebrew to support Mojave. It was done for macOS Tiger a long time ago (Tigerbrew), so you can have MojaveBrew if you want. But we are not going to change our policy, mainly due to lack of bandwidth on our side.

**Comment by gromgit** [comment]
I've been quietly working on an Mojave core tap fork, that mirrors the main repo as closely as possible, but with freshly-built Mojave bottles. Some stuff is unavoidably "stuck in time" due to upstream updates that break Mojave compatibility (e.g. anything that involves Swift or Xcode), but otherwise you'll find the same formulae versions here as on the official core tap, just delayed by a few days.

Anyone who's brave enough to give it a shot should first read the README on my project page: https://github.com/gromgit/homebrew-core-mojave. It's more-or-less a drop-in replacement for official core, so you can switch back and forth between the two as your needs require.

*CAVEAT:* This is strictly an experimental side project, as Ubuntu and Debian are now my daily drivers. If anything's broken, please file an issue on my repo, **NOT** on official core.

**Comment by GuillaumeDIDIER** [comment]
@gromgit if you are able to keep stuff bottled that’s a huge improvement. I guess I’ll go redirect my dad’s and my own Mojave system to this fork to avoid long build times for Mojave for thé software de use there.

**Comment by gromgit** [comment]
Bottling is trivial; it's _building_ current software versions on Mojave that sometimes breaks in head-scratching ways.

If you see a formula without a bottle, one of the following is true:
1. The formula can't be built at all; `brew info` should tell you why somewhere in its output.
2. The formula hasn't been updated yet.
