### ISSUE TITLE
casks using: :svn to depend on svn

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/brew#11724]
### Provide a detailed description of the proposed feature

A lot of cask-fonts are using `svn` to download artifacts, but fail to download on a fresh system. It would be nice if `svn` will be automatically installed if url is `using: :svn`.

### What is the motivation for the feature?

Less manual steps and font download errors.

### How will the feature be relevant to at least 90% of Homebrew users?

Anyone who tries to install on a fresh system wouldn't need to install `svn` manually.

### What alternatives to the feature have been considered?

Explicitly add `svn` dependency to those casks.

**Comment by yurikoles** [comment]
As I understand, this issue was introduced when Xcode CLT stopped shipping `svn` binary.

**Comment by MikeMcQuaid** [comment]
Yes, this seems reasonable. Are there any other `using:` that auto-install dependencies?

**Comment by yurikoles** [comment]
I'm unsure, I didn't see this before.

**Comment by Git-Jiro** [comment]
Hi!
I would like to take a look at this.

If I understand this correctly:
New code will probably go here: 
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/font.rb

And this property needs to be parsed: https://github.com/Homebrew/brew/blob/1909d89d003bdf1f34775faf81b8c0529729013f/Library/Homebrew/cask/artifact/relocated.rb#L51

is this halfway correct?

**Comment by MikeMcQuaid** [comment]
@Git-Jiro don't think it's going to be font-specific logic. @Homebrew/cask folks can provide more help here, feel free to open a PR that's a bit broken and we'll do what we can to help ❤️

**Comment by vitorgalvao** [comment]
Note that installing `svn` happens *once **ever** per machine*. It is at worse a minor inconvenience which might not be worth it if it significantly complicates the code.

Alternatives:

* Relinquish the fonts repo to a third-party. (Not because of this; the matter has been considered before)
* Remove the SVN dependency [in favour of newer git commands](https://github.com/Homebrew/homebrew-cask/issues/111460).

**Comment by EricFromCanada** [comment]
Note that for formulae relying on SVN, brew already acknowledges that SVN is a dependency on systems where it isn't installed:
```
1015-Catalina ~ % brew deps --tree --include-build acme
acme
└── subversion
    ├── openjdk
    │   └── autoconf
    │       └── m4
    ├── pkg-config
    ├── python@3.9
...
```
The trick is getting brew to install SVN in those cases before attempting to download anything else.

**Comment by colindean** [comment]
While messing around with font casks in an experiment, I installed subversion to validate that my experiment's changed didn't break svn fonts. Searching around to check history of my experiment led me to this ticket.

I noted that I had no other reason to have svn installed. Upon installation, it newly installed several dependencies outside of my standard config for Linuxbrew. `brew deps --tree subversion` was surprising to me. I know some are very common but I'm curious if requiring subversion creates some extra package upgrade burden that would be nice to avoid for folks who otherwise don't need svn or its less-widely installed dependencies.

**Comment by Jerry1144** [comment]
> I know some are very common but I'm curious if requiring subversion creates some extra package upgrade burden that would be nice to avoid for folks who otherwise don't need svn or its less-widely installed dependencies.

There's always a way to do it manually. Just `svn checkout` then `tar -czf` then `brew edit` and replace these resources with your local copy - a `file://` URL.

I have a related issue though. `brew` now requires the newest `svn` for those resources even though an older `svn` works fine… In my case I'm running High Sierra so the latest bottled svn is `svn@1.8`, and building SVN builds some really heavy duty stuff beforehand, AND if I were to upgrade svn sometime later I'd need to upgrade those build dependencies again(!)

Think I need an environment variable that bypasses the svn dependency check and just use whatever svn it found in /usr/local/bin/

**Comment by MikeMcQuaid** [comment]
> Think I need an environment variable that bypasses the svn dependency check and just use whatever svn it found in /usr/local/bin/

No, sorry, we don't wish to adjust behaviour in this way for versions we no longer support (e.g. High Sierra)

**Comment by apainintheneck** [comment]
It looks like this could probably be handled with `git sparse-checkout` instead of `svn` now that https://github.com/Homebrew/brew/pull/14035 got merged in.

An extra `only_path:` option must be passed with the `git` url to specify the sparse checkout.

- [Description in the docs](https://docs.brew.sh/Cask-Cookbook#git-urls)
- [Example PR](https://github.com/Homebrew/homebrew-cask-fonts/pull/5758)

**Comment by MikeMcQuaid** [comment]
> It looks like this could probably be handled with `git sparse-checkout` instead of `svn` now that #14035 got merged in.
> 
> An extra `only_path:` option must be passed with the `git` url to specify the sparse checkout.

Yes, this would be ideal solution 👍🏻. CC @hmarr for thoughts or if you're working on this already.

**Comment by hmarr** [comment]
Thanks for the ping @MikeMcQuaid. I just moved the remaining fonts over to git in https://github.com/Homebrew/homebrew-cask-fonts/pull/6725

**Comment by MikeMcQuaid** [comment]
Thanks for finishing this off @hmarr!
