### ISSUE TITLE
Options for "brew search" to restrict search to online or local

### ISSUE THREAD

**Issue by chrisgrieser** [Homebrew/brew#11828]
### Provide a detailed description of the proposed feature

`brew search` should get an option to restrict where the search takes place. [The current options only allow to search for casks or formulaes](https://docs.brew.sh/Manpage#search--s-options-textregex-), but do not make it possible to restrict the search to online or local only. 

From what I can tell from [this issue from 2017](https://github.com/Homebrew/brew/issues/3056), it seems that homebrew looks online, local, and via the GitHub API for the searchterm. But often, you already know that you have a formulae/cask not installed and just want to search online (or you know that you have it installed and hence only want to search locally).

### What is the motivation for the feature?

Such an additional option would speed up `brew search` which takes ~7 seconds for me – as compared to the almost instand search results you get when searching at `https://brew.sh/blog/` directly.

Compared with other methods for optimizing search, this one should  be a fairly easy one to implement. Which means implementing this feature would have an efficient effort-to-benefit-ratio. ("low hanging fruit").

### How will the feature be relevant to at least 90% of Homebrew users?

- Increasing the speed of `brew search` will benefit practically all homebrew users.
- restricting your search only to certain areas will benefit all users who perform bulk searches online. 

### What alternatives to the feature have been considered?

to speed up many consecutive searches, I have used the web search at `https://brew.sh/blog/`, but it is of course not as convenient and programmable than doing it via `brew search`

**Comment by summer-wu** [comment]
I wish the same feature. I am comfortable with debian's `apt search`,which is a offline operation. 
Actually, I can use `find /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/ -name "*git*"` to find formulae that matches "*git*",but this way is hard to write.

**Comment by chrisgrieser** [comment]
@summer-wu oh good idea – I just wrote a small script that performs such a search. Well, in case this FR gets rejected, I at least got a decent workaround out of it, thanks.

```
casks=`find "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/" -name "*.rb" | cut -c 64- | sed -E 's/\.rb$/ --cask/'`
formulae=`find "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula" -name "*.rb" | cut -c 65- | sed -E 's/\.rb$/ --formula/'`

echo -n $casks $formulae | grep $query
```

**Comment by Rylan12** [comment]
You can bypass the GitHub API queries by temporarily setting `HOMEBREW_NO_GITHUB_API`. You can either set this in your shell profile to always forbid Homebrew from making these API calls or you can set it only for a given `brew` invocation by running `HOMEBREW_NO_GITHUB_API=1 brew search <foo>`

I did a quick speed test:

```console
$ hyperfine 'brew search git' 'HOMEBREW_NO_GITHUB_API=1 brew search git'
Benchmark #1: brew search git
  Time (mean ± σ):      6.151 s ±  0.341 s    [User: 3.862 s, System: 2.365 s]
  Range (min … max):    5.748 s …  6.613 s    10 runs

Benchmark #2: HOMEBREW_NO_GITHUB_API=1 brew search git
  Time (mean ± σ):      3.192 s ±  0.083 s    [User: 2.369 s, System: 0.752 s]
  Range (min … max):    3.110 s …  3.329 s    10 runs

Summary
  'HOMEBREW_NO_GITHUB_API=1 brew search git' ran
    1.93 ± 0.12 times faster than 'brew search git'
```

And you could, of course, make an alias to set this for you so you don't need to type the whole thing out every time. A script like the one you posted above will be even faster, too.

I'm not necessarily opposed to adding a `--local` flag here, but because there are other ways to accomplish the same thing I don't feel overly inclined to add it.

An alternative might be to use the [formula](https://formulae.brew.sh/api/formula.json] and [cask](https://formulae.brew.sh/api/cask.json]) APIs we have available on https://formulae.brew.sh (where you can, of course, search for formulae and casks). This would require downloading those JSON files and parsing them, though, which still takes some time (probably more time than just using the GitHub API).

Does the above solution work for you? If so, I think we can close this and if more people express interest in a `--local` flag we can re-evaluate.

**Comment by chrisgrieser** [comment]
@Rylan12 thanks for the detailled response!

I actually did not know about the possibility of just bypassing the Github API and happily set an alias for it. (Also, the code I posted above also works fine may have a lot of caveats, but works fine for 90% of the cases I use `brew search`. )

From me side, this issue can be closed. However, I would maybe suggest to mention this method at the brew-search-section of brew's man page, to make it easier to find for people like me who did not think of looking of the environment variables.

**Comment by Rylan12** [comment]
@chrisgrieser feel free to open a PR if you'd like. I wonder if this might be something that fits better in the [FAQ](https://docs.brew.sh/FAQ), though.

To understand my thinking, here's an analogous situation with `brew install`: if a user doesn't have homebrew/core or homebrew/cask tapped locally, they can still install official formulae and casks without needing to manually run `brew tap`. In these cases, `brew install` recognizes that the formula/cask is available in one of those taps and automatically taps it so that the formula/cask can be installed. This means that any user who understands that `brew install` installs what they want can effectively use Homebrew. They don't need to understand anything about the way it works behind the scenes (i.e. taps which can be very unfamiliar users) if they don't want to. As a result, we avoid frustrating users who don't understand why running `brew install` doesn't Just Work.

Similarly, we want `brew search` to be as useful for new users as possible. Any user should be able to just run `brew search` to search for something that they can immediately `brew install`, if that makes sense. Having a situation where a user doesn't get any results for a search because the taps aren't installed locally can be very confusing and frustrating. Especially since they could likely `brew install` what they were searching for just fine.

My worry with having information about `HOMEBREW_NO_GITHUB_API` so publicly is that setting this variable disables these helpful features. I anticipate a situation where a user sees in the help text "setting this variable will make Homebrew faster", setting it, and suddenly not being able to search and install things. Sure, those who want should be able to set it if they'd like, but it does seem okay to me to have it a bit hidden because only the people who know what they're doing will find it (hopefully).

Feel free to open a PR, anyway, though and we can see how other maintainers feel (they might not agree with me). Or, if you have a compromise I'd be happy to take a look.

Hope that makes sense and seems reasonable.

**Comment by chrisgrieser** [comment]
to be honest, I think you make a good point. Guess when I am (almost) the only one suggesting sth like `--local`, then the status quo should be fine after all.
