### ISSUE TITLE
Homebrew 3.2.10 does not respect HOMEBREW_NO_AUTO_UPDATE=1

### ISSUE THREAD

**Issue by ajsharp** [Homebrew/brew#12066]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab2118a402a44451b1d7559167b6956dc47cc19a
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 073c1b2f9d79dda3c5145782a12105bc086d221f
Core tap last commit: 13 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
```

### `brew doctor` output

```shell
Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  openexr

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to `brew install httpie` a library, and it updated every keg I have installed, despite the fact that I have the `HOMEBREW_NO_AUTO_UPDATE=1` env variable set. 

### What happened (include all command output)?

It updated every keg

### What did you expect to happen?

The keg I was installing to be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install httpie`
```

**Comment by Bo98** [comment]
`HOMEBREW_NO_AUTO_UPDATE` is to do with updating Homebrew itself, not formulae/kegs.

There is no system to autoupdate for every formula/keg in brew itself. There is however https://github.com/Homebrew/homebrew-autoupdate.

However, when installing new formulae or upgrading a specific one, this may sometimes trigger an upgrade for other formulae in the dependency tree. This is due to the nature of ABI compatibility and how the latest version of a formulae is only built and tested with the latest version of its dependencies - not with an arbitrary mixture. This can be large if you haven't upgraded much in quite some time. https://docs.brew.sh/FAQ#why-does-brew-upgrade-formula-also-upgrade-a-bunch-of-other-stuff

**Comment by ajsharp** [comment]
The problem is I don't want homebrew to randomly update all my packages when I run `brew install`. I was under the impression that's what the environment variable does. Is some other way to disable this behavior?

**Comment by scpeters** [comment]
take a look at the documentation for `HOMEBREW_NO_INSTALL_UPGRADE`, but we don't provide support for using outdated bottles

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/env_config.rb#L267-L270

**Comment by wjk** [comment]
> The problem is I don't want homebrew to update unrelated packages when I run `brew install`.

This. 100% this. I run Homebrew on my GitHub Actions CI server to install two formulae (CMake and Ninja), but then Homebrew goes and updates seven more formulae, stuff like aws-cli (which I don’t use), adding a solid 3 minutes or more to my build. For me this is just an annoyance since my repo is public, but were this a private  repo, this problem would be costing me money by eating up my expensive Mac build minutes.

I have added `export HOMEBREW_NO_INSTALL_UPGRADE=1` in [my CI script](https://github.com/PureDarwin/PureDarwin/blob/github-actions/.github/workflows/build-pr.yml), to no effect. I am using Homebrew 3.2.12, as installed on GitHub Actions’ macOS hosted runner ([documented here](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md)). Could you please provide some pointers as to what I am missing here? Thanks!

**Comment by Bo98** [comment]
Sounds like you're actually looking for `HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK`.

**Comment by ajsharp** [comment]
This should be a global default. Typing `brew install [package]` and then having homebrew update every other package installed on your system is so far outside of expected behavior and causes all kinds of downstream problems. Please please please disable this behavior by default.

**Comment by Bo98** [comment]
Having broken packages on your system is not a desirable default. It's not true it upgrades everything - only those in the same dependent tree.

Homebrew is an evergreen (rolling release) package manager. That means we only ship the latest version of anything, but this comes at the cost that we _also_ ship ABI breaking updates (which means anything depending on it needs a rebuild or they will simply no longer run at all) which can happen somewhat regularly depending on the formula. If you want this to not happen, you're looking for a package manager that enforces full "freezes" and only does major updates once a year or so. Evergreen package managers target people who upgrade their installed packages often and want the latest (and thus the number upgraded during the dependents check ends up being close to zero).

`HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK` exists because we recognise the CI scenario where the broken packages are often ones the developer didn't actually install themselves in the first place.

**Comment by MikeMcQuaid** [comment]
Yes, what @Bo98 said. If (and when) it was the global default: Homebrew will regularly break unrelated packages instead of upgrading them. 

Relatedly, just because you personally don't like this behaviour that's not a good reason for changing the default. We set the defaults based on what works for the majority of our millions of users based on issues reported and error-based analytics. We're not going to move to a default that's known to break installations in many circumstances.

**Comment by tlk** [comment]
> `HOMEBREW_NO_AUTO_UPDATE` is to do with updating Homebrew itself, not formulae/kegs.

I'm afraid this statement may need at little more detail because `HOMEBREW_NO_AUTO_UPDATE` may indeed prevent surprise upgrades of formulas.


By default, the `brew install [package]` command automatically runs `brew update --preinstall` which will update the formula files located in  Library/Taps/homebrew/homebrew-core before Homebrew proceeds to install [package].

Chances are, however, that some dependencies of [package] were already installed on the system before the user ran the `brew install [package]` command. Let's refer to those as *shared dependencies*. 

If there are updates available to a *shared dependency* (e.g. the corresponding .rb file in Library/Taps/homebrew/homebrew-core was updated since the dependency was installed) Homebrew will carry on and upgrade it.

Homebrew will **also** carry on and upgrade all packages that depend on a *shared dependency*.

This may lead to a cascade effect and users who are surprised to see existing packages/services ending up in an unusable state after running a seemingly innocent `brew install [package] command. See https://github.com/Homebrew/discussions/discussions/57 for examples of this.

The `HOMEBREW_NO_AUTO_UPDATE` environment variable changes this behaviour entirely (see [1]) because it stops `brew install [package]` commands from running `brew update --preinstall`. As a consequence, *shared dependencies* are not upgraded, and `brew install [package]` does not trigger a cascade effect of dependency upgrades.

With `HOMEBREW_NO_AUTO_UPDATE` the user must run `brew update` manually (to update Library/Taps/homebrew/homebrew-core) because it is no longer done automatically as part of install/upgrade/etc commands.

Personally, I find this leads to a more stable user experience and this is how I prefer to use Homebrew.

----

[1] The `HOMEBREW_NO_AUTO_UPDATE` environment variable prevents `brew install [package]` from upgrading *shared dependencies*:
https://github.com/Homebrew/brew/blob/e8ee5b05f9dfd0ec42870810f245d4ea3305845b/Library/Homebrew/brew.sh#L230-L270
