### ISSUE TITLE
Environment variable to always use --force-bottle

### ISSUE THREAD

**Issue by danijar** [Homebrew/brew#12366]
### Provide a detailed description of the proposed feature

Add an environment variable `HOMEBREW_ALWAYS_FORCE_BOTTLE` that if set to `1` causes all `brew install` commands to use the `--force-bottle` flag.

### What is the motivation for the feature?

When using a non-default Homebrew prefix, `brew install` often builds from source which is extremely slow. Passing the `--force-bottle` flag allows to install prebuilt binaries most of the time.

### How will the feature be relevant to at least 90% of Homebrew users?

The feature is relevant to all users who unfortunately cannot use the default Homebrew prefix `/use/local`. Using the default prefix is not possible on many company-managed laptops.

### What alternatives to the feature have been considered?

Manually passing the `--force-bottle` flag to all `brew install` commands is a possible alternative. However, it's easy to forget, especially when copying install commands from a website or running existing shell scripts. This causes frustration due to extreme slow installation.

**Comment by carlocab** [comment]
I don't think it's a good idea to make passing `--force-bottle` all the time easy for users to do. This prevents users from using bottles that likely don't work properly for their install prefix.

If some bottles are being mistakenly identified as non-relocatable, we should fix those instead rather than ignore `brew`'s relocatability detection wholesale.
