### ISSUE TITLE
Reinstate support for macOS Mojave

### ISSUE THREAD

**Issue by dandee** [Homebrew/brew#12371]
### Provide a detailed description of the proposed feature

Keep as long as possible pre-built bottles for macOS Mojave.

### What is the motivation for the feature?

As far as I know there's a number of developers holding on onto macOS Mojave due to a number of reasons (i.e. 32-bits support, older hardware, just minor migration to iOS UI.) I am the one.

There's still quite a number of applications and libraries still supporting macOS 10.14 either in binary/release form or build system not requiring any hacks to build and install on 10.14.

### How will the feature be relevant to at least 90% of Homebrew users?

Unfortunately I don't know the profile of Homebrew users. Is there an official web page reporting Homebrew user's macOS development environment?

### What alternatives to the feature have been considered?

Migration to MacPorts or Nix.

Or just do it manually, like in the olden, dark times : )

**Comment by carlocab** [comment]
We don't delete Mojave bottles. They do go away when a formula is rebuilt because we have no machines running Mojave to build them on. This happens, for example, when a formula gets a new version. You should be able to install bottles from formulae that haven't been updated since we dropped support for Mojave. (Indeed, some formulae still have bottles for Yosemite.)

Regarding the profile of Homebrew users, this might help: https://formulae.brew.sh/analytics/os-version/365d/

**Comment by dandee** [comment]
Thank you for the update. Can I sponsor machines running Mojave so you could keep providing precompiled bottles?

**Comment by scpeters** [comment]
> Thank you for the update. Can I sponsor machines running Mojave so you could keep providing precompiled bottles?

I'm not sure that Apple officially states the support lifetimes for their macOS releases, but you can see historically from the following table that the time between the "Initial release" and "Most recent version" is about 3 years, which in practical terms means that Apple stops supporting OS versions after 3 years, or equivalently that they only support 3 versions at any given time.

* https://en.wikipedia.org/wiki/MacOS_version_history#Releases

That is a kind offer of sponsorship, but it's not simply a matter of machine resources. I think the fact that Apple doesn't support macOS Mojave any longer is a blocker to homebrew-core continuing to support macOS Mojave by building bottles for it.

**Comment by carlocab** [comment]
As @scpeters explains, it's not just about the lack of build machines running Mojave: it's also about the support burden that building bottles on Mojave entails. (Indeed, the lack of build machines is a relatively trivial concern compared to the amount of work actually using those machines entail.)

Getting formulae to build on three macOS versions is tricky enough; we don't have the resources to add a fourth to that.

We do, however, welcome pull requests that fix formulae so that they work on versions of macOS that we don't test, as long as [it's newer than 10.10](https://docs.brew.sh/Installation). We do go to some lengths to make sure `brew` itself continues to function on Yosemite and newer. Extending support for formulae, however, would stretch our resources far too thinly.

**Comment by dandee** [comment]
Thanks for the discussion guys.
