### ISSUE TITLE
Improve user experience around package updates

### ISSUE THREAD

**Issue by 0xc0000007b** [Homebrew/brew#12523]
### Provide a detailed description of the proposed feature

Increase time to auto-update to `604800` from the current `300` specified.

### What is the motivation for the feature?

Homebrew tries to update dependencies more often than I use the bathroom.

### How will the feature be relevant to at least 90% of Homebrew users?

They will love it. All of them. Especially the `HOMEBREW_NO_AUTO_UPDATE` fans.

### What alternatives to the feature have been considered?

Add a `HOMEBREW_YES_AUTO_UPDATE` flag and disable auto-updates by default.

**Comment by carlocab** [comment]
`HOMEBREW_NO_AUTO_UPDATE` does not change any software you have installed, so it seems your motivation is based on a misunderstanding.

It's very unlikely that we're going to do this, since the `300` second default is configurable. If you still want to purse this despite that, please open a pull request so we can have a proper discussion about the merits of this.
