### ISSUE TITLE
Make public the request from GitHub regarding full clone and fetch.

### ISSUE THREAD

**Issue by Dmole** [Homebrew/brew#12558]
### Provide a detailed description of the proposed feature

I found this issue

https://github.com/Homebrew/brew/issues/11693

then looked at the data

https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/

Git CPU spent per operation on the Linux kernel
```
Shallow clone and    full fetch: 40s +    50ms
Full    clone and    full fetch: 60s +    40ms
Full    clone and shallow fetch: 60s + 1,000ms
```

So I can see why github would not want many shallow fetches but even with many fetches they also pay for data so "Shallow clone and full fetch" seems like is should be best for github and best for users.

Can we make the "request from GitHub" public to clarify their stance?

### What is the motivation for the feature?

space, time, cpu, $, saving

### How will the feature be relevant to at least 90% of Homebrew users?

space, time, cpu, $, saving

### What alternatives to the feature have been considered?

Black boxes

**Comment by MikeMcQuaid** [comment]
> Can we make the "request from GitHub" public to clarify their stance?

No.

> Git CPU spent per operation on the Linux kernel

1) the Linux kernel and homebrew-core/homebrew-cask have very different layouts and clone behaviours
2) the full vs. shallow clone time and CPU usage are not enough here without also factoring in repeatedly fetching from a shallow clone (which is what the issue is and is the behaviour we avoid). There's nothing to stop you doing a manual shallow clone, we just won't `brew update it.
