### ISSUE TITLE
Add HOMEBREW_FORCE_BREWED_PATCH variable

### ISSUE THREAD

**Issue by sergeycherepanov** [Homebrew/brew#12688]
### Provide a detailed description of the proposed feature

I working on standalone build for the Docker, but currently it not possible to apply patch if only the gpatch formula installed. It requires to setup whole build envirment for the linux, although the formula can builded from source by the Homebrew without any dependencies.

### What is the motivation for the feature?

Independence from installed binaries on the target OS.

### How will the feature be relevant to at least 90% of Homebrew users?

I think it can make builds like docker image more flexible.

### What alternatives to the feature have been considered?

Currently workaround only install the patch command to the target system.

**Comment by MikeMcQuaid** [comment]
I don't understand what you're asking, can you explain a bit more? Are you saying you want to use `gpatch` from Homebrew instead of `patch` from the system?

**Comment by MikeMcQuaid** [comment]
And if so: why is that? Thanks!

**Comment by carlocab** [comment]
> the formula can builded from source by the Homebrew without any dependencies.

Currently it can. There's no guarantee it will stay that way, however, since it's entirely possible that the `gpatch` formula may itself need patching at some point. Then you would still need a pre-existing `patch` to install `gpatch`.

Note that `HOMEBREW_FORCE_BREWED_{CURL,GIT}` doesn't remove the requirement of a system install of `curl`/`git`, for essentially the same reasons as above, so I don't think implementing a `HOMEBREW_FORCE_BREWED_PATCH` will really do what you want.

It may cover over 90% of cases, though, so maybe doing something like it may still work. However, instead of `HOMEBREW_FORCE_BREWED_PATCH`, I suggest having `brew` fall back to `gpatch`'s `patch` when it can't find `patch` in your system.

**Comment by sergeycherepanov** [comment]
@carlocab @MikeMcQuaid 
Yes, the main idea to use system tools only during installation of brewed alternatives. Currently this works for the curl and git. But not for the gpatch.
I checked it in the debug mode and noted that it does not exists in the PATH folders. 
May be issue related to a shim, but I am not sure.

**Comment by MikeMcQuaid** [comment]
> I suggest having `brew` fall back to `gpatch`'s `patch` when it can't find `patch` in your system.

We'd review a PR request for this but I don't think this is a priority for maintainers at the moment, sorry.
