### ISSUE TITLE
32-bit Support for iSH/Alpine Linux running on iOS/iPad OS devices

### ISSUE THREAD

**Issue by hilga007** [Homebrew/brew#12862]
### Provide a detailed description of the proposed feature

Tweak the installation script to allow Homebrew to be installed in an iSH instance running essentially a sandboxed Alpine Linux 3.14 instance. This Linux instance is running an ARM64 --> i686 layer so Alpine is a 32-bit distribution of Linux. **This is for non-jailbroken devices. iSH is available via the AppStore.** 

### What is the motivation for the feature?

Being able to run Homebrew on iPhones and iPads with all of the potential that unlocks and brings to the table for having Linux applications and development "natively" available even when unable to SSH into anything, or if the iOS is the student/person's only device. 

Basically Homebrew unlocks quite a bit of potential on the Mac, and it would do so as well on iDevices thanks to Alpine. However: it uses musl instead of glibc, and the shell is "ash" instead of bash (according to Neofetch): so consideration must be made there. 

However, installing _apk add bash_ seems to work. 

### How will the feature be relevant to at least 90% of Homebrew users?

If 90% of Homebrew users are using Homebrew on a Mac: then they likely also have an iPhone. They will then be able to develop and play natively on their iDevice and also be able to use iSH to SSH into their Mac to keep there work and play going there! 

### What alternatives to the feature have been considered?

Have considered A-Shell as well, but that is more complicated to get Homebrew on I believe as it is a shell emulator with no actual Linux kernel, no complete toolchain, and yeah it just sucks.

**Comment by carlocab** [comment]
We're unable to provide binary packages for 32-bit or musl-based Linux systems. iSH is both 32-bit and musl-based, so it's probably a very long way from getting binary packages.

The install script works only on systems for systems where our binary packages work, and we're not interested in extending the installer beyond this.

If having to build from source doesn't deter you, you might be able to install `brew` using one of the [alternative install methods](https://docs.brew.sh/Installation#alternative-installs). You will likely need to provide your own `ruby` that is compatible with Ruby 2.6.8. This should be enough to get `brew` working, but I suspect you'll struggle with getting things you install to work (because `brew` currently only works with `glibc`).

If you want to play around with `brew` on your iOS device, it's probably a lot easier to just `ssh` into a Mac and run `brew` from there.
