### ISSUE TITLE
uwsgi failed to run properly on 10.11.6

### ISSUE THREAD

**Issue by achikin** [Homebrew/brew#1288]
```
brew install uwsgi --with-python
uwsgi --plugin python,http --http :9000 --wsgi-file myapp/wsgi.py
!!! UNABLE to load uWSGI plugin: dlopen(/usr/local/Cellar/uwsgi/2.0.14/libexec/uwsgi/http_plugin.so, 10): Symbol not found: _uwsgi_opt_corerouter
  Referenced from: /usr/local/Cellar/uwsgi/2.0.14/libexec/uwsgi/http_plugin.so
  Expected in: dynamic lookup
 !!!
uwsgi: option `--http' is ambiguous
getopt_long() error
```
config, doctor and gist-logs https://gist.github.com/achikin/2a2397fe4a251c39802fcfc2a70931e9

**Comment by MikeMcQuaid** [comment]
@achikin a note for future: please create formulae issues on homebrew/homebrew-core and please either edit or comment on existing issues rather than closing and reopening them. Leave this one as-is for now though, thanks.

> → brew gist-logs uwsgi
> Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
> Scopes it has: ["public_repo"]
> Create a new personal access token: https://github.com/settings/tokens
> and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
> Error: {
>   "message": "Not Found",
>   "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
> }

There's no logs here; can you follow the quoted instructions to upload them? Thanks.

**Comment by achikin** [comment]
@MikeMcQuaid It is not clear from docs what access the token should have. Could you please clarify?
