### ISSUE TITLE
`brew doctor` checks files in /usr/local/* rather than $HOMEBREW_PREFIX/*

### ISSUE THREAD

**Issue by notxarb** [Homebrew/brew#13079]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.4-44-gb2b029e-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: b2b029e311ca64b77635e5ea2478fd2b5a32e656
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6d39ec57711aba718cb650660540b85e124316f7
Core tap last commit: 20 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-arm64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am running `brew doctor` on an m1 mac

### What happened (include all command output)?

```
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h
```

### What did you expect to happen?

no issues to find

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
This is running on an m1 mac.
This computer had things installed on it by my employer (probably dropping some libs into `/usr/local` prefix).
Homebrew is installed with the `/opt/homebrew` prefix because this is a m1 mac, and shouldn't be conflicting with things installed in `/usr/local`.
```

**Comment by gromgit** [comment]
`brew doctor` tells you _why_ it's warning about _/usr/local_:
>```
>If you didn't put them there on purpose they could cause problems when
>building Homebrew formulae, and may need to be deleted.
>```

If you _never_ build Homebrew formulae from source, then you can ignore the warning.

However, a whole bunch of other Homebrew users do so, and since most open-source software default to looking in `/usr/local` for their dependencies _regardless of platform_, having unexpected libraries and include files that don't match what a Homebrew-mediated build expects can result in truly bizarre errors and a lot of head-scratching all round. `brew doctor` always checking `/usr/local` helps Homebrew maintainers, and helpers like me, quickly zero in on potential reasons for issues and/or quickly eliminate the same from consideration.

**Comment by notxarb** [comment]
That makes sense.

**Comment by dexterurbane** [comment]
But the `brew doctor` command *only* checks for stray files in `/usr/local`, and does *not* check `/opt/homebrew`, on an m1 mac. While there may be a rationale for checking `/usr/local`, surely this should at least be *in addition to* `HOMEBREW_PREFIX`, if they are different. See [this closed pull request](https://github.com/Homebrew/brew/pull/13080) from [notxarb](https://github.com/notxarb).

**Comment by gromgit** [comment]
FWIW, I'm not sure it's worth the additional `brew doctor` runtime, because it's far less likely that errant stuff is dumped in a purpose-built hierarchy like `/opt/homebrew` that no one but Homebrew codes for, than a purposely well-known one like `/usr/local` that's used by default in most projects.

But anyone who feels strongly enough can put up a PR to add checking `/opt/homebrew` to `brew doctor`. It must just be rejected by the maintainers, that's all.

**Comment by dexterurbane** [comment]
Yes, that logic occurred to me right after I posted above as being the likely argument here.

I was stung by this, because for some reason that I can't fathom and didn't bother investigating (maybe just some past brainfart on my part), meson + ninja was installing some user built stuff in /opt/homebrew. I ended up temporarily changing homebrew's diagnostic.rb script to make sure everything was cleaned up properly. However, I agree this circumstance would be extremely rare, so I'll opt out here!

**Comment by carlocab** [comment]
> meson + ninja was installing some user built stuff in /opt/homebrew. 

This is odd. If you discover that this turns out to be a consequence of the way we configure `meson`, please file an issue at Homebrew/Homebrew-core.

**Comment by dexterurbane** [comment]
Will do. However, I just tested using my freshly updated homebrewed meson, and the default install directory seems to be `/usr/local` as expected. Either a temporary problem has been fixed or, more likely, there was some lapse of concentration on my part, where I accidentally set a custom prefix to `/opt/homebrew`. No idea why I'd do that, but not worth worrying too much about!

**Comment by MikeMcQuaid** [comment]
> FWIW, I'm not sure it's worth the additional `brew doctor` runtime, because it's far less likely that errant stuff is dumped in a purpose-built hierarchy like `/opt/homebrew` that no one but Homebrew codes for, than a purposely well-known one like `/usr/local` that's used by default in most projects.
> 
> But anyone who feels strongly enough can put up a PR to add checking `/opt/homebrew` to `brew doctor`. It might just be rejected by the maintainers, that's all.

Agreed.
