### ISSUE TITLE
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install）"

### ISSUE THREAD

**Issue by Xcq5678** [Homebrew/brew#134]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue.

### Feature Requests:

**Please note by far the quickest way to get a new feature into Homebrew is to file a [Pull Request](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by DomT4** [comment]
What problem are you having? There doesn't seem to be any description beside the template above.

**Comment by wakerman** [comment]
╰─○ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Counting objects: 463, done.
remote: Compressing objects: 100% (420/420), done.
remote: Total 463 (delta 26), reused 271 (delta 17), pack-reused 0
Receiving objects: 100% (463/463), 748.41 KiB | 47.00 KiB/s, done.
Resolving deltas: 100% (26/26), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
HEAD is now at 2921795 update: rebase (rather than merge) by default.
/usr/local/Library/brew.sh: line 235: /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby: No such file or directory
/usr/local/Library/brew.sh: line 235: exec: /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby: cannot execute: No such file or directory
Failed during: /usr/local/bin/brew tap homebrew/core


help me.please.

**Comment by mikemcquaid** [comment]
What does `ls -lha /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby` say? It looks like you may have deleted it.

**Comment by phylaxis** [comment]
I'm having this same issue using Homebrew on an old Mac running OS X 10.6.8 and for the ruby results I get this:

```-rwxr-xr-x  1 root  wheel    50K Jan 23  2013 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby```

**Comment by mikemcquaid** [comment]
@phylaxis You probably need to `brew install git`

**Comment by phylaxis** [comment]
Hey @mikemcquaid thanks for the response, I though GIT was installed on this machine, but maybe not. I'll check it out more closely.

**Comment by ilovezfs** [comment]
@Xcq5678 were you able to fix the problem?

**Comment by mikemcquaid** [comment]
Closing this out as no-one has provided the information requested in the templates.
