### ISSUE TITLE
Feature proposal: Extrernal Tap Config

### ISSUE THREAD

**Issue by DerekTBrown** [Homebrew/brew#13499]
### Provide a detailed description of the proposed feature

At install-time, a user can specify a path/url to a JSON file. Example:

```
export TAP_FILE=/etc/my_tapfile.json
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

export TAP_FILE=https://raw.githubusercontent.com/my-org/my-brew-config/master/brew.json
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

This JSON file is stored in `Library`, and is as the source of truth for tap configuration. This enables some additional functionality:

### Feature 1: Repository list
The json file can define a list of taps. For instance:
```
{
"taps" : {
  "Homebrew/homebrew-core" : {
     ...
  },
  ....
}
```

When homebrew checks for repository updates, Homebrew will:
1. Update its local copy of the JSON file (if a URL).
2. `tap` each of the taps specified in the `taps` object.

Users will be unable to modify `

### Feature 2: Specific commits
As an extension of the feature above, the json file can specify a specific version of a tap to use:
```
{
"taps" : {
  "Homebrew/homebrew-core" : {
     "commit": "475895599513d9fc6731ca4aa9b7db1fdb4659f1",
     ...
  },
  ...
}
```
When homebrew checks for package updates, Homebrew will:
1. Update its local copy of the JSON file (if a URL).
2. `tap` each of the taps specified in the `taps` object.
3. Checkout this specific commit

### Feature 3: Tarball
In lieu of the `commit` option, the json file can specify a tarball to use:
```
{
"taps" : {
  "Homebrew/homebrew-core" : {
     "tar": "https://github.com/Homebrew/homebrew-core/tarball/master",
     ...
  },
  ...
}
```
When homebrew checks for package updates, Homebrew will:
1. Update its local copy of the JSON file (if a URL).
2. `tap` each of the taps specified in the `taps` object by downloading a tarball (no git).

### Feature 4: Allowed versions
In each tap object, the user can specify a permitted set of formulae or casks:
```
{
"taps" : {
  "Homebrew/homebrew-core" : {
     "allowedFormulae": [
            "ansible"
     ],
     "allowedCasks": [
            ...
      ]
  }
  ...
}
```

If specified, a user may only install these formulae/casks.

### What is the motivation for the feature?

Homebrew is a powerful way for users to install development tools. However, allowing enterprise users to install packages via Homebrew introduces a number of security risks:

- Users often install formulas/casks without confirming that these formulas are secure.
- Casks/formula can change over time, meaning that a security vulnerability could be introduced after a cask has been audited.

External tap configuration would allow administrators to install *guardrails* to make it easier for users to verify the tools they are installing are safe/supported.

### How will the feature be relevant to at least 90% of Homebrew users?

These features provide benefits for enterprise and non-enterprise Homebrew users alike:

1. Many Homebrew users complain about long download times. The ability to download core/taps via a tarball will greatly reduce download and update time.

2. Currently, it is difficult to install an old version of a Homebrew formula. These features will make it easy for Homebrew users to downgrade to an older version of a formula, if needed.

3. These changes would encourage the adoption of Homebrew in more enterprise contexts, and allow existing Homebrew users to use their Homebrew tooling at work.

### What alternatives to the feature have been considered?

The best alternative I can think of would be to maintain a selective Homebrew mirror (as it seems several academic institutions do). This has a few drawbacks:

1. Mirrors still rely on `git` for underlying replication, which can be slow for users.

2. In order to limit the set of installable formulae/casks, the mirror maintainer must selectively copy Formulae into the mirror. This is potentially tedious and error prone (since Cask dependencies can change).

3. This is not an extensible solution; institutions must maintain a mirror for each tap.

Alternatively, an institution could copy the formulae it wishes to permit into their own tap. This has even more drawbacks:

1. Mirrors still rely on `git` for underlying replication, which can be slow for users.

2. The maintainer must manually copy formulae (and dependencies) into the tap.  Users may not receive immediate upgrades.

3. This leads to a poor user experience, as there are package conflicts.

**Comment by Rylan12** [comment]
Thanks for the write-up, but I don't think this is something we're currently interested in implementing. Here are my responses to some of your comments:

> * Many Homebrew users complain about long download times. The ability to download core/taps via a tarball will greatly reduce download and update time.

The `HOMEBREW_INSTALL_FROM_API` environment variable helps with this by not requiring a user to have Homebrew/homebrew-core and Homebrew/homebrew-cask installed locally. It's currently functional for most packages (and you're welcome to use it), but is also still being actively improved since there are a few known issues.

> * Currently, it is difficult to install an old version of a Homebrew formula. These features will make it easy for Homebrew users to downgrade to an older version of a formula, if needed.

[Homebrew doesn't support installing old versions of formulae](https://github.com/Homebrew/homebrew-core/security/policy#supported-versions), so we're not really interested in making it easier to do that.

> * These changes would encourage the adoption of Homebrew in more enterprise contexts, and allow existing Homebrew users to use their Homebrew tooling at work.

If an organization is going to spend the time to compile which taps are needed, which revisions must be used, and which formulae are available, it's not really much more work to create their own tap with the exact formulae and versions that are desired.

> * Users often install formulas/casks without confirming that these formulas are secure.
> * Casks/formula can change over time, meaning that a security vulnerability could be introduced after a cask has been audited.

Homebrew believes that [users are expected to know about the software they are installing](https://docs.brew.sh/Acceptable-Casks#apps-that-bundle-malware), so if an organization is concerned enough about potentially insecure software being installed via Homebrew that they don't want their members installing things that aren't pre-approved, they should either not use Homebrew or create a tap containing only the formulae they allow.

**Comment by MikeMcQuaid** [comment]
> 2\. `tap` each of the taps specified in the `taps` object.

`brew bundle` (https://github.com/homebrew/homebrew-bundle) is a better fit for this.



> However, allowing enterprise users to install packages via Homebrew introduces a number of security risks:
> 
> * Users often install formulas/casks without confirming that these formulas are secure.

There's an assumption that enterprise administrators are better custodians of secure software delivery than Homebrew maintainers that, unsurprisingly, I disagree with.

> * Casks/formula can change over time, meaning that a security vulnerability could be introduced after a cask has been audited.

In theory, yes. In practise, freezing formulae or casks at a specific version is more likely to result in users sitting on old versions with known or unknown security vulnerabilities.

> External tap configuration would allow administrators to install _guardrails_ to make it easier for users to verify the tools they are installing are safe/supported.

This sounds bad for Homebrew and bad for Homebrew's users. It only sounds good for enterprise administrators to be able exert more control on Homebrew's users. I don't want to encourage or enable this.

> * Currently, it is difficult to install an old version of a Homebrew formula. These features will make it easy for Homebrew users to downgrade to an older version of a formula, if needed.

It is difficult because these old versions are not supported because they are often broken with new macOS versions, Xcode versions and dependency tree changes. 

> 3\. These changes would encourage the adoption of Homebrew in more enterprise contexts, and allow existing Homebrew users to use their Homebrew tooling at work.

Homebrew is already widely used in many enterprises. I would rather the enterprises that do not currently allow usage of Homebrew update their understandings of consuming open source software rather than providing a tool for Homebrew's users to be restricted by their employers.

> The `HOMEBREW_INSTALL_FROM_API` environment variable helps with this by not requiring a user to have Homebrew/homebrew-core and Homebrew/homebrew-cask installed locally. It's currently functional for most packages (and you're welcome to use it), but is also still being actively improved since there are a few known issues.

Yup, this will make a big different to download times.

---

Passing on this, sorry!
