### ISSUE TITLE
`livecheck` `PageMatch` should allow CSS `selector`/`xpath` queries rather than only a `regex`

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/brew#13531]
### Provide a detailed description of the proposed feature

Since _Nokogiri_ is already available, why not make use of it’s [`HTML.parse`](https://nokogiri.org/tutorials/parsing_an_html_xml_document.html#from-the-internets) and [`at_css`](https://nokogiri.org/rdoc/Nokogiri/XML/Searchable.html?h=at_css#method-i-at_css) [[selector](https://devhints.io/css)] methods?

Given for example, something like:
~~~ html
<h2 class="version">
  Version
</h2>
<div id="latest">
  1.2
</div>
~~~
it can be awkward to write a regular expression to find the version match, whereas instead, we could have something like:
~~~ rb
livecheck do
  url :homepage
  strategy :page_match
  selector "h2.version + #latest"
end
~~~
which would actually be a method that looks something like this:
~~~ rb
module Livecheck
  def selector(selector) # "h2.version + #latest"
    require "nokogiri"
    doc = Nokogiri::HTML.parse url # :homepage
    version = doc&.at_css selector # "\n  1.2" 
    /(\d+(?:\.\d+)+)/.match version&.text&.squish # 1.2
  end
end
~~~
giving us the `1.2` version match. Another example would be, given:
~~~ html
<a href="https://github.com/user/example/archive/v1.2.3.tar.gz">Download</a>
~~~
we could do:
~~~ rb
repo = "github.com/user/example"

livecheck do
  url :homepage
  strategy :page_match
  selector "a[href*='#{repo}'][href$='.tar.gz']"
end
~~~

### What is the motivation for the feature?

Regular Expressions can be an awkward way to parse HTML.

### How will the feature be relevant to at least 90% of Homebrew users?

Many formulae/Casks rely on `livecheck` blocks. Making them easier/faster to write and get working helps contributors like me, which in turn benefits users.

### What alternatives to the feature have been considered?

Alternatively, we could allow using [XPath queries](https://devhints.io/xpath), making use of the [`at_xpath` method](https://nokogiri.org/rdoc/Nokogiri/XML/Searchable.html?h=at_xpath#method-i-at_xpath).

Given the example above:
~~~ html
<h2 class="version">
  Version
</h2>
<div id="latest">
  1.2
</div>
~~~
we could do:
~~~ rb
livecheck do
  url :homepage
  strategy :page_match
  xpath "//h2[@class='version']/following::div[@id='latest']" #/text()
end
~~~

Although these are less well-known/user-friendly than CSS selectors, they are not mutually exclusive approaches and both are already available with Nokogiri.

**Comment by MikeMcQuaid** [comment]
CC @samford and @nandahkrishna for thoughts.

**Comment by samford** [comment]
I updated the title as this would not apply to `HeaderMatch` (i.e., it only checks HTTP headers, not body content like HTML).

I've explored using `nokogiri` within livecheck before, primarily in relation to exceptional situations where a regex may not be the easiest solution (e.g., technically feasible but potentially complex). For what it's worth, `nokogiri` is in our dependency tree but we don't directly use it anywhere in `brew` at the moment (we previously used it for XML parsing but we replaced it with `REXML` and removed `nokogiri` from the `Gemfile`).

One thing that's important to mention is that `livecheck` block regexes serve two purposes: matching text containing version information and using capture groups to extract [version] strings.

From my perspective, a CSS selector can help to match specific elements but the complexity lies in how the version information is extracted. A regex is flexible enough to be able to accommodate a variety of situations and `PageMatch` simply uses the first capture group from each match (anything more complex requires a `strategy` block). I don't see us being able to create one approach that would work for all Nokogiri elements in a similar fashion. For example, sometimes we want to work with an element attribute (e.g., `href`), other times we want to parse the inner text, etc.

For me, this idea has previously taken the shape of an `Html` strategy (using `nokogiri` internally) that could use a CSS selector to determine which elements are matched, with the logic for extracting version strings defined in a `strategy` block. A regex wouldn't be explicitly required but could be passed into a `strategy` block (e.g., to extract the version from text), if provided.

As an example, one situation that we've faced before where this could potentially be beneficial is when we want to match the inner text of an element without having to work around nested tags:

```html
<span class="version">
  Version <b>1.2.3</b>
</span>
```

A somewhat robust regex matching elements with the `version` class could look like:

```ruby
regex(/<[^>]+?class=["'][^"']*?version[^"']*?["'][^>]*?>\s*Version\s+?.*?(\d+(?:\.\d+)+)\s*</im)
```

Though this would work, the amount of boilerplate just to accommodate ambiguity (e.g., handling other classes before/after `version`, whitespace, etc.) makes for a pretty gnarly regex. Granted, we would likely just use `/>\s*Version\s+?.*?(\d+(?:\.\d+)+)\s*</i` for the sake of brevity, if we could get away with it in this context.

An alternative implementation using an `Html` strategy could look like:

```ruby
livecheck do
  url :homepage
  selector ".version"
  regex(/v?(\d+(?:\.\d+)+)/i)
  strategy :html do |elements, regex|
    elements.map { |element| element.text[regex, 1] }
  end
end
```

The strategy would take care of parsing the HTML, selecting the elements, and passing them to the `strategy` block. It ends up being more sane/readable but it may raise the barrier to entry rather than lowering it (i.e., requiring knowledge of CSS selector syntax in addition to Nokogiri's API). If we make some common regexes available within livecheck as constants (I have some local work in the pipeline that I need to wrap up), then we could sometimes omit the `#regex` call in this particular situation but inevitably we would end up needing `#selector`, `#regex`, and a `strategy` block in some situations.

As another example, let's say we want to match versions from `href` attributes, which is a very common situation. A regex approach typically looks like:

```ruby
livecheck do
  url "https://www.example.com/downloads"
  regex(/href=.*?example[._-]v?(\d+(?:\.\d+)+)\.t/i)
end
```

An `Html` alternative may look like:

```ruby
livecheck do
  url "https://www.example.com/downloads"
  selector "a"
  regex(/example[._-]v?(\d+(?:\.\d+)+)\.t/i)
  strategy :html do |elements, regex|
    elements.map do |element|
      url = element.attr("href")
      next if url.blank?

      url[regex, 1]
    end
  end
end
```

Since this is common, maybe it would just be its own strategy that handles the above logic internally:

```ruby
livecheck do
  url "https://www.example.com/downloads"
  regex(/example[._-]v?(\d+(?:\.\d+)+)\.t/i)
  strategy :html_links
end
```

In the end, the only difference compared to the regex-only example is that we could omit `href=.*?` from the start of the regex, so it doesn't seem worth the additional overhead in common cases like this. [It's maybe worth mentioning that we could technically parse versions from some URLs using `Version#parse` but it may not be useful, as we would need to restrict matching to appropriate URLs using `#selector` or `#regex` anyway.]

-----

All that said, I don't see this as necessarily easier/faster in practice and may just be different (i.e., it trades one type of complexity for another). I'll admit that most contributors probably wouldn't want to touch the lengthy regex above with a ten foot pole but regexes like that are uncommon and it was a fairly extreme example for the sake of discussion.

This could be useful for certain less common situations but I haven't introduced an `Html` strategy yet because of some misgivings. I'm not convinced that this would be something that we would want to adopt as a default in place of `PageMatch` and I've been concerned that making it available could fracture the `livecheck` block ecosystem if we're not careful (i.e., some may use an `Html` strategy out of preference, even when it's not necessary).

I've put a lot of effort into establishing some sort of standardization of `livecheck` blocks over time (more so in homebrew/core, as I'm still working on cleaning up homebrew/cask `livecheck` blocks) and I worry that this could make things worse by reducing overall consistency. I support the general idea of trying to make it easier to write `livecheck` blocks but this feels like a lateral move rather than a step forward.

Granted, this is just my perspective and I could be overlooking things, so I would be interested in other viewpoints.
