### ISSUE TITLE
'brew style --fix' does not autocorrect syntax format of bottle block

### ISSUE THREAD

**Issue by uptycs-rishi** [Homebrew/brew#13685]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.9-3-g4a623e0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4a623e0a2532a00a42474c755b8c03e927594676
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6964a087067d323f14e9ebc188be8d72be46e275
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.37.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 12.3
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (12.3) is outdated.
Please update to Xcode 13.2.1 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

My project currently uses Homebrew 2.7.x to install its required dependencies on macOS 11.x
So, I'm trying to update Homebrew to 3.5.x (to be able to build my project on macOS 12.x)

### What happened (include all command output)?

On updating Homebrew, installation of my project dependencies specified through formulae files, fails with an **undefined method 'cellar'** error due to the change in syntax format of the bottle block added in version 3.0.0 ([link](https://brew.sh/2021/02/05/homebrew-3.0.0/)), where it is also mentioned that `brew style --fix` should autocorrect formulae to this new format.

However, `brew style --fix` does not make the required changes to the bottle block for these formulae files

Attached is one such formula file [xz.rb](https://github.com/Homebrew/brew/files/9308155/xz.rb.txt) and the same file after running `brew style --fix` [xz_fixed.rb](https://github.com/Homebrew/brew/files/9308154/xz_fixed.rb.txt)
Also attached is the command output [command_output.txt](https://github.com/Homebrew/brew/files/9308153/command_output.txt)

### What did you expect to happen?

`brew style --fix` should autocorrect bottle blocks in the formulae according to the new syntax format

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew style --fix xz.rb
brew install xz.rb
```

**Comment by Rylan12** [comment]
Is that formula part of a tap? I think the problem might be that you're running `brew style` on the file directly instead of on a formula in a tap. If it's in a tap, try running without the `.rb` extension (you probably will need to pass the full formula name so there's no conflict with homebrew/core `xz`) like `brew style --fix foo/bar/xz`. If it's not in a tap, try temporarily creating one and putting the formula in there (see `brew tap-new`). You can delete the tap when you're done.

**Comment by uptycs-rishi** [comment]
Thanks for your comment @Rylan12
Yes, the formula is part of a tap and I tried `brew style --fix full_formula/xz` but I still get the **undefined method 'cellar'** error when trying to install it

**Comment by Rylan12** [comment]
Gotcha. I can reproduce this.

The cause is that in your formula, you have `Xz < AbstractOsqueryFormula` while the default for most formulae is `Xz < Formula`. The list of valid superclasses can be found [here](https://github.com/Homebrew/brew/blob/e30b2a173cfe4c7ed0cf9bb4103db020a542879b/Library/Homebrew/rubocops/extend/formula.rb#L184-L189), but all of those except `Formula` have been deprecated. I think the best solution for your case may be to temporarily change `AbstractOsqueryFormula` to `Formula`, run `brew style --fix`, and then re-replace with `AbstractOsqueryFormula` (assuming it's not practical to actually use `Formula` as the superclass which would be preferable)

**Comment by uptycs-rishi** [comment]
This works!
Yes it would not be possible to use `Formula` as the superclass in my case.
Temporarily replacing `AbstractOsqueryFormula` with `Formula` and running `brew style --fix` does fix the issue.
Thanks for the help and analysis! @Rylan12
