### ISSUE TITLE
`brew deps -n` does not work

### ISSUE THREAD

**Issue by alexreg** [Homebrew/brew#137]
The output dependencies are clearly not in topological order.

```sh
$ brew deps --1 -n --installed --include-build --include-optional
aalib: 
asciidoc: docbook docbook-xsl
atk: glib gobject-introspection pkg-config xz
autoconf: 
autogen: guile pkg-config xz
automake: autoconf xz
aview: aalib
bash: readline
homebrew/versions/bash-completion2: 
bashdb: bash
bdw-gc: libatomic_ops pkg-config
berkeley-db: 
binutils: 
boost: icu4c open-mpi
bullet: cmake
cairo: fontconfig freetype glib libpng pixman pkg-config xz
homebrew/boneyard/celt: libogg
cloog: gmp isl pkg-config
homebrew/versions/cloog018: gmp4 isl011 pkg-config
cmake: sphinx-doc
colordiff: 
coreutils: gmp xz
cpptest: 
cppunit: 
cpulimit: 
cscope: 
ctags: 
curl: c-ares libidn libmetalink libressl libssh2 nghttp2 openssl pkg-config rtmpdump
homebrew/x11/curlftpfs: autoconf automake glib libtool osxfuse pkg-config
czmq: libsodium pkg-config zeromq
czmqpp: autoconf automake czmq git libtool pkg-config
dar: gettext gnu-sed libgcrypt lzo upx
djvu2pdf: djvulibre ghostscript
djvulibre: jpeg libtiff
docbook: 
doxygen: cmake graphviz
duck: ant
eigen: cmake
faac: 
homebrew/games/fairymax: git
fdk-aac: 
flac: libogg pkg-config xz
flex: gettext
fondu: 
fontconfig: freetype pkg-config
freeimage: 
freetype: libpng
homebrew/fuse/fuse4x-kext: 
gawk: xz
gd: fontconfig freetype jpeg libpng libtiff libvpx xz
gdbm: 
gdk-pixbuf: glib gobject-introspection jpeg libpng libtiff pkg-config xz
geoip: geoipupdate
gettext: xz
ghostscript: little-cms2 pkg-config
gist: 
glib: gettext libffi pkg-config xz
glibmm: glib libsigc++ pkg-config xz
homebrew/science/glpk: gmp
gmp: xz
homebrew/versions/gmp4: 
gnu-getopt: gettext
gnu-sed: 
go: git
gobject-introspection: cairo git glib libffi pkg-config xz
graphicsmagick: freetype ghostscript jasper jpeg libpng libtiff libtool libwmf little-cms2 pkg-config webp
graphviz: freetype gts libpng librsvg pango pkg-config
gsl: 
gtk+: atk gdk-pixbuf gobject-introspection hicolor-icon-theme jasper pango pkg-config xz
guile: bdw-gc gmp libffi libtool libunistring pkg-config readline xz
harfbuzz: cairo freetype glib gobject-introspection graphite2 icu4c pkg-config
help2man: xz
hicolor-icon-theme: xz
httrack: openssl
icu4c: 
id3lib: autoconf automake libtool
imapsync: 
intltool: 
isl: gmp
homebrew/versions/isl011: gmp4
jasper: jpeg
jbig2dec: autoconf automake libpng libtool
jpeg: 
keychain: 
kore: openssl postgresql
kqwait: 
lame: 
libao: pkg-config
libatomic_ops: 
libcroco: glib intltool pkg-config xz
libevent: doxygen openssl pkg-config
libffi: 
libgcrypt: libgpg-error
libgpg-error: 
homebrew/dupes/libiconv: 
libmpc: gmp mpfr
homebrew/versions/libmpc08: gmp4 mpfr2
libogg: 
libpng: xz
libquvi: lua pkg-config xz
librsvg: cairo gdk-pixbuf glib gtk+3 libcroco libgsf pango pkg-config xz
libsigc++: xz
libsmf: glib pkg-config
libsndfile: autoconf automake flac libogg libtool libvorbis pkg-config
libsodium: 
libssh: cmake openssl xz
libtar: autoconf automake git libtool
libtasn1: 
libtiff: jpeg
libtool: xz
libunistring: xz
libusb: 
libvo-aacenc: 
libvorbis: libogg pkg-config xz
libyaml: 
libzzip: pkg-config sdl
little-cms2: jpeg libtiff
log4cxx: autoconf automake libtool
lua: 
makedepend: pkg-config
maven: 
mercurial: 
homebrew/science/metis: cmake
mpfr: gmp xz
homebrew/versions/mpfr2: gmp4
node: openssl pkg-config xz
nspr: 
openssl: makedepend
ossp-uuid: 
osxutils: 
homebrew/boneyard/p11-kit: libtasn1 pkg-config
pango: cairo fontconfig glib gobject-introspection harfbuzz pkg-config xz
pcre: 
homebrew/tex/pdfjam: 
alexreg/utilities/pdfmarks: ghostscript
pixman: pkg-config
pkg-config: 
plotutils: libpng
poco: cmake openssl
popt: 
portaudio: pkg-config
potrace: 
proctools: bsdmake
pstree: 
python: berkeley-db4 gdbm homebrew/dupes/tcl-tk openssl pkg-config readline sqlite
python3: gdbm homebrew/dupes/tcl-tk openssl pkg-config readline sqlite xz xz
quvi: libquvi pkg-config
readline: 
recode: gettext libtool
rtmpdump: openssl
homebrew/tex/rubber: texinfo
ruby: gdbm gmp libffi libyaml openssl pkg-config readline
scons: 
sdl: 
sdl_net: pkg-config sdl
sdl_sound: flac libmikmod libogg libvorbis physfs pkg-config sdl speex
sleepwatcher: 
spidermonkey: nspr readline
sqlite: icu4c readline
sub2srt: 
subversion: apr-util gpg-agent openssl pkg-config python scons sqlite
homebrew/science/suite-sparse: metis openblas tbb
szip: 
t1utils: 
tbb: 
texi2html: gettext
texinfo: 
tinyxml: cmake
tor: libevent libnatpmp libscrypt miniupnpc openssl
tpl: autoconf automake libtool
tree: 
txt2tags: 
uriparser: cpptest pkg-config
wget: gpgme libmetalink libressl openssl pcre pkg-config xz
xmltoman: 
xvid: 
xz: 
zeromq: libpgm libsodium norm pkg-config
```

Also, `--1` and `--union` seem to have no effect on this command. Is that expected?

**Comment by UniqMartin** [comment]
> The output dependencies are clearly not in topological order.

In a way they are, because only the immediate dependencies of formulae are shown. Topological order would only matter if the dependency tree was fully expanded, which it is not. I think the confusion stems from the fact that `brew deps --installed` has two different meanings, depending on whether formulae are supplied to the command or not:

- `brew deps --installed` simply lists all installed formulae and their immediate dependencies (the output you saw). It respects the `--include-*` and `--skip-*` options, but all other options are ignored. It does support the `--tree` option, but I'd say the usefulness of that is limited.

- `brew deps [--installed] <formula>` expands the complete dependency tree of `<formula>` (or trees, if multiple formulae are given). Aside from the `--include-*` and `--skip-*` options it also respects the `--1`, `-n` (topological order), and `--union` options. The effect of `--installed` in this case is to intersect the computed dependency list with the list of installed formulae. Maybe two examples can help illustrate this:
  - `brew deps gtk+` lists all dependencies of `gtk+`.
  - `brew deps --installed gtk+` lists all already installed dependencies of `gtk+`.
  - The difference between these outputs is roughly the list of dependencies that would be installed in addition to what is already on my system if I decided to run `brew install gtk+`.

Does this help? I'd say this is primarily a documentation issue. I'd be more than happy if you created a pull request that improves our documentation. [`Library/Homebrew/cmd/deps.rb`](https://github.com/Homebrew/brew/blob/1451553188276117a574b2abe8957cb60ef7ced7/Library/Homebrew/cmd/deps.rb#L1-L23) is the file that needs to be changed. [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md) should get you started and I'm happy to answer any questions.

**Comment by alexreg** [comment]
It would be nice if the first variant of `brew deps` (without a formula given) would also support `--1` and `-n`, I think.

**Comment by UniqMartin** [comment]
> However, it would be nice if the first variant of `brew deps` (without a formula given) would also support `--1` and `-n`, I think.

The problem with this is, that `brew deps --installed` basically implies `--1` as it's only printing the first level of the dependency tree (the immediate dependencies) and thus `-n` is irrelevant. And we can't easily change the defaults as that would break other users' scripts that rely on the current output/behavior.

We could potentially introduce a `--no-1` option to invert the behavior, but I'm not convinced yet that we need a mode where every installed formula is listed with *all* its dependencies. What would be the use for that? If you really need this functionality *now*, here's how this can be done with a Bash one-liner:

```shell
for f in $(brew list --full-name) ; do echo "$f:" $(brew deps -n "$f") ; done
```

(Admittedly, this is a bit slow. Is that what you would expect from `brew deps --installed --no-1 -n`?)

**Comment by alexreg** [comment]
Yeah, that's fair enough actually. I've accomplished my goal by a bit of text manipulation and `tsort`, so no worries.

Since the output format of `deps --installed` (without any formula given) is different to that of a single formula, maybe it's just worth separating that out in the docs, or making it explicit at least.
