### ISSUE TITLE
`brew audit --online` not adding the HOMEBREW_GITHUB_API_TOKEN as HTTP Authorization Header

### ISSUE THREAD

**Issue by rustymagnet3000** [Homebrew/brew#13789]
### `brew config` output

```shell
▶ brew config          
HOMEBREW_VERSION: 3.5.10-89-g451bded
ORIGIN: https://github.com/Homebrew/brew
HEAD: 451bded34d315f21ff8fcdd0a61c6ba052625b30
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 001186aea9d67bb1829448098ec89f0b363d65f4
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
https_proxy: 127.0.0.1:8081
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.8-x86_64
CLT: 12.5.0.22.9
Xcode: 13.0
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I bumped a private Formula.  All worked.

I set the HOMEBREW_GITHUB_API_TOKEN as a local environment variable.

OK:

`brew upgrade foo-private-cli`

OK:

`brew audit foo-private-cli --git --skip-style -d`

NOK:

`brew audit foo-private-cli --online --git --skip-style -d`

### What happened (include all command output)?

```
  * The homepage URL https://github.com/foo/foo-private-cli is not reachable (HTTP status code 404)
  * Stable: The source URL https://github.com/foo/foo-private-cli/releases/download/0.1.1/foo-private-cli is not reachable (HTTP status code 404)
Error: 2 problems in 1 formula detected
```

### What did you expect to happen?

As I can `brew install`, `upgrade` and `reinstall` from these private repos, I know my `HOMEBREW_GITHUB_API_TOKEN` works and there are no "Single Sign On" (SSO issues with the GitHub Personal Access Token.

![image](https://user-images.githubusercontent.com/5367141/187891046-42b99a4c-29c9-4212-b3fc-007dc28f6206.png)

**Comment by MikeMcQuaid** [comment]
We'll review a PR to fix this. We're unlikely to do it ourselves because we don't support any private formulae, sorry.

**Comment by troymccabe** [comment]
@rustymagnet3000 When you try to just curl your private repo @ _just_ "github.com" with your token, are you able to? I may be doing things incorrectly, but it appears there's going to have to be some re-writing to `api.github.com` to support token auth instead of just passing it as a header.

**Comment by troymccabe** [comment]
Thinking more on this, would it make more sense to tell `brew` that the Github URL is private before rewriting anything? Thinking something similar to the following to not have any knock-on effects from implicit actions:

```
class MyPrivateFormula < Formula
  desc "The formula used for my Dr. Doofenshmirtz Gonkinator"
  homepage "https://github.com/doofenshmirtz/gonkinator/", :private => true
  url "https://github.com/doofenshmirtz/gonkinator/releases/download/v21.5/gonkinator-all-21.5.tar.gz", :private => true
  ...
```

This way it's only when a formula explicit calls for the URLs to be private

**Comment by carlocab** [comment]
We're unlikely to carry code that implements this in `brew`, but you could probably make that work by creating your own download strategy. 

See: https://docs.brew.sh/Formula-Cookbook#specifying-the-download-strategy-explicitly

**Comment by troymccabe** [comment]
Sorry--example above should have been `head "https://github.com/doofenshmirtz/gonkinator.git"` instead of `url`.

It doesn't look like `homepage` & `head` support any custom strategy, and that's where I was asking if it made sense to allow those to have a custom strategy (or just mark them private and allow resolution of private github repos)

**Comment by troymccabe** [comment]
Alright, think I'm close to a possible solution here

Convert `homepage` for `Cask` & `Formula` to be a `URL` & `Resource` respectively (I assume the disparate usage between the two is based on different times of implementation, but I kept convention with what was there).

Would anyone be willing to preview my changes, or should I just PR what I have once everything's passing & discussion can move there?

**Comment by MikeMcQuaid** [comment]
@troymccabe I don't think we want them to be a `url` or `resource`. This should be scoped to the code called from the auditor when making GitHub/GitHub API queries.

**Comment by troymccabe** [comment]
Totally fair--would you be open to the following approach to keep it scoped there? Without anything additional hinting that this is a private repo, it'll have to be a bit hamfisted

If Github's web ui (which doesn't use tokens) 404s, and the user has a Github api token set, fetch the repository definition from Github's API (which _does_ use tokens) & check that that 200s

(pseudocode, since I'm still picking up Ruby)
```
problem = http_content_problem = curl_check_http_content(...)
if problem.match(/http status code 404/i) && homepage.url.match(/^https:\/\/github.com/) && ENV["HOMEBREW_GITHUB_API_TOKEN"]
  # rewrite to `api.github.com` url & check that with token
end
```

**Comment by troymccabe** [comment]
Several possible impls to compare:
1. Using `Resource`/`URL`: https://github.com/Homebrew/brew/compare/master...troymccabe:brew:bugfix/13789-homepage-as-resource
2. Checking private repo, failing, checking GH API: https://github.com/Homebrew/brew/compare/master...troymccabe:brew:bugfix/13789-homepage-gh-private-repo-check
3. Short-circuiting if `private` is a query param of a Github repository: https://github.com/Homebrew/brew/compare/master...troymccabe:brew:bugfix/13789-homepage-gh-private-repo-check-query-param

There's another possible, which is using an object lighter than `Resource`/`Url`, which just contains the check strategy. Anything that allows a custom strategy I'd personally prefer since it's less hard-coded for 1 provider. Avoids "hey I have a private bitbucket repo" convos, and puts the onus on the developer who wants private formulae to ensure the strategy for fetching the homepage can do so

**Comment by carlocab** [comment]
Alternatively, you could try subclassing `Formula` with, say, `AbstractPrivateFormula`. Inside `AbstractPrivateFormula`, you can override the `homepage` as you please.

Your private formulae would then inherit from `AbstractPrivateFormula` instead of `Formula`.

See

https://github.com/Homebrew/homebrew-portable-ruby
https://github.com/shivammathur/homebrew-php

for examples of this.

**Comment by troymccabe** [comment]
Hrm, not sure that'd work, since `homepage` is expected to be a string, and the code in `formula_auditor`/`cask/audit` expects the same. 

If the auditors called an instance method (e.g. `homepage_is_online`) of `Formula` (falling back to the current curl impl) or something, for sure I could see that, but as it stands the _`Auditor`_ would have to be overridden, instead of `Formula`

As it stands, there's no way to externally override the behavior of `audit_homepage` (`Formula`) or `check_https_availability` (`Cask`). They both call `curl_check_http_content`, which doesn't have any code paths to modify the request before checking

**Comment by MikeMcQuaid** [comment]
> Checking private repo, failing, checking GH API: [master...troymccabe:brew:bugfix/13789-homepage-gh-private-repo-check](https://github.com/Homebrew/brew/compare/master...troymccabe:brew:bugfix/13789-homepage-gh-private-repo-check)
> Short-circuiting if `private` is a query param of a Github repository: [master...troymccabe:brew:bugfix/13789-homepage-gh-private-repo-check-query-param](https://github.com/Homebrew/brew/compare/master...troymccabe:brew:bugfix/13789-homepage-gh-private-repo-check-query-param)

Either of these approaches look good to me with a mild preference for the first.
