### ISSUE TITLE
`livecheck` experiencing failures when checking GitHub release pages

### ISSUE THREAD

**Issue by p-linnane** [Homebrew/brew#13853]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.1-6-g427f646
ORIGIN: https://github.com/Homebrew/brew
HEAD: 427f6465e95eecef9c8c255a8933f593e7548f33
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9b3ba2aabdf9c83263eb289f4fcc9093e0c83203
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_FORCE_BREWED_CA_CERTIFICATES: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.3 => /opt/homebrew/opt/git/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to run `livecheck` on various casks to perform version bumps. This appears to be happening to some casks that use `:page_match` or `:github_latest` strategies. The content returned by `curl` is different for these pages than usual, in that it doesn't return full links to binaries. **To emphasize, this is not happening to all casks. I cannot find any kind of commonality with affected casks**.

For example, grabbing the [bitwarden release page](https://github.com/bitwarden/clients/releases) with `curl` returns:

```
        <a href="/bitwarden/clients/releases/download/desktop-v2022.9.0/Bitwarden-2022.9.0-universal.dmg" rel="nofollow" data-skip-pjax>
          <span class="px-1 text-bold">Bitwarden-2022.9.0-universal.dmg</span>
```

By contrast, grabbing the [abricotine release page](https://github.com/brrd/Abricotine/releases) with `curl` does not return a direct path to the .zip file that is listed on the release page, thus causing `livecheck` to fail.

### What happened (include all command output)?

Full output for another cask with the same issue using `:github_latest` strategy:

```
brew lc --cask --debug --verbose btcpayserver-vault
#<Homebrew::CLI::Args named=["btcpayserver-vault"], remaining=["btcpayserver-vault"], d?=true, debug?=true, Display any debugging information.?=false, q?=false, quiet?=false, Make some output more quiet.?=false, v?=true, verbose?=true, Make some output more verbose.?=false, h?=false, help?=false, Show this message.?=false, full_name?=false, Print formulae and casks with fully_qualified names.?=false, tap=nil, Check formulae and casks within the given tap, specified as <user>`/`<repo>.=nil, eval_all?=false, Evaluate all available formulae and casks, whether installed or not, to check them.?=false, all?=false, @@HIDDEN@@?=false, installed?=false, Check formulae and casks that are currently installed.?=false, newer_only?=false, Show the latest version only if it's newer than the formula/cask.?=false, json?=false, Output information in JSON format.?=false, Suppress warnings, don't print a progress bar for JSON output.?=false, formula?=false, formulae?=false, Only check formulae.?=false, cask?=true, casks?=true, Only check casks.?=false>
~/.brew_livecheck_watchlist

Cask:             btcpayserver-vault
Livecheckable?:   Yes

URL (url):        https://github.com/btcpayserver/BTCPayServer.Vault/releases/download/Vault%2Fv2.0.5/BTCPayServerVault-osx-x64-2.0.5.dmg
Strategies:       GithubLatest, PageMatch
Strategy:         GithubLatest
Regex:            /href=.*?\/BTCPayServerVault-osx-x64-(\d+(?:\.\d+)+)\.dmg/i
URL (strategy):   https://github.com/btcpayserver/BTCPayServer.Vault/releases/latest
URL (final):      https://github.com/btcpayserver/BTCPayServer.Vault/releases/tag/Vault/v2.0.5
Error: btcpayserver-vault: Unable to get versions
```

### What did you expect to happen?

Current version is returned, or newer version is returned.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above command output above.
```

**Comment by p-linnane** [comment]
CC @samford

**Comment by samford** [comment]
Thanks for bringing this to my attention. The HTML for the first page of releases previously contained all of the asset lists but it looks like now it only includes the first one if we're lucky (as you mentioned, some omit all asset lists from the HTML).

One way to deal with this situation is to go through existing `livecheck` blocks that check GitHub releases (either a releases URL or the `GithubLatest` strategy) with a regex that identifies version information from a file and reevaluate the approach. If it's adequate to match the version information from tag URLs like the `GithubLatest` strategy does by default (e.g., `%r{href=["']?[^"' >]*?/tag/v?(\d+(?:\.\d+)+)["' >]}i`), that would allow us to work around this limitation.

The issue is that we have some casks where upstream doesn't publish the file that we need in every release (e.g., the cask uses a dmg file but not every release provides a dmg file). When the releases HTML previously contained all the asset lists, we could properly identify the newest release with the file we want. With the GitHub changes described in this issue, this doesn't work anymore and the alternative approach will unfortunately end up surfacing versions that don't provide the file we need. However, there are only a relatively small number of casks that meet this particular criteria (fewer than 100).

It's technically possible to programmatically fetch each asset list individually until we find one with a matching file but this would multiply the number of requests we need to make for these checks and it could lead to rate limit issues. In the past, we would sometimes reach a limit when modifying a large number of github.com checks in one PR in the homebrew-livecheck repository CI back in the day, so I'm still wary of making too many GitHub requests.

That said, I'll do a livecheck run tomorrow with all of the formulae/casks that check GitHub using `PageMatch` or `GithubLatest` to see how many are broken but I don't think it will be too bad.

**Comment by miccal** [comment]
The `sage` Cask is also having this issue:
```
|-> brew livecheck sage --debug

Cask:             sage
Livecheckable?:   Yes

URL:              https://github.com/3-manifolds/Sage_macOS/releases/latest
Strategy:         PageMatch
URL (final):      https://github.com/3-manifolds/Sage_macOS/releases/tag/v1.4.2
Error: sage: Unable to get versions
```

**Comment by p-linnane** [comment]
@samford @miccal Not running into this today. All my usual checks are passing and the casks we've called out in this issue are working. Not sure if this was a transitory GitHub thing, or a sign of changes to come with release pages.

**Comment by samford** [comment]
> Not running into this today. All my usual checks are passing and the casks we've called out in this issue are working. Not sure if this was a transitory GitHub thing, or a sign of changes to come with release pages. If either of you can confirm the same I think we can close this one out.

Can confirm. I checked all the related formulae/casks and they're working as expected now. Here's hoping this was just a temporary issue and not a test of future changes (e.g., selectively rolling out changes to a subset of repositories to see if anyone tells you it broke something for them). Either way, at least we're aware of it.

**Comment by p-linnane** [comment]
Unfortunately this issue has returned today. I'm seeing a long list of casks that can't retrieve versions from release pages.

**Comment by p-linnane** [comment]
I can confirm that this is impacting significantly more casks today.

@samford Did you get a chance to look at that workaround from https://github.com/llvm/torch-mlir/issues/1374#issuecomment-1248689697?

**Comment by powderluv** [comment]
Yeah this works: https://github.com/nod-ai/SHARK/blob/main/setup_venv.sh#L74-L79 for us I am not sure if you have any api limits on that URL though for Homebrew's volume

**Comment by p-linnane** [comment]
Update from GitHub support:

>I've heard back from the engineering team now.
>
>They confirm that we have indeed recently made some changes to render the asset lists on Releases collapsed by default, for performance reasons.
>
>It sounds like these projects have been doing some web scraping to find the asset download URLs, and now that web scraping has broken, because it isn't aware that the asset list will start out collapsed by default.
>
>Our recommended method of getting such a list would be to instead use the [Release assets API](https://docs.github.com/en/rest/releases/assets#list-release-assets) to programmatically obtain the list of asset download URLs. The API response would provide the download URLs that they want.
>
>I hope that is an acceptable solution, and it should lead to a more robust process, as APIs are not prone to refactoring in the same way web pages are.

**Comment by samford** [comment]
Thanks for contacting GitHub support to better understand the situation, @p-linnane. It's been another busy week for me but I'm going to try to find some time to continue digging into this Saturday and/or Sunday. As it stands, I think we should approach these failing `livecheck` blocks as follows:

**For checks using the `GithubLatest` strategy and a regex that matches the version from a download file URL**: Either remove the regex (if the default strategy regex works for the tag format) or update it to use a modified version of the default `GithubLatest` strategy that works for the repository's tag format. The default `GithubLatest` regex is currently `%r{href=["']?[^"' >]*?/tag/v?(\d+(?:\.\d+)+)["' >]}i` but sometimes we have to override it with a modified version to account for a tag prefix (e.g., `release-1.2.3`), tweak the version regex, etc.

**For checks using the first page of the GitHub releases and a regex that matches the version from a download file URL**: We will need to identify which casks require checking all versions for technical reasons (e.g., the releases for a given repository don't consistently include the file the cask uses, etc.). I've tried to document these `livecheck` blocks in a preceding comment when I created/modified them (i.e., so we could easily identify them in the future) but there are bound to be some that haven't received the same treatment. Some of these may be fine simply matching versions from tag URLs (i.e., we would update it to use either the regex from the `GithubLatest` strategy or a modified version of it) but some of these will require a different approach.

**For checks that absolutely need to match versions from release filenames due to technical limitations**: We will have to figure something else out. Up to this point, I've tried to avoid using the GitHub API in livecheck because rate limiting is involved and that led to failures in the past (i.e., we once had some checks that did this but I worked to get rid of them all years ago because they were a pain on CI and sometimes even failed locally).

I'm going to try to work through some of these as time permits but we're also in the final week of our livecheck GSoC project, so trying to get that wrapped up unfortunately takes precedent over this at the moment.

**Comment by p-linnane** [comment]
@samford The list I edited in the comment above from a few days ago is still accurate. There may be a couple additional ones but I haven't checked in the last day or so. Now that you've provided some guidance, I'm happy to help work through these this weekend so you can focus on wrapping up the GSoC project.

**Comment by samford** [comment]
Though the majority of these are in homebrew-cask, I've updated the tracking list to also include the other first-party taps. At this point, I've taken care of homebrew/core and homebrew/cask-drivers. I also confirmed that the list for homebrew-cask is complete with respect to what I'm seeing.

I'm continuing to work through these as time permits and I intend to work on strategy changes (modifications/additions) after these checks are working again. I think I have a good understanding of the various scenarios that we encounter related to this issue but I'll be working with a more complete perspective at that point.
