### ISSUE TITLE
Xpath support as a livecheck strategy

### ISSUE THREAD

**Issue by andrewcrook** [Homebrew/brew#13991]
### Provide a detailed description of the proposed feature

When alternative strategy methods cannot be used 
- To be able to use Xpath as strategy for livecheck instead of and in addition to regex.
- Xpath can also be used with XML for file parsing.

### What is the motivation for the feature?

- To make it easier to get data out of HTML, XHTML webpages example software versions on a changelog or release page.
- If the returned text still requires further parsing regex can be used on the Xpath result example different version format or additional unwanted text.
- If website has a XML file (for integration with services or applications) with version data etc Xpath can be used to parse that data.
- read data from APIs requests
- I suppose Xpath can parse RSS as well as certain formats are based on XML. 
 
I see this being most useful for livechecks

### How will the feature be relevant to at least 90% of Homebrew users?

easier to provide updated formula and casks to the user

### What alternatives to the feature have been considered?

script files

**Comment by MikeMcQuaid** [comment]
CC @samford @nandahkrishna for thoughts

**Comment by samford** [comment]
I've had a basic implementation of a generic `Xml` strategy mostly done for a while but there's still some work to do before I can create a PR (writing tests, finishing documentation, moving some of the XML-parsing logic out of the `Sparkle` strategy, etc.). Like the `Sparkle` strategy, it uses `REXML` internally, so you will be able to use an Xpath in an `Xml` `strategy` block (e.g., `xml.get_elements("//abc//def//ghi")`).

We could also add an `#xpath` method to the `livecheck` block DSL, as this would allow the xpath to be surfaced in livecheck's debug/JSON output (and maybe simplify some related `strategy` blocks). However, we would need to ensure it's only used for appropriate strategies (`Xml` in this case). We would also only allow this for XML files because supporting Xpath for HTML/XHTML would require parsing those files and we [specifically avoid using `nokogiri` in brew](https://github.com/Homebrew/brew/blob/de8d78dc10fd7d7b4d4cc671bcf7f4c4c1ad18c6/Library/Homebrew/Gemfile#L11-L12).

I'll think about this some more when I have a moment to wrap up the `Xml` strategy but I'm tied up with some other livecheck work at the moment (i.e., fixing broken checks released to GitHub releases).

**Comment by andrewcrook** [comment]
agree `rexml` looks like its probably the way to go.

[https://ruby.github.io/rexml/REXML/XPath.html](https://ruby.github.io/rexml/REXML/XPath.html)

**Comment by MikeMcQuaid** [comment]
> I've had a basic implementation of a generic `Xml` strategy mostly done for a while but there's still some work to do before I can create a PR (writing tests, finishing documentation, moving some of the XML-parsing logic out of the `Sparkle` strategy, etc.).

@samford any updates here?

**Comment by samford** [comment]
I've been working on wrapping it up recently and I should have a PR up this week or next: https://github.com/Homebrew/brew/issues/13992#issuecomment-1440420203

**Comment by samford** [comment]
I've created a PR for the `Xml` strategy and it can be found at https://github.com/Homebrew/brew/pull/14845. The PR description (and tests) include some examples of what common `strategy` blocks may look like, though this will naturally vary in relation to the upstream XML you're working with.
