### ISSUE TITLE
Is that possible to specify MACOSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by fuji246** [Homebrew/brew#14136]
### Provide a detailed description of the proposed feature

Need use the libraries built with brew as dependencies for my binary and run on previous version of MacOS, tried to specify MACOSX_DEPLOYMENT_TARGET in env variable, I've no idea why it doesn't work.

### What is the motivation for the feature?

Homerbrew is convenient  to install libraries, however the libraries are only built for the current version of MacOS, and will cause problem when running the binary depends on those libraries on previous version of MacOS

### How will the feature be relevant to at least 90% of Homebrew users?

Many developers are using Homebrew to install dependencies.

### What alternatives to the feature have been considered?

Manually compile the dependencies, but that is tedious.

**Comment by EricFromCanada** [comment]
Because of [environment variable filtering](https://docs.brew.sh/Formula-Cookbook#using-environment-variables), vars from the build environment will be ignored. This is partly why bottled libraries in `homebrew/core` aren't suitable for distribution. You'd need to copy the formula to your own tap and add it to the formula itself, which is something I did for [Endless Sky](https://github.com/endless-sky/endless-sky/blob/master/utils/mad-compat.rb#L20-L21).
