### ISSUE TITLE
xcode dependency should be ignored if bottle is available

### ISSUE THREAD

**Issue by psibre** [Homebrew/brew#1448]
Apologies if this is not the correct tracker.

I just tried installing [`homebrew/science/r-gui`](https://github.com/Homebrew/homebrew-science/blob/34eb0d2bd590b0eb50720161365d7ee874b58a46/r-gui.rb), which `depends_on :xcode`. I had only the command-line tools installed, so it forced me to download and install the full version of Xcode, which (at 2.6 GB) took about *six hours* on my slow connection, but eventually completed without problems.

Then I tried again:
```
$ brew install r-gui
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
```
OK, whatevever. Again:
```
$ brew install r-gui
Warning: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing r-gui from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/r-gui-1.67_1.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring r-gui-1.67_1.mavericks.bottle.tar.gz
==> Caveats
.app bundles were installed.
Run `brew linkapps r-gui` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/r-gui/1.67_1: 129 files, 3.6M
```
Which took about two seconds. Yay!

So my question is, *why did I need to install Xcode?* Shouldn't Homebrew just install the bottle if it's available, and only nag about the missing full Xcode installation if it actually needs to rebuild from source?

**Comment by apjanke** [comment]
Yep, that looks like that `:xcode` dependency in the r-gui formula could probably be changed to be build time only, so it wouldn't be required when installing from a bottle. That would be a bug in the formula.

This bug report should go over in the [homebrew-science bug tracker](https://github.com/homebrew/homebrew-science), since it appears to be specific to the `r-gui` formula, not an issue with the `brew` tool itself. Would you mind just reposting it over there? That could also get it looked at by the homebrew-science folks who are more familiar with r-gui and can confirm whether it's just a build-time dependency.

**Comment by MikeMcQuaid** [comment]
Closing as a formula bug in homebrew-science.
