### ISSUE TITLE
brew bash competion error line 27

### ISSUE THREAD

**Issue by piotr-sikora-v** [Homebrew/brew#14643]
### `brew doctor` output

```shell
brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 932d2cf3b77c9439a57b6a43577fc8d3b6399a62
Last commit: 8 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5a240c5e373c212ff7a4ecd955afee76d798bbd7
Core tap last commit: 36 minutes ago
Core tap branch: master
Core tap JSON: 06 Feb 16:27 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

I want to use bash completion

### What happened (include all command output)?

when my bash_profile try to run  script for bash completion that include /opt/homebrew/etc/bash_completion.d/brew then I see error:
```
-bash: /opt/homebrew/etc/bash_completion.d/brew: line 27: syntax error near unexpected token `<'
-bash: /opt/homebrew/etc/bash_completion.d/brew: line 27: `  while read -r line; do COMPREPLY+=("${line}"); done < <(compgen -W "${list}" -- "${cur}")'
```

### What did you expect to happen?

not see error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Remove bash completion, remove /opt/homebrew/etc/bash_completion.d/brew file
now everything works
install bash-comletion:

brew install bash-completion
```
error again show
```

**Comment by Rylan12** [comment]
@maxim-belkin could this be related to the recent completion changes?

**Comment by Bo98** [comment]
I suspect this can happen if you have posix mode enabled (`POSIXLY_CORRECT`).

**Comment by carlocab** [comment]
> I suspect this can happen if you have posix mode enabled (`POSIXLY_CORRECT`), but that isn't new.

Yup, seems like it:
```
❯ cat test.sh
#!/bin/bash
source "$(brew --prefix)/etc/bash_completion.d/brew"
❯ ./test.sh; echo $?
0
❯ POSIXLY_CORRECT=1 ./test.sh
/usr/local/etc/bash_completion.d/brew: line 27: syntax error near unexpected token `<'
/usr/local/etc/bash_completion.d/brew: line 27: `  while read -r line; do COMPREPLY+=("${line}"); done < <(compgen -W "${list}" -- "${cur}")'
```

**Comment by piotr-sikora-v** [comment]
@emopinata 
GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)

I now found that I have two versions of bash... one is installed couse of dependecy to wireguard (strange) ... and it's 5.2.15
Second version is normal for system, and it's 3.2.57. 
On 3.2.57 I don't have this problem.

@carlocab 
I try to `unset POSIXLY_CORRECT` and it works! Thanks!

It will be nice to add somewhere info about this... maybe  after install to add this unset before including files  in bash_profile?

**Comment by maxim-belkin** [comment]
So, submitted a PR to detect POSIX mode.

On a related subject: `brew config` doesn't show shell info and it probably should.

**Comment by MikeMcQuaid** [comment]
> On a related subject: `brew config` doesn't show shell info and it probably should.

@maxim-belkin Good idea. Alternatively, I wonder if we can just unset stuff like this automatically in the completions themselves?

**Comment by maxim-belkin** [comment]
> > On a related subject: `brew config` doesn't show shell info and it probably should.
> 
> @maxim-belkin Good idea. Alternatively, I wonder if we can just unset stuff like this automatically in the completions themselves?

If our objective is to ensure that Bash completions can be used in POSIX mode (which, in my opinion, is a reasonable goal), it would be more appropriate to make the code POSIX-compatible. I will create a pull request that demonstrates the required changes for making Bash completions compatible with POSIX.

**Comment by MikeMcQuaid** [comment]
@maxim-belkin Sorry, poor communication on my part here: I don't think it's worth supporting POSIX mode based on a single issue like this that could have been fixed on our end due to better environment filtering. I guess I'm wondering if we could instead set e.g. `unset POSIXLY_CORRECT` in our Bash completions?

**Comment by timvisher** [comment]
@MikeMcQuaid @maxim-belkin I just noticed this myself.

```
+++ [[ brew != @(*~|*.bak|*.swp|\#*\#|*.dpkg*|*.rpm@(orig|new|save)|Makefile*) ]]
+++ [[ -f /opt/homebrew/etc/bash_completion.d/brew ]]
+++ [[ -r /opt/homebrew/etc/bash_completion.d/brew ]]
+++ . /opt/homebrew/etc/bash_completion.d/brew
++++ test -v POSIXLY_CORRECT
bash: test: -v: unary operator expected
++++ test -o posix
++++ complete -o bashdefault -o default -F _brew brew
```


If we keep in mind that bash `3.2.57` is still the default bash on all macOS systems, the problem with the change introduce [here](https://github.com/Homebrew/brew/pull/14669) is only that it uses a feature not introduced until bash 4.2 ([faq](https://mywiki.wooledge.org/BashFAQ/083)).

I think that it's reasonable to assume that anyone attempting to source this bash completion will be attempting to source it from bash so maintaining strict POSIX compliance within the completion script itself seems counter-productive.

Instead, I would propose simply using a test with standard bash (or POSIX if we must):

Regular bash:

```diff
diff --git a/completions/bash/brew b/completions/bash/brew
index d7197267f..ea015eb54 100644
--- a/completions/bash/brew
+++ b/completions/bash/brew
@@ -1,6 +1,6 @@
 # Bash completion script for brew(1)
 
-if test -v POSIXLY_CORRECT || test -o posix 
+if [[ -n $POSIXLY_CORRECT ]] || shopt -qo posix
 then
   echo "Homebrew Bash completions do not work in POSIX mode" 1>&2
   return

```

results in

```
bash-3.2.57$ compgen -v BASH_VERSION POSIXLY_CORRECT; shopt -o posix
BASH_VERSION
posix          	off
bash-3.2.57$ source /opt/homebrew/etc/profile.d/bash_completion.sh
bash-3.2.57$ /bin/bash --norc --posix
bash-3.2.57$ compgen -v BASH_VERSION POSIXLY_CORRECT; shopt -o posix
BASH_VERSION
posix          	on
bash-3.2.57$ source /opt/homebrew/etc/profile.d/bash_completion.sh
Homebrew Bash completions do not work in POSIX mode
…
bash-3.2.57$ /opt/homebrew/bin/bash --norc
bash-5.2.15$ compgen -v BASH_VERSION POSIXLY_CORRECT; shopt -o posix
BASH_VERSION
posix          	off
bash-5.2.15$ source /opt/homebrew/etc/profile.d/bash_completion.sh
bash-5.2.15$ /opt/homebrew/bin/bash --norc --posix
bash-5.2.15$ compgen -v BASH_VERSION POSIXLY_CORRECT; shopt -o posix
BASH_VERSION
posix          	on
bash-5.2.15$ source /opt/homebrew/completions/bash/brew
Homebrew Bash completions do not work in POSIX mode
…
```

and if we wanted to be strictly POSIX for some reason we could follow the advice in the [faq](https://mywiki.wooledge.org/BashFAQ/083) which I'm sure could be made to result in similar behavior.

I would not recommend simply unsetting things like POSIXLY_CORRECT or `shopt -u posix` because I think switching back and forth between POSIX and bash would likely result in undefined behavior compared to, say, turning `extglob` on and off but I don't know that for sure.

I could prepare a PR with the above if you're amenable or, since @maxim-belkin is already on it in [here](https://github.com/Homebrew/brew/pull/14673), maybe they would prefer to change it?

**Comment by MikeMcQuaid** [comment]
> Instead, I would propose simply using a test with standard bash

Yes, a PR for this would be great, thanks!

> I would not recommend simply unsetting things like POSIXLY_CORRECT or `shopt -u posix`

Are the Bash completions able to change global environment settings? I'd assumed they cannot in which case unsetting seems more sensible to avoid users breaking Homebrew's completions.

**Comment by timvisher** [comment]
> > Instead, I would propose simply using a test with standard bash
> 
> Yes, a PR for this would be great, thanks!

Incoming. :)

> > I would not recommend simply unsetting things like POSIXLY_CORRECT or `shopt -u posix`
> 
> Are the Bash completions able to change global environment settings? I'd assumed they cannot in which case unsetting seems more sensible to avoid users breaking Homebrew's completions.

Since completions are sourced in they can change anything about the current shell. So while this doesn't affect any other shells if a user, for whatever reason, wanted to have `shopt -s posix` and in the completion script we `shopt -u posix` without turning it back on at the end (which relies on the script having perfect error handling) we could inadvertently turn it off for their whole shell. You also technically would have to test for POSIX so that you knew whether you had had to turn it off. Furthermore I'm still not sure what bash would do if one file was loaded in non-POSIX compliance mode and the rest of the shell was running in POSIX mode. Admittedly I don't know much about this feature of bash so maybe that would just work but it seems risky when I think all we really need to do is tell the user that brew's completion script doesn't work in POSIX mode and let them decide what to do.

**Comment by maxim-belkin** [comment]
> the problem with the change introduced [here](https://github.com/Homebrew/brew/pull/14669) is only that it uses a feature not introduced until bash 4.2 ([faq](https://mywiki.wooledge.org/BashFAQ/083)).

Sorry about that. I tested that PR in Bash 5.0 only.

> Are the Bash completions able to change global environment settings?

Yes, these are scripts sourced in the current shell, so they can change environment settings. I'm 👎🏻 on unsetting POSIX mode in Bash completions -- this is user's choice to work in this mode.

> I would not recommend simply unsetting things like POSIXLY_CORRECT or `shopt -u posix` because I think switching back and forth between POSIX and bash would likely result in undefined behavior compared to, say, turning `extglob` on and off but I don't know that for sure.

I agree with this concern and I don't think Bash completions should change POSIX mode -- again, this is user's choice to enable this mode. Bash completions can either support it or not. Supporting POSIX mode is not difficult and requires a one-time effort like this one here.

> I think that it's reasonable to assume that anyone attempting to source this bash completion will be attempting to source it from bash so maintaining strict POSIX compliance within the completion script itself seems counter-productive.

My apologies but I'm not quite following you here -- why do you think it's counter-productive to support POSIX mode? Bash can operate in POSIX mode just fine.

**Comment by maxim-belkin** [comment]
> Furthermore I'm still not sure what bash would do if one file was loaded in non-POSIX compliance mode and the rest of the shell was running in POSIX mode.

Completion functions are executed in the currently active mode. If functions are written in a POSIX-compliant way they will execute just fine in any mode. If functions are written in a non-POSIX compliant way, they will fail in POSIX mode.

**Comment by timvisher** [comment]
> > Furthermore I'm still not sure what bash would do if one file was loaded in non-POSIX compliance mode and the rest of the shell was running in POSIX mode.
> 
> Completion functions are executed in the currently active mode. If functions are written in a POSIX-compliant way they will execute just fine in any mode. If functions are written in a non-POSIX compliant way, they will fail in POSIX mode.

I think that makes sense but I don't think it's addressing what I was saying.

I'm saying that if a user turns on POSIX mode and then we load completions that _aren't_ POSIX compliant but do so by `shopt -u posix; …; shopt -s posix` or similar I'm not sure what would happen. I'd assume that the completions would fail at some point since the actual active mode is still POSIX despite the fact that we briefly turned it off.

**Comment by maxim-belkin** [comment]
I think `shopt` can't set/unset POSIX mode, `set` can (`shopt -o` lists options to be used with `set`). 
Regarding whether it is going to work: it should, but, honestly, switching POSIX mode back and forth in a function doesn't strike me as the best idea.
