### ISSUE TITLE
Disable/remove deprecated 16.04 Docker image 

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#14661]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

This image should be removed. It takes ~6m every time on our `docker` build.

@Bo98 had ideas previously about the best way to kill it.

### What is the motivation for the feature?

We stated end of support on 2022-09-07 and we're well past that.

### How will the feature be relevant to at least 90% of Homebrew users?

Faster builds, faster maintainers.

### What alternatives to the feature have been considered?

Not removing it.

**Comment by Bo98** [comment]
> We stated end of support on 2022-09-07 and we're well past that.

To be clear this was the date of deprecation but yes 5 months since deprecation seems about time to consider disabling.

What we would do is remove from the workflow and issue a one-time update that replaces `brew` with an error script.

I can do this but it would be good to have somewhere that I can note down what I did, and have a copy of the old deprecated-image push workflow step we currently have so that we can use them again in the future. Not sure where that should be though.

**Comment by MikeMcQuaid** [comment]
> I can do this but it would be good to have somewhere that I can note down what I did, and have a copy of the old deprecated-image push workflow step we currently have so that we can use them again in the future. Not sure where that should be though.

Yeh, sounds good. Could have a custom workflow or something that takes `workflow_dispatch` and we could do so with 18.04/22.04 eventually too?

**Comment by issyl0** [comment]
Also there are docs in https://github.com/Homebrew/brew/blob/master/docs/Linux-CI.md#past-and-next-versions that need updating.

**Comment by Bo98** [comment]
> It takes ~6m every time on our docker build.

For next time we do this: this probably could/should have run in parallel with the other Docker build - they don't depend on each other.
