### ISSUE TITLE
[CI] Stop using deprecated Actions params

### ISSUE THREAD

**Issue by issyl0** [Homebrew/brew#14692]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

GitHub are deprecating `set-output`, `save-state` in favour of "Environment Files". 

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### What is the motivation for the feature?

Reducing noise in the "Checks" view on a PR.

<img width="827" alt="Screenshot 2023-02-17 at 16 32 19" src="https://user-images.githubusercontent.com/355033/219710566-bca980f9-ecb7-48ce-9437-40d2264449c4.png">

### How will the feature be relevant to at least 90% of Homebrew users?

It won't, but it'll reduce cognitive load for maintainers seeing these warnings.

### What alternatives to the feature have been considered?

Leave them and let our Actions break in June 2023.

**Comment by Bo98** [comment]
Yeah was non-trivial work it turned out but I think most of the tricky stuff is dealt with. setup-homebrew is the big one and that's sorted. actions/cache@v3 can now be used but with care (it rarely errors if it's not working) - I can pick up that.

There's a couple of smaller tasks in Homebrew/actions that needs sorting too.

Not sure if there's anything else. These warning overviews don't exactly tell you the relevant step/action it happened in.

**Comment by DestroyerXyz** [comment]
@Bo98 checkout my PR, seems to fix the cache issue.
