### ISSUE TITLE
use the last working formula

### ISSUE THREAD

**Issue by georgalis** [Homebrew/brew#14809]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Provide a means to **list prior versions** of a (any) formula available in brew, such that a (working) **former version can be identified, rolled back, and pinned**; on the occasion that `brew upgrade` installed a buggy (or local incompatible) formula. 

In many cases, it may be obvious what formula is broken. In other cases it may only be known that `brew upgrade` introduced the problem. This could be addressed by enabling roll back of the date used for brew formula ruby files, a listing of advanced formula versions, and a procedure to, as needed, install and pin the older versions.

### What is the motivation for the feature?

**It should be anticipated that software maintainers release software bugs** even if they use regression testing, and other reasonable efforts to catch bugs, before cutting a release.

### How will the feature be relevant to at least 90% of Homebrew users?

Any formula has the potential for release with bugs. Indeed, some brew users may use formula in novel ways that the upstream authors never considered, or a given formula may just have too many potential use cases to test. It would be nonsense to anticipate comprehensive unit testing on all formula.

One recent example is vim shell syntax highlighting. Any unit testing for this functionality would be challenging or impossible. Nevertheless, broken syntax highlighting is immediately obvious to impacted coders. In the case of `vim90/syntax/sh.vim` three weeks ago, an issue was quickly identified, resolved, and closed, https://github.com/vim/vim/issues/11937#issuecomment-1442595540 however the fix did not make the most recent release.

A formula version listing, rollback, and pin feature would provide brew users with a reasonable (and quick) means to fix their local installs, when upstream bugs get introduced into formula. A means to seamlessly identify, and choose a release revision to roll back to, is essential to restore local functionality, in a timely manner.

### What alternatives to the feature have been considered?

As noted in https://github.com/Homebrew/discussions/discussions/4247 even if it is obvious what formula is broken, determining the precise url of a presumed working formula ruby file is challenging. Per internet discussions, it was once possible, for example, to

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d24021129dba6149a352cb742bd331da5288c22f/Formula/vim.rb
`

however today that functionality has (apparently) been removed. In the case of this vim issue, the issue is simple enough that overwriting the broken syntax file with a working one, resolves the issue.

In most cases, I would suppose introduced bugs would full stop local operations? Or, at least 100% of local attentiobn would be focused on a convoluted discovery, with an aim to roll back a release?

**Comment by alebcay** [comment]
We already have the `brew extract` command that can find a previous version of a formula from the repository history and restore it, not as a replacement of the current formula, but as a specific version alongside it on your local machine. This older version is not guaranteed to work anymore (after all, users can extract a formula from e.g. 1-2 years ago) and the Homebrew team does not offer any sort of support for the resulting formula.

Homebrew was designed from day one as a rolling evergreen-style package manager. While there was support for version pinning previously, it was buggy, only worked some of the time, and created a lot of support burden as complicated dependency graphs would become untenable due to some dependency or dependent being pinned. To properly support version pinning or "install any version anytime" behavior would require a substantial re-architecture of `brew`. The `brew extract` command placing the old version alongside the current one, rather than replacing it, is a deliberate design choice that allows for some (admittedly hacky) working around these limitations.

You can learn more by running `brew extract --help`.

Currently, there's no way to list versions available for extraction; I think this is a reasonable enhancement to add to the `brew extract` command.
