### ISSUE TITLE
Error: Refusing to uninstall `/opt/homebrew/Cellar/apache-arrow/11.0.0`

### ISSUE THREAD

**Issue by nbro10** [Homebrew/brew#14863]
### `brew doctor` output

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [ ] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 3 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: be69d16e761c0a8312cbb4a18c1358a4db4744f9
Core tap last commit: 3 days ago
Core tap branch: master
Core tap JSON: 02 Mar 09:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

I just tried to do another `brew uninstall apache-arrow` after what I did here https://github.com/apache/arrow/issues/34395 and now I get this error

```
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=#=#                                                                         
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=#=#                                                                         
Error: Refusing to uninstall /opt/homebrew/Cellar/apache-arrow/11.0.0
because it is required by apache-arrow-glib, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies apache-arrow
```

Clearly, if I do `brew uninstall apache-arrow-glib` first, I don't get the error anymore, but it's weird that I cannot install `apache-arrow` just because of another dependency, so I'm reporting the issue here.

Notes: Originally posted [here](https://github.com/apache/arrow/issues/34396)

### What happened (include all command output)?

See above

### What did you expect to happen?

See above

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above
```

**Comment by carlocab** [comment]
`brew` won't uninstall `apache-arrow` when `apache-arrow-glib` is installed because this would break `apache-arrow-glib`. This is not weird at all.

If you don't care about breaking `apache-arrow-glib` but want to keep it installed, you can follow the command suggested by the error message:
```
You can override this and force removal with:
  brew uninstall --ignore-dependencies apache-arrow
```

**Comment by carlocab** [comment]
Regardless of whether you remembered installing `apache-arrow-glib`, it was still installed. And `brew uninstall` should not break other installed formulae.

What change in behaviour in `brew` are you looking for here? It's not clear at all from your comments so far.

**Comment by carlocab** [comment]
> I opened this issue just to report the issue itself

What exactly is the issue here? I still don't really understand what the issue is.

> maybe, `apache-arrow-glib` might have been installed automatically when I installed `apache-arrow`.

That should not happen, and most likely did not: otherwise we'd have heard it from others by now. `apache-arrow` has ~80,000 installs a year, and the `apache-arrow` maintainers often test the Homebrew formula (and have reported issues with it in the past).

On the other hand, the _reverse_ should happen. That is, `apache-arrow` should be installed automatically when `apache-arrow-glib` is installed, because `apache-arrow-glib` depends on `apache-arrow` (and not vice-versa).

**Comment by carlocab** [comment]
That's not really how GitHub issues work, I'm afraid.

In the future, please file issues only if there is a reproducible bug that needs to be fixed in `brew`, or if you're requesting a new feature. The issue reporting template even makes it pretty clear what kind of things you should be reporting here.

If you'd just like somewhere to post about error messages you've seen from `brew` and how you've handled them, please do that elsewhere.
