### ISSUE TITLE
brew --prefix fails to git clone when HOMEBREW_NO_INSTALL_FROM_API is set

### ISSUE THREAD

**Issue by trefis** [Homebrew/brew#15147]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 931327df1f30a3a5b1aa07657c0d1070e61988f9
Last commit: 4 days ago
Core tap JSON: 04 Apr 11:44 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Use brew --prefix pkg inside of a sandboxed environment using sandbox-exec (read-only file system).

### What happened (include all command output)?

```
$ env HOMEBREW_NO_INSTALL_FROM_API=1 sandbox-exec -p '(version 1)(allow default)(deny network*)(deny file-write*)(allow network* (remote unix))(allow file-write* (literal "/dev/null") (literal "/dev/dtracehelper"))' brew --prefix openssl
==> Tapping homebrew/core
fatal: could not create work tree dir '/opt/homebrew/Library/Taps/homebrew/homebrew-core': Operation not permitted
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /opt/homebrew/Library/Taps/homebrew/homebrew-core --origin=origin --template=` exited with 128.
```

### What did you expect to happen?

Get the output `/opt/homebrew/opt/openssl@3`.
Which I do get when I don't set the environment variables.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ env HOMEBREW_NO_INSTALL_FROM_API=1 sandbox-exec -p '(version 1)(allow default)(deny network*)(deny file-write*)(allow network* (remote unix))(allow file-write* (literal "/dev/null") (literal "/dev/dtracehelper"))' brew --prefix openssl
$ sandbox-exec -p '(version 1)(allow default)(deny network*)(deny file-write*)(allow network* (remote unix))(allow file-write* (literal "/dev/null") (literal "/dev/dtracehelper"))' brew --prefix openssl
```
```

**Comment by trefis** [comment]
Note: seems related to https://github.com/Homebrew/brew/issues/14663 (ping @kit-ty-kate ).

**Comment by kit-ty-kate** [comment]
The maintainer in https://github.com/Homebrew/brew/issues/14663 seemed to imply the contrary though. In any case this is required for opam so if this isn't isn't going to be supported we'd have to look into removing our brew support sadly.

**Comment by MikeMcQuaid** [comment]
> Why is a manual `brew tap` required?

Because they didn't run `brew update` with `HOMEBREW_NO_INSTALL_FROM_API=1`. If they had: it would have already created and cloned this.

> The maintainer in #14663 seemed to imply the contrary though.

Whether it's implied or not: we do not support this. It's an incredibly niche use-case that we have never claimed to support. If we ever did: that's an accident.

> we'd have to look into removing our brew >= 4.0.0 support sadly.

Homebrew is a rolling release package manager. We don't support any older versions. Not supporting Homebrew >=4.0 means not supporting Homebrew.

**Comment by Bo98** [comment]
The problem here really is that you are using `HOMEBREW_NO_INSTALL_FROM_API`. Unless you have a really good reason to set this, unset this and all your problems will probably go away. It is only needed for legacy purposes or homebrew-core development.

`brew --prefix` works fine in a sandbox except in two scenarios:

* This is the first time you are using Homebrew with `HOMEBREW_NO_INSTALL_FROM_API` (this is the situation you describe in this issue)
* This is the first time you are using Homebrew under a new macOS user account (initial installation even counts as "using Homebrew").

If you don't set `HOMEBREW_NO_INSTALL_FROM_API` you remove one of these scenarios. The latter scenario is not one you typically need to worry about and resolves when the user runs most other brew commands (including `brew update`).

**Comment by kit-ty-kate** [comment]
`HOMEBREW_NO_INSTALL_FROM_API` was necessary for us to keep compatibility with homebrew 4.0.0 and 4.0.1 but I suppose this is not necessary anymore since 4.0.2 and i can simply point to upgrading homebrew for users who encounter the problem. I'll remove it then. Thank you.

**Comment by trefis** [comment]
Thanks!
