### ISSUE TITLE
Supporting multiple versions of a dependency

### ISSUE THREAD

**Issue by hiql** [Homebrew/brew#15298]
### Verification

- [ ] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

I am a java developer, I use openjdk/maven/gradle.

maven depends on openjdk
gradle depends on openjdk@17

so I have to install 2 jdks on my mac.It's a little bit annoying:(

actually, openjdk@17 is ok for both maven and gradle 

### What is the motivation for the feature?

to reduce duplicate packages

### How will the feature be relevant to at least 90% of Homebrew users?

  Nothing

### What alternatives to the feature have been considered?

 Nothing

**Comment by ZhongRuoyu** [comment]
Just to add a little bit of context: I switched `gradle` from `openjdk` to `openjdk@17` in https://github.com/Homebrew/homebrew-core/pull/126337 because the current latest `gradle` does not support running on `openjdk` 20. This is temporary; once `openjdk` 20 support is shipped (starting from `gradle` 8.3, according to https://github.com/gradle/gradle/issues/23488), we will switch it back to `openjdk`.
