### ISSUE TITLE
Ignore github pre-releases in livecheck

### ISSUE THREAD

**Issue by joshka** [Homebrew/brew#15416]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

brew livecheck should ignore pre-release versions from packages that use github releases.

### What is the motivation for the feature?

Example E.g. https://github.com/johnlindquist/kitapp/releases.
At the time I created this issue, the current release (marked "latest") is:
- https://github.com/johnlindquist/kitapp/releases/tag/v1.54.53
The most recent release is:
- https://github.com/johnlindquist/kitapp/releases/tag/v1.59.1

(this is not yet a cask as it fails local audit due to picking up the livecheck version)

### How will the feature be relevant to at least 90% of Homebrew users?

Avoids inaccurately suggesting pre-release versions of software that is delivered via github releases. This is likely < the 90% threshold

### What alternatives to the feature have been considered?

Perhaps this could also be delivered via a github specific livecheck strategy rather than an update to the git release strategy (I'm not particularly aware of the implementation details on this)

**Comment by joshka** [comment]
for local repro:
```ruby
cask "script-kit" do
  version "1.54.53"
  sha256 "fa91e52301e33e14ac6d48d22760406c509f0c30492072008e911d6b46e2980d"

  url "https://github.com/johnlindquist/kitapp/releases/download/v#{version}/Kit-macOS-#{version}-x64.dmg",
    verified: "https://github.com/johnlindquist/kitapp/releases/download"
  name "script-kit"
  desc "An open-source kit to optimize your developer workflow"
  homepage "https://www.scriptkit.com/"

  app "Kit.app"
end
```

```
❯ brew audit --cask --new script-kit

==> Downloading https://github.com/johnlindquist/kitapp/releases/download/v1.54.53/Kit-macOS-1.54.53-x64.dmg
Already downloaded: /Users/joshka/Library/Caches/Homebrew/downloads/0c8f0f95073ea8cee4199ff147a9bc1f5d1fb7cbbf4976f43d746a2c385b8e9c--Kit-macOS-1.54.53-x64.dmg
==> Downloading https://github.com/johnlindquist/kitapp/releases/download/v1.54.53/Kit-macOS-1.54.53-x64.dmg
Already downloaded: /Users/joshka/Library/Caches/Homebrew/downloads/0c8f0f95073ea8cee4199ff147a9bc1f5d1fb7cbbf4976f43d746a2c385b8e9c--Kit-macOS-1.54.53-x64.dmg
audit for script-kit: failed
 - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
 - Version '1.54.53' differs from '1.59.1' retrieved by livecheck.
 - Version '1.54.53' differs from '1.59.1' retrieved by livecheck.
Error: 2 problems in 1 cask detected
```

**Comment by MikeMcQuaid** [comment]
CC @samford @nandahkrishna @SMillerDev for thoughts.

**Comment by SMillerDev** [comment]
That's what `:github_latest` is for AFAIK.

**Comment by joshka** [comment]
Makes sense. I missed that other strategies existed as they were not documented in the cookbook. I think this can probably be closed (or noted as a doc update suggestion rather than a feature request)

**Comment by SMillerDev** [comment]
Yeah, they're in https://docs.brew.sh/Brew-Livecheck rather than a specific cookbook.

**Comment by samford** [comment]
Yes, since this cask uses a GitHub release asset, you will want to use the following `livecheck` block to use the `GithubLatest` strategy:

```ruby
livecheck do
  url :url
  strategy :github_latest
end
```

For what it's worth, the livecheck information cask cookbook needs to be updated. I can vouch for the main [livecheck documentation](https://docs.brew.sh/Brew-Livecheck) and the [technical documentation](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.html), since I wrote almost all of it myself. I'm not sure who wrote the related section in the cask cookbook but some of the information is giving incorrect advice.

I have some planned changes for the documentation (including the cask cookbook section) but I have to merge a technical change (after working through current PRs) beforehand. I only mention it as a way of saying that the existing documentation isn't perfect but it should be helpful for getting started with livecheck.
