### ISSUE TITLE
Deprecate cmd::missing

### ISSUE THREAD

**Issue by binury** [Homebrew/brew#15450]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

> code for resolving dependency trees is already in deps.rb, so porting that over to the missing cmd would mean refactoring (into, I imagine, dependencies_helpers)
I agree that there is a redundancy
which **begs the question: 'what does missing do, now, that deps --missing cannot?'**
It's a nice alias… 🤷‍♀️
the missing cmd -aside from refactorings- hasn't been changed in 11+ years since its inception. And it is like a dozen LOC.
**I think that not unlike the obsolete brew deps-tree cmd (which was changed to an arg, -tree), the missing module is extremely specific in purpose and so will probably only ever have a single specific value. I.e., there's only so much functionality one can dream up that the missing module would ever have, no?**

### What is the motivation for the feature?

#15445 Adds the functionality of cmd::missing as an arg (--missing) for cmd::deps

This will create a minor redundancy. This issue simply serves to note that redundancy.

Since the urgency of this is near-zero and the changes are small in scope… I think this deprecation/refactoring _could be_ a nice "good-for-first-time-contributors" task that can sit for awhile without any negative impact

### How will the feature be relevant to at least 90% of Homebrew users?

> More productive maintainers and contributors are better for all users.

### What alternatives to the feature have been considered?

N/A

**Comment by Daddy4637** [comment]
Please take me off the subscription list and email list! I do not want to be apart of this and am unsure how I got added but these emails are taking up my space and I do not want to be involved! Sent from my iPhoneOn May 17, 2023, at 4:17 PM, Robin Ury ***@***.***> wrote:﻿
Verification

 This issue's title and/or description do not reference a single formula e.g. brew install wget. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

Provide a detailed description of the proposed feature

code for resolving dependency trees is already in deps.rb, so porting that over to the missing cmd would mean refactoring (into, I imagine, dependencies_helpers)
I agree that there is a redundancy
which begs the question: 'what does missing do, now, that deps --missing cannot?'
It's a nice alias… 🤷‍♀️
the missing cmd -aside from refactorings- hasn't been changed in 11+ years since its inception. And it is like a dozen LOC.
I think that not unlike the obsolete brew deps-tree cmd (which was changed to an arg, -tree), the missing module is extremely specific in purpose and so will probably only ever have a single specific value. I.e., there's only so much functionality one can dream up that the missing module would ever have, no?

What is the motivation for the feature?
#15445 Adds the functionality of cmd::missing as an arg (--missing) for cmd::deps
This will create a minor redundancy. This issue simply serves to note that redundancy.
Since the urgency of this is near-zero and the changes being so small in scope… I think this deprecation/refactoring could be a nice "good-for-first-time-contributors" task that can sit for awhile without any negative impact
How will the feature be relevant to at least 90% of Homebrew users?

More productive maintainers and contributors are better for all users.

What alternatives to the feature have been considered?
N/A

**Comment by MikeMcQuaid** [comment]
> What alternatives to the feature have been considered?

A suggested alternative: don't merge https://github.com/Homebrew/brew/pull/15445 and keep `brew missing` around instead?

CC @carlocab for thoughts

**Comment by carlocab** [comment]
There's some overlap, but I don't think we're in a place where either of `brew deps --missing` or `brew missing` is a full replacement of the other.

`brew deps --missing foo` shows missing recursive dependencies for `foo` but `brew missing foo` shows only missing direct dependencies.

On the other hand, `brew missing` can be called without a formula argument to show all missing dependencies, but `brew deps --missing` will error if not given a named argument.

I don't have a strong opinion about which one to keep, but I think we should at least have the full functionality implemented in one of them before deprecating the other. I have a mild preference for keeping `brew deps --missing`,  but I am unsure about how much sense it makes for `brew deps --missing` to not require a named argument but `brew deps` does.

**Comment by binury** [comment]
Ah, sorry; I overlooked `missing` called _without_ formula args.

1. Is there a specific/intended reason that `missing` just looks direct requirements? Or is it just that the functionality was never added?
FWIW, `brew deps --missing --direct $F` args are compatible, so users _can_ exclude depdeps.

2. A noteworthy difference I see is that `brew deps --verbose --missing --direct $(brew list)` cannot yet alias `brew missing` because **errors can be raised by 'invalid' formulae**… whereas `missing`, calling `Formula.installed directly`, is a honey badger and does **not** care,. (e.g., I for some reason have the old `mongodb` keg around and `brew deps mongodb` exits (1) because  ‘FormulaUnreadableErrorError: mongodb: unknown or unsupported macOS version: :mountain_lion` )

**Comment by binury** [comment]
unintentionally ended up looking at this for a few hours… 

There are 2 similar but implicitly distinct methods of determining whether a formula's deps have been satisfied:

a. `brew missing` checks whether `some_formula.missing_dependencies` is empty, and `missing_dependencies` checks `installed_prefixes` for the (non)existence of the keg(s).

https://github.com/Homebrew/brew/blob/946478aed4c3a8b0271ef6ef36e93f9d8d6de216/Library/Homebrew/formula.rb#L2091-L2102


b. `brew deps --missing` and `some_dependency.satisfied?` also check these directories, but **unlike `brew missing`** will **not** report a dep as installed if the installation exists but is not the latest…

https://github.com/Homebrew/brew/blob/946478aed4c3a8b0271ef6ef36e93f9d8d6de216/Library/Homebrew/formula.rb#L569-L582
