### ISSUE TITLE
Wrong SDKROOT on 10.11 with Xcode 8.1

### ISSUE THREAD

**Issue by jszakmeister** [Homebrew/brew#1550]
With Xcode 8.1 on El Capitan (10.11), SDKROOT is left pointing at the 10.12 SDK.  This is causing some compile time detections of features to pass when the host operating system doesn't actually support it.  I'm not sure what the right answer is here as Xcode 8.1 doesn't have an 10.11 SDK packaged.  However, I think the system ones (from the CLT?) are correct.  We can work around this by having it build in the std environment, but it seems better to fix the root problem.

This can be easily seen by running `brew sh` and dumping the environment:

```text
:: brew sh
:: env | grep SDKROOT
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
```

This was discovered while troubleshooting install issues with Neovim (neovim/homebrew-neovim#194) and found that jemalloc was detecting an os feature (os_unfair_lock) that is not present on the host OS.  As part of the build, it generates doc tags and the runtime loader discovers that the required symbol is missing.

**Comment by MikeMcQuaid** [comment]
This is correct behaviour but @ilovezfs will be able to elaborate on why better than I will as he's got a much firmer grasp of the problem/

**Comment by ilovezfs** [comment]
Putting aside the more general conversation for the moment, regarding jemalloc specifically:

This has been reported to jemalloc:
https://github.com/jemalloc/jemalloc/issues/494

It was resolved by jemalloc here:
https://github.com/jemalloc/jemalloc/commit/9b94c015af7fe7f86b19c71059be8758afd06fe3

The Homebrew jemalloc formula already contains the fix (which is the same as the fix upstream ultimately decided to go with after experimenting with an alternative):
https://github.com/Homebrew/homebrew-core/blob/master/Formula/jemalloc.rb#L19

Regarding the SDK issue, since we do not, and cannot, require the CLT (given that we want users to be able to build formulae with Xcode alone), just using the version 7 CLT whenever an Xcode 8 SDK issues arises on 10.11 is a not a viable option for us. Apple intends the 10.12 SDK to be fully usable by both 10.11 and 10.12, with each setting the MACOSX_DEPLOYMENT_TARGET accordingly. However, setting the deployment target doesn't automatically take into account which symbols are defined on each version of macOS.

There are issues that arise with this when software doesn't heed the set of weak symbols for 10.11 either with a compile time check in the build system or with run-time support for undefined dynamic lookup. For brew, we have mitigated such bugs by setting the autoconf and CMake cache values to false in order to help the compile-time checks get it right.

In the specific case of os_unfair_lock_lock, it's a weak symbol added as of Xcode 8.1, though Apple hasn't yet gotten around to adding it to the list in MacOSX.sdk/usr/lib/system/libsystem_c.tbd. Also, jemalloc uses their own autoconf variable for it (je_cv_os_unfair_lock) so our built-in workaround wouldn't help anyway for this one.

**Comment by jszakmeister** [comment]
> Putting aside the more general conversation for the moment, regarding jemalloc specifically:
> 
> This has been reported to jemalloc:
> jemalloc/jemalloc#494
> 
> It was resolved by jemalloc here:
> jemalloc/jemalloc@9b94c01

I'm aware of the issue there, but it seems to me that there is a larger danger here in having the build environment targeting a different version of the OS than the host system.  And I wouldn't call it a resolution, it's more of a workaround for a broken environment.  I'm not saying that it's Homebrew's fault necessarily--I think the absence of a true 10.11 SDK is at fault, IMHO.

> The Homebrew jemalloc formula already contains the fix (which is the same as the fix upstream ultimately decided to go with after experimenting with an alternative):
> https://github.com/Homebrew/homebrew-core/blob/master/Formula/jemalloc.rb#L19

Yep, I'm aware of that too.  Thanks.

> Regarding the SDK issue, since we do not, and cannot, require the CLT (given that we want users to be able to build formulae with Xcode alone), just using the version 7 CLT whenever an Xcode 8 SDK issue arises on 10.11 is not a viable option for us. Apple intends the 10.12 SDK to be fully usable by both 10.11 and 10.12, with each setting the MACOSX_DEPLOYMENT_TARGET accordingly. However, setting the deployment target doesn't automatically take into account which symbols are defined on each version of macOS.

Is there documentation stating that Apple intends the 10.12 SDK to be used for 10.11?  I've seen nothing that eludes to that, and in fact, if you try creating a new project in Xcode 8.1, there is no option to target 10.11, only 10.12--which seems to indicate that the 10.12 SDK is truly meant to be for 10.12 only.

> There are issues that arise with this when software doesn't heed the set of weak symbols for 10.11 either with a compile-time check in the build system or with run-time support for undefined dynamic lookup. For brew, we have mitigated such bugs by setting the autoconf and CMake cache values to false in order to help the compile-time checks get it right.

I'm not sure how to interpret this.  Does it mean that jemalloc is at fault for not implementing the check correctly?  Or autoconf for not wrapping things properly?  Apple for failing to improperly specify things?  Something else?  Is there a portable to do this check that does not involve executing something at configure time?

> In the specific case of os_unfair_lock_lock, it's a weak symbol added as of Xcode 8.1, though Apple hasn't yet gotten around to adding it to the list in MacOSX.sdk/usr/lib/system/libsystem_c.tbd. Also, jemalloc uses their own autoconf variable for it (je_cv_os_unfair_lock) so our built-in workaround wouldn't help anyway for this one.

So is the issue that Apple broke things here?  Do you know if anything has been filed in radar about it?  We can certainly workaround the issue with jemalloc, but I'd like to see the root cause fixed and prevent propagating the headache. :-)

**Comment by ilovezfs** [comment]
You may find these helpful:

Why You Should Use the Latest SDK:
https://developer.apple.com/library/content/qa/qa1806/_index.html

Setting the Base SDK:
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringYourApp/ConfiguringYourApp.html#//apple_ref/doc/uid/TP40012582-CH28-SW37

Setting the Deployment Target:
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringYourApp/ConfiguringYourApp.html#//apple_ref/doc/uid/TP40012582-CH28-SW21

>Does it mean that jemalloc is at fault for not implementing the check correctly?

Yes.

>So is the issue that Apple broke things here?

No.

>And I wouldn't call it a resolution, it's more of a workaround for a broken environment.

There are different ways to approach the problem. I'm not going to criticize jemalloc's decision to punt given what was said here in reference to their attempt to use a more "proper" approach: https://github.com/jemalloc/jemalloc/issues/494#issuecomment-261031550


In the future, we'll possibly rely more heavily on the linker flag `-no_weak_imports` but since the version 7 CLT is still in the mix, that's currently problematic since only version 8 CLT and Xcode 8 implement `-no_weak_imports`. Note that developers can make use of it immediately to help catch these problems.

**Comment by jszakmeister** [comment]
@ilovezfs Beautiful!  Thanks for the pointers.  I'll be sure to look at them soon!

**Comment by ilovezfs** [comment]
@jszakmeister you're welcome. Let us know if you have any more questions :)

**Comment by jszakmeister** [comment]
@ilovezfs Just wanted to say thanks again.  The links were a real help!

**Comment by ilovezfs** [comment]
@jszakmeister You're welcome!

**Comment by Jose123456** [comment]
The problem with setting SDKROOT that way is that it can lead to the generation of static libraries which depend on symbols that don't exist in OS X 10.11. This happened to me with librdkafka. A librdkafka compiled with Homebrew contains a reference to `_clock_gettime`:
```
nm /usr/local/lib/librdkafka.a  | grep gettime
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _clock_gettime
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
```
Trying to link statically with that archive fails like this:
```
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _mtx_timedlock in librdkafka.a(tinycthread.o)
      __tthread_timespec_get in librdkafka.a(tinycthread.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The offending code is [here](https://github.com/edenhill/librdkafka/blob/0.11.0.x/src/tinycthread.c#L937). The very same code compiled outside of Homebrew does not contain the offending reference. I tracked this down to `SDKROOT`. Running a brew interactive install and unsetting `SDKROOT` before the `./configure` and `make` steps fixes the problem. This is on OSX 10.11.6 with Xcode 8.2.1.

**Comment by ilovezfs** [comment]
We intentionally set SDKROOT along with MACOSX_DEPLOYMENT_TARGET, which should be sufficient for the code to compile correctly. Please report this to upstream. You can refer them to 

https://github.com/pyca/cryptography/commit/b637aec1624e558b0e158064264a2523a4dcba31
and
https://github.com/pyca/cryptography/pull/3841
