### ISSUE TITLE
Unavailable patch file for readline

### ISSUE THREAD

**Issue by pbald** [Homebrew/brew#1563]
When i try to install readline i get this 404 error
```
# brew install readline
clang version 1.0 (http://llvm.org/svn/llvm-project/cfe/tags/Apple/clang-23 exported)
Target: x86_64-apple-darwin10
==> Downloading http://ftpmirror.gnu.org/readline/readline-6.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/readline-6.3.8.tar.gz
==> Downloading https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2af/raw/746fc543e56bc37a26ccf05d2946a45176b0894e/readline-6.3.8.diff

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "readline--patch"
Download failed: https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2af/raw/746fc543e56bc37a26ccf05d2946a45176b0894e/readline-6.3.8.diff
```

**Comment by MikeMcQuaid** [comment]
You need to run `brew update --force`

Please in future:
- read and fill out the issue template 
- file formulae issues in Homebrew/homebrew-core instead

**Comment by jpdevries** [comment]
I've run `brew update --force` and still get this error. I ran into when trying to `brew install php71`

<details>
<summary>Terminal Output</summary>
<pre>
j15:~ jP$ brew update --force
Already up-to-date.
j15:~ jP$ brew install readline
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Downloading https://ftpmirror.gnu.org/readline/readline-6.3.tar.gz
Already downloaded: /Users/jP/Library/Caches/Homebrew/readline-6.3.8.tar.gz
==> Downloading https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2a

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "readline--patch"
Download failed: https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2af/raw/746fc543e56bc37a26ccf05d2946a45176b0894e/readline-6.3.8.diff
j15:~ jP$ 
</pre>
</details>

**Comment by jpdevries** [comment]
I was affected by the update bug. After following this instruction I was OK 🍺
