### ISSUE TITLE
Request: Add Dry Run for Uninstall

### ISSUE THREAD

**Issue by Geoff12889** [Homebrew/brew#15837]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Could we have the ability to uninstall as a dry-run?

brew uninstall [formula] --dry-run

### What is the motivation for the feature?

To test what would be removed and potentially bugged with missing dependencies.

### How will the feature be relevant to at least 90% of Homebrew users?

Ensuring we don't potentially remove necessary files, scripts and programs.

### What alternatives to the feature have been considered?

Running uninstall not as a dry run

**Comment by MikeMcQuaid** [comment]
Good idea.

**Comment by MikeMcQuaid** [comment]
Sorry, I misread this as a request for dry run for `https://github.com/Homebrew/install/blob/master/uninstall.sh`. If this is a request for that or e.g. `brew autoremove`: I'd consider it but as-is I won't, sorry.

**Comment by Geoff12889** [comment]
Sorry I don't understand well enough to say which I was suggesting. Basically like how we can `--dry-run` with `brew install`. It won't actually install, but it prints what would have been installed as a result. Something like that but for uninstall.

**Comment by Geoff12889** [comment]
My exact scenario is that I have two versions of openssl, @1 and @3. I assume I only need @3, but I'm hesitant to remove @1 because other packages may rely on it as dependencies.

When uninstalling a package, it'd be helpful to see what all would be removed (aliases, files, folders, etc.) and what could cause potential problems with other packages before going through with the uninstall.

I hope I'm explaining that well enough.

**Comment by apainintheneck** [comment]
`brew uninstall` should print an error message and refuse to remove an packages that are actively being used as dependencies of other packages.

I'm not personally opposed to adding this option but it might be difficult since there are some extra checks to see if a package is still being used that show up pretty late in the uninstall code. It might be kind of a pain to try and pre-evaluate that stuff just to be able to add a dry run command. At the same time, dry run is really helpful when you don't know or aren't interested in figuring out all of the technical details of a random command line program.

Also, `brew autoremove` already has a dry run option. That could be combined here since autoremove gets run automatically if you have the `HOMEBREW_AUTOREMOVE` environment variable set.
