### ISSUE TITLE
Funding information in .rb file

### ISSUE THREAD

**Issue by patrick-geyer-21** [Homebrew/brew#15890]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Other package managers allow you to attach maintainer/funding information to the package.json file for example.
Can brew create a standardized field for this such that funding could be done programatically for packages one is using, rather than having to browse to project's homepage etc.

### What is the motivation for the feature?

Open source development funding

### How will the feature be relevant to at least 90% of Homebrew users?

Fund open source devs

### What alternatives to the feature have been considered?

Scraping github pages, home pages

**Comment by MikeMcQuaid** [comment]
How do you imagine this working? Can you provide more detail on your proposal both from the programmatic API and user perspective? Thanks!

**Comment by alebcay** [comment]
Not the original poster, but one outcome is that the implementation/experience _could_ resemble [`npm fund`](https://docs.npmjs.com/cli/v7/commands/npm-fund), which can show funding information for a particular package or for all installed packages, etc.

When running `npm install`, the message `[number] dependencies are seeking funding, run npm fund for info` (or something like that, I'm paraphrasing here).

Now, that's what NPM does. There's certainly room for doubt regarding if such a message at `brew install` time is a desirable user experience (I've certainly read blog posts of people annoyed about seeing nag messages<sup>1</sup>). Maybe we just leave it as a voluntary command for people to discover/use on their own.

The metadata for how NPM supports this is [a `funding` property in `package.json`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#funding). In formulae (and casks?), a new `funding` DSL could be introduced that just accepts a string containing the URL to Patreon, GitHub Sponsors, etc. Maybe it could be a more complex structure if needed.

As a maintainer, I think this is the aspect that gets a bit hairy. This works for NPM because package owners maintain their own package directly and have full control over the `funding` property in their `package.json`. If we have that metadata here, the onus is now on us (Homebrew maintainers and contributors) to ensure the correctness of the funding links.

I would not be surprised if some bad actor would try to hide a change of funding link inside a bigger PR, for instance. Or if an author switches donation platforms, we would have to keep track of this as well. Projects switch homepages/code hosting sites at times too, but the stakes of getting it right are always a bit higher if there's money (or the prospect of money) involved. I would feel a lot more comfortable if we had audits/cops in place when such a feature is released.

Just my thoughts on how such a feature might look in Homebrew. Maybe someone has a better (more maintainable?) conception. 🙂

---

<sup>1</sup> - In `npm install`, it's possible to execute code, so prior to this feature being available in `npm`, it was not uncommon for package owners to spam solicitations for funds in the log output. This would accumulate quickly due to nested dependencies and be an absolute nightmare if one needed to review/go through the install logs (in case of failure, etc.). With `npm fund`, there is at least a designated place to put such info so it's less common to see such messages in the install log output nowadays.

**Comment by MikeMcQuaid** [comment]
> ust my thoughts on how such a feature might look in Homebrew. Maybe someone has a better (more maintainable?) conception. 🙂

I agree with these thoughts and concerns. I think pulling the same contents as the the sponsors button output (if there's an API, I think there is, I should know this as I worked on it 😅) then that seems like a good middle ground here. If we had something else: I think I'd want it to e.g. link directly to something on the homepage.

**Comment by RandomDSdevel** [comment]
- This could be an external coomand first.  Should it?  
 - Could or should this information also get displayed in formulas' '`brew info`' output at some point?  I don't recall external commands having the ability to extend `brew info`'s output, so this would likely only happen after merger into the main '`brew`' codebase, if/when that happened.

**Comment by patrick-geyer-21** [comment]
I personally would like something as flexible as npm's 'funding' key in package.json

In there, you should be able to specify patreon etc, but also email addresses.
I think in the next few years a lot of email addresses will be able to receive money. E.g. I receive money at paco@walletofsatoshi.com. This means that developers that install an auto-tipping tool can automatically tip cents or fractions of cents straight to the maintainers every time they install dependencies.

[sudonym-btc/zap](https://github.com/sudonym-btc/zap)

Totally understand if people think it's too risky, but maybe getting funds to open source maintainers is worth some risk!

**Comment by MikeMcQuaid** [comment]
> I personally would like something as flexible as npm's 'funding' key in package.json

As explained above: that doesn't work for us because the model is different. `package.json` is controlled by the maintainer of the NPM package who also uploads it to NPM. Homebrew formulae are controlled by Homebrew maintainers who are not the NPM maintainers.

> This means that developers that install an auto-tipping tool can automatically tip cents or fractions of cents straight to the maintainers every time they install dependencies.

This would need hooks into Homebrew that we will not add.

> Totally understand if people think it's too risky, but maybe getting funds to open source maintainers is worth some risk!

I think your proposal is too risky, yes, and not worth the risk but, as mentioned above, using some existing metadata makes most sense to me.



> I agree with these thoughts and concerns. I think pulling the same contents as the the sponsors button output (if there's an API, I think there is, I should know this as I worked on it 😅) then that seems like a good middle ground here.

This is accessible through https://docs.github.com/en/graphql/reference/objects#fundinglink

**Comment by patrick-geyer-21** [comment]
I understand the model is different. Most homebrew packages contain a link to a git repository don't they? 
Maybe the best way to get funding info is to follow that link and then parse maintainer information from there.

**Comment by MikeMcQuaid** [comment]
> Maybe the best way to get funding info is to follow that link and then parse maintainer information from there.

That's what the API I suggested does.

**Comment by colindean** [comment]
While collecting funding data in formulae and casks' definitions is attractive, I'm not sure it's a scalable idea. `license` is a precedent, though.

A first pass could be as easy as building a funding URL dynamically for GitHub projects with a valid GH API FundingLink.

A runtime check could suffice. Perhaps:

* If a package's `url` or `head` is a GitHub URL, use that GH API FundingLink.
* Otherwise, retrieve the source package or the git repo and look for one of the heuristics below.

A DSL modification could allow an arbitrary URL as an override. However, I'm unsure if Homebrew wants to get into directing people where to fund a package. _I_ would prefer to see that come from some file in the source code itself.

Sourcing the data and updating it is basically another artifact in the repo. Perhaps one data source can be the `.github/FUNDING.yml` file in a package's source working dir at build time. Some part of the build process can look for this and then somehow attach its information to a particular package version's metadata. Maybe it could also look at `./FUNDING.yml` or maybe parse out a `Donations` header from `./README.md` or show the entirety of a `./DONATIONS.{txt,md,adoc,…}`.

A problem with this is that this data could fall out of date if recorded in the package metadata or in the formula itself.
