### ISSUE TITLE
Add user definition to HOMEBREW_CASK_OPTS

### ISSUE THREAD

**Issue by lashomb** [Homebrew/brew#159]
This is a feature request. I recently tried to automate some developer setups and wanted to use cask, but couldn''t get around it needing to be run as the end user. I can easily discover and provide that user, but my scripts run as root. It would be immensely useful if a user could be defined in the HOMEBREW_CASK_OPTS variable and then set permissions that way so that it can be provisioned without user interaction.

**Comment by DomT4** [comment]
You probably want to file this at the [Caskroom](https://github.com/caskroom/homebrew-cask) for now. The two projects are working on moving closer together but it's a complicated process and we remain two separate entities sharing a common ecosystem, with differing development teams and processes.

That's where the `HOMEBREW_CASK_OPTS` environment scheme is defined, rather than by us, at this point in time.

**Comment by lashomb** [comment]
Ok thanks, I will.
