### ISSUE TITLE
Not all scripts installed to zsh/site-functions are completion scripts

### ISSUE THREAD

**Issue by zachwhaley** [Homebrew/brew#1594]
### Propose a feature:

When installing a script to the directory `share/"zsh/site-functions"`, it is assumed this is a zsh completion script, and the zsh completion caveat is printed after installation (see https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg.rb#L300).

But not all scripts in zsh/site-functions are completion scripts. Some are scripts for functions that can be loaded on demand with zsh's `autoload` command.
The zsh/site-functions directory is actually a part of the zsh `fpath` array which, I believe, is specifically used for loading function scripts (see http://zsh.sourceforge.net/Doc/Release/Functions.html), and the completion system happens to use this directory to store and load completion scripts (see http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Autoloaded-files).

Since both function scripts and completion scripts are stored in zsh/site-functions, it is incorrect to assume all files installed to zsh/site-functions are completion scripts.

A proposed change:
According to the the zsh completion docs
> The convention for autoloaded functions used in completion is that they start with an underscore

So maybe homebrew could check for scripts installed to zsh/site-functions beginning with an underscore before printing the zsh completion caveat message.

**Comment by apjanke** [comment]
I mostly or kind-of agree with this. `site-functions` can contain arbitrary globally-visible autoloadable functions; it's only the underscore-prefixed ones that are completions. (And they should have a `#compdef ...` header, too, as an additional check.) So it's incorrect to say completions have been installed for other functions that go there.

However: other zsh functions that get installed to Homebrew's `share/zsh/site-functions` are also probably meant to be globally-available. And doing that means doing the same actions as for making completions available: getting that directory on your `$fpath`, which requires user intervention. Formulae which install non-completion functions to our `zsh/site-functions` might also deserve basically the same caveat, just with slightly different wording (E.g. "Zsh functions have been installed..." instead of "zsh completion has been installed...".)

Maybe this deserves just a wording change than removing the caveat entirely.

Do you have any specific examples of formulae which install non-completion zsh functions to the `share/zsh/site-functions` directory?

**Comment by zachwhaley** [comment]
The wording change sounds good to me.

The example would be my little [project](https://github.com/zachwhaley/homebrew-beer/blob/master/bp4o.rb), which installs a zsh function to `zsh/site-functions` but no zsh completion scripts.

**Comment by apjanke** [comment]
Yep, that makes sense. In that case, `brew` is kind of lying about "completions", but the user still should probably be advised that something went to a directory that may not be on their `$fpath` by default. (Otherwise they'll run your setup command and get a "command not found" error.)

Sounds like a dynamically-chosen wording change is in order.

Fixing this will probably be low priority, since it's a subtle-ish documentation change – the proper steps for the user to take are the same as if completions actually had been installed, so the current advisories `brew` is giving probably aren't breaking anything.

**Comment by MikeMcQuaid** [comment]
> Fixing this will probably be low priority, since it's a subtle-ish documentation change – the proper steps for the user to take are the same as if completions actually had been installed, so the current advisories brew is giving probably aren't breaking anything.
>  👍 1

Yep. Given it's not affecting a core formulae we'll accept a PR for this but probably not gonna work on it ourselves. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
