### ISSUE TITLE
Correct log level when ignoring pinned package on brew upgrade

### ISSUE THREAD

**Issue by janerikmai** [Homebrew/brew#16212]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 4.1.20-2-gd72ee37
ORIGIN: https://github.com/Homebrew/brew
HEAD: d72ee37f60e287e833ef9b1882bc6ca8ded01aea
Last commit: 65 minutes ago
Core tap JSON: 13 Nov 14:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.42.1 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false
```

### What were you trying to do (and why)?

Doing a brew upgrade with a pinned package and expecting output 

``` shell
Error: Not upgrading 1 pinned package:
helm 3.13.2
```
NOT to be kind 'Error'.

### What happened (include all command output)?

``` shell
brew upgrade
==> Downloading https://formulae.brew.sh/api/formula.jws.json

Error: Not upgrading 1 pinned package:
helm 3.13.2
==> No packages to upgrade
==> Downloading https://formulae.brew.sh/api/cask.jws.json
```

### What did you expect to happen?

Maybe raise discussion about what to expect as information in output but for me personally `Error` seems wrong when brew just skips a package.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew pin package

brew upgrade
```

**Comment by MikeMcQuaid** [comment]
Error seems correct to me: you have requested that everything is upgraded and it has not been.

**Comment by janerikmai** [comment]
Probably, just for me Error means broken or something failed, but it did not fail it worked as intended to skip this upgrade. So I guess I am expecting a 'Skipped' over an 'Error'.

**Comment by apainintheneck** [comment]
I agree that this is surprising behavior though it seems like it was built this way intentionally.

@MikeMcQuaid Do you remember the original use case where people relied on the behavior of `brew upgrade` returning a non-zero error code caused by not upgrading pinned packages? It seems like we even have a flag to avoid doing that called `--ignore-pinned` which causes the command to not display this error message.

IMO this should probably just be a warning since this is expected behavior according to the man page:

```
If <cask> or <formula> are specified,
        upgrade only the given <cask> or <formula> kegs (unless they are pinned; see `pin`, `unpin`).
```

**Comment by MikeMcQuaid** [comment]
> Do you remember the original use case where people relied on the behavior of `brew upgrade` returning a non-zero error code caused by not upgrading pinned packages?

`brew upgrade` means "Homebrew upgrade everything". To not upgrade pinned packages means that you are not upgrading everything and, similarly, that you are not upgrading anything that recursively depends on anything that is pinned.

In general: pinned packages do not work well and not as people expect. If you pin things: you can expect both those packages and other packages depending on them to eventually break.

**Comment by apainintheneck** [comment]
Right but just because pinning packages is discouraged doesn't mean it should be an error. Errors should be reserved for unexpected failures. This is not unexpected. The user made the choice to pin the package in the first place.

**Comment by MikeMcQuaid** [comment]
> Errors should be reserved for unexpected failures.

@apainintheneck I do not agree with this. For me asking Homebrew to do something and it won't do it because you've told it/configured it to not do so should be an error, not a warning.

I could be convinced that the error should be more limited i.e. it's prevented something else from being upgraded, not just the pinned package, though, and would review a PR to adjust that scope.

**Comment by apainintheneck** [comment]
Right but it's confusing to users as seen here. This seems to be the exception in the codebase. Most of the time when we print error messages it means that something unexpected happened. That can be either a user error when the input is unexpected or a software problem when something fails during install for example.

What is the action we're expecting the user to take when they see this error message? How are they supposed to react to it?

**Comment by MikeMcQuaid** [comment]
> What is the action we're expecting the user to take when they see this error message?

Unpin the formula or use `brew upgrade <formula>` instead.

**Comment by apainintheneck** [comment]
That's not clear from the error message at all though.

**Comment by MikeMcQuaid** [comment]
@apainintheneck Agreed. I think at least the messaging can be improved here (which is why I've left the issue open 😅). Thanks for pushing on this ❤️

**Comment by apainintheneck** [comment]
Okay, let's see what we can do to improve the messaging here. The main worry here is that we seem to allow users to upgrade packages that have pinned dependencies which could potentially cause those packages to not function correctly since their dependencies are outdated.

There is no mention of this possibility in the `brew pin` docs though. Maybe it would make sense to add a note there.

https://github.com/Homebrew/brew/blob/8b2af53f322ec1a87e9ca271210f20e5954e3926/Library/Homebrew/cmd/pin.rb#L14-L15

Inside the update code, we have three situations where we might print messages related to pinned formulae.

1. Inside `Homebrew::Upgrade.check_installed_dependents`. This looks like it should probably be at least a warning since we already print a warning for skipped outdated dependents a few lines above this.

https://github.com/Homebrew/brew/blob/8b2af53f322ec1a87e9ca271210f20e5954e3926/Library/Homebrew/upgrade.rb#L338-L344

2. Inside `Homebrew::Upgrade.check_installed_dependents` again. This prints an error which seems appropriate.

https://github.com/Homebrew/brew/blob/8b2af53f322ec1a87e9ca271210f20e5954e3926/Library/Homebrew/upgrade.rb#L414-L421

3. Inside the upgrade command itself in the `.upgrade_outdated_formulae` method. This is the one we've been discussing here. We could add a line here that says something like `and this might cause formula that depend on them to not work correctly`. This could be printed only in the case that one of the pinned formulae was installed as a dependency. Warning message 1 already seems to imply this though.

https://github.com/Homebrew/brew/blob/8b2af53f322ec1a87e9ca271210f20e5954e3926/Library/Homebrew/cmd/upgrade.rb#L194-L197

**Comment by MikeMcQuaid** [comment]
@apainintheneck I think it'd be easiest to discuss a PR at this point rather than in an issue. I'm worried about going to start contradicting myself just from trying to mentally map what's going on here 😅
