### ISSUE TITLE
Disable brew upgrade without confirmation

### ISSUE THREAD

**Issue by himat** [Homebrew/brew#16850]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

It can be hard to remember `brew update` vs `brew upgrade` if you don't use them that often.
I ran `brew upgrade` by accident just now and now all my dozens of packages are being updated.

I instead just wanted to update brew itself with `brew update`

I don't really ever want `brew upgrade` to run, and so I think it would be nicer if running `brew upgrade` showed a prompt requiring explicit confirmation or calling it with a `-y` flag as `brew upgrade -y`

### What is the motivation for the feature?

To reduce confusion and prevent unwanted packages from changing 

### How will the feature be relevant to at least 90% of Homebrew users?

Many people probably accidentally upgrade packages which now breaks a lot of their setup

### What alternatives to the feature have been considered?

NA

**Comment by reitermarkus** [comment]
By design, Homebrew will always install and upgrade to the latest stable version and not ask for permission from the user (except when `sudo` is required) to do so. 

> breaks a lot of their setup

Homebrew is not a version manager, so if your setup depends on specific versions of software, you should use a dedicated version manager for that software, or host that specific version in your own tap. You can also use `brew pin`, but that comes with some caveats.

That all aside, suddenly requiring `-y` would break even more scripts/setups.
