### ISSUE TITLE
[Suggestion] Use $JAVA_HOME to detect java version instead java_home

### ISSUE THREAD

**Issue by meritozh** [Homebrew/brew#169]
I use **[jabba](https://github.com/shyiko/jabba/)** to manage my Java versions. But it will install java in `$HOME/.jabba/jdk/`

`/usr/libexec/java_home` will only check `/Library/Java/JavaVirtualMachines`, so `brew --config` will show `JAVA: N/A`.

Please add a function to find Java by `javac` if `$JAVA_HOME` is not empty. The output of `javac -version` is so simple, just need skip six characters.

**Comment by mikemcquaid** [comment]
I agree with this. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by apjanke** [comment]
Sounds like a good idea.

We may still need to fall back to `/usr/libexec/java_home` if a specific version of Java is needed and `$JAVA_HOME` doesn't meet the version requirement, but another JDK that does is available in the default system locations. E.g. in my `.bashrc`, I set `$JAVA_HOME` by calling `/usr/libexec/java_home`, because some programs need `$JAVA_HOME` and don't know how to use OS X's `/usr/libexec/java_home`.

**Comment by mikemcquaid** [comment]
Closing this in favour of the PR in https://github.com/Homebrew/brew/pull/183.
