### ISSUE TITLE
deps command for all/installed formula does not support --full-name

### ISSUE THREAD

**Issue by chbrown** [Homebrew/brew#1692]
**Bug/inconsistency report** (is improving consistency a feature request?)

`brew deps --installed` (or `--all`) ignores the `--full-name` argument. For example:

    $ brew deps --full-name netcdf
    homebrew/science/hdf5
    szip

Which is good and proper, but:

    $ brew deps --full-name | grep netcdf
    homebrew/science/netcdf: hdf5

The output should instead be:

    homebrew/science/netcdf: homebrew/science/hdf5

**Comment by MikeMcQuaid** [comment]
Makes sense. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by apjanke** [comment]
This is complicated a little bit, because some dependencies, but not all, are currently displayed with qualified names. It looks like the X11 ones are.

```
$ brew deps --installed  --full-name | grep netcdf
homebrew/science/gmt: fftw gdal netcdf pcre
homebrew/science/mbsystem: fftw gdal gmt homebrew/x11/gv homebrew/x11/openmotif netcdf proj
homebrew/science/netcdf: hdf5
homebrew/science/xmgredit: homebrew/x11/openmotif netcdf triangle
```

I believe this is because they are displayed using the `Dependency` name in this format, and not the `Formula` name, and the `Dependency` name depends on whether they are specified in qualified form in the formula. For example, this is from mbsystem.

```
  depends_on "fftw"
  depends_on "gdal"
  depends_on "homebrew/x11/gv"
  depends_on "homebrew/x11/openmotif"
```

Is this current behavior expected and to be preserved? I would think so, because that's useful information, and `--full-name` could be interpreted more as "expand unqualified names".

**Comment by apjanke** [comment]
I put in a PR for this: #1706.
