### ISSUE TITLE
Remove `FormulaTextAuditor`.

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/brew#17159]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Replace `FormulaTextAuditor` with RuboCops, if it isn't already.

### What is the motivation for the feature?

`FormulaTextAuditor` is only used for two audits.

### How will the feature be relevant to at least 90% of Homebrew users?

Easier maintenance.

### What alternatives to the feature have been considered?

None.

**Comment by issyl0** [comment]
Yay! Were you planning on working on this, Markus, or can I take it? I have time this weekend (I'm on-call, so at home for once).

**Comment by issyl0** [comment]
The [`audit_text`](https://github.com/Homebrew/brew/blob/7e0c137955d269befdd69f01fa989fb38c2b49b5/Library/Homebrew/formula_auditor.rb#L904) audit requires loading a formula and looking at its name, aliases and `bin`/`sbin`/etc. binary names. Since RuboCop is just a massive text processor, we might have to keep it around?

**Comment by reitermarkus** [comment]
We load the formula anyways for `audit`, so we could add a `TestAuditor` which audits the test block by calling the block with overridden `system`, `shell_output` and `pipe_output` methods and `method_missing` with a list of allowed test methods.
