### ISSUE TITLE
Major Install Fail (complex)

### ISSUE THREAD

**Issue by samcharles90** [Homebrew/brew#1729]
I’m studying for the entrance exam to a programming course i’m interested in. I was following the instructions on my school’s website for learning to use terminal. I didn’t really know what I was doing or how high the stakes were. I’m working on a 2009 Macbook Pro, OS X 10.9.5.

The problem started when I was unable to install a gem in the ruby directory (computer told me I didn’t have permission, even though I am the admin) so I did a google search, decided to install Homebrew, but I didn’t know what I was doing and started to install it in terminal with the command brew update. After a few seconds I got scared and decided to quit terminal mid-process. What was I thinking? I wasn’t. And now I’m in deep trouble.

I then thought it would be a good idea to fix the problem (not being able to install a gem) by giving myself (admin) permission for everything on my startup disk. (clicked get info on my Mac HD, sharing & permissions, add, me, read & write, settings, apply to enclosed items). Took about 30 minutes.

That’s when these weird problems started:

1) a .command file I was previously able to open and run says it can no longer be executed because I don’t have appropriate access privileges.

2) my vpn program that used to work flawlessly can no longer connect.

3) not sure if this is a problem, but I noticed that the top line of terminal now says on console after “Last login: Day Month Date Time…”. That’s new.

4) I noticed that there are programs called “com.apple.dock.extra.xpc” and “com.apple.ShareKitHelper.xpc” that are open now when I start my computer.

Fixes I already tried that have failed:

1) I used disk utility to “repair permissions” on my whole disk. Twice. Each time took 30 minutes and nothing changed. I also looked at the get info > permissions on my .command file, which is normal and says I should be able to read & write. Yet I still get the error message when I try.

2) I uninstalled and reinstalled my vpn program, twice, to no avail. restarted my computer a bunch of times.

3) I fully installed Homebrew (correctly this time, using the raw Github link). I ran brew doctor and it told me I had some things that were "unlinked" and that I had to follow the instructions to link them. So I did. And then I uninstalled Homebrew, again using GitHub, also correctly to the best of my knowledge. At the end of the uninstall, I got the following message:

The following possible Homebrew files were not deleted:
/usr/local/bin/
/usr/local/etc/
/usr/local/Homebrew/
/usr/local/include/
/usr/local/lib/
/usr/local/libexec/
/usr/local/MacGPG2/
/usr/local/man/
/usr/local/share/
/usr/local/var/
You may wish to remove them yourself.

I don’t know If I should, but I’m too scared to try anything else at this point. I’m freaking out that I might have really messed up my computer. I could really use some help from a kind soul out there!!

**Comment by vitorgalvao** [comment]
> I was following the instructions on my school’s website for learning to use terminal. I didn’t really know what I was doing or how high the stakes were.

A single command can wipe your entire drive. That said, as long as you don’t just give your `sudo` password to any command without knowing what it actually does, it’s unlikely you’ll harm your system irreparably (you might nuke your personal files, though, which are usually more important).

> computer told me I didn’t have permission, even though I am the admin

That doesn’t mean you can do everything all the time time, but that you can elevate your permissions temporarily ([`sudo`](https://en.wikipedia.org/wiki/Sudo)). It’s a security feature.

> giving myself (admin) permission for everything on my startup disk. (clicked get info on my Mac HD, sharing & permissions, add, me, read & write, settings, apply to enclosed items).

There’s your cause right there. You’re really not supposed to do that, and I’m actually slightly surprised the OS let you (El Capitan, with [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection), might not have). In your position, I’d backup my stuff and do a clean install of the whole system, starting over. Likely not how you want to spend your Christmas/end of year, but if you’re that uncomfortable with the terminal, it’ll be safer than trying a bunch of debug commands from strangers.

If you want to try and fix it, though, I’d advise asking on [Ask Different](https://apple.stackexchange.com/) or [Stack Overflow](https://stackoverflow.com/), since this was not caused by Homebrew. I’ll leave the issue open in case someone else wants to chime in, though.

As a bit of a side note, instead of `gem install <whatever>`, `sudo gem install <whatever>` would’ve done it. Though that also isn’t generally recommended it wouldn’t have been that harmful. [RVM](https://rvm.io/) (and others) would also have sufficed. Basically with `sudo gem (…)` you’re using your system’s ruby, and with Homebrew (or RVM) you’re installing a parallel ruby that you can mess with at your leisure.

Finally, don’t get discouraged! Mistakes are how we learn. You had bad luck this time, but it’s an important stepping stone. The terminal is as powerful as it is useful, and learning to use CLI tools is extremely rewarding. Good luck!

**Comment by samcharles90** [comment]
Thank you for taking the time to explain that to me! I think I'll take your advice and do a complete reinstall. I feel so lucky I avoided doing any major damage. It was a mistake, but I won't get discouraged.
