### ISSUE TITLE
golang not update to 1.23.0

### ISSUE THREAD

**Issue by bing127** [Homebrew/brew#18048]
### `brew doctor` output

```shell
Warning: go 1.22.6 already installed
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Warning: go 1.22.6 already installed
```

### What were you trying to do (and why)?

Warning: go 1.22.6 already installed

### What happened (include all command output)?

Warning: go 1.22.6 already installed

### What did you expect to happen?

Warning: go 1.22.6 already installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Warning: go 1.22.6 already installed
```

**Comment by krehel** [comment]
Please fill out the questions in the issue.

**Comment by gromgit** [comment]
Also, @bing127, if you can help resolve the remaining issues with https://github.com/Homebrew/homebrew-core/pull/175310, that'll get your desired Go release out the door faster.

As a general rule, Homebrew takes _days_ to roll out major releases of popular toolchains like Go, Rust and Python, simply because at least half of the dependent formulae will fail building and/or testing with the new toolchains.
