### ISSUE TITLE
Analytics should be opt-in

### ISSUE THREAD

**Issue by kunwon1** [Homebrew/brew#18479]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

Analytics should be opt-in only. This is the ONLY way you can respect your users privacy. As it stands now, while installing homebrew, there is a very inconspicuous text notice explaining that analytics are opt-out. I was lucky to catch it. 

If you're going to keep it opt-out, the warning should be huge and impossible to miss. Anything else is unacceptable

### What is the motivation for the feature?

Respect for users privacy

### How will the feature be relevant to at least 90% of Homebrew users?

Respect for users privacy

### What alternatives to the feature have been considered?

There is absolutely no conceivable alternative

**Comment by p-linnane** [comment]
The reality is that opt-in analytics are useless. Opting-in would skew toward a very small group which would prevent us from making informed decisions for the project. In order to get anything meaningful it has to be opt-out. We don't collect analytics on first run, we print a message explaining how to opt-out before ever collecting information, and it's completely anonymous with no ability to identify individual users data.

I'm a security professional, and I hate analytics, but this is necessary for us to understand the user base and prioritize highly used software. Meaningful analytics will help us continue running this project for years to come, and I think the approach of not collecting anything until the user has a change to opt-out is the best case scenario.
