### ISSUE TITLE
brew install octave hangs macos-12 github action runner, due to qt installation

### ISSUE THREAD

**Issue by fangq** [Homebrew/brew#18595]
### `brew doctor` output

```shell
This has been previously reported in #16209 against macos-11, but it has been closed due to macos-11 was no longer supported in github.

however, this issue appears again in macos-12, which is currently supported github runner.

example hanged build can be found here

https://github.com/fangq/iso2mesh/actions/runs/11413968520/job/31762253381
https://github.com/fangq/iso2mesh/actions/runs/11408582821/job/31747587033
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
see #16209
```

### What were you trying to do (and why)?

see #16209

### What happened (include all command output)?
example hanged build can be found here

https://github.com/fangq/iso2mesh/actions/runs/11413968520/job/31762253381
https://github.com/fangq/iso2mesh/actions/runs/11408582821/job/31747587033

### What did you expect to happen?

see #16209

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
add the below file to a github project as `.github/workflow/test_brew.yml` and commit it to github


name: test brew install octave

jobs:
  brew_test:
    name: brew test
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: [[ "$RUNNER_OS" == "macOS" ]] && brew install octave
```

**Comment by Bo98** [comment]
The same reasons apply. There isn't a Qt 6.7 bottle for macOS 12 so it's building it from source. It's not hanging forever - it's just very slow because of that. We don't build prebuilt bottles for macOS 12 anymore. We ended prebuilt bottle support for macOS 12 on our side last month. Note that we have no connections to GitHub Actions team so support periods do not always precisely align.

With that said, [GitHub deprecated macOS 12 runners earlier this month](https://redirect.github.com/actions/runner-images/issues/10721) and are slowly phasing them out. Your workflow will stop working entirely soon. The runners will be removed on 3rd December, but you will start seeing them disappear for periods from 4th November.

Please migrate to `macos-13` instead.

**Comment by fangq** [comment]
> There isn't a Qt 6.7 bottle for macOS 12 so it's building it from source.

is there any reason why previously built bottle could not be used? does it have to be rebuild?

> Please migrate to macos-13 instead.
I tried macos-13 and macos-14, both failed octave tests as they do not seem to come with any default graphics toolkits

https://github.com/fangq/iso2mesh/actions/runs/11414566357/job/31763625359
https://github.com/fangq/iso2mesh/actions/runs/11414732000/job/31763994250

**Comment by Bo98** [comment]
> I tried macos-13 and macos-14, both failed octave tests as they do not seem to come with any default graphics toolkits

I'm not an expert on `octave` so not sure the answer to this. It may be a bug but it may also be that it requires some configuration. I know macOS 14 and later on GitHub Actions are different because it uses arm64 and is virtualised in a different way. I don't know the internals of how macOS 13 is deployed on GitHub however.

**Comment by fangq** [comment]
thanks, I posted my question at https://github.com/orgs/Homebrew/discussions/5687 as you suggested.

Because macos-12 never  completed installation, so I did not know if it had similar issues as macos-13 and -14.
