### ISSUE TITLE
How are we meant to use the new versions system?

### ISSUE THREAD

**Issue by telemachus** [Homebrew/brew#1937]
I apologize if this is the wrong place to bring this up, but I'm not sure where else to raise the issue. In a nutshell, I'm not sure I understand how best to use the new versioning system.

I'd like to be able to install the latest version of Lua (5.3.4) and have it appear as `/usr/local/bin/lua` with `luarocks` at `/usr/local/bin/luarocks`. But that doesn't appear possible any longer. I suppose that I can make the symlinks myself or rig some way for scripts that assume `/usr/bin/env lua` to find `lua-5.3@`, but that feels cludgy and clumsy. So, without assuming that the new Homebrew system is at fault, I just want to understand how you all intend for it to be used. What is the right way for end-users who just want to use one version (the newest or any other) of a program to simplify things?

Another way of putting my question is why not let users determine which version of a package gets installed with the default executable names? Only one at a time can be default, but why can't each user decide for themselves which one?

TIA

**Comment by MikeMcQuaid** [comment]
This is a good place to bring this up and the right conversation to have. Our current system is still very much under discussion and negotiation. Currently there's two types of keg-only formulae:

1. Those that can exist side-by-side with all other versions
2. Those that cannot exist side-by-side

For 1 you have stuff like GCC and Lua 5.3 where the executables and libraries are suffixed so they don't clash. Lua is in [violation of our docs here](https://github.com/Homebrew/brew/blob/master/docs/Versions.md) because it requires patched to do so so I'll update this shortly.

For 2 you have things like MySQL which don't exist to have multiple versions installed at once and don't support prefixing. These are installed as `keg_only :versioned_formula`.

What I'm still debating is: should everything be 2 (without exception), should almost everything be 2 (with the exception of things like GCC that can be easily invoked as `CC=gcc6` or should we just decide everything on a case-by-case basis?

**Comment by telemachus** [comment]
I'm not sure I follow. Sorry if this question is me not getting it. If everything is (or becomes) like 2, where does that leave things like Lua 5.3? There's very little point (as I see it) in allowing users to install Lua 5.3, but forcing it to be keg only.

Also, unless I'm missing it, you didn't answer part of my question: would `brew` ever consider allowing users to install non-default versions (e.g., Lua 5.3 right now), but with default names (e.g., the binaries are `lua` and `luarocks`)?

**Comment by MikeMcQuaid** [comment]
> There's very little point (as I see it) in allowing users to install Lua 5.3, but forcing it to be keg only.

That's the mentality we're hoping to change through better tooling. Keg only things just mean you need to add an extra location to your `PATH`. Longer term `brew switch` or a similar tool may allow you to specify that they should always be linked to `/usr/local/bin` but we need to avoid our dependency system exploding on that before then.

> would brew ever consider allowing users to install non-default versions (e.g., Lua 5.3 right now), but with default names (e.g., the binaries are lua and luarocks)?

Yes but with the choice of either: 
- default names and being keg only 
- suffixed names and being linked into /usr/local/bin

**Comment by telemachus** [comment]
> That's the mentality we're hoping to change through better tooling. Keg only things just mean you need to add an extra location to your PATH.

Ah, that does make sense. Now I half-wish that lua-5.3 *was* keg only—provided it was called `lua`.

> Longer term brew switch or a similar tool may allow you to specify that they should always be linked to /usr/local/bin but we need to avoid our dependency system exploding on that before then.

Ok. That sounds reasonable. (At the moment `brew switch` doesn't seem able to handle or find things like `lua-5.3` at all. Am I correct about that or just using it wrong? The documentation for it is pretty terse.)

**Comment by MikeMcQuaid** [comment]
> Now I half-wish that lua-5.3 was keg only—provided it was called lua.

I opened https://github.com/Homebrew/homebrew-core/pull/9472 to try this out.

> At the moment brew switch doesn't seem able to handle or find things like lua-5.3 at all. Am I correct about that

You are correct.

**Comment by MikeMcQuaid** [comment]
Closing this as the discussion is mostly over but thanks for the 💭s.
