### ISSUE TITLE
I can't install /usr/local/Homebrew/.git: Permission denied Failed during: git init -q

### ISSUE THREAD

**Issue by BarryZhan** [Homebrew/brew#2062]
After fresh install macOS Sierra 10.12.3, I tried to install homebrew, but I can't install.

It says

/usr/local/Homebrew/.git: Permission denied Failed during: git init -q

What am I gonna do?

**Comment by MikeMcQuaid** [comment]
Fill in the issue template in future or we'll close the issue without comment.

In this case try `sudo chown -R $USER:admin /usr/local`

**Comment by maxgorovenko** [comment]
@MikeMcQuaid Your solution is very bad! What if I need that a few users use homebrew on same mac?

I have a real example with CI tool Teamcity. Its agent is running on macos (to build ios apps). I don't know why, but it wants to have access to /usr/local/etc/gitconfig. May be just for reading. And it doesn't have the rights to do this, because teamcity is not the only brew user on that macos.

For now I added teamcity user to group wheel and chowned whole /etc/local to group wheel. But this is no very good.

**Comment by MikeMcQuaid** [comment]
> What if I need that a few users use homebrew on same mac?

Put them all in the admin group and it will work.

> Your solution is very bad!

Your comment is very bad at motivating open source maintainers to help you. It's rude and entitled.
