### ISSUE TITLE
HB Homebrew JK Jekyll RE: Bad Interpreter: No such file or directory

### ISSUE THREAD

**Issue by rwebaz** [Homebrew/brew#2368]
Hello: 

RE: Confirmed this is a problem with specific formulae and not Homebrew/brew?

RE: If it's a general Homebrew/brew problem please file this issue at:

https://github.com/Homebrew/brew/issues/new

Response: I think I will file this issue here and at the link provided above.

Why? Because the issue may be with a Ruby install, a Jekyll install via Ruby Gem, or a tool.

And, when I can't get my Jekyll server to run locally on my development machine, how am I to submit code to the GitHub server that has not been run locally and confirmed?

C=> https://gist.github.com/rwebaz/64330b2f5a37f857a27a59075d55dac7

Robert

P.S. The above link is to a 'private' GIST ... unless, of course you would prefer a public gist that is followed by the search engines;

**Comment by joshka** [comment]
Hi Robert,
I'm finding it a bit difficult to understand the nature of your problem. You might find others will have the same difficulty. I'd like to offer a couple of quick tips that might help you get a resolution to your problem:

First up, it's likely to be easier on the developers to open a single issue for this rather than multiple issues. If the issue belongs somewhere else, the discussion can migrate. Perhaps leave this one open and close the other issue at https://github.com/Homebrew/homebrew-core/issues/11290.

Secondly, the info in the gist be much more useful included in this issue rather than a secondary location. You might consider using [some Markdown features](https://guides.github.com/features/mastering-markdown/) to make the problem report easier to read. In particular it's common to show command line output like so:
```
$ brew install someprogram
... the output of the command goes here too
```
Use three backticks on the lines before and after (```) to do this.

Next up there's a few things mandatory things that every bug report needs:
1. Project pre-reqs (run brew update, brew doctor)
2. What is your goal
3. What you did
4. What you expected
5. What actually happened
6. Extra info that you think might help

Your bug report contains a lot of 6, I think I can guess at 2, 3, and 4, and maybe 5 but it took a lot of work to do so.

The issue template you saw when you raised an issue has a few check boxes ticked indicating that you've done the basics troubleshooting steps. It's unclear whether you've done these. Have you run `brew update` and `brew doctor`? 

I think your goal is to run Jekyll.
I think what you did is:
```
jekyll serve --watch --baseurl ""
-bash: /usr/local/bin/jekyll: /usr/local/opt/ruby/bin/ruby: bad interpreter: No such file or directory machinemessiah:mminail.github.io
```
And you expected Jekyll to run, but it didn't.

It's unclear to me how the rest of the stuff in the gist relates to the problem.

I'm going to take a stab at solving what I think might be your problem. When you run the `jekyll` binary, it loads ruby from wherever you've initially installed it from. In your case that's `/usr/local/opt/ruby/bin/ruby`. This is the default location that Homebrew installs ruby to.

I'm guessing that you've installed ruby via Homebrew at some stage, then uninstalled / moved / deleted / changed the path. Run the following commands and paste the output.
```
ls -l /usr/local/opt/ruby
ls -l /usr/local/opt/ruby/bin/ruby
brew info ruby
brew list ruby
```

You may find that the fix is going to be as simple as `brew install ruby` if the above indicate that ruby is not installed to the expected locations.

**Comment by MikeMcQuaid** [comment]
Sorry, this isn't a problem when running a Homebrew command so it isn't a Homebrew issue.

**Comment by rwebaz** [comment]
Hello Josh: The original copy of Ruby (1.87) was pre-installed on my Mac Development machine many moons ago by Apple and defaulted to a standard user account.

I believe this is called "system" Ruby.

I then later on upgraded the "system" Ruby to (2.0) using Macports.

Even today, when logged in as the standard user on my development machine, the Terminal returns the following:

ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

To upgrade Ruby to the current release (2.4.0), the admin must install a separate instance of Macports in the admin User account on the development machine from Build in a separate /opt/ subdirectory.

This I was able to accomplish today with a restricted $PATH variable for the admin User account.

As a result, I was then able to upgrade system gem, as well.

When I switched back to the standard User, I simply let Macports be and let the upgraded gem re-install Jekyll into the /usr/local/bin.

Solution: How To Re-Install Jekyll From The Terminal In Mac OSX Sierra

From the Terminal, if Jekyll needs to be re-installed ...

1.) First update Gem

sudo gem update --system

2.) Second update Jekyll

sudo gem install -n /usr/local/bin jekyll

By the way, I posted another issue with a private GIST, this time at Macports base.

When I was building the 2nd instance of Macports with my Development machine admin account I encountered 50 error flags all pointing to a deprecated SysCall interface after upgrading to Macports ver (2.4.1)

During the make phase, the Terminal kept prompting to 'please switch to a supported interface'.

Is that not a programming issue for the developers of the binary archive over at Macports?

See: GIST https://gist.github.com/rwebaz/b71f520970c456745b4a93842a02bbe4

Note. Hit the RAW button at GitHubGist to view the text with original Terminal spacing.

I would have never been able to troubleshoot the local Jekyll server on my Development machine successfully without your timely response to my now closed issue.

Thx for your expert guidance.

Robert

**Comment by joshka** [comment]
Hi Robert, glad you got it all sorted out. The questions you've asked relate to Macports rather than homebrew, so I can't be of assistance.

I'd encourage you update the linked gist so that it can be viewed as intended by using the triple backtick trick I mentioned above. This will make it less frustrating for the Macports developers to assist you.

**Comment by rwebaz** [comment]
Ok ... Josh.
Markdown it is ...
RE: Triple backtick trick for Referenced GIST
Done.
Note. Triple backticks before (```) and Triple backticks after (```) when highlighting code statements. Check!
Plus. Double stars before (**) and Double stars after (**) when designating emboldened text ie.) Subtitles and the Beginning title to an article. Check!
Now, I am a Markdown wizard, to boot!
Thx for the tip!
Roberto

**Comment by rwebaz** [comment]
Hello Again Josh Mc:

Wow! RE: "Applying backticks to the Terminal code ... Will make it less frustrating for the Macports developers to assist you."

You are correct sir!

( Developers can be like hornets when you tap into their milliseconds, heh? )

C ( updates ) => https://gist.github.com/rwebaz/b71f520970c456745b4a93842a02bbe4

Robert

**Comment by ilovezfs** [comment]
This is Homebrew repository not the MacPorts repository. Hence locking.
