### ISSUE TITLE
Installations for non-existing formulas left around and cannot be controlled

### ISSUE THREAD

**Issue by Blaisorblade** [Homebrew/brew#238]
It seems Homebrew can't be directed to autodetect installations of removed formulas (as opposed to installations of existing formulas).
They seem problematic because they exist in some limbo, as some commands know of them and some don't. They seem to violate the invariant "all installations belong to some formula", but it's not clear it is there and it's not clear it is enforced by `brew doctor` or anything else.

Since formulas are removed (or moved into taps), I'd like to know how to review them.

`brew ls` will include them in its output (without special mention), but `brew info` will not list them.

- I'd like `brew info formula` to list such installations for formula.
- I'd like a command to list all such installations, across formulas, so I can review them, but I found none.
- In my limited testing, `brew doctor` will not complain for them (except if they are unlinked), `brew cleanup` will not remove them (which is good).

I noticed this after #234, where `brew info` gave me confusing output, leading me to conclude no `neovim` installation was around:

```
$ brew info neovim
Error: No available formula with the name "neovim"
$ ls /usr/local/Cellar/neovim/HEAD/
INSTALL_RECEIPT.json  README.md
```

**Comment by mikemcquaid** [comment]
This is not possible because the filesystem is our storage mechanism rather than a database. You can still remove then with `brew uninstall` and it's not possible for us to tell the difference between a e.g. `neovim` formula that's working and was installed from another branch and an orphaned one like in the example you have. `brew ls` still lists them and `brew uninstall` still uninstalls them so that's the best we can do really, sorry.

**Comment by Blaisorblade** [comment]
Thanks for the response. But can't you compare installations with existing
formulas? Of course you can't detect whether installations work, I'm not
asking for that, and I don't want such installations to be autoremoved.

-- 
Paolo Giarrusso
From smartphone, sorry for typos or excessive brevity

**Comment by mikemcquaid** [comment]
We could but then they would break if your tap was missing or you changed branch etc. If you'd like to add a check for this we'll accept a pull request but I'm not sure what would have handled this case for you anyway (unless you looked at e.g. `brew missing` and/or `brew doctor` regularly before installing).

**Comment by apjanke** [comment]
Keep in mind this may be difficult for `brew` to detect correctly, because `brew` also supports installing packages from formula files at arbitrary locations: you can write your own `foo.rb` formula file, and then do a `brew install /path/to/foo.rb` to install it. So you may have legit installations of packages that have no corresponding formula file inside any of your taps, or anywhere else. In short, the answer to "But can't you compare installations with existing formulas?" is "no", because there are legit, supported use cases for installations that do not correspond to existing formulae, regardless of the tap state WRT branches and so on.

The installation receipt file may be able to help distinguish that. But this may be an edge case that `brew` just can't give very good diagnostic info on without deprecating other `brew` functionality.

**Comment by xu-cheng** [comment]
FWIW, Homebrew even supports no-formula at all. i.e. Compile the source by yourself and install it to an arbitrary prefix, and run `brew link` manually.
