### ISSUE TITLE
`brew doctor` after fresh install crashes with undefined method error

### ISSUE THREAD

**Issue by dimo414** [Homebrew/brew#2428]
I just installed Homebrew on a fresh Macbook with Xcode 8.2.1 installed, and `brew doctor` fails with the following error:

```
$ brew doctor
Error: undefined method `rebuild' for #<BottleSpecification:0x007fd5489b30a0>
Please report this bug:
    https://git.io/brew-troubleshooting
/Users/dimo414/homebrew/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:10:in `block in <class:Findutils>'
/Users/dimo414/homebrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/Users/dimo414/homebrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/Users/dimo414/homebrew/Library/Homebrew/formula.rb:1726:in `bottle'
/Users/dimo414/homebrew/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:8:in `<class:Findutils>'
/Users/dimo414/homebrew/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:1:in `load_formula'
/Users/dimo414/homebrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/Users/dimo414/homebrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/Users/dimo414/homebrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/Users/dimo414/homebrew/Library/Homebrew/formulary.rb:83:in `load_file'
/Users/dimo414/homebrew/Library/Homebrew/formulary.rb:74:in `klass'
/Users/dimo414/homebrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/Users/dimo414/homebrew/Library/Homebrew/formulary.rb:207:in `factory'
/Users/dimo414/homebrew/Library/Homebrew/formula.rb:1183:in `[]'
/Users/dimo414/homebrew/Library/Homebrew/diagnostic.rb:1217:in `check_for_non_prefixed_findutils'
/Users/dimo414/homebrew/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/Users/dimo414/homebrew/Library/Homebrew/cmd/doctor.rb:27:in `each'
/Users/dimo414/homebrew/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/Users/dimo414/homebrew/Library/brew.rb:84:in `<main>'
```

I installed Homebrew with the following command (I don't want it installed into `/usr/local`):

    mkdir homebrew && curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C homebrew

Running `brew update` is sufficient to resolve this issue and get `brew doctor` to report success, but that really shouldn't be necessary for a fresh install.

**Comment by dimo414** [comment]
Update, I just noticed the install command I was using *isn't* the one listed at http://docs.brew.sh/Installation.html - I used `https://github.com/Homebrew/homebrew/tarball/master` while the installation page says `https://github.com/Homebrew/brew/tarball/master` (`brew`, not `homebrew`). I'm guessing the `homebrew` URL used to be the documented URL, and it's now out of date.

So this bug is about that URL, in this case - it should either be removed or updated.

**Comment by JCount** [comment]
What exactly is the bug you are talking about? There is nothing incorrect about the install instructions, you simply mistyped the GitHub url.

Therefore, what is it that you would like us to do? What exactly is supposed to be updated or removed? I am a bit lost here.

**Comment by dimo414** [comment]
I didn't mistype it, I referenced apparently-stale documentation that seemed to work, since it installed Homebrew, but the URL is out of date. `https://github.com/Homebrew/homebrew/tarball/master` should be updated or removed, as its existence is confusing for anyone who's referencing old Homebrew installation instructions like I was.

Re: template:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

**Comment by MikeMcQuaid** [comment]
> I don't want it installed into /usr/local):

We don't support non-/usr/local installs and you installed using the wrong URL so need to reinstall using the right URL.

**Comment by dimo414** [comment]
I don't see the need to be so hostile; I'm trying to report a confusing user experience in the hope of helping others who might wind up in my situation.

> We don't support non-/usr/local installs

That's not what http://docs.brew.sh/Installation.html says - sure it's *discouraged*, but it's clearly supported, seeing as how do to so is documented.

> you installed using the wrong URL

Yes, but that URL *exists* and contains *some* Homebrew installation. As best I can tell this used to be the URL users were supposed to use (since the documentation I referenced linked to it). Again, the existence of that URL is confusing, and I'm going to the trouble of letting you know that. Is there some reason you're opposed to removing or updating it?

**Comment by JCount** [comment]
Have you happened to look at the HEAD response from your incorrect installation URL? Your answer is there and in GitHub's automatic behavior. This is not something that warrants further discussion.

**Comment by dimo414** [comment]
Gee, if only I'd thought to do that...

Thanks for the top-notch support folks.

**Comment by MikeMcQuaid** [comment]
> So this bug is about that URL, in this case - it should either be removed or updated.
> Again, the existence of that URL is confusing, and I'm going to the trouble of letting you know that. Is there some reason you're opposed to removing or updating it?

It should not and cannot; it's needed to migrate people from older versions of Homebrew to newer ones. If you visited https://github.com/Homebrew/homebrew/ you'd note it redirects to https://github.com/Homebrew/legacy-homebrew/

> I referenced apparently-stale documentation that seemed to work, since it installed Homebrew, but the URL is out of date

Our official installation instructions are correct. I suggest you report this to wherever you found the incorrect installation instructions rather than to us.


> Re: template:

You omitted:
> Please replace this section with a brief summary of your issue AND the output of brew config and brew doctor. 

Note also the following line:
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

> I don't see the need to be so hostile; I'm trying to report a confusing user experience in the hope of helping others who might wind up in my situation.

There's was no hostility here but there is both conciseness and irritation that you didn't follow the issue template as requested.

> That's not what http://docs.brew.sh/Installation.html says - sure it's discouraged, but it's clearly supported, seeing as it's documented.

The word "supported" is never used in relation to alternate installs and regardless it's up to us to decide what's supported. Documentation does not imply support. Note we explicitly say:

> One of the reasons Homebrew just works relative to the competition is because we recommend installing to /usr/local. Pick another prefix at your peril!

> Gee, if only I'd thought to do that...
> Thanks for the top-notch support folks.

Your GitHub profile states you work for Google and from you location it's the middle of the day in your timezone. Whether you're using Homebrew for work or not mull on this for a second that you're an engineer working at one of the biggest tech companies in the world and being sarcastic towards people who are providing you with software for free in their spare time who are trying to help you. Also note that Homebrew's license states:

> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED

The reason I bring all this up is that from a brief browse of your GitHub history: you're not new to open source and it's worth noting that interactions like this are what result in unpaid, under-resourced open source maintainers burning out.

**Comment by dimo414** [comment]
Ok, apologies for starting a burnout-inducing interaction. Know that I started this issue as a honest attempt to be helpful and report a confusing user experience. I was taken aback by directives like "*Have you happened to look at the HEAD response*" which I perceive as dismissive and unconstructive - I do not generally send HEAD requests before following installation instructions (which perhaps is a mistake, but I imagine most users are similar).

The "*It should not and cannot*" comment was all I was looking for - I had presumed the `homebrew` URL was simply out of date (and therefore was letting you know about a stale resource), and not a necessary part of the legacy upgrade path.

**Comment by JCount** [comment]
@dimo414 
> Have you happened to look at the HEAD response from your incorrect installation URL? Your answer is there and in GitHub's automatic behavior.

To achieve the brevity I needed, I simply posed a question and then indicated that your answer could be found within answering it. I never (intentionally) implied that you should have done so already. It was simply much faster to give you the information needed to find the answer. Otherwise, I would have been essentially wasting time I did not have, or could have been better spent elsewhere, explaining something you could see for yourself. In your evaluation of the first sentence you seem to be forgetting the second. Also, remember please, I was responding for your benefit, not mine.

**Comment by MikeMcQuaid** [comment]
@dimo414 Thanks, I genuinely appreciate the apology and I apologise for being more concise with my original replies than I could have been ❤️
