### ISSUE TITLE
Code of Conduct: please stop censoring expressions of concern in re: analytics.

### ISSUE THREAD

**Issue by geoff-codes** [Homebrew/brew#246]
Dear @Homebrew/@owners:

I **must** at this time express my _utmost consternation_ and disappointment at the way in which those members of this community who have been voicing their concerns about the recent addition of anonymous collection of analytics to homebrew have been (and continue to be) treated. 

I am long-term member of this community. Homebrew is something that I care _deeply_ about.

In almost any other circumstance I would be loath in the extreme to "humblebrag" as I will now, but for what little it is worth, I am somewhere between the 34th and 70th most frequent contributor to this project. I have been involved to one degree or another for most of its seven years of existence. I have dedicated many, many hours to it, I think I have made some significant contributions. So it is in my capacity as a deeply invested, deeply committed, **non**-maintainer of this project that I humbly speak on the behalf of the thousands of other members of this community who are, or might be, distraught, and wish, or may wish, to express it.

I am **not saying** _I am opposed_ to analytics. On the contrary, I think they could be immensely helpful in steering the future direction of the project. But I am also someone who is very privacy and security-minded, _and I have some **legitimate** concerns_. And while there are times when censorship is necessary when _users_ are in breach of the Code of Conduct, this is not an excuse to violate it oneself.

I know "managing an open-source community is easy when your project is small but grows harder the larger your project becomes." It must be _incredibly frustrating_ to face this kind of backlash and hysteria.  But I think at this point we all need to remember that learning "how to grow your project’s community and ensure that it remains a healthy, happy and fun place" is a process that does not cease.

I see little point in citing _where_ I see plain violations of this project's Code of Conduct. There are many. Instead, I would kindly ask user and maintainer alike to please review:

- https://github.com/Homebrew/brew/blob/master/CODEOFCONDUCT.md#open
- https://github.com/Homebrew/brew/blob/master/CODEOFCONDUCT.md#considerate
- https://github.com/Homebrew/brew/blob/master/CODEOFCONDUCT.md#respectful

...and reflect for a moment. Because frankly, I currently do not feel welcome here at all. 😢

**Comment by DomT4** [comment]
Geoff,

I won't speak on behalf of other maintainers, but I can and will speak to my own concerns & experiences.

I'll also note the following for transparency's sake:
* In the last 3 months I have erased the contents of one Issue, because it contained purely personal abuse to the Homebrew maintainers on really quite a nasty level.
* Over my time in Homebrew 4 people have been blocked organisation-wide by me:
  * One for persistent GitHub insults to maintainers, and then finding maintainer's personal Twitter accounts and tweeting personal abuse to each of us repeatedly, over a persistent period of a couple of days.
  * One for sending abusive emails to maintainers' personal email accounts after doing so repeatedly on GitHub and being asked to stop.
  * One for posting repeated personal abuse on various GitHub issues, including to normal contributors, and refusing to stop when asked. That block was removed after a week, and then re-implemented when that person went right back to abusing contributors.
  * One for creating a new account that had been blocked previously to continue abusing the maintainers.

I'll also note that fundamentally, whilst the Code of Conduct is absolutely applied equally, white men have a severe imbalance in influence over open source and the voices and experiences of women and non-white contributors are frequently trampled over by FOSS communities. Homebrew is determined to not become one of those communities.

You have free speech to call me a prick, insist I should quit FOSS, suggest I should jump off a bridge, etc, and I'll note those aren't _theoretical examples_ of things that have been emailed, tweeted or posted on GitHub at me personally during my time maintaining Homebrew.

You have the free speech to say those things to me, but I have the free speech to say we don't welcome those comments around Homebrew and we won't endure them. Your free speech does not === the right to abuse me. That's not what free speech is, not even in law for many legal systems; most have "harm exemptions" to the free speech mechanism.

Just as your local pub can throw you out to stop you yelling at the guy sat next to you that you think he's a waste of oxygen and looks like Shrek, Homebrew can do the same thing. This is why Code of Conduct's exist, to enforce a _minimum_ conduct. Not to make sure every comment is one of grovelling approval but to make sure it doesn't degrade into outright insults and personal attacks.

Your local pub tossing you out because you won't stop yelling insults at that poor guy is by the strictest definition censorship, but degrees of censorship are everywhere in life _(Twitter will suspend your account if you do nothing but tweet racist abuse @ people, for example)_. Yelling censorship like its a one-size-fits-all problem is disingenuous, and I apply that broadly over the last couple of weeks more than I apply it to your comment, I add.

I will note that if people have constructive suggestions to make about analytics that go beyond _"you are all terrible human beings and this is something the NSA would do"_ your Issue will remain open until we can resolve it one way or another. As a shining example [this issue](https://github.com/Homebrew/brew/issues/152) was opened on a productive subject Homebrew could work with, and has remained open for 18 days without significant issue.

Come to us with _"Oh you could improve the opt-out mechanism with this tweak"_ or _"Have you considered this analytics provider instead?"_ or anything like that and the issue is not only welcome but encouraged. If you come to us with _"You're all a disgrace to open source, spies for Google and have been paid off by the government to collect this data"_ and again, those aren't _theoretical examples_, that's an Issue that clearly isn't going anywhere and harm reduction comes into play.

In terms of the "humblebrag" I contributed _the most_ commits to the Homebrew organisation last year, let alone the amount of Issues and Pull Requests I review. Contribution buys you _trust_, it doesn't necessarily buy you the right to make others feel absolutely awful, and look, I have fairly crappy health, I've written about that publicly before now _(and removed the posts 6 months later worrying about them)_, but none of this has been good for my health and I _have a lot of fondness_ for working on Homebrew.

Imagine being someone who doesn't know Homebrew, or someone who is vulnerable or from a section of society whose voices are respected less than us white men, and going to file an Issue with Homebrew, but before you do you check the Issue below and discover someone calling the maintainers every name under the sun and comparing them to their favourite government spy agency. Would that make _you_ want to contribute to Homebrew or would it make you want to run in the opposite direction as fast as you could? This isn't a theoretical problem. Look at tech's ongoing diversity problem, that is amplified _significantly_ in FOSS.

To be blunt, if you feel threatened by us trying to make Homebrew a safer space for everyone, from all walks of life, and the people who feel threatened feel a bit safer, I'll take that trade off because the difference between their real threat level and your's is almost universally huge, just huge.

And don't take that as me wanting you to feel like you aren't welcome here, because you _absolutely are_ and I appreciate your contributions and the discussions we've had this week _alone_, but we're both privileged to be white men and that discussion has a place in free speech and its consequences.

I am permanently uneasy with the erasure of comments, but I will not discard the harm inflicted by those comments in terms of both maintainer health and also with the view that Homebrew and FOSS would not be a worse place if people who weren't white men felt more comfortable contributing on a regular basis. There is a balance here, but the balance isn't to allow people to say and do unto others whatever they desire without consequence.

**Comment by mikemcquaid** [comment]
Hi @geoff-codes,

Firstly, our bug tracker is not an area for public expression; it's a place for reporting actionable bugs or issues we have previously not closed as a WONTFIX. People who want to express themselves publicly have Twitter, blogs and any number of other places on the internet for doing that (but @DomT4 has already made the point on this better than I have).

Secondly, you're one of the first (maybe the only) person who has created an issue about this who has actually contributed meaningfully to Homebrew. Most people who have "expressed concerns" have not been part of this community and have been publicly or privately abusive (particularly to me and @DomT4). I don't want to bore you by digging up the number or content of the private abusive emails I've been getting over the last few weeks but I'm beyond bored of them now. I edit content because I regularly have to click through issues and I don't want to read abuse repeated to me again and again.

Thirdly, the priority for me when running Homebrew is the sanity of the maintainers who contribute the most to Homebrew. As @DomT4 mentioned, between him and I we're two of the most active maintainers on this project and there's a bunch of stuff in the sidelines (applying for GSoC, keeping CI servers running, managing our finances, apply for SFC) that may not happen if the two of us dropped off. This whole analytics situation has had me very tempted on more than one occasion to leave open-source altogether and (without being too arrogant here): that would be bad for this project. If Homebrew has no more maintainers the project will die.

Finally, I'm happy to work to address concerns beyond "no analytics!" and "analytics should be opt-out" for reasons I've explained at extreme length in multiple other places. Whenever these concerns have been raised I've made PRs to fix them usually merged within 24 hours.

**Comment by mikemcquaid** [comment]
@geoff-codes Interested in your thoughts on the above comments when you get the chance, thanks!

**Comment by mikemcquaid** [comment]
Closing this out as there's nothing more actionable here but still interested in @geoff-codes' reply.

**Comment by geoff-codes** [comment]
@DomT4 @mikemcquaid Thank you for your very thoughtful and considerate replies. I apologize for not responding sooner (I've been away for a few days). I intend to follow up in greater detail with some additional, detailed thoughts very soon, but for the time being, I'll just say your points are well taken, and again, thank you for your thoughtful responses.

**Comment by MikeMcQuaid** [comment]
> I intend to follow up in greater detail with some additional and more detailed thoughts very soon, but for the time being, I'll just say your points are well taken, and again, thank you for your kind and detailed response(s).

@geoff-codes Still interested in this, even if it's privately.
