### ISSUE TITLE
List command isn't formatting columns correctly.

### ISSUE THREAD

**Issue by Phlosioneer** [Homebrew/brew#257]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Brew's list command is printing things weirdly. Here's how it's printing them: (git window isn't wide enough to show the issue, and pastebin mucked up the indentation, so here's a picture:)
 
![bugreport](https://cloud.githubusercontent.com/assets/11892150/15377930/9e9fc8a8-1d5f-11e6-94ae-5a3c24faac83.png)

The upper one is using fish shell, the lower one is using bash shell.
Issue may be related to / may be fixed by #201. 

Brew is fully up to date:
```
Homebrew 0.9.9 (git revision 406fdb; last commit 2016-05-18)
Homebrew/homebrew-core (git revision 2040; last commit 2016-05-18)
```

Brew doctor reports absolutely nothing wrong.

--

**Edited by @UniqMartin:** Attached the image so the issue still makes sense once the link is dead.

**Comment by UniqMartin** [comment]
Thanks for the report! Does `ls $(brew --cellar)` show the same behavior? If so, do you have anything in your environment that could affect the operation of `ls`? Do you see the same issue if you, e.g., use `brew search git`? What terminal are you using? Are you using `screen` or `tmux`?

> Issue may be related to / may be fixed by #201.

I'm pretty sure that's unrelated. What makes you think otherwise?

**Comment by Phlosioneer** [comment]
>Does `ls $(brew --cellar)` show the same behavior?

No, it doesn't. It prints everything perfectly.

>Do you see the same issue if you, e.g., use `brew search git`?

No, it shows searches perfectly, even for one as large as that.

>What terminal are you using?

Standard OS X one. Terminal version 2.6.1, OS X version 10.11.4

>I'm pretty sure that's unrelated. What makes you think otherwise?

I thought it might be, because they're doing a lot of changes to the methods that output stuff to terminals. I may be wrong; it was the most interesting one I found while searching older issues for list problems.

**Comment by UniqMartin** [comment]
Interesting, but I don't have an idea yet and cannot reproduce. (I asked about `ls` because that's what is used internally by `brew list`.) What is the output of `echo "$TERM"`? What does `which ls` print? What do you get from `env | egrep '^(LANG|LC_)'`?

**Comment by Phlosioneer** [comment]
> Interesting, but I don't have an idea yet and cannot reproduce.
Huh. I'll try and provide as much information as I can, because I can reproduce the bug indefinitely.

> What is the output of echo "$TERM"?

`xterm-256color`

I tried cycling through the various terminal types that are built in to the OS X Terminal. After a while, I figured out that only one instance of the shell was misprinting. So this probably wasn't brew's fault.

However, it is still _very_ interesting that the `brew list` behavior differed from `ls (brew --cellar)`
I'm going to close this issue, though the difference might be worth looking at the code.

**Comment by apjanke** [comment]
`brew ls` has two forms: one that lists the files in a formula, and one that lists the installed formulae. In this case, OP is calling the formula-listing form, and that one doesn't involve the `ls` command, at least not for output. The output of plain `brew ls` is formatted by `brew`'s own [`puts_columns` method](https://github.com/Homebrew/brew/blob/9e7b8c61a99c4d4c69da36f95759e375b7a4e116/Library/Homebrew/utils.rb#L360) in `utils.rb`. So its formatting won't necessarily match that of `ls`.

I'd suspect a minor arithmetic bug in `puts_columns` in [this part of the code](https://github.com/Homebrew/brew/blob/9e7b8c61a99c4d4c69da36f95759e375b7a4e116/Library/Homebrew/utils.rb#L380-L393) which calculates column widths and pads the items for output with `ljust`. If so, this would be sensitive to your terminal window's exact size, and the exact list of items you have installed. Opening a new session might have fixed it just because you had a different terminal window size.

Should be able to reproduce this by taking that list of formula names and feeding it to some test code that calls `puts_columns` on an arbitrary list of strings, and re-running that at various terminal window sizes. (Or just overriding the `$COLUMNS` value when calling it, which you could script.)

If this is the case, I bet the bug could be fixed, and the `puts_columns` code made more readable, by switching it to use `printf` with fixed field widths in the format specifiers, instead of padding the input items before passing to `puts`.

**Comment by UniqMartin** [comment]
> `brew ls` has two forms: one that lists the files in a formula, and one that lists the installed formulae. In this case, OP is calling the formula-listing form, and that one doesn't involve the `ls` command, at least not for output. The output of plain `brew ls` is formatted by `brew`'s own [`puts_columns` method](https://github.com/Homebrew/brew/blob/9e7b8c61a99c4d4c69da36f95759e375b7a4e116/Library/Homebrew/utils.rb#L360) in `utils.rb`. So its formatting won't necessarily match that of `ls`.

Nope. :wink: It probably should be like you say, but it isn't. See [`cmd/list.rb`](https://github.com/Homebrew/brew/blob/406fdbb391e844ea604c3eac1075c3f2562d07a9/Library/Homebrew/cmd/list.rb#L50-L51).

**Comment by UniqMartin** [comment]
> If this is the case, I bet the bug could be fixed, and the `puts_columns` code made more readable, by switching it to use `printf` with fixed field widths in the format specifiers, instead of padding the input items before passing to `puts`.

And this cannot be done because the character count is not equal to the display width thanks to ANSI escape characters that we use for formatting, but that are effectively zero-width in the output. (At least if we want to get the columns to align in both formatted and unformatted output using the same code.)

**Comment by apjanke** [comment]
Ooooops. Sorry for the misread.

Though it looks like `puts_columns` [does use `strip_ansi`](https://github.com/Homebrew/brew/blob/9e7b8c61a99c4d4c69da36f95759e375b7a4e116/Library/Homebrew/utils.rb#L371) to remove (some) terminal control sequences when calculating column widths. And it wouldn't be hard to expand it to cover other control sequences if there's still an issue with that.

That's weird then. Possibly a similar arithmetic edge case bug in `ls`? Though I'm hesitant to think that.

**Comment by UniqMartin** [comment]
We're getting a bit off track, but oh well …

> Though it looks like `puts_columns` [does use `strip_ansi`](https://github.com/Homebrew/brew/blob/9e7b8c61a99c4d4c69da36f95759e375b7a4e116/Library/Homebrew/utils.rb#L371) to remove (some) terminal control sequences when calculating column widths. And it wouldn't be hard to expand it to cover other control sequences if there's still an issue with that.

Yes, `strip_ansi` is used to compute the display width of the items. (I doubt there's an issue with this code, but who knows. It strips the ANSI control sequences we insert for formatting, but of course doesn't take into account other characters that might already exist in a given string and affect the output rendering in a terminal.)

I tested this code (`puts_columns`) pretty thoroughly with various item widths, terminal widths, and column counts. Thus I'm pretty confident it works correctly and has no arithmetic edge cases.

To get back to the question of format strings: My impression was that they are not too popular in the Ruby community. And I'm dubious whether

```ruby
items = items.each_with_index.map do |item, index|
  format("%-*s", col_width + (item.length - plain_item_lengths[index]), item)
end
```

is any clearer than

```ruby
items = items.each_with_index.map do |item, index|
  item + "".ljust(col_width - plain_item_lengths[index])
end
```

> Possibly a similar arithmetic edge case bug in `ls`? Though I'm hesitant to think that.

Very unlikely, IMO. I guess we will never know unless we find a way to reproduce this.

**Comment by apjanke** [comment]
> We're getting a bit off track, but oh well …
> [...] Thus I'm pretty confident [`puts_columns`] works correctly [...]

You're right, this is a red herring. The only reason to suspect a bug in the `puts_columns` code was the OP's observed bad output. But since that code path is not actually getting hit, no reason to think it's buggy.
