### ISSUE TITLE
brew install upgraded dependencies (cmake, pcre, swig) without asking

### ISSUE THREAD

**Issue by telamonian** [Homebrew/brew#2595]
Just now I ran

`brew install libsbml`

and for whatever reason, homebrew upgraded (ie installed the latest versions of) `pcre`, `cmake`, and `swig`, even though all of these formulas were already installed. `pcre` isn't even listed as a dependency in the `libsbml` formula.

This behavior is new. Homebrew definitely didn't used to upgrade formulas without asking, and it's definitely unwanted behavior. Is this a bug? If it isn't, how do I turn it off?

Here's the output of `brew config`:

HOMEBREW_VERSION: 1.2.0-46-g93d4fdf
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 93d4fdf938779a5cccb4aabed7d82cb533f9506e
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 232144b8435737fef95c7c314d323d101cdec8f2
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 7.0 build 700
Git: 2.6.4 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/tel/.pyenv/shims/python => /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66, 1.7.0_51
macOS: 10.11.6-x86_64
Xcode: 7.3
CLT: 7.2.0.0.1.1447826929
X11: 2.7.112 => /opt/X11

**Comment by MikeMcQuaid** [comment]
> pcre isn't even listed as a dependency in the libsbml formula.

It's a a dependency of `swig` so was needed for `swig` to be updated.

> This behavior is new. Homebrew definitely didn't used to upgrade formulas without asking, and it's definitely unwanted behavior. Is this a bug? If it isn't, how do I turn it off?

It is not new behaviour, Homebrew has always upgraded dependencies when installing software because we cannot support software which ends up using arbitrary versions of dependencies due to bugs, not being compatible or not shipping files our binary packages do.

You cannot turn this off and we are not willing to add an option to do so. This is required for Homebrew to function correctly.

Finally, please fill out the issue template as requested in future.
