### ISSUE TITLE
stty: stdin isn't a terminal

### ISSUE THREAD

**Issue by agramfort** [Homebrew/brew#2742]
Apparently since https://github.com/openmeeg/openmeeg/pull/200 was merged
we have our travis build failing:

https://travis-ci.org/openmeeg/openmeeg/jobs/239912944

See the messages:

stty: stdin isn't a terminal

in the before_install.sh section.

cc @iMichka

**Comment by iMichka** [comment]
Just to be clear, I think this is unrelated to openmeeg but more a general problem. I didn't even merge openmeeg to homebrew-science at this point.

I guess you are talking about this script:
https://github.com/openmeeg/openmeeg/blob/master/build_tools/travis/before_install.sh

Multiple brew commands in there are throwing:
> stty: stdin isn't a terminal

Maybe this is related to that change: https://github.com/Homebrew/brew/pull/2714 ? The bug has been appearing on their travis build since a few days now.

P.S. it would have been good to fill out the issue template :)

**Comment by MikeMcQuaid** [comment]
Closing this until we have an issue template filled out.

**Comment by agramfort** [comment]
sorry @MikeMcQuaid . Fixed now.

**Comment by MikeMcQuaid** [comment]
> Ran brew config and brew doctor and included their output with your issue?

You still didn't do this.


> stty: stdin isn't a terminal

This is fixed as-of https://github.com/Homebrew/brew/issues/2745 but seems unrelated to your issue.

**Comment by agramfort** [comment]
@iMichka apparently it's a libmatio issue. I can replicate after a brew update / upgrade.
Basically our binaries cannot read anymore any .mat file.

did anything change with libmatio recently?

**Comment by agramfort** [comment]
@iMichka for the record if I revert libmatio formula to the version of 3 days ago:

https://github.com/Homebrew/homebrew-science/blob/c2042d3f910bffe1311fe7ce23992cd91a13eed7/libmatio.rb

tests pass again on my mac

**Comment by iMichka** [comment]
Please, don't post unrelated issues here. This issue was about the stty problem. We can continue to discuss the openmeeg problems on your issue tracker.
