### ISSUE TITLE
Clearer explanation on how to change editor of vim

### ISSUE THREAD

**Issue by BLCKPSTV** [Homebrew/brew#2743]
Could there be a detailed instruction in to defaulting the brew editor in for example Atom.app.

Because I create more problems with vim than I make solutions with...

As change editor where to find this and how to edit this etc.. ?

**Comment by RandomDSdevel** [comment]
@BLCKPSTV:  See the description for the '`HOMEBREW_EDITOR`' environment variable under the '`ENVIRONMENT`' section of Homebrew's `man` page, as quoted here:  

```
⋮

       HOMEBREW_EDITOR
              If set, Homebrew will use this editor when editing a single formula, or  several  formulae  in
              the same directory.

              Note: brew edit will open all of Homebrew as discontinuous files and directories. TextMate can
              handle this correctly in project mode, but many editors will do strange things in this case.

⋮
```

Basically, set `HOMEBREW_EDITOR` to the correct command invocation sequence for launching your editor of choice, and you should be good to go.  (_Does_ Atom have a command-line launcher beyond macOS's built-in `open` command, though?  I've heard you can pass application binaries within '`.app`' bundles arguments with it, but I've never figured out how…)

**Comment by BLCKPSTV** [comment]
I'm just not sure where to set this HOMEBREW_EDITOR is this in my bash_profile? 
Als how can I just use nano to change to lines of codes in brew edit = I need to change dylib paths for installation of opencv/caffe to run on cpu

Thanks!

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yup, got it in one:  `~/.bash_profile` is where you'd set `HOMEBREW_EDITOR`, so just add it in there.  To use `nano` with `brew edit`, you would set `HOMEBREW_EDITOR` equal to `nano`; Homebrew will take care of the rest.  The same goes for any text editor that can be opened from within Terminal, I believe, though I haven't tested this.  As for editing files in `nano`, it works pretty similar to how TextEdit does when you use it to edit plain text files except that it doesn't have nearly as many commands (`nano` lists the ones it supports in a dynamic footer at the bottom of your screen when it's open, which I find helps a lot) and doesn't seem to support [overtype mode](https://en.wikipedia.org/wiki/Insert_key), though I _could_ be overlooking something simple (like pressing the [Insert key](https://en.wikipedia.org/wiki/Insert_key) to enable it) in the latter case.  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If you want to jump to a particular line, the command you would want to use would be 'Go To Line,' which, as listed like I explained above at run-time, is bound to the key combination <kbd>Control</kbd>-<kbd>_</kbd>.  Pressing this keystroke makes `nano` further prompt you for your intended destination line and (optional) column number(s) (the latter defaults to '1' if not supplied.)  I'm not sure you should be having to mess with dynamic linking targets, though…; if the problem is that the packages you're troubleshooting can't find some of their link-time dependencies, then rebuilding from source usually fixes that.  Have you tried that, or am I misunderstanding what you're attempting to do?  Beyond that, you _might_ have to ask a Homebrew maintainer for additional debugging assistance.

**Comment by jprokos** [comment]
For those who are don't know how to "set" something. Add this line to your bash profile: (/Users/username/.bash_profile)

`export HOMEBREW_EDITOR="/usr/bin/nano"`

When done adding that line save your changes and then refresh your bash_profile by entering this command in Terminal.

`source ~/.bashrc`
