### ISSUE TITLE
macOS High Sierra: Error: brew doctor --> undefined local variable or method `ruby_version'

### ISSUE THREAD

**Issue by sspilleman** [Homebrew/brew#2754]
Hi,

I upgraded to macOS high sierra. Running "brew doctor" I get the following error(s):

```
Error: undefined local variable or method `ruby_version' for #<Homebrew::Diagnostic::Checks:0x007f91ba1c1210>
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb:202:in `check_ruby_version'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
macpro:dupchecker sander$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
```

So far I've not encountered any issues un/installing packages etc...

S.

**Comment by scpeters** [comment]
I think this was fixed in #2738. I think if you set the `HOMEBREW_DEVELOPER` environment variables and make sure that `HOMEBREW_UPDATE_TO_TAG` is unset, then `brew up` will pull in this latest fix. Otherwise you would have to wait for the next tagged release.

**Comment by ilovezfs** [comment]
What @scpeters said.

**Comment by RandomDSdevel** [comment]
Huh, didn't know/recall that the `HOMEBREW_UPDATE_TO_TAG` environment variable existed in the first place.  (:man_facepalming:.  Next time I run a `brew` developer command while composing a Homebrew Core PR&thinsp;—&thinsp;I'm not yet proficient enough in Ruby to be making any contributions to `brew` itself&thinsp;—, I'll set this before running `brew update` again from/in that state instead of setting `homebrew.devcmdrun` back to `false` inside my local Homebrew installation's main Git repository's `git config` and checking a stable branch back out, making it even with the most recent release tag.)
