### ISSUE TITLE
OpenSSL1.1

### ISSUE THREAD

**Issue by blogabe** [Homebrew/brew#2855]
Unsure if this is for brew or core, but I have a question on formulae that depend on wget and therefore OpenSSL 1.1 (https://github.com/Homebrew/homebrew-core/pull/14000) especially if other dependencies still require OpenSSL 1.0.x.

I just want to confirm that at present the only way around this issue to by changing the wget formula locally to depend on 1.0 and not 1.1.  Is there any other way?  And given the conversation at https://github.com/Homebrew/homebrew-core/pull/14158 will there be any short term workaround to address any conflicts or will we wait until all formulae are brought up to the 1.1 version?

Thank you!

**Comment by ilovezfs** [comment]
>I just want to confirm that at present the only way around this issue to by changing the wget formula locally to depend on 1.0 and not 1.1.

That's the only way. See
https://github.com/Homebrew/homebrew-core/pull/14000
https://github.com/Homebrew/homebrew-core/pull/14012
https://github.com/Homebrew/homebrew-core/pull/14013
https://github.com/Homebrew/homebrew-core/pull/14014
https://github.com/Homebrew/homebrew-core/pull/14016
https://github.com/Homebrew/homebrew-core/pull/14019
https://github.com/Homebrew/homebrew-core/pull/14021
https://github.com/Homebrew/homebrew-core/pull/14456

>And given the conversation at Homebrew/homebrew-core#14158 will there be any short term workaround to address any conflicts or will we wait until all formulae are brought up to the 1.1 version?

In general formulae shouldn't be depending on wget anyway since macOS ships with curl. But if you do need to depend on wget for some very good reason, that could potentially be basis for switching the formula that needs wget to use 1.1.
