### ISSUE TITLE
Use less jargon

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#290]
e.g. `keg`, `tap`, `bottle`, `Cellar`, etc.

Migrated from https://github.com/Homebrew/legacy-homebrew/issues/41884

**Comment by Jack-Barry** [comment]
I'm somewhat of a novice but I'd like to start contributing to some open source projects and this improvement seems do-able given my current skill level.  

Where would be a good place to start with these?

**Comment by MikeMcQuaid** [comment]
@Jack-Barry Good questions. As a novice you'd be a great person to work on this. I'd post to this issue the various terms of jargon in Homebrew that you understood immediately, understood after a while and don't understand. Feel free to say your understanding of some of your terms here and we can clarify if they are correct (which will help understand whether they are jargon or not). Once we've got that we can help you create a pull request to change some of them. Thanks!

**Comment by Jack-Barry** [comment]
In all honesty I had to look these up in blog posts, since I have not paid much attention to the jargon during use.  (If the software I'm trying to download works, I usually just keep on truckin'.)  However, some of the terms are more understandable than others.

1. `Cellar` is the directory where all Homebrew installed software lives.  
   This one is pretty straightforward, it's where you keep all your beers, aka downloaded materials 
2. A `bottle` is a piece of software downloaded by Homebrew that will reside in your `Cellar`  
   This is also very clear. (I guess I should say brown or green, depending on the beer, heh heh)  
3. A `keg` is a package downloaded by Homebrew.  
   This one I'm a little unclear on, is a `keg` comprised of multiple `bottles`? Or are `kegs`/packages referring to something else entirely? If something else entirely would maybe `can` or `pint` be a valid replacement?
4. A `tap` refers to a repo/source for software to be downloaded from.  
   Also pretty understandable.  If you're looking for different flavors of beers, or `bottles` you'll pour them from different `taps`
  
Let me know if these are accurate or way off base, and any other terms to look into.

Cheers

**Comment by MikeMcQuaid** [comment]
> Cellar is the directory where all Homebrew installed software lives.
> This one is pretty straightforward, it's where you keep all your beers, aka downloaded materials

Yep correct 👍 except downloaded things are in `HOMEBREW_CACHE`

> A bottle is a piece of software downloaded by Homebrew that will reside in your Cellar
> This is also very clear. (I guess I should say brown or green, depending on the beer, heh heh)

This is not quite right; a bottle is a precompiled (or technically: the `install` method already run) package which not everything installed by Homebrew is.


> A keg is a package downloaded by Homebrew.
> This one I'm a little unclear on, is a keg comprised of multiple bottles? Or are kegs/packages referring to something else entirely? If something else entirely would maybe can or pint be a valid replacement?

A keg is the installation location for a particular package. It can be installed from a bottle or not from a bottle.


> A tap refers to a repo/source for software to be downloaded from.
> Also pretty understandable. If you're looking for different flavors of beers, or bottles you'll pour them from different taps

Yeh, pretty much; it's a repository that contains `formulae` (package installation instructions) and/or external commands but otherwise: yep 👍

**Comment by snood1205** [comment]
I actually really like the so called jargon. I think it fits in perfectly with `brew`'s theme and is pretty easy to understand.

**Comment by Jack-Barry** [comment]
What would be the next steps here?  I also like the jargon a lot but if there's ways to make it more accessible/user friendly I'm all for it.

**Comment by scpeters** [comment]
Would a picture or a cartoon help?

**Comment by MikeMcQuaid** [comment]
> I actually really like the so called jargon. I think it fits in perfectly with brew's theme and is pretty easy to understand.

@snood1205 But yet many users I met do not fully understand the jargon and it's demonstrated on a regular basis on our issue trackers (and @Jack-Barry's comments above).

> What would be the next steps here? I also like the jargon a lot but if there's ways to make it more accessible/user friendly I'm all for it.

@Jack-Barry what are your thoughts on my reply above? Do you feel your understanding of any of those terms was sufficiently incorrect to warrant using a more widely understood term?

> Would a picture or a cartoon help?

@scpeters Perhaps but it'd be best to aim for not needing explanation.

**Comment by Jack-Barry** [comment]
@MikeMcQuaid I think the only one that was in need of a more widely understood term was `keg`.  If `bottles` are something you download, but `kegs` aren't, it's a little misleading because the way I'd take it is "kegs are basically like giant bottles," but in this analogy you'd be pouring `bottles` (or non-bottles) into a `keg`.

Aside from that, everything else made pretty decent sense aside from some minor technical details, but nothing that would be too hard to figure out.  Those details would only come into play when digging deep and getting really far under the hood which I'm *guessing* most users of Homebrew won't be involved in.

**Comment by MikeMcQuaid** [comment]
@Jack-Barry Keg could be hidden as an implementation detail; can you remember where you say it as a user?

**Comment by MikeMcQuaid** [comment]
Passing on this.
