### ISSUE TITLE
How to disable sandboxing for external taps?

### ISSUE THREAD

**Issue by CamJN** [Homebrew/brew#2986]
In https://github.com/Homebrew/brew/commit/fb310c57b18c3835ed69e25e653cddc3570f64ac sandboxing was turned on for non homebrew taps, breaking the phusion tap because we cache the user's download token for passenger enterprise in their home dir. How can I disable the sandboxing or keep the cache somewhere allowed?

**Comment by ilovezfs** [comment]
You'll need to configure `phusion` to use `/usr/local/var/phusion` (i.e. `#{var}/phusion`) or similar, or move whatever needs access to $HOME into a step the users run after installation, and mention it in the caveats.

**Comment by CamJN** [comment]
That won't work it has to be available at the point when the curl user/password are resolved and var isn't defined at that point. See: https://github.com/phusion/homebrew-passenger/blob/master/Formula/passenger-enterprise.rb#L6-L22

**Comment by ilovezfs** [comment]
It looks like you'll need to rely on the `PASSENGER_ENTERPRISE_TOKEN` environment variable. Note that environment filtering will remove access to that soon as well (`HOMEBREW_ENV_FILTERING=1` will soon be the default), though you may be able to escape that filtering by renaming the variable `HOMEBREW_PASSENGER_ENTERPRISE_TOKEN`.

**Comment by CamJN** [comment]
That can't be cached for the users though.

**Comment by ilovezfs** [comment]
Right, they'll need to set it in their profile. But you can later cache it in `#{var}/phusion` once it exists.

**Comment by CamJN** [comment]
It only matters while fetching the tarball, so there's no point in putting it somewhere that can't be read while doing so.

Basically the formula and tap only exist to allow the users to avoid having to edit their env. If that is no longer a value of homebrew's we'll probably have to pull the formula & tap since it won't offer any benefit any more.

**Comment by ilovezfs** [comment]
That may well be the case.

**Comment by CamJN** [comment]
That's too bad. I like homebrew, but almost every time I interact with this project user-hostile behaviour is justified by the decisions of just a few people, and that makes me sad.

**Comment by MikeMcQuaid** [comment]
That's because the bulk of the work on Homebrew the package manager is done by just a few people.

Additionally, this is definitely not user-hostile behaviour, quite the opposite. We're making it so users can install from any tap without fearing that it will write random files to random places on their filesystem. This is a valuable security feature. It's a pain for tap maintainers to have to adjust to, I agree, but the writing has been on the wall for a few years for this, I'm afraid.

**Comment by chdiza** [comment]
To answer the original question:  This change also broke my shenanigans with a few select formulas in my own tap, in which I utterly abuse HB by  installing some packages outside of `HOMEBREW_CELLAR`.  (I know, I know.)  Rather than resorting to not installing that software with HB,  I got around it by setting `HOMEBREW_NO_SANDBOX` in a script that tells `brew` to install those few formulas.  Once could also leverage the `--no-sandbox` flag, I believe.

**Comment by ilovezfs** [comment]
@chdiza please do not suggest undocumented command line options and environment variables intended for internal use.
