### ISSUE TITLE
brew uses should be (much) faster

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#3007]
The algorithm used by `brew uses` ends up being really slow. Through a new algorithm, rewrite or heavy caching it would be good to make it much faster. [`brew prof uses`](https://github.com/Homebrew/homebrew-dev-tools/blob/master/cmd/brew-prof.rb) is probably the best way to optimise this.

**Comment by richiethomas** [comment]
Hi @MikeMcQuaid, I'm new to the Homebrew project and shell scripting as well, but I'm keen to take a crack at this if possible.

**Comment by richiethomas** [comment]
UPDATE: I see the `uses` script is written in Ruby, so I'm guessing I'd learn less shell scripting than a pure BaSH script.  That's fine though, still very keen to pitch in on this issue.

**Comment by MikeMcQuaid** [comment]
@richiethomas Yeh, we'd welcome any work on it. Feel free to open a PR!

**Comment by richiethomas** [comment]
Thanks @MikeMcQuaid.  You mentioned caching as a potential solution, can you give me an example of where caching is currently used in the codebase so that I don't deviate too far from the best practice?

**Comment by MikeMcQuaid** [comment]
@richiethomas I general the caching we do in cases like this looks a bit like:

```
@some_hash[formula_name] ||= begin
  # expensive operation here
end
```

In this case, doing effectively a `brew readall` and converting the entire formula tree into a hash seems like it may be a sensible approach and much quicker to query. For bonus points: make `brew readall` faster too will make this faster too.

**Comment by richiethomas** [comment]
Hey @MikeMcQuaid, I noticed this doesn't appear to be current practice, but do you think it would be a wise move to store the entire formula tree locally, like in a JSON file in the Homebrew directory, in order to reduce the compile time of the formula tree?  The tradeoff would be adding that little extra work up from when adding or removing Brew formulas, but saving the compile time (which is substantial) on the `readall` and `uses` call, essentially making it into just a straight read operation on that JSON hash (which would theoretically be O(1) or close to it).  I'm sure you've thought of this before, just wondering if there were concerns about that approach that I as a newer dev aren't seeing.  Looking forward to your feedback!

**Comment by MikeMcQuaid** [comment]
@richiethomas There's similar discussion in https://github.com/Homebrew/brew/issues/3072.

> Hey @MikeMcQuaid, it appears that, since each brew command is a new process, the dependency tree would need to be re-created from scratch every time a command is run, since even if it's cached in an instance variable, it would still be destroyed when the process dies.

It may be we're unnecessarily recomputing information that we don't need to. I think it's worth using https://github.com/Homebrew/homebrew-dev-tools/blob/master/cmd/brew-prof.rb to optimise the non-cached-on-disk case first before moving on to any cache files on disk.

> I'm sure you've thought of this before, just wondering if there were concerns about that approach that I as a newer dev aren't seeing.

We'd need the cache build operation to be extremely fast and the invalidation to be clear and pretty much idiot/error-proof. In general cache invalidation is one of the Hard Problems in software so if we can improve performance without a cache that may be good and cache without retaining state across processes that may be even better.

> it's a design choice to optimize the performance of the most commonly-used tasks, which means cutting out non-essential operations like one I suggested adding above. Is that an accurate assessment?

Yes. That said, `brew desc` is a good example for using a cache that's built on first command run and only invalidated on updates.

**Comment by MikeMcQuaid** [comment]
Another thing worth noting: we'll upgrading to Ruby 2.3 when High Sierra is released (or a bit before) which will provide performance improvements itself and add opportunities for others.

**Comment by richiethomas** [comment]
Hey @MikeMcQuaid, just checking in on this issue.  I was waiting until the Ruby upgrade to continue working, and now that it's happened I'll resume.

I'm looking at `brew prof` next, here's a screenshot of my results from `brew prof uses node`: https://imgur.com/a/nZvVa

I'll keep plugging away, feel free to update here if you've had any further thoughts on this.

**Comment by scpeters** [comment]
I just ran `brew prof uses boost` on a high sierra machine with an SSD. Here's the top few lines from profile.flat.txt

~~~
Total: 13.685066
Sort by: self_time

 %self      total      self      wait     child     calls  name
 36.89      8.427     5.048     0.000     3.379     4520   Module#module_eval
  2.13      0.337     0.292     0.000     0.046   261459   Regexp#===
  1.63      4.713     0.223     0.000     4.490   392893  *Class#new
  1.52      0.410     0.208     0.000     0.202   171762   Kernel#initialize_dup
  1.47      0.202     0.202     0.000     0.000   171440   String#initialize_copy
  1.40      0.191     0.191     0.000     0.000    88898   <Class::File>#basename
  1.30      0.190     0.177     0.000     0.012   103144   Regexp#match
  1.27      0.555     0.174     0.000     0.381    74949   Pathname#chop_basename
  1.22      1.035     0.167     0.000     0.868    17630   Pathname#plus
  1.19      0.377     0.163     0.000     0.213    76014   Pathname#initialize
  1.16      0.158     0.158     0.000     0.000    94032   Regexp#=~
  1.00      0.137     0.137     0.000     0.000   116884   Kernel#class
  0.97      2.509     0.133     0.000     2.377     8786   Formula#initialize
  0.87      0.119     0.119     0.000     0.000     4412   IO#read
  0.73      0.100     0.100     0.000     0.000   293359   NilClass#nil?
  0.72      0.098     0.098     0.000     0.000   107387   String#[]
  0.71      0.421     0.097     0.000     0.323    59197  *Hash#fetch
~~~

The biggest chunk of time (37%) is in `Module#module_eval`, but after that it's a long tail of function calls with 2% or less of the total time. I'm not sure what `Module#module_eval` means.

Seeing the regex was second on the list, I peeked at some of the html files and noticed that many of those calls come from the [version parser](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/version.rb#L325), which takes about 5% of the total time (0.677 / 13.685):

~~~
 %self      total      self      wait     child     calls  name
  0.71      0.677     0.097     0.000     0.580     9518   <Class::Version>#_parse
~~~

I notice that function has a bunch of conditional return statements for different version formats. I wonder which version format is most common in homebrew-core. We could potentially sort the regex return statements based on which are most common (as long that doesn't change the results), which could reduce the number of regex calls.

That's all that jumps out at me on first glance, unless someone knows what `Module#module_eval` means.

**Comment by richiethomas** [comment]
@scpeters `module_eval` takes a string of code (ex. "class GitFlow < Formula\ndesc \"Extensions to follow Vincent Driessen's branching model\"\n.....") and turns it into an instance of Formulary::FormulaNamespace.

Seems like the fact that this transformation is happening 9518 times is probably the best best for speeding up this command.

**Comment by MikeMcQuaid** [comment]
> We could potentially sort the regex return statements based on which are most common (as long that doesn't change the results), which could reduce the number of regex calls.

It would change the results, unfortunately.

**Comment by scpeters** [comment]
>> We could potentially sort the regex return statements based on which are most common (as long that doesn't change the results), which could reduce the number of regex calls.

> It would change the results, unfortunately.

Understood. It's not the biggest bottleneck anyway.

**Comment by richiethomas** [comment]
Hi @MikeMcQuaid, you mentioned earlier that it's really not ideal to solve this issue by using caching, due to the inevitable cache invalidation issues.  If it turns out that a non-caching solution isn't viable, we could instead make the experience "feel" faster by streaming the command's results as they're derived, vs. logging them all to the console at once.  I haven't given up yet on the original goal, but I would like to hear your thoughts on this alternate approach.

**Comment by MikeMcQuaid** [comment]
> you mentioned earlier that it's really not ideal to solve this issue by using caching

I think in-process caching could speed things up as I suspect there's things being calculated/compared/loaded multiple times unnecessarily. I agree with on-disk caching being bad due to invalidation issues.

> we could instead make the experience "feel" faster by streaming the command's results as they're derived

I'm afraid I don't think this would add things to the consumer of this tool which usually will need all the results. It's certainly not making things worse, though, so I'd 👍 a PR.

**Comment by richiethomas** [comment]
> I think in-process caching could speed things up as I suspect there's things being calculated/compared/loaded multiple times unnecessarily.

So some sort of memoization?  As a start, I can investigate whether any formulas are being added multiple times to `Formulary::FormulaNamespace` in the resource-intensive `module_eval` method discussed above.  Anything else come to mind that could be a culprit?

**Comment by MikeMcQuaid** [comment]
> So some sort of memoization?

Yep.

> As a start, I can investigate whether any formulas are being added multiple times to Formulary::FormulaNamespace in the resource-intensive module_eval method discussed above.

👍 


> Anything else come to mind that could be a culprit?

It could be the speed in which all formulae being loaded (`brew readall` can benchmark that) or it could be the algorithm that's being used by `brew uses`.

**Comment by scpeters** [comment]
It just occurred to me that we could also try to parallelize this because my cpu usage showed only one cpu being used. An outer loop in [uses.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/uses.rb#L57-L58) iterates over all ruby formula with `formulae.select do`, while the inner loop iterates over all formulae specified in ARGV with `used_formulae.all? do`. I noticed that we have the [parallel gem](https://github.com/grosser/parallel) vendored, which has a parallel version of `all?`, but I didn't see a parallel version of `select`. I tried parallelizing the inner `all?` loop with the following patch, but it made `brew uses boost` go slower. Maybe if you specified a bunch of formulae on ARGV it would be faster, but I think parallelizing the `formulae.select do` loop would be more profitable.

~~~
diff --git a/Library/Homebrew/cmd/uses.rb b/Library/Homebrew/cmd/uses.rb
index 0b09e1bf19..1200a2a569 100644
--- a/Library/Homebrew/cmd/uses.rb
+++ b/Library/Homebrew/cmd/uses.rb
@@ -17,6 +17,7 @@
 #:    `--devel` or `--HEAD`.
 
 require "formula"
+require "parallel"
 
 # `brew uses foo bar` returns formulae that use both foo and bar
 # If you want the union, run the command twice and concatenate the results.
@@ -55,7 +56,7 @@ module Homebrew
     ignores << "recommended?" if ARGV.include? "--skip-recommended"
 
     uses = formulae.select do |f|
-      used_formulae.all? do |ff|
+      Parallel.all? used_formulae do |ff|
         begin
           if recursive
             deps = f.recursive_dependencies do |dependent, dep|
~~~

**Comment by scpeters** [comment]
Looks like there's a clue to implementing a parallel select in https://github.com/grosser/parallel/pull/200

**Comment by MikeMcQuaid** [comment]
https://www.jstorimer.com/blogs/workingwithcode/8085491-nobody-understands-the-gil is worth a read. It's also remembering that parallelism will only speed up certain operations; if `brew uses` is IO-bound then it is unlikely to be sped up by throwing more threads at the problem.

**Comment by scpeters** [comment]
Thanks for your patience with this roob noob here. That was a helpful article. Also the point about possibly being IO-bound makes sense too.

**Comment by richiethomas** [comment]
@MikeMcQuaid I had a couple ideas I wanted to run by you:

In `uses.rb`, I memoized the code that's executed when passing the `--recursive` flag, reducing the number of calls from 63,000+ to 5300ish.  However, constructing the memo hash appears to actually increase the total running time, as shown in [this gist](https://gist.github.com/richiethomas/6eb102aa6dbbc719a2f9fd3bcaa4bd02).  I used the `time` command line tool as opposed to another benchmarking tool, and only ran the command a few times, so it's possible that there aren't enough data points.  I'm submitting a PR as well, to show how I constructed the hash in case there's a more optimal way to do it (although I can't imagine what that would be).  I'm just posting my progress here in case there's something I'm missing, as I would expect a reduction of calls of this order of magnitude to have a net positive effect on runtime.

**Comment by richiethomas** [comment]
For your reference, the latest PR [here](https://github.com/Homebrew/brew/pull/3304/files) contains the code for the memoization that resulted in the reduction in calls I mentioned.

**Comment by MikeMcQuaid** [comment]
@richiethomas Thanks for checking that out. I'm surprise the memoisation slowed things down but I guess it probably illustrates there's caching (perhaps at the Ruby layer) that's handling this better than we are.

**Comment by richiethomas** [comment]
I noticed some similarities between my memoization attempt and this article's coding challenge: 

https://dev.to/rpalo/secret-message-7do

Looks like the author saw similarly counter-intuitive results.

**Comment by MichaelSquires** [comment]
I'm new to this project and new to ruby so please excuse any silly comments I might make below.

It seems like the biggest hit to performance when running commands like `brew readall` or `brew uses` is that these commands load every formula from every tap installed on the system. In my case, where I only have the {`caskroom/cask`, `homebrew/core`, `homebrew/dev-tools`} taps installed, I have 4384 formulae that have to be loaded. Obviously, as more taps are installed, the total number of formulae will increase and run time will increase.

Using the output of `brew prof readall`, I can see that a lot of time is spent in `Module#module_eval` while brew tries to load all of the formulae from disk. In order to speed that process up, I had the idea that maybe we could pre-compile, store, and load the formulae from disk. I have a diff ([562b2f0](https://github.com/MichaelSquires/brew/commit/562b2f0e25fd45404020fe01348b843c05d57fc0)) as a proof of concept (clearly not ready for a PR).

Pre-compiling the formulae gives about a 40% savings in run time. Performance stats below. The `time` command has give pretty consistent results. (I'm on a mid-2014 MacBook Pro in case anyone is curious).
* Without cache:
```
$ time brew uses node
alexjs                  bower                   grunt-cli               jsdoc3                  webpack
angular-cli             coffeescript            heroku                  jsonlint                write-good
autocode                emscripten              http-server             nativefier              yarn
azure-cli@1             firebase-cli            insect                  pow
babel                   generate-json-schema    ios-sim                 svgo
bit                     gitter-cli              jhipster                typescript

real    0m5.749s
user    0m5.250s
sys     0m0.448s
```

* With cache:
```
$ time HOMEBREW_USE_FORMULA_STORE=1 brew uses node
alexjs                  bower                   grunt-cli               jsdoc3                  webpack
angular-cli             coffeescript            heroku                  jsonlint                write-good
autocode                emscripten              http-server             nativefier              yarn
azure-cli@1             firebase-cli            insect                  pow
babel                   generate-json-schema    ios-sim                 svgo
bit                     gitter-cli              jhipster                typescript

real    0m3.487s
user    0m2.971s
sys     0m0.470s
```

* Cache generation (one time cost):
```
$ time brew cache

real    0m3.653s
user    0m3.199s
sys     0m0.416s
```
* Time difference:
```
>>> 3.487/5.749
0.6065402678726736
```

There have been concerns about cache invalidation. I also have an idea about that but haven't implemented it yet. `Formulary#load_formula` receives the contents of the file being loaded as an argument and the formula store has the SHA-256 digest of the file it compiled. We could compare the digest of the compiled cache with the digest of the on-disk formula and if they are different, either update it then or just load the on-disk version. Perhaps the cache is rebuilt when a tap gets updated. Any other times it should be updated? Thoughts?

I think the point of this whole comment is to ask: What do you think about my approach? Is it worth pursuing further? Are the time savings worth the maintenance complexity of the solution? Any feedback is appreciated.

**Comment by MikeMcQuaid** [comment]
> Pre-compiling the formulae gives about a 40% savings in run time. Performance stats below. The time command has give pretty consistent results. (I'm on a mid-2014 MacBook Pro in case anyone is curious).

That's a pretty decent performance gain, nice work.

> Perhaps the cache is rebuilt when a tap gets updated.

Yep, that seems reasonable. The main issue there is that the Homebrew/homebrew-core cache is going to be invalidated pretty much perpetually for most users. I wonder if there's some way of reducing the amount of times we need to invalidate the cache?

> I think the point of this whole comment is to ask: What do you think about my approach? Is it worth pursuing further? Are the time savings worth the maintenance complexity of the solution?

I think as-is: probably not unless we can figure out a way to not have to invalidate the entire cache when a single formula changes, unfortunately. There may be other approaches I'm missing too, though.

**Comment by scpeters** [comment]
You can see the most recent commit to change a formula with:

~~~
git log -n 1 --format=format:%H formula_name.rb
~~~

Perhaps you could store the most recent checksum that in the cache and update when there has been a new commit? This wouldn't recognize local changes that haven't been committed, so that would have to be considered as well.

For one final point, maybe some changes to the dsl in `homebrew/brew` should invalidate the cache as well?

**Comment by scpeters** [comment]
The `git log` command I proposed can take a long time if formula haven't been updated in a while. There's probably a more efficient way that uses a range of commits. So if you made a branch named `cache` that points to the commit when the cache was last updated, then maybe `git diff --stat cache` would be an easier way to see which files have changed in that time, so you can just reload those files, then move the branch to the HEAD.

**Comment by MichaelSquires** [comment]
Thanks everyone for the feedback, it's been very helpful!

From @scpeters:
> Perhaps you could store the most recent checksum that in the cache and update when there has been a new commit? This wouldn't recognize local changes that haven't been committed, so that would have to be considered as well.

I was originally storing the SHA256 digest of the contents of the formula but that proved to be quite an expensive operation across so many formulae. Your comment did get me thinking about other file metadata though and I went with the modified time of the file. It also addresses your concern about local changes that haven't been committed.

From @MikeMcQuaid: 
> The main issue there is that the Homebrew/homebrew-core cache is going to be invalidated pretty much perpetually for most users.

I've modified my approach to account for formulae being randomly updated. My current solution (see [this WIP PR](https://github.com/MichaelSquires/brew/pull/1/files)) saves the modified time (mtime) of each formula in the store. When loading a formula from the store, the mtime is checked and if they differ, the new formula is used and the store is updated. If a formula is not in the store at all, it will be loaded using the current formula loader method (`method_eval`).

>  I wonder if there's some way of reducing the amount of times we need to invalidate the cache?

I think the right answer here is two-fold: First is to make sure there is a way of checking that the formula on-disk and the store are synchronized. I believe that is solved by storing the modified times of the formulae in the store and updating the store at run-time. Second, we need to proactively update the formula store during operations we know are going to cause it to be out of sync. For example, `brew update` and `brew tap` are the big ones that come to mind.

Terms I've been using in the code:
- cache: Temporary cache, usually In-memory
- store: Permanent or long-term cache, usually on-disk

For clarity, the format of the formula store is an on-disk marshalled hash with the following format:
```
{
  <path to formula1> => {
    "byte_code" => <bytecode of formula stored in binary>,
    "extra_data" => <formula data after the __END__>,
    "mtime" => <integer of modified time>
  },
  ...
  <path to formulaN> => {
    "byte_code" => <bytecode of formula stored in binary>,
    "extra_data" => <formula data after the __END__>,
    "mtime" => <integer of modified time>
  },
}
```

I believe the structure of the store addresses the concern about invalidating the whole thing every time one or more formulae are updated. Please correct me if I'm completely missing the mark here.

Here is an example where formulae have been updated and their mtime has changed. First, get a baseline.
```
$ time brew readall

real    0m3.146s
user    0m2.673s
sys     0m0.432s
```
Then, update the modified times of a bunch of formulae and re-run `brew readall`.
```
$ touch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/[a-f]*.rb
$ time brew readall

real    0m3.700s
user    0m3.076s
sys     0m0.567s
```
The updated formulae were detected and updated during the `brew readall`. Now, run `brew readall` again to show that we're back to (approximately) our baseline.
```
$ time brew readall

real    0m3.226s
user    0m2.735s
sys     0m0.449s
```

Tasks remaining:
- Figure out where the right places are to proactively update the formula store.
  - brew update
  - brew tap
  - brew untap
  - brew doctor: Rebuild cache from scratch
  - Anything else that I'm missing?
- Remove cache command I've been using for development and move to dev-tools?

**Comment by DomT4** [comment]
> I was originally storing the SHA256 digest of the contents of the formula but that proved to be quite an expensive operation across so many formulae.

Potentially fun fact: On 64-bit systems, hashing a large quantity of data is often significantly faster using SHA512 than SHA256.

**Comment by MikeMcQuaid** [comment]
> I believe the structure of the store addresses the concern about invalidating the whole thing every time one or more formulae are updated. Please correct me if I'm completely missing the mark here.

Yep, it does, nice work.

> brew update
> brew tap
> brew untap

I think these are all that would be needed. Nice work!

> I was originally storing the SHA256 digest of the contents of the formula but that proved to be quite an expensive operation across so many formulae.

MD5 or SHA1 could be used in a situation like this where it's being used for a cache key rather than for anything related to security if it's faster. `mtime` seems sufficient to me, though.

**Comment by aiddroid** [comment]
Why always "Updating Homebrew" ?

**Comment by MikeMcQuaid** [comment]
I no longer care about this.
