### ISSUE TITLE
how to install emacs with xwidgets support 

### ISSUE THREAD

**Issue by kirk86** [Homebrew/brew#3078]
Hi, I was wondering if someone could give me some advice on how to install emacs with xwidgets support. 
When I try `brew install emacs --with-xwidgets` I get the following `Warning: emacs: this formula has no --with-xwidgets option so it will be ignored!`

How can I pass the argument `--with-xwidgets` on brew during `./configure` and `compilation` stages. Is that possible?

**Comment by ilovezfs** [comment]
`brew` does not let you pass arbitrary configure options. There would need to be an option for xwidgets in the formula. This is not something we can support because it requires webkitgtk, which was removed from Homebrew in https://github.com/Homebrew/homebrew-core/pull/9053. So you'd need to maintain a personal tap with a tweaked version of the emacs formula and with a resurrected webkitgtk formula.
