### ISSUE TITLE
Incorrect core count in brew config

### ISSUE THREAD

**Issue by NiklasBr** [Homebrew/brew#3473]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Get config info.

- What happened (include command output)

Config shows quad-core (CPU: quad-core 64-bit broadwell) when [system is dual-core](https://support.apple.com/kb/sp715?locale=en_GB). [2 cores, 4 thread](https://ark.intel.com/products/84985/Intel-Core-i5-5257U-Processor-3M-Cache-up-to-3_10-GHz).

- What you expected to happen

Config should show two physical cores. Terminal also reports two cores:

```bash
$ sysctl machdep.cpu.core_count
machdep.cpu.core_count: 2
```

- Step-by-step reproduction instructions (by running `brew` commands)
```bash
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 1.3.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 236b0172306a6f4b233d374fcc20adce5c3e3261
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ca40d6627a6f80bc88204a6d2d6d909d49eccdc4
Core tap last commit: 42 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
HOMEBREW_VISUAL: nano
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 9.1
CLT: 9.1.0.0.1.1508540944
X11: N/A
```

**Comment by MikeMcQuaid** [comment]
What Mac do you own?

**Comment by NiklasBr** [comment]
See the link "system is dual-core" in my original post, more specifically I have the 2.7GHz version.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/blob/ee4172159bc09f23dbcccc2fca471b12d8bc7ecd/Library/Homebrew/extend/os/mac/hardware/cpu.rb#L79

We run `sysctl hw.ncpu` not `sysctl machdep.cpu.core_count`

```
iMac-TMP:~ joe$ sysctl hw.ncpu
hw.ncpu: 8
iMac-TMP:~ joe$ sysctl machdep.cpu.core_count
machdep.cpu.core_count: 4
```

These are not the same thing.

**Comment by NiklasBr** [comment]
Shouldn't you use the physical CPU count?

```
$ sysctl hw.physicalcpu
hw.physicalcpu: 2
```

**Comment by ilovezfs** [comment]
At least in terms of the words, I would think so, yeah.
`system_profiler` says
```
      Processor Name: Intel Core i7
      Total Number of Cores: 4
```
So it is a bit strange for `brew config` to say `CPU: octa-core 64-bit skylake`

**Comment by MikeMcQuaid** [comment]
Will review a pull request to change the approach here but don't consider this a bug as-is.

**Comment by apjanke** [comment]
I looked at a PR on this. But, as usual, there are complications.

When running macOS on bare metal, this is a straightforward switch. But when you consider VMs, it gets more complicated. The "physical" CPUs presented to the guest by the virtualization environment may not correspond directly to what we'd think of as physical CPU cores.

Here's an example. I've got an iMac with an i7-6700K CPU (quad-core, with hyperthreading). (And the problems rear their heads already, since I'm calling that chip a "CPU", while "cpu" means something different in this diagnostic output.) I'm running macOS 10.12.6, VMware Fusion 10, and have a guest running macOS 10.12.2 inside it. The VM is configured to have 4 "processor cores" in the VMware GUI, which I assume are virtual CPUs, since VMware Fusion lets me allocate up to 8 of them and I have a quad-core, hyperthreading processor.

The guest reports:

```
[local] $ sysctl hw.physicalcpu
hw.physicalcpu: 4
[local] $ sysctl machdep.cpu.core_count
machdep.cpu.core_count: 2
```

I believe that the interpretation of this is that `hw.physicalcpu` = "the hardware processor this is running on has 4 cores, regardless of how much is allocated to this VM", and `machdep.cpu.core_count` = "the CPU this VM is running on has 2 physical cores allocated to it". But that, at least the latter, is pretty implementation-dependent: a VM host doesn't need to provide core affinity for guests, so "number of physical cores" isn't necessarily meaningful for a VM guest.

For example, in VMware, I can allocate *3* "processor cores" to this VM guest. Then it reports:

```
[~] $ sysctl hw.ncpu
hw.ncpu: 3
[~] $ sysctl hw.physicalcpu
hw.physicalcpu: 3
[~] $ sysctl machdep.cpu.core_count
machdep.cpu.core_count: 3
```

And that throws off my previous theories about how to interpret these numbers.

Regardless of these ratios, it's an implementation-dependent thing about how VM hosts allocate processor time from guest vCPUs back to hardware cores. A VM guest simply may not have a certain number of physical processors allocated/reserved to it. For example, right now in my VMware Fusion host, I'm currently running four VM guests that have a total of 15 "processor cores" on my quad-core iMac. Whatever allocation strategy Fusion is using, I don't think it's meaningful to talk about these VMs as "having" a certain number of physical cores.

Should also consider Linuxbrew's output for `brew config` here. In my quick testing, the number of cores discoverable by a VMware Fusion Linux guest always matches the number of virtual cores dedicated to it. So if we did switch to a "real physical cores" reporting, the semantics of the output of `brew config` might diverge for Homebrew and Linuxbrew.

Instead, maybe it would be useful for `brew config` to output the exact processor it's running on, to the best of its knowledge, e.g. "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz"?

Maybe it would also be useful for `brew config` to detect and output whether it was running in a virtualized environment?

**Comment by apjanke** [comment]
Or maybe we should just change the `brew config` output to say `-vcore` instead of `-core` to clarify what it's counting?

**Comment by NiklasBr** [comment]
Just a question, what is the primary question the line `CPU: n-core Somename` is trying to answer?

I'm thinking that perhaps the number of threads might be of equal or better value than the number of physical cores for some contexts, and those contexts might be more relevant here.

**Comment by MikeMcQuaid** [comment]
> Just a question, what is the primary question the line CPU: n-core Somename is trying to answer?

"What CPU does the person have"

**Comment by apjanke** [comment]
Here's a PR: https://github.com/Homebrew/brew/pull/3649
