### ISSUE TITLE
Pinned package force upgraded

### ISSUE THREAD

**Issue by koallen** [Homebrew/brew#355]
### Bug reports:

I've pinned `gcc` since I don't want to upgrade it. However, when I upgrade `R`, `gcc` will be force upgraded to the newest `gcc 6.1.0`. Is this a design choice or a bug?

I think it's better to notify the user if package A requires a newer version of package B while package B is pinned. Thoughts?

**Comment by DomT4** [comment]
It's a design choice. `R` has a hard dependency on `gcc` _(For Fortran)_ so it'll be upgraded. We don't support building current formula against known-to-be-outdated dependencies because it's a recipe for chaos & a significant support burden on us, essentially.

If you want to use the old GCC the most reasonable route to get there is to `brew install homebrew/versions/gcc5` for example. GCC is too widely used to be reasonably pinned, really.

> I think it's better to notify the user if package A requires a newer version of package B while package B is pinned. Thoughts?

It'd be easier to discuss a PR rather than an abstract idea on this sort of thing. It's hard to say until mechanisms are discussed. Interactivity after `brew install`/`upgrade`/etc has begun is off the table, but we'd review other ideas.
