### ISSUE TITLE
Feature Request: bump-formula-pr --online

### ISSUE THREAD

**Issue by devonhollowood** [Homebrew/brew#3897]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Feature Request: `bump-formula-pr --online`

## Description of proposed feature
Add an `--online` flag to `brew bump-formula-pr`, which would run `brew audit --online` before submitting the pull request. This would be able to be combined with the `--strict` flag to run `brew audit --strict --online`.

## Motivation
There are some additional checks which are required to merge a PR, which are not run offline. It would be nice to be able to automatically catch these before a PR is submitted. For example, in my first attempt at https://github.com/Homebrew/homebrew-core/pull/24976, I had forgotten to use https in the `url=` parameter. Running `brew audit --strict --online` would have caught this, but because that is not an option with `bump-formula-pr` I had effectively just run `brew audit --strict`, which missed the issue. Jenkins then [rejected the PR](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19883/), but ideally it never would have made it to Jenkins in the first place.

## Relevance 
This is relevant to every user who runs `bump-formula-pr`. Admittedly, this is almost certainly less than 90% of Homebrew users, but I believe it would be very useful to every user who requests a version bump using this `brew` command.

## Alternatives
- Do nothing. These issues are relatively easy to catch, and the cost of fixing them (via an extra commit or a force-pushed re-write) is low.
- Pass `--online` by default when `bump-formula-pr` is run with `--audit` or `--strict`. A user needs to be online to submit a PR anyways, and there are rarely cases where you would want to run `--audit` / `--strict` but not run this check. This has the additional advantage of not requiring any changes to the `brew` interface.

---

I'm happy to work on this and submit a PR if you can point me to some resources to get me started. Looking at [bump-formua-pr.rb](https://github.com/Homebrew/brew/blob/eee6e98d90cdbc7d61b1e3ae6d4508883ca88311/Library/Homebrew/dev-cmd/bump-formula-pr.rb), this seems relatively simple, but I'm not sure if there is any automated infrastructure to update bash / zsh completions, etc.

**Comment by ilovezfs** [comment]
I'm fine with having an option for this but don't think it should be made a default given how slow `--online` audits are. That said, `--online` is a somewhat confusing option name given that `bump-formula-pr` is always an online command, and I don't think there's a problem with the status quo.

Note that https://github.com/Homebrew/homebrew-core/blob/master/.github/PULL_REQUEST_TEMPLATE.md does not recommend `--online` because `brew audit --online` violations are relatively uncommon and not checked on all versions of macOS (so you may think `--online` passed and then get surprised anyway when the violations show up on Jenkins). When they do occur, they may merit no change (e.g. the homepage is temporarily down does not mean we want to change the homepage). So the upside value here is relatively low given that we're already running `--online` on Jenkins but I don't see much downside if it's non-default other than wasting people's time who opt-in.

**Comment by MikeMcQuaid** [comment]
Closing given @ilovezfs's comment. Thanks anyway @devonhollowood!
