### ISSUE TITLE
linkapps and Spotlight issue

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/brew#473]
The brew linkapps no longer work with Spotlight. I just figured out why.

Spotlight only displays apps that are NOT symlinks. So instead of linking the dot app folder, brew should generate something like this, I guess

```
%> cat MacVim.app/Contents/MacOS/MacVim
#!/bin/bash

exec /usr/local/homebrew/bin/gvim "$@"
```

That works great for me.

**Comment by chdiza** [comment]
I don't think `linkapps` *ever* worked with Spotlight.  This issue has been raised numerous times here, e.g:
https://github.com/Homebrew/legacy-homebrew/issues/28798
https://github.com/Homebrew/legacy-homebrew/issues/49033
https://github.com/Homebrew/legacy-homebrew/issues/45429
https://github.com/Homebrew/legacy-homebrew/issues/8970
https://github.com/Homebrew/legacy-homebrew/pull/35050
https://github.com/Homebrew/legacy-homebrew/issues/41238

Each time, as far as I can remember, HB decides not to do anything about it, because the maintainers decide that nothing reasonable can be done about it.

**Comment by metakirby5** [comment]
If you [alias apps](https://github.com/Homebrew/legacy-homebrew/issues/16639#issuecomment-42813448) instead of symlinking, it works.

**Comment by MikeMcQuaid** [comment]
Please read the various issues before this; aliasing has its own issues.
