### ISSUE TITLE
"Updating Homebrew" - repeatedly, every time I want to install something

### ISSUE THREAD

**Issue by LoganDark** [Homebrew/brew#4751]
Every time I want to install something, I have to wait 5 minutes for Homebrew to update.

I don't want to wait for 5 minutes doing nothing.

Is it possible to block these annoying updates?

**Comment by DomT4** [comment]
From `man brew`:

```
HOMEBREW_NO_AUTO_UPDATE
    If set, Homebrew will not auto-update before running brew install, brew upgrade or brew tap.

HOMEBREW_AUTO_UPDATE_SECS
    If set, Homebrew will only check for autoupdates once per this seconds interval.

    Default: 60.
```

Please don't erase the issue template when filing issues in future, thanks.

**Comment by LoganDark** [comment]
"Please don't erase the issue template when filing issues in future, thanks."

Then please explain to me what "replace this section with" means, because apparently by following the instructions I've broken a rule somewhere.

**Comment by vitorgalvao** [comment]
> Then please explain to me what "replace this section" means, because according to you by following the instructions I've broken a rule somewhere.

Since you mentioned “replace this section”, it seems you used the [new feature suggestion template](https://github.com/Homebrew/brew/issues/new?template=New-Feature-Suggestion.md). Said template asks for:

> - a detailed description of your proposed feature
> - the motivation for the feature
> - how the feature would be relevant to at least 90% of Homebrew users (if it's not: do not open a feature request)
> - what alternatives to the feature you have considered

Separating those in clear steps ([like so](https://github.com/Homebrew/brew/issues/3619)) is helpful, though not mandatory. Your original post is missing at least the bottom half of that request — it’s phrased as a question for a personal use case, not as a feature beneficial to most users.

For that reason your post looked like a bug report, not a feature suggestion. [Bug reports also have detailed steps](https://github.com/Homebrew/brew/issues/new?template=Reproducible-Bug-Report.md) that need to be filled.

So when using either of those options, please be sure to include all the requested information. Those templates took a lot of time to build and continue to be improved. Following them is crucial to help us better help you, which is why we ask you follow them.

**Comment by LoganDark** [comment]
I will never understand why templates are required for someone to understand what I mean, but whatever you say.

**Comment by vitorgalvao** [comment]
> I will never understand why templates are required for someone to understand what I mean

Without clear instructions, users tend to not share enough information, leading maintainers on a wasteful back and forth until enough information is provided (which frequently it isn’t, even with said exchanges).

That’s an inefficient expenditure of resources (time and sanity). Seeing as we’re all volunteers and encounter the same problems and requests over and over, we prefer to have the process as streamlined as possible.

For example, by filling the last point (“what alternatives to the feature you have considered”) you might have searched online for “homebrew annoying updates” to see if anyone is using a workaround, and found that the top results refer to auto-updating, thus negating the need for opening a new issue.

Hope that clarified. The templates are there out of necessity, so we can be efficient in improving Homebrew. Asking for a few minutes of a user’s time to fill a template saves maintainers hours of work, from which we all benefit.

**Comment by MikeMcQuaid** [comment]
@LoganDark Enough of the snark; either do what you're asked or don't submit issues here in future. Also, read the documentation before filing issues wasting people's time in future.
