### ISSUE TITLE
Installation brakes when updated

### ISSUE THREAD

**Issue by Henrietta1989** [Homebrew/brew#5117]
I updated "mas" to 1.4.1 and now my script don't work. It's because my script has full path to mas.

>/usr/local/Cellar/mas/1.4.1/bin/mas list

Why i can't just use

>mas list

Then it would work always no matter what version number is.

**Comment by RandomDSdevel** [comment]
@Henrietta1989, CC @MindTooth:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For what it's worth, this may have something to do with an issue known both upstream and in the context of [Homebrew Bundle](https://github.com/Homebrew/homebrew-bundle):  see Homebrew/homebrew-bundle#370 (particularly [this comment on it](https://github.com/Homebrew/homebrew-bundle/issues/370#issuecomment-425727732) and those following it,) as well as mas-cli/mas#164, for details.  As far as I understand it, the issues this problem causes are already handled well enough in Homebrew Bundle for that tool's users as of the merger of Homebrew/homebrew-bundle#374.  In any case, this is not an issue with `brew` itself, but with `mas` as installed by Homebrew from [the Homebrew Core tap](https://github.com/Homebrew/homebrew-core).  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Be that as it may, however, @MindTooth is right to point out that you shouldn't have overlooked the issue template:  it specifically states that issues with specific individual formulas should be filed with their host tap.  Furthermore, since you haven't reported that the `mas` formula's associated package installed incorrectly, I further suspect that this issue, as you've filed it, likely has more to do with your script relying on tool implementation details that upstream has found itself unable to guarantee not breaking; upstream _may_ be able to point out ways you could work around this, but you'll probably have to adapt your script regardless.  I therefore wouldn't be at all surprised if this issue was summarily closed by `brew`'s maintainers as being irrelevant.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Thanks, @GauthamGoli; that could far more likely solve @Henrietta1989's issue.  I've edited my earlier post to reflect this.  (Sorry for initially butting in with something that probably has nothing to do with problems here; lurking as usual, I saw it the other day last week while the linked issues/PRs were still brewing&thinsp;—&thinsp;pardon the pun&thinsp;—&thinsp;and rushed to conclusions by mistake.  I'll step out now…)
