### ISSUE TITLE
Codesign locally built binaries automatically

### ISSUE THREAD

**Issue by mikaeleiman** [Homebrew/brew#5187]
It would be neat if brew could automagically sign any locally built binaries if it can find a signature identity.

Why? Personally I'd like to be rid of the "unsigned binary" warnings in Little Snitch, and considering that Apple is putting more and more effort into getting everything signed I'd say it's likely something that'll be required sooner or later.

Some docs on how it's done: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html

**Comment by colindean** [comment]
How often does this "unsigned binary" warning appear? What triggers it?

How would this feature be relevant and approachable to at least 90% of Homebrew users?

**Comment by MikeMcQuaid** [comment]
We're not going to sign binaries where we haven't written the code ourselves. This would also require every Homebrew user to setup code signing on their machine.



> Personally I'd like to be rid of the "unsigned binary" warnings in Little Snitch

Suggestion: this should be fixed in Little Snitch.

> Apple is putting more and more effort into getting everything signed I'd say it's likely something that'll be required sooner or later.

I've seen no evidence they will ever require signing of command line utilities installed by Homebrew. We have our own contact channels with Apple.

Thanks anyway but closing, sorry!
