### ISSUE TITLE
Don't abort entire brew cask upgrade if one cask fails

### ISSUE THREAD

**Issue by Amorymeltzer** [Homebrew/brew#5203]
Right now, if you run `brew cask upgrade` and one of your casks fails (e.g., the `depends_on macos` stanza), two things happen:
1. You get the correct message (e.g. `Error: Cask cask_name depends on macOS release...`, `Error: Checksum for Cask 'superduper' does not match`, `Error: Download failed on Cask cask_name...`, etc.)
2. `brew cask upgrade` stops

`brew cask` thus won't ever upgrade any casks coming alphabetically after the failing cask.  While most issues should be fixable, if there is a macOS dependency issue, there's nothing to "fix" outside of updating to the latest macOS: a cask depending on `mojave` will obstruct `high_sierra` users, despite homebrew-cask officially supporting the two latest macOS point releases.

One workaround is to manually parse out each cask by piping `brew cask outdated` through `grep -v` and then into `brew cask upgrade`; this should work but is repetitive and obviously not ideal or easily scalable.  Another is to remove the relevant files from the caskroom and stop using `brew-cask` for the application(s) in question; likewise, this isn't ideal.

Expected behavior would be for `installer` to raise the error as appropriate but for `upgrade` to `rescue` and continue with any remaining casks.  This would match what `brew` does after #3644 and I believe is essentially what @ilovezfs suggested should be the default behavior in https://github.com/Homebrew/brew/issues/3634#issuecomment-356304225.

**Comment by reitermarkus** [comment]
No objections from me.

**Comment by MikeMcQuaid** [comment]
@ascheman Please 👍 in future instead, thanks.

**Comment by issmirnov** [comment]
Stale bot, keep this open!

**Comment by tls11** [comment]
keep it open!

**Comment by ascheman** [comment]
keep it open!

**Comment by jonchang** [comment]
If you are interested in adding this feature, feel free to submit it as a pull request and a maintainer will review it. Even a partial implementation is fine since we can help you work through the rest of it. "Upvoting" an issue doesn't help since no maintainer is currently working on this feature.

**Comment by issmirnov** [comment]
I did a bit of digging, but don't have time right now to finish a fix. Adding code pointers to any others who are open to picking this up.

- cask upgrade code: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/cmd/upgrade.rb
- Interception point: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/cmd/upgrade.rb#L94

General thoughts: 

- IMO best option would be to collect various errors rather than immediately throwing them up to the caller. This will allow the cask upgrade to finish, and the notify the user of any problems.
- Caveats to the above are where casks depend on each other and the dependency is broken, since then it would be ideal to intelligently abort the attempted upgrade only for the child casks.

Hope this helps other fellow hackers.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/brew/pull/5983

**Comment by amyspark** [comment]
Wasn't this fixed by #5983 ?

**Comment by MikeMcQuaid** [comment]
Yes, it was. Good spot @amyspark and thanks again @zachauten!
