### ISSUE TITLE
xcode?

### ISSUE THREAD

**Issue by isomorphisms** [Homebrew/brew#5317]
I’m getting problems with the App Store. Wish you supported downloading xcode through brew. Is it a rights thing or too much trouble?

**Comment by jonchang** [comment]
Hi @isomorphisms thanks for the suggestion. Please [fill out the issue template each time](https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE/New-Feature-Suggestion.md), even if you think it's a simple question. I don't think we can support downloading Xcode through Homebrew since Apple only distributes Xcode through the Mac App Store.
