### ISSUE TITLE
On travis-ci pkg-config can't find zlib

### ISSUE THREAD

**Issue by sledgehammer999** [Homebrew/brew#563]
First of all sorry if this isn't the correct place to report this. Also I am not entirely sure that this is a homebrew problem.

I am the maintainer of qBittorrent. We have set up our travis.yml to do OS X builds a long time ago. Up until now everything went ok. But the last few days( or weeks) our configure script complains that it cannot find zlib. So I assume that something changed in newer versions of homebrew.

1. We didn't change our travis.yml before this failure
2. We didn't change our configure script before this failure
3. The configure script uses pkg-config macros to query for packages(and for zlib)
4. We don't install the zlib package from homebrew. We use the system one. On my system the configure script works great in this way. But I can't figure out why it fails on a clean system(aka travis-ci).

Do you guys have any insight on how to solve this?

Here is the latest travis failure: https://travis-ci.org/qbittorrent/qBittorrent/jobs/146165871
Here is our travis.yml: https://github.com/qbittorrent/qBittorrent/blob/master/.travis.yml

**Comment by scpeters** [comment]
This sounds like #539 and https://github.com/Homebrew/homebrew-core/issues/3051

Sorry I don't have a specific suggestion, but you might find clues in those other issues.

**Comment by DomT4** [comment]
See also: https://github.com/travis-ci/travis-ci/issues/6329

We recommend people add something like:
```
brew outdated "pkg-config" || brew upgrade "pkg-config"
```
To their Travis scripts. We're attempting to make Homebrew more cross-platform, which has involved moving some elements around. Sadly Travis doesn't routinely update the dependencies shipped on their boxes automatically, which is problematic in multiple ways for us but I understand the logic behind it.

Apologies on our side that us moving things around can be annoying. The end product will be useful to more people & help various projects (Linuxbrew, Homebrew, Tigerbrew, Caskroom) share the same core (_non-formula_) code rather than maintaining unique forks, but it's not entirely painless getting there.

> We don't install the zlib package from homebrew. We use the system one.

OS X doesn't bother providing a pkg-config file for `zlib` or various other things, despite plenty of projects expecting to find it that way. Consequently, things that use `pkg-config` to find system dependencies on OS X can end up relying on Homebrew's vendored `.pc` files to do so. That will be the case here.

**Comment by MikeMcQuaid** [comment]
Once we hit Homebrew 1.0 (coming soon!) this will hopefully stabilise a bit and we can request some of these images get recreated.

**Comment by sledgehammer999** [comment]
>`brew outdated "pkg-config" || brew upgrade "pkg-config"`

:+1: Yup this works. I hadn't realized that homebrew preinstalls pkg-config and that we need to upgrade it manually.

**Comment by DomT4** [comment]
We don't, but Travis preinstalls a bunch of formulae for user convenience.
