### ISSUE TITLE
when i typed brew update -d ,this error happened

### ISSUE THREAD

**Issue by gyzclw** [Homebrew/brew#5703]
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head http://7xkcej.dl1.z0.glb.clouddn.com/bottles/libtiff-4.0.10_1.mojave.bottle.tar.gz
Error: undefined method `b' for nil:NilClass
Warning: Bottle installation failed: building from source.

**Comment by vitorgalvao** [comment]
@gyzclw You were just [asked in another issue](https://github.com/Homebrew/brew/issues/5698#issuecomment-462165410) to follow the template, because we cannot help you if you do not follow it.

The template itself warns you of the consequences of not following it:

> **Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Please do follow the template the next time you open a issue — and more importantly, do not ignore direct maintainer requests — or you might be blocked.
