### ISSUE TITLE
Consider flipping HOMEBREW_NO_INSTALL_CLEANUP or making it easier to install previous formula versions

### ISSUE THREAD

**Issue by h3adache** [Homebrew/brew#5821]
Since brew 2.0.0 introduced auto cleanups I now have to set

`export HOMEBREW_NO_INSTALL_CLEANUP=1 # prevent brew from auto cleanup so it's easier to swith to previous versions`

But cleanup are all or none. I think it would make more sense to flip this to `HOMEBREW_INSTALL_CLEANUP` if you want to have the cleanup feature.

As an alternative (since it's already version 2.0.2 now) make it easier to install older versions after update/upgrade if needed.

As an example.
`bazel` was just bumped to `0.23.0` and that breaks flags that use to be valid in `0.20.0-0.23.0`

But on upgrade you can no longer switch
```
brew switch bazel 0.22.0
Error: bazel does not have a version "0.22.0" in the Cellar.
bazel installed versions: 0.23.0
```
and installing previous versions doesn't work

```
brew install bazel@0.22.0
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

Error: No available formula with the name "bazel@0.22.0"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

so you are left with 2 alternatives.
Find the formula from github that represented the version you want and apply it from there
Or

```
cd $(brew --repo bazelbuild/tap)
git reset --hard $(git log --grep 0.22 --pretty=format:%h)
brew reinstall bazel
```

Either feels pretty hacky and a longer workaround vs `brew switch`

### How the feature would be relevant to at least 90% of Homebrew users
Honestly, I don't know how to represent 90% of the users. I can only speak on behave of my teams (OSS and work) and this would definitely help.
Especially if installing previous version was easier.

**Comment by jonchang** [comment]
Sorry, we won't be implementing this. We've gotten a ton of feedback over the years about how `brew cleanup` should run automatically in order to save multiple gigabytes of disk space. Back then, most users were completely unaware that they had to run `cleanup` occasionally to clear out old bottles. Changing the behavior to opt-in is a clear step back for most users.

If your team is dependent on old versions of Homebrew bottles they should be willing to do a bit more work to accommodate your uncommon use case. There are two things that might help:

* `brew extract` will extract an old version of a Homebrew formula from git history. You can then host this formula in your own tap.

* The third-party [`brew installv` external command](https://github.com/brewsci/homebrew-base/blob/master/cmd/brew-installv.rb), but Homebrew does not support this and things could break at any given moment.

**Comment by h3adache** [comment]
Great thanks @jonchang! `brew extract` definitely speeds this up!
That should be added to `brew help`

**Comment by jonchang** [comment]
`brew help` is intentionally limited to fit within an 80x24 Terminal window. It's listed in `man brew` though.

**Comment by h3adache** [comment]
I was wrong. brew extract doesn't work always. [this](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/extract.rb#L101) restricts it from being used on `Homebrew/core` formulas

**Comment by jonchang** [comment]
@h3adache see https://github.com/Homebrew/brew/issues/5857 for where this work is being coordinated.
