### ISSUE TITLE
brew cask upgrade failed

### ISSUE THREAD

**Issue by MrMic** [Homebrew/brew#5834]
Hello,

- I try today this command:
$> brew cask upgrade
and got this error:
Error: Cask 'betterzipql' definition is invalid: Token '{:v1=>"betterzipql"}' in header line does not match the file name.

$> brew upgrade 
is still OK.

Any idea to fix that?
Thanks for the reply.
Rgds,

**Comment by vitorgalvao** [comment]
Welcome @MrMic,

When you open an issue, please:

1. Follow the template (as it warns you to).
2. Do not open issues for formulae or casks in this repo (as the template warns you to).

The consequences are clear, and right at the top:

> Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

When you ignore the template, you waste maintainer time and everybody loses. So please read and follow the instructions.

Your problem is that you have a very old setup. Open an issue [in the correct repo](https://github.com/Homebrew/homebrew-cask) **and follow the template**, as it has commands that are likely to fix this without you even having to open the issue.
