### ISSUE TITLE
Issue while trying to install imagick...

### ISSUE THREAD

**Issue by hebertb** [Homebrew/brew#586]
# Please follow the general troubleshooting steps first:

Done - [ ] Ran `brew update` and retried your prior step?
Done - [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
N/A - [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

OS X 10.11.5

brew install brew/php/php56-imagick --without-homebrew-php
==> Tapping brew/php
Cloning into '/usr/local/Library/Taps/brew/homebrew-php'...
Username for 'https://github.com': 

Why is it asking for a login?

**Comment by DomT4** [comment]
Homebrew's tap mechanism is based around `git`, and if you attempt to `git clone` something on GitHub that GitHub can't "see" as public the assumption is made that you're attempting to clone a private repository:
```
~> git clone https://github.com/example/pigeon.git
Cloning into 'pigeon'...
Username for 'https://github.com':
```

That's what you're seeing. Why you're seeing it is because there's a typo in your command, you actually want:
```
brew install homebrew/php/php56-imagick --without-homebrew-php
```
