### ISSUE TITLE
HOMEBREW_TEMP does not allow ~ on path

### ISSUE THREAD

**Issue by kakawait** [Homebrew/brew#593]
### Bug reports:

```
$ HOMEBREW_TEMP="~/.homebrew/tmp/" brew reinstall git
==> Reinstalling git
Error: No such file or directory - ~/.homebrew/tmp/homebrew20160727-24280-m1bvf6
```

Whereas using fully qualified path

```
$ HOMEBREW_TEMP=/Volumes/diskE/Users/kakawait/.homebrew brew reinstall git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.9.2.tar.xz
Already downloaded: /Volumes/diskE/Users/kakawait/Library/Caches/Homebrew/git-2.9.2.tar.xz
==> make install prefix=/Volumes/diskE/Users/kakawait/.homebrew/Cellar/git/2.9.2 sysconfdir=/Volumes/diskE/Users/kakawait/.homebrew/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
==> make CC=clang CFLAGS= LDFLAGS=
==> make clean
==> make CC=clang CFLAGS= LDFLAGS=
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.9.2.tar.xz
...
```

Even following is working

```
$ HOMEBREW_TEMP="$HOME/.homebrew/tmp/" brew reinstall git
```

**Comment by UniqMartin** [comment]
> ```console
> $ HOMEBREW_TEMP="~/.homebrew/tmp/" brew reinstall git
> ```

Unlike the other variants, this cannot work because there's no chance for the shell to expand the `~` to your home directory. (And Homebrew like many other command line tools, doesn't do it for you and thus assumes you meant a literal `~`.) You simply have to omit the quotation marks (because there are no special characters in your path) and it will work:

```console
$ HOMEBREW_TEMP=~/.homebrew/tmp brew reinstall git
```

(Note that in general the trailing slash doesn't cause any issues, but it should usually be omitted.)

---

Here's a demonstration how the quoting makes a difference:

```console
$ echo "~/.homebrew/tmp"
~/.homebrew/tmp
$ echo ~/.homebrew/tmp
/Users/martin/.homebrew/tmp
$ echo ~/".homebrew/tmp"
/Users/martin/.homebrew/tmp
```

**Comment by scpeters** [comment]
I generally use `$HOME` instead of `~` in scripts since I'm never sure how the quoting will work.

**Comment by UniqMartin** [comment]
> I generally use `$HOME` instead of `~` in scripts since I'm never sure how the quoting will work.

I tend to use `~/"whatever"` or `~/whatever` if it's obvious that there's nothing that needs to be escaped. Using `$HOME` is equally fine. I don't think any of those variants is clearly  superior when compared to the alternatives.
