### ISSUE TITLE
Stop doctor from complaining about Node

### ISSUE THREAD

**Issue by corysimmons** [Homebrew/brew#6017]
I installed Node from the Node website or https://npm.im/n or something... This is fine. But when I run `$ brew doctor` I always get 10k lines of `Warning: Unbrewed header files`

Please add a flag like `$ brew doctor --shhh-node` :(

**Comment by jonchang** [comment]
Always fill out the issue template.

```console
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```

**Comment by chdiza** [comment]
It's hard to use the doctor if, as alleged, it spews thousands of lines of pointless warnings.

**Comment by iMichka** [comment]
If you have no issue, you should not be using `brew doctor`. Just don't run that command. You do not need it.

If you have an issue, run it, and give us the output. Even if it is thousands of lines. We will decide what is pointless or not.

If you want to play around with the command (because you are a maintainer, or are just curious): feel free to do so, but there is not need to report the issues here.
