### ISSUE TITLE
assert_no_match: support substrings

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#602]
```
Error: luyten: failed
The first argument to assert_no_match should be a Regexp..
Expected "Exception" to be an instance of Regexp, not String.
```
I found that error somewhat surprising given the rule that we should always use a string, not a regex, for the first argument to assert_match if the match is for a mere substring. Presumably the same rule should apply to substring non-matches as well.

**Comment by UniqMartin** [comment]
There's an easy solution for that: Use `refute_match` instead! The counterparts to the `assert_*` methods from `MiniTest::Assertions` are all named `refute_*` (if a negation makes sense) and that's what we tend to use. (The `assert_no_match` method is from `Test::Unit::Assertions` instead.)

**Comment by ilovezfs** [comment]
@UniqMartin thanks.

>that's what we tend to use.

I don't see that used in core at all. Only assert_no_match, with all but one of them just substrings.

**Comment by ilovezfs** [comment]
@UniqMartin Yep, refute_match worked beautifully http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5542/version=el_capitan/console proving that indeed the preexisting luyten test was totally bogus since it didn't redirect stderr to stdout :)

**Comment by UniqMartin** [comment]
> I don't see that used in core at all.

I think my view is a bit skewed by looking at our test suite in this repository (something I see more frequently than test code in formulae, if I'm being honest). There you see a pretty clear dominance of the `\brefute_` style assertions vs. the `\bassert_non?_` style assertions.

Thinking a bit more about it, and given what I see in [`formula_assertions.rb`](https://github.com/Homebrew/brew/blob/3469f177f043b163e0c362b0fa10f9f99c31114b/Library/Homebrew/formula_assertions.rb), my suggestion might be not as useful as I thought. In formula tests, we only seem to use `MiniTest` if it is available and I'm not sure for what versions of Ruby it is guaranteed to be there. Otherwise we fall back to `Unit::Test` only (in which case we cannot use the `refute_*` family of assertions). I guess it's a bit hard to correctly code against a common subset, if what gets exposed is usually more. 😕

**Comment by UniqMartin** [comment]
I'm sorry for the hasty and possibly bad advice …

**Comment by ilovezfs** [comment]
Yup, you're right. Mavericks CI:
```
undefined method `refute_match' for #<Formulary::FormulaNamespacea21d6e504776a132376876c79d2d610f::Luyten:0x104e5cd88>
```
What a shame.
