### ISSUE TITLE
Delegate `brew update package` to `brew upgrade package`

### ISSUE THREAD

**Issue by StefMa** [Homebrew/brew#6125]
# A detailed description of the proposed feature
I do **always** the same misstake by ~updating~ upgrating packages and type:
```
$ brew update scrcpy
```
the currently response is then:
> Error: This command updates brew itself, and does not take formula names.
> Use 'brew upgrade scrcpy' instead.

Is it possible to "delegate" this issue to the correct command? 
So that this leads to something

> brew upgrade updates brew itself. We are using `update` for update $packagename for you

Another solution would be - instead of "just doing it" - *ask* the user to doing a `upgrade` instead.

> [Same message as above] but addionally:
> Do you want to upgrade $packagename?
> Press [Y/N]:

# The motivation for the feature
I'm so lazy and what that this is a better "UX" experience :)

# How the feature would be relevant to at least 90% of Homebrew users
I'm not sure if 90%. But I think most of the users who uses `update` instead of `upgrade` - so yes :)

**Comment by MikeMcQuaid** [comment]
That means we'd need to handle all `upgrade` options as part of `update` which isn't a route we want to go down.

**Comment by AvnerCohen** [comment]
I wonder how common this issue is...
I always, always make this mistake.
My suggestion is a bit different:

Set `upgrade` as an alias to  `update`.
and than, map `update` to, either one of the following:
`brew self-update`
`brew renew`
`brew rejuvenate`
etc..

Can also add a migration path if hitting `brew update` with no args, point to the above selected option.
