### ISSUE TITLE
Cask uninstall fallback/suggestions

### ISSUE THREAD

**Issue by teddy-error** [Homebrew/brew#6260]
# A detailed description of the proposed feature

When attempting to uninstall a cask with incorrect syntax a generic error message is displayed:

```shell
$ brew uninstall discord
Error: No such keg: /usr/local/Cellar/discord
```

A more useful error message might be to suggest the correct syntax:

```shell
$ brew uninstall discord
Found a cask named "discord" instead. Try `brew cask uninstall discord`
```

This would be just like the error-handling behavior exhibited when incorrectly installing a cask:

```shell
$ brew install discord
Error: No available formula with the name "discord-canary"
Found a cask named "discord-canary" instead.
```

# The motivation for the feature

I was removing a brew-installed application that stopped working and I was stumped for much longer than I would have imagined when seeing the error message above. Although I was well-aware of the need to specify `cask` when installing, I don't remember ever needing to use it when uninstalling.

I thought, because the app had totally broken, that some permissions issues might be preventing uninstall. And so I tried with the `--force` flag, which has does not fail and so has no output whatsoever. Then I was even more confused for a bit.

# How the feature would be relevant to at least 90% of Homebrew users

Any user that forgets `cask` syntax should be provided some hint towards using `brew` with success.

# What alternatives to the feature have been considered

As there should be no namespace conflicts, it might even be more beneficial to users to simply fallback to removing the cask installed application, rather than forcing the syntax change.

**Comment by teddy-error** [comment]
Updated

**Comment by MikeMcQuaid** [comment]
@zachauten Thoughts on this?

**Comment by zachauten** [comment]
Yeah, I think this seems like a good idea. Are there any other commands besides `info` and `install` that could benefit from a "suggestion"?

I think the quick way would be to catch the `NoSuchKegError` thrown by `ARGV.kegs`, check if a cask with the same name is installed, and if it is then suggest `brew cask uninstall`. 

It would be nice if we could reuse some of the code from `cask_reason` in `MissingFormula` since this is such a similar issue to #6245. But I think that would take a decent amount of refactoring to be reusable for this.

I can work on this some tomorrow!

**Comment by MikeMcQuaid** [comment]
> Are there any other commands besides `info` and `install` that could benefit from a "suggestion"?

I'm not sure; maybe `upgrade`?

> I think the quick way would be to catch the `NoSuchKegError` thrown by `ARGV.kegs`, check if a cask with the same name is installed, and if it is then suggest `brew cask uninstall`.
> 
> It would be nice if we could reuse some of the code from `cask_reason` in `MissingFormula` since this is such a similar issue to #6245. But I think that would take a decent amount of refactoring to be reusable for this.

Yeh, I think reusing this would be nice. Maybe it could be another module that `MissingFormula` can call instead? Then again, `brew uninstall` could also just use the `MissingFormula` logic?

**Comment by zachauten** [comment]
> Then again, brew uninstall could also just use the MissingFormula logic?

Aren't most of the reasons in `MissingFormula` irrelevant to an uninstall (deleted, blacklisted, tap migration)? The only one we care about in this situation is `cask_reason`, but the way `cask_reason` checks if something is a cask would also need to be different, because `uninstall` would only need to look through installed casks.

This does seem like something that conceptually belongs in `MissingFormula` though; `brew uninstall` is looking for a formula (keg) in order to do something with it, and can't find it.

**Comment by MikeMcQuaid** [comment]
> Aren't most of the reasons in `MissingFormula` irrelevant to an uninstall (deleted, blacklisted, tap migration)?
> because `uninstall` would only need to look through installed casks, rather than all casks like `cask_reason` currently does for `install` or `info`.

Great points.

> This does seem like something that conceptually belongs in `MissingFormula` though; `brew uninstall` is looking for a formula (keg) in order to do something with it, and can't find it.

Yeh, could just be another method in there called directly with some shared logic.

**Comment by zachauten** [comment]
Based on #5730, `ARGV.rb` is legacy, and we should favor using `parser.rb` right? Asking because `uninstall.rb` uses `ARGV.rb` in a few places and I'd like to clean that up while I'm working in the file if that would be appropriate.

If this is the case, where should the `ARGV.kegs()` logic be moved? `keg.rb`?

**Comment by MikeMcQuaid** [comment]
Sounds good!

> If this is the case, where should the `ARGV.kegs()` logic be moved? `keg.rb`?

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cli/args.rb
