### ISSUE TITLE
Does brew permanently change "stty echo" in a shell?

### ISSUE THREAD

**Issue by sje30** [Homebrew/brew#651]
I often run brew within an Emacs shell generated by M-x shell.

I've noticed the following problem.  In a fresh shell, the terminal does not echo, as it is done by Emacs.  After running a brew command, all commands are then duplicated:

```
$ pwd
/Users/stephen

$ stty
speed 9600 baud;
lflags: -echo echoe echoke echoctl
oflags: -onlcr -oxtabs
cflags: cs8 -parenb
erase   kill    
<undef> <undef> 

$ brew install pandoc
Warning: pandoc-1.17.1 already installed

$ stty
stty
speed 9600 baud;
lflags: echoe echoke echoctl
oflags: -oxtabs
cflags: cs8 -parenb
```

Note that after running brew, "-echo" has disappeared from the stty command, and so commands now echo.  As well as seeing two copies of shell commands, it now means that other Emacs commands (such as M-x dirs) no longer work.

The work around for me is to do `stty -echo` when I notice it.

THis also happens in regular mac termninals, e.g. if I `stty -echo` I can no longer see what I type.  However after (blindly) typing a brew command, the "echo" flag is back on and I can see my typing.

**Comment by sje30** [comment]
p.s. current config:

```
brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: cc0ca73183f1e92579169eb038b10a98bd7c455a
Last commit: 7 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e7fd17b4b8fa3ff467e33d39bd0358b1af647d45
Core tap last commit: 7 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Clang: 7.3 build 703
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/stephen/.rbenv/shims/ruby => /Users/stephen/.rbenv/versions/2.3.0/bin/ruby
Java: 1.7.0_45
System Ruby: 2.0.0-p648
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: N/A
X11: 2.7.9 => /opt/X11
```

**Comment by apjanke** [comment]
This sounds kind of like #560, but "in the other direction".

I don't think `brew` intentionally changes the terminal settings. But it pulls in code, particularly IRB support, which may do so in certain circumstances. If it's turning off `-echo`, or otherwise leaving your terminal settings changed after a `brew` run, that's probably a bug.

Do you have an `~/.editrc` file, and if so, what does it contain?

Does it happen with all `brew` commands? For example, do `brew ls` and `brew tap` also cause double echoing?

**Comment by sje30** [comment]
> This sounds kind of like #560, but "in the other direction".

yes, it sounds similar, thanks.


> I don't think `brew` intentionally changes the terminal settings. But
> it pulls in code, particularly IRB support, which may do so in certain
> circumstances. If it's turning off `-echo`, or otherwise leaving your
> terminal settings changed after a `brew` run, that's probably a bug.

thanks for checking.  that's why I seem  to see happen.

> Do you have an `~/.editrc` file, and if so, what does it contain?

No.

> Does it happen with all `brew` commands? For example, do `brew ls` and
> `brew tap` also cause double echoing?

No.  e.g. when `brew ls` is run, -echo is preserved.

Is it likely to be caused by the bit of code that shows progress bars
when files are downloaded?

Stephen

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by medington** [comment]
I'm running into this as well. In my case I have `stty discard undef` in my dotfiles because I want to use Control+O (^O) in my .inputrc for history search backwards.

This seems to be lost _only_ happen with a `brew install`, uninstalls and searches don't seem to be a problem.

@apjanke wrote:
>I don't think brew intentionally changes the terminal settings. But it pulls in code, particularly IRB support, which may do so in certain circumstances. If it's turning off -echo, or otherwise leaving your terminal settings changed after a brew run, that's probably a bug.

Presuming the bug here isn't in Homebrew but in some library it uses perhaps I might try to submit a bug to the appropriate project where the bug actually exists. Any pointers on how to narrow it down?

*FYI, steps to reproduce this are:*
```
stty discard undef
stty
# confirm setting override present in output
brew install <something>
stty
# confirm setting override is lost

```

Thanks,
--Mark

**Comment by MikeMcQuaid** [comment]
> I'm running into this as well.

Everyone will run into this. As mentioned above: we'll accept PRs to fix this. I'd suggest searching through Homebrew's codebase for uses of `stty`.

**Comment by sje30** [comment]
my hunch was that it was the "progress bar" code that was interfering
with stty settings...

**Comment by MikeMcQuaid** [comment]
> That's pretty conclusive evidence to me that it's brew readline's bug.

If you can provide a reproducible test-case then please create a new issue in Homebrew/homebrew-core and we'll may have a look at the readline issue. As mentioned above: no Homebrew maintainers are working on this right now but we'd consider accepting PRs that resolve it.
