### ISSUE TITLE
How to change multiple usernames on a single machines for homebrew?

### ISSUE THREAD

**Issue by shyamalschandra** [Homebrew/brew#652]
I executed the following command...

> Shyamals-iMac-174:click shyamalchandra$ brew install homebrew/science/opencv
> ==> Tapping homebrew/science
> fatal: could not create work tree dir '/usr/local/Library/Taps/homebrew/homebrew-science': Permission denied
> Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-science /usr/local/Library/Taps/homebrew/homebrew-science --depth=1

and each time, I have to do a sudo chown -R $USER /usr/local on my mac before I can get the permissions to do a brew <operation> from command line.

Find a solution to this problem so that multiple users can be handled by the brew rather than I making a group and adding users to it and then making the /usr/local write permissions accessible by the group of users.

Someone come up with a solution.

**Comment by apjanke** [comment]
Using a group is the usual way of handling permissions for multiple users, especially a set that may change over time, instead of granting per-user permissions to multiple individual users. It tends to make system administration easier.

Could you use `sudo chmod -R +a ...` to use ACL-based permissions to grant write access to an additional group, or the individual user accounts you want to have access?

**Comment by Yann-R** [comment]
Yes.
Even if, most of the time, the admin is also the user and the user is single-user ;-)
It's true that macOS (unix-based) is intrinsically for multiples users.
And since among the motivations of brew there is:
- directly make the additional software available for all users in a standard directory (that's why `/usr/local` is targeted)
- avoid switching to root account to install additional software

Then: why not make brew configure and prepare this privileged unix-group for authorized users to write and install in the brew repository?

**Comment by MikeMcQuaid** [comment]
@Yann-R I'm not really sure what you're asking but Homebrew allows you to set group permissions and will respect them, it just doesn't set them by default.

**Comment by perlun** [comment]
> @Yann-R I'm not really sure what you're asking but Homebrew allows you to set group permissions and will respect them, it just doesn't set them by default.

Is there an easy HOWTO for how to do this? The fact that Homebrew by default puts files in `/usr/local/Cellar` owned by _me_, my personal account, is something that bothers me quite a bit actually (since I also use multiple user accounts on my Mac, and sometimes installed packages as one user, sometimes the other.)

I'd much rather have a more `apt-get`-like experience: packages can be owned by `root` or some other system account, I have to `sudo brew install` everytime I install a package. To me, that's completely worth it, but I realize others may have different opinions.

_And_ it probably goes completely against the way that Homebrew has been designed etc. 😉

**Comment by MikeMcQuaid** [comment]
> And it probably goes completely against the way that Homebrew has been designed etc.

It does, yes.

**Comment by MikeMcQuaid** [comment]
The best bet for this would be for someone to submit a PR to our [docs folder](https://github.com/Homebrew/brew/tree/master/docs) with a new Markdown document describing how to set this up.
