### ISSUE TITLE
Homebrew GitHub API Access Should Not Use Password Authentication

### ISSUE THREAD

**Issue by ryanfb** [Homebrew/brew#6862]
# A detailed description of the proposed feature

Homebrew's `api_credentials` function will currently attempt to use password-based authentication from the OS X keychain for GitHub API access in some cases: https://github.com/Homebrew/brew/blob/2e382cdbdf266d716c7369255f3bf57eadbf60f3/Library/Homebrew/utils/github.rb#L82

On November 5th, 2019, GitHub announced they would be deprecating password-based authentication for all API access: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/

As a result, Homebrew should no longer use password-based authentication when accessing the GitHub API.

# The motivation for the feature

Users may not even realize Homebrew is falling back to password-based authentication, resulting in notification emails from GitHub like this one: https://twitter.com/telemachus/status/1207674513871298561

# How the feature would be relevant to at least 90% of Homebrew users

If Homebrew users don't realize it's automatically attempting to use a deprecated GitHub API access method, they won't know why they're getting notified about this deprecation or why GitHub API access eventually stops working, possibly causing issues with regular Homebrew operations.

# What alternatives to the feature have been considered

Since Homebrew already supports using an API token, this largely seems like an issue for removing the password-based authentication fallback from Homebrew and providing better documentation to help transition users who may have been unknowingly using password-based authentication.

**Comment by MikeMcQuaid** [comment]
I agree that we should deprecate using password-based authentication. The problem is that the `api_credentials_from_keychain` results are not a password for anyone using 2FA and I'd like to keep the fallback for that case. 

Is there an easy way/any way to detect that we're using password-based authentication in this case? If not, I'm tempted to leave this as-is until this support is removed and then handle the error message.

**Comment by nuclearpidgeon** [comment]
I got one of the aforementioned Github notification emails out of the blue the other day - I figured it was worth posting a screencap here seeing as the original tweet linked in the issue has now been deleted:

<img width="647" alt="[GitHub] Deprecation Notice email" src="https://user-images.githubusercontent.com/891761/72063687-5cffc680-332e-11ea-853c-3026e660d6bd.png">

Also FWIW, it doesn't seem like there's currently really any _direct_ documentation on how users can migrate away from this issue. As @ryanfb speculated - I had no idea my credentials were even being used for the `brew search` functionality. Googling the problem led me to [this gist](https://gist.github.com/willgarcia/7347306870779bfa664e) on adding an API key, which did the trick, but nothing in the gist directly indicates it's the 'solution' to the 'problem' of getting this email (the main point of it is for mitigating the Github API rate limit). The only official brew things I could seem to find were this issue and the [environment variable docs](https://docs.brew.sh/Manpage#environment) on `HOMEBREW_GITHUB_API_TOKEN`, which again, is a bit roundabout because it's not completely clear that it's the right thing to set to stop this old password fallback(?) from being used.

Hopefully this is useful for anyone else who got the same email and is looking to mitigate this as well.

**Comment by ryanccn** [comment]
I get this problem too!
<img width="1029" alt="screenshot-brew-dark" src="https://user-images.githubusercontent.com/47623453/72071873-b9abb300-3327-11ea-8f74-0c158476306e.png">
Thanks @nuclearpidgeon

**Comment by MikeMcQuaid** [comment]
> I got one of the aforementioned Github notification emails out of the blue the other day
> I get this problem too!

Yes, that's why it's an open issue. Please hold off adding "me too" comments to this.


---


Quoting myself again from above:

> I agree that we should deprecate using password-based authentication. The problem is that the `api_credentials_from_keychain` results are not a password for anyone using 2FA and I'd like to keep the fallback for that case.
> 
> Is there an easy way/any way to detect that we're using password-based authentication in this case? If not, I'm tempted to leave this as-is until this support is removed and then handle the error message.

There needs to be work/help from people affected (i.e. the people motivated to have this be addressed of which I am not one as I use 2FA and a personal access token) to get this resolved.

**Comment by ryanfb** [comment]
As a signpost for others, I have 2FA on my account (and use an environment-set personal access token as a result), and was personally unaware that if you're using 2FA you can also use a personal access token as your HTTPS password which will be stored/returned in the OS X keychain: https://github.blog/2013-09-03-two-factor-authentication/#how-does-it-work-for-command-line-git (I was originally confused by the statement that `api_credentials_from_keychain` would return anything useful for users with 2FA)

**Comment by ryanfb** [comment]
It looks like all GitHub personal access tokens are 40-character hexadecimal strings, so maybe one potential solution would be to only use the results of `api_credentials_from_keychain` if they match those criteria, and fail with an informative error/warning message otherwise. Of course it's possible that there will be some very minute number of people whose non-2FA passwords will match those exact criteria, but I think it might be an acceptable workaround.

**Comment by MikeMcQuaid** [comment]
> It looks like all GitHub personal access tokens are 40-character hexadecimal strings, so maybe one potential solution would be to only use the results of `api_credentials_from_keychain` if they match those criteria, and fail with an informative error/warning message otherwise.

That is a good idea and acceptable workaround to me 👍
