### ISSUE TITLE
Simplify update/upgrade procedures

### ISSUE THREAD

**Issue by mthld** [Homebrew/brew#6950]
Hello !

## A detailed description of the proposed feature
It would be very cool to simplify the update/upgrade procedure, actually there is 3 different commands needed to be run periodically:
```
$ brew update
$ brew upgrade
$ brew cask upgrade
```

## The motivation for the feature
It would be simpler for users, to not have to use 3 different commands for the purpose of keeping stuff installed up-to-date.

## How the feature would be relevant to at least 90% of Homebrew users
Everyone would profit from simpler process I guess... 🤷🏻‍♀️

## What alternatives to the feature have been considered
I checked running some of these as CRON jobs but it's not really practical because of reading the scripts output.

Thanks in advance.

**Comment by MikeMcQuaid** [comment]
> $ brew update
> $ brew upgrade

`brew upgrade` already runs `brew update`.

> It would be simpler for users, to not have to use 3 different commands for the purpose of keeping stuff installed up-to-date.

We could consider having a `brew upgrade --casks --formulae`. Would that work for you?

**Comment by mthld** [comment]
Hi Mike,

Many thanks for your answer and the solution proposed. That would be lovely!

**Comment by MikeMcQuaid** [comment]
Passing on this for now @mthld as no other commands take `--formulae` (and only one, `brew search`, takes `--casks`) but this is something we could consider in future for more commands to support casks or formulae. CC @homebrew/cask for thoughts.

**Comment by vitorgalvao** [comment]
It’s already confusing that some commands require `cask` and others don’t but may take a `--cask` flag instead (`search`). Both `--formulae` and `--cask` flags are unintuitive and we should have neither. I think we should pick a direction and plunge further into it: either have `brew` and `brew cask` commands well defined, or have as little `brew cask` commands as possible.

For the former, it would mean readding `brew cask search`, even if it just calls whatever `brew search --casks` does now. The one exception would be `update`, because that deals with *taps*, not formulae and casks. To solve the request in this issue, I’d have no problem with an `all` subcommand that just does both `brew` and `brew cask` commands in succession. Example: `brew all upgrade` would run `brew upgrade && brew cask upgrade` behind the scenes.

For the latter, it would mean that commands like `brew upgrade && brew cask upgrade` would be a single `brew upgrade`. Ambiguous options, like `brew install` would need a rethink for when there are conflicts between a formulae and a cask (for which there’s no good solution). This doesn’t seem viable for now.

### Or, simplest solution that can be done now

Make `brew upgrade`, when given without arguments, upgrade both formulae and casks. You’re already calling it without arguments, so you either don’t care what gets upgraded or already reviewed what will be. Either way, you’ve signaled you want everything.

**Comment by MikeMcQuaid** [comment]
> Example: `brew all upgrade` would run `brew upgrade && brew cask upgrade` behind the scenes.

I like the idea of this but I think I'd prefer this to be something like `brew upgrade --also-casks` (or a better flag name).



> Either way, you’ve signaled you want everything.

I think for a Homebrew 3.0 where we warn people a bunch in advance this is going to happen: I agree. Until then: I'm not so sure. People assume `brew foo` means `foo on my formulae`. I'm not sure this matters if it's a something like `search` or `update` (or potentially `info`) where you aren't changing any state but I think `install` or `upgrade` and particularly `uninstall` should be the last to change (if they ever do) and I'd favour a flag rather than a subcommand if we do that (partly for technical reasons).

**Comment by vitorgalvao** [comment]
I agree `install` and `uninstall` should be the last (if ever) to change.

> I like the idea of this but I think I'd prefer this to be something like `brew upgrade --also-casks` (or a better flag name).

But again, I don’t think flags are the solution for as long as `brew cask` (i.e. the subcommand) is a thing. Flags that refer to subcommands—especially if they only exist for either formulae or casks—are confusing and hard to discover. Telling people to make an `alias` seems better.

I even think `brew cask search` should be reinstated, but [that’s another issue](https://github.com/Homebrew/brew/issues/6975).

**Comment by MikeMcQuaid** [comment]
> But again, I don’t think flags are the solution for as long as `brew cask` (i.e. the subcommand) is a thing.

I think flags should be effectively a migration path from `brew cask` commands.

**Comment by vitorgalvao** [comment]
> I think flags should be effectively a migration path from `brew cask` commands.

I’ve thought about that idea a few times over the course of this issue, and while it seems good to me at first, the fact that casks and formulae are different things (in how they’re built—and that by their nature require different rules), always stops me in my tracks and makes me pause. I *feel* like there’s somewhere that could become problematic but I haven’t been able to figure out what. I’ll let it marinate.

**Comment by MikeMcQuaid** [comment]
My take: you care about their differences when you're installing (because they have different permissions to install different stuff into different places) but generally not when you're searching/querying/etc.

**Comment by mthld** [comment]
Maybe it'll be good to reopen this issue? There seems to be some discussion about all this.

**Comment by MikeMcQuaid** [comment]
@mthld Discussion can continue on the closed issue. I don't think we have anything directly actionable as-is.
