### ISSUE TITLE
Highlight the BOINC cask on the Brew homepage

### ISSUE THREAD

**Issue by mcandre** [Homebrew/brew#7209]
# A detailed description of the proposed feature

Use the BOINC cask as the example package on the home page.

# The motivation for the feature

Synthesizing a COVID-19 vaccine.

# How the feature would be relevant to at least 90% of Homebrew users

We live in a society.

# What alternatives to the feature have been considered

Buying up toilet paper.

**Comment by iMichka** [comment]
Hi.

We could do that. but why Boinc, and not another tool to do open source research? There are many out there. We could rotate the packages too, to give more visibility to some of them. But I am not sure we want to advertise any package particularly. @vitorgalvao and others from homebred-cask might have an opinion on this.

Of course we are supportive to any effort to help with the fight against Covid 19. A lot of homebrew maintainers are currently stuck at home.

There are some other initiatives worth mentioning here:
https://discourse.covid-oss-help.org
https://github.blog/2020-03-23-open-collaboration-on-covid-19/

In my opinion we have been doing enough for the software world since years, and not only regarding Covid 19: this is the hot topic right now, but when it is gone, the next crisis will come (or is already here, like climate change).

Thank you for the idea though.

If any maintainer thinks I am wrong and we should make that change, please tell me so, as this is a sensible matter and I wrote this answer all by myself. Also, we do not want to bikeshed too much here, because the discussion might be endless.

**Comment by MikeMcQuaid** [comment]
> If any maintainer thinks I am wrong

I think you are right.
