### ISSUE TITLE
Update exiftool from 11.85 to 11.93

### ISSUE THREAD

**Issue by stuff-and-nonsense** [Homebrew/brew#7272]
I'd update:

`https://github.com/Homebrew/homebrew-core/blob/master/Formula/exiftool.rb`

but I cannot understand how it is possible to have different sha256 results on different versions of macos.

Thanks.

**Comment by zachauten** [comment]
Closing this issue because it's not really relevant to this repo (the homebrew cli tool). 

But to answer your question the sha256's will be different because the binaries produced by building on different versions are different. But you don't need to worry about that if you want to make updates to a formula because the sha256's in the `bottle` block are placed there by the CI, you don't need to modify them.

**Comment by stuff-and-nonsense** [comment]
Thanks -- helpful.
