### ISSUE TITLE
system_command add an unnecessary backslash to > character

### ISSUE THREAD

**Issue by ErickYataco** [Homebrew/brew#7523]
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was working on a custom cask formula where I just want to create a config file to jdk but the file never it’s created or any error it’s showed

`preflight do
    system_command '/bin/echo',
      args: ["WEB_JAVA=Disable\nAUTO_UPDATE=Disable", ">", "/etc/java/config/jre-install.properties"], sudo: true
end`

## What happened (include command output)

system_commnand add an unnecessary backslash to > character

`/usr/bin/sudo -E -- /bin/echo -e WEB_JAVA=DisableAUTO_UPDATE=Disable \> /Library/Java/JavaVirtualMachines/jre-install.properties`

**Comment by vitorgalvao** [comment]
It is working as intended. If you tried doing the same with `system` or `Open3` you’d get the same result.

The problem is that you’re treating `system_command` as if it simply concatenated the arguments and ran them through a shell, but that’s not the case. In a shell `>` is used to redirect the output somewhere (which is your goal), but `system_command` is taking your `>` and (by design) interpreting it as part of the arguments, thus escaping it.

What you need is proper redirection. I haven’t checked on `system_command`, but on `system` you’d achieve it like `system(<code here>, out: <path to write stdout>, err: <path to write stderr>)`
