### ISSUE TITLE
Provide a way to run more audit checks for a non-core tap

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/brew#7739]
# A detailed description of the proposed feature
Adding a flag to `brew audit` or updating a flag such as `--online` or `--strict` to provide a way of running more of the audit checks on a non-core tap. 

# The motivation for the feature
Prior to submitting a PR to the core tap, a contributor may want to audit their formula locally to detect and resolve errors. As it stands right now, if a user is developing in a fork of the core tap, the `brew audit --online` check doesn't include checks such as the GitHub prerelease check: https://github.com/Homebrew/brew/blob/7ad7834b15ff5ac2ec3e1fa34ca81ae8d61de093/Library/Homebrew/dev-cmd/audit.rb#L652 A case where this happened recently is https://github.com/Homebrew/homebrew-core/pull/56059 .

# How the feature would be relevant to at least 90% of Homebrew users
The feature would save time of contributors/maintainers as well as reduce strain on CI in cases where contributors elect to run these more substantial tests locally.

# What alternatives to the feature have been considered
Waiting to allow CI to catch the error followed by contributors being notified of the failure and pushing a new version.

**Comment by issyl0** [comment]
> Prior to submitting a PR to the core tap, a contributor may want to audit their formula locally to detect and resolve errors.

I'm not sure of your use case for having a custom tap for testing revision bumps to core formulae. 

If you run macOS (or Linux) locally and have Homebrew installed, you can run all the audits by making your changes in the local copy of the core tap - `cd $(brew --repo homebrew/core)`, `brew edit $formula`, followed by `brew audit ...`, then adding your fork as a remote to push to. Rather than having a separate local checkout of just your fork.

If that doesn't solve this issue, I'm interested in hearing more about your setup! 🤔

**Comment by dtrodrigues** [comment]
That worked better than I thought it would. I have `homebrew/core` in the default location - `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` -  but have my fork checked out separately in my home directory, and do any local testing there, with the core tap repository set as an upstream remote. Adding my own repository as a remote for the default-installed homebrew worked out well and also lessens the the duplication on my local machine.

There still may be some value in having a way to force all/more audit checks to run when not in the core repository, but probably not enough to merit a change to the existing behavior.
