### ISSUE TITLE
Suppress automatic command invocations from analytics reporting

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/brew#788]
Running `brew update` creates analytics views for `update` and `update-report`; `brew upgrade` creates analytics views for `update` and `upgrade`. It would be good to suppress analytics reporting for automatic command invocations or to at least flag them to give us a better sense of how people are using `brew`.

**Comment by MikeMcQuaid** [comment]
@tdsmith Is this something you're personally planning on implementing in the short-to-medium term? If not, can you stick it in https://github.com/homebrew/brew-evolution? Generally I think it would be good if maintainers can create PRs rather than issues...

**Comment by tdsmith** [comment]
No plans. I'm not invested enough to draft a proposal but the current behavior seems weird to me.

**Comment by tdsmith** [comment]
Can you provide some feedback about whether this was a design decision, whether this facilitated implementation, and why you chose to close this issue? I'd like to collaborate to improve the analytics data but the evolution process is too heavy and I haven't invested enough time to understand the implementation.

**Comment by MikeMcQuaid** [comment]
> Can you provide some feedback about whether this was a design decision

This was not a design decision. It seems like it would be a sensible change but it's very down my personal list of priorities. 

> whether this facilitated implementation

This issue does not facilitate implementation. It does not suggest any specifics and it does not use the process that we've created to discuss feature requests.

> I'd like to collaborate to improve the analytics data

Collaboration is best achieved through pull requests.

> I haven't invested enough time to understand the implementation

I would suggest that it's worth doing this before opening issues.

--

As I've mentioned before: I think maintainers opening "personal preference" issues they don't plan to work on is a project smell. If you're the person who cares about this: you should be the person to work on it and unless that's happening in the short-term the best bet is to create a pull request when you are ready to work on it. Otherwise our open issue count keeps growing and growing and it becomes hard to keep track of what are actual outstanding problems that need addressed and what are just maintainer "nice-to-haves" that will not be worked on.
