### ISSUE TITLE
Brew install may make Mac cannot shutdown

### ISSUE THREAD

**Issue by yiheng233** [Homebrew/brew#7912]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ yes] ran `brew update` and can still reproduce the problem?
- [ yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ no] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install google-earth-pro loopback keka virtualbox

## What happened (include command output)

First brew let me type the root password 
When I shutdown my Mac ,it came into black screen then reboot by itself.

<details>
  <summary>Command output</summary>
  <pre>

  To install google-earth-pro type the password 

  </pre>
</details>

## What you expected to happen

Install this app without problems

## Step-by-step reproduction instructions (by running `brew` commands)

Brew cask install google-earth-pro loopback magicprefs google-chrome 

## Output of `brew config` and `brew doctor` commands

<pre>
Your system is ready to brew
</pre>

**Comment by vitorgalvao** [comment]
Hello @yiheng233,

All of those are casks, so the report should be over at [Homebrew/cask](https://github.com/Homebrew/homebrew-cask). Note we have a different template.

That said, all we do is run the software’s installation procedure as if you’d done it manually. If there’s a problem with one of the softwares, you’ll have to figure out which one (my bet is on Virtualbox) and try to install it manually. Only if you cannot reproduce it manually but can reproduce it via `brew cask install` will we take a look, because otherwise it’s an upstream issue and needs to be taken up with them.
