### ISSUE TITLE
brew terraform@0.13 when is it coming

### ISSUE THREAD

**Issue by gauravachatrath** [Homebrew/brew#8095]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

# A detailed description of the proposed feature

May i know when is brew terraform@0.13 coming ?

# The motivation for the feature

There are lot of features in terraform we can use specially foreach loop for module 

# How the feature would be relevant to at least 90% of Homebrew users

We can use new upgrade new terraform with new changes

# What alternatives to the feature have been considered

To manually replace the terraform file

**Comment by claui** [comment]
Homebrew includes only stable versions so the best place for you to know the general availability (GA) date for 0.13 would be the Terraform project itself.

Turns out the maintainers even have a tracking issue at https://github.com/hashicorp/terraform/issues/25016. Currently it says August 10 but the date may be postponed at their discretion.
