### ISSUE TITLE
Add livecheck support to bump-formula-pr

### ISSUE THREAD

**Issue by josh** [Homebrew/brew#8563]
# Feature suggestion

The idea is that if you omitted a url or version flag, we'd use livecheck to automatically pick the latest version.

```
$ brew bump-formula-pr git --version 2.28.0

# omit --version and we'll use livecheck to find the latest version
$ brew bump-formula-pr git
```

# A detailed description of the proposed feature

Instead of error when the `args.version` flag is `nil`, we'd run livecheck on the formula and use that value.

# The motivation for the feature

Personally, I think it's pretty handy for updating my own Taps. Ideally I want to use this with GitHub Actions to automatically update formulas. That part would be for my personal Taps, not for homebrew core formulas.

# How the feature would be relevant to at least 90% of Homebrew users

The feature would primarily be useful to contributors using `bump-formula-pr`.

# What alternatives to the feature have been considered

One could compose the two shell commands like so:

```sh
VERSION=$(brew livecheck git --json | jq --raw-output '.[0].version.latest')
brew bump-formula-pr git --version "$VERSION"
```

--- 

I can volunteer to implement the feature. I just wanted to make sure it fits the core teams vision of livecheck and bump-formula-pr. Thanks for your consideration!

Also thanks to the core team for all their hard work on the Big Sur changes this summer! 💖 

CC: @MikeMcQuaid @samford @nandahkrishna

**Comment by dawidd6** [comment]
In the meantime you can check out a GitHub Action that works exactly how you describe what you want to do in your tap:
https://github.com/dawidd6/action-homebrew-bump-formula#livecheck-mode

**Comment by samford** [comment]
At this point, livecheck is still a work in progress and the version results it returns are imperfect in a number of cases. We've done a lot of work to improve livecheck's strategies and the checks in formulae but we still have a ways to go.

Of the working checks that we have, there's a subset that give an incorrect version as newest. However, we don't know which formulae these are unless we check upstream ourselves and review livecheck's output. Some of these issues are relatively easy to spot (i.e., "_that's_ a weird looking version...") but we usually only identify the others when someone comes along and points it out. I can say with certainty that we have formulae that meet this criteria right now, at least.

For example, it may be that a formula is at version 1.2.3 and livecheck gives us 1.3.0 as newest but this turns out to actually be a prerelease version. To the user, this looks totally fine and if they simply feed this information to `brew bump-formula-pr`, then we can end up with a bad PR. Adding this feature to `brew bump-formula-pr` may simply lower the bar to creating bad PRs and end up making more noise for maintainers to have to deal with.

I've seen this happen a number of times in homebrew-core, where someone was using `brew bump-formula-pr` and not making sure the version is something we should be using in the formula. It's also unfortunately common for maintainers to not check upstream to make sure that the version is stable before merging a version bump PR. I've warned about this a number of times but it's a continual issue, even when several maintainers review a PR.

On the surface, this seems beneficial and you're not alone in wanting this type of feature. We definitely have some maintainers who use livecheck as a way of identifying formulae that can be potentially version bumped.

However, I've spent so much time working on livecheck at this point that I'm all too familiar with its shortcomings and I have a conservative view of its current progress. I think the fact that a good number of checks work fine may give users a false sense that livecheck is a more reliable source of truth than it actually is.

The end goal is for livecheck to be a good source of information for tools like this (though it'll never be perfect) but I personally don't feel that it's quite there yet. I feel that it would be better to give it another few months and it will be in better shape. I'm loosely aiming to have livecheck "done" by the end of the year (i.e., checks for 99% of the formulae, all the existing checks known to be good (until they're not), etc.).

That said, others may have a different view on this. There _are_ a good number of checks that are reliable right now and would probably be fine for this sort of tool. If I'm in the minority here, I imagine that this could be restricted to known-good formulae (as we've previously discussed when talking about other automatic version-bumping solutions in the past) and that may allow us to reap the benefits while avoiding most of the detriments. I'm wary of this being implemented right now but, who knows, a cautious approach may be suitable.

I'll be interested to hear others' take on this, as I think this warrants discussion before proceeding.

**Comment by josh** [comment]
> The end goal is for livecheck to be a good source of information for tools like this (though it will never be perfect) but I personally don't feel that it's quite there yet. I feel that it would be better to give it another few months and it should be in better shape then. I'm loosely aiming to have livecheck "done" by the end of the year (i.e., checks for 99% of the formulae, all the existing checks known to be good (until they're not), etc.).

That make sense! I was excited to see it move into core, but we can let it settle and circle back to this idea later. Thanks!

**Comment by maxim-belkin** [comment]
I like this idea 👍 and I think this is where livecheck should be heading in general
I also agree with @samford about "bad" PRs and limiting formulae that can be updated this way to a "known-good formulae" might be a good approach in the beginning (at least for homebrew/core).

@samford, to enable this, we would need a function (or add a new mode of operation for 'latest_version') that _returns_ new URL that `bump-formula-pr` could then use.

**Comment by samford** [comment]
> I like this idea 👍 and I think this is where livecheck should be heading in general

That's the direction we're headed but I think the important distinction is that this is primarily about the _data_ livecheck produces. There are a variety of uses for livecheck's data but livecheck itself should remain relatively agnostic of how its data is used in other tools.

That said, there's been no shortage of ideas about how we can use livecheck's data to reduce the burden on maintainers/contributors. This has been my goal from when I first started working on livecheck and it's where I see the most value.

The blocker right now is getting livecheck to a point where its data is more complete/reliable and we still have a ways to go there. Once I take care of the most pressing items on my to-do list, I'm planning to return to working on adding/improving `livecheck` blocks again.

---

> to enable this, we would need a function (or add a new mode of operation for 'latest_version') that _returns_ new URL that `bump-formula-pr` could then use.

This remains on my to-do list but it's not as straightforward as it seems. I discussed some of the challenges previously in an MLH PR but I'll reiterate in brief here:

1. Only a subset of the existing checks identify versions from an archive URL. Due to external factors, the other checks identify the version from some content where the archive URL (as found in the formula) isn't present. We can only return the upstream URL of a new archive (without guessing) in the former case.
2. Being able to return the upstream URL of an archive would require us to modify all the regexes that match a version in an archive file URL. Currently, regexes use a capture group to identify the version part of the regex and the rest of the regex often includes more than just the URL, as the context is necessary to match only what we want. For example, a common regex pattern is `/href=.*?v?(\d+(?:\.\d+)+)\.t/i`, so this would need to be modified to only include the URL part of the regex in the match (e.g., making the leading part a lookbehind) and to extend the trailing part to match the full URL (e.g., `\.t[^"' >]+?`). Livecheck would also need to be modified internally to handle this data and include it in the JSON output but that's a given. Updating the existing checks is the more challenging part.
3. With the checks that aren't matching an archive URL, we can attempt to generate the URL of the archive ourselves by taking the existing stable URL and substituting the current version with the latest version. We would want to make sure this URL is valid (e.g., doing a `HEAD` request and following redirects until we get a 200) before using it, of course. This isn't a foolproof approach but it may work in some cases. However, this sort of URL substitution to guess archive URLs is something that should happen in a tool _outside_ of livecheck (`brew bump-formula-pr` or something else). Livecheck is concerned with concrete data it identifies from upstream sources and shouldn't introduce "guessed" data like this.

There may be more than this that I'm forgetting but these are the salient points I remember off the top of my head. [There are some other ideas floating around in my head related to this but they're not worth talking about until I've done more research to assess feasibility.]

**Comment by MikeMcQuaid** [comment]
I don't think livecheck should do this but the new `brew bump` command seems like the perfect candidate for this. It already checks repology.org, Livecheck and if there's already open PRs for this. Something like `brew bump wget --open-pull-request` (or similar) would be a good extension/addition to do this.
