### ISSUE TITLE
Consistent output for pinned casks in the upgrade command

### ISSUE THREAD

**Issue by jrslv** [Homebrew/brew#8796]
#### Description of issue

In the presence of pinned casks, the output of `brew upgrade` shows something like:
```
λ ~ > brew upgrade
Error: Not upgrading 1 pinned package:
awscli 2.0.50
==> Would upgrade 109 outdated packages:
rubberband 1.8.2_1 -> 1.9.0
git-quick-stats 2.0.12 -> 2.1.4
...
```

For the sake of consistency, I believe the "Not upgrading 1 pinned package" message should be prefixed with "==> " instead of "Error".

**Comment by MikeMcQuaid** [comment]
It is considered an error because it returns an error exit code.

Please always fill out the issue template.

**Comment by maxim-belkin** [comment]
> It is considered an error because it returns an error exit code.

The user didn't specify a pinned package explicitly, so it's neither a user's mistake nor a real Homebrew error when we can't continue. I think this should be either `ohai` (==>) or `opoo` (Warning) instead of `ofail` (Error) because this is solely to inform the user about why Homebrew is not going to update the package.

**Comment by MikeMcQuaid** [comment]
It didn't used to be an error and people complained about the error exit code. It didn't used to have an error exit code and people complained that it didn't upgrade everything they expected. I think the current behaviour the best considering.
