### ISSUE TITLE
Force link openssl error?

### ISSUE THREAD

**Issue by Bebeau** [Homebrew/brew#891]
I'm trying to update openssl and I got this error in the terminal that says to report this bug..

Error: /usr/local/cellar/openssl/1.0.2h_1/bin/openssl:1: invalid multibyte char (UTF-8)

Please report this bug:
https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:83:in `klass'
/usr/local/Library/Homebrew/formulary.rb:79:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:216:in `factory'
/usr/local/Library/Homebrew/formulary.rb:261:in `to_rack'
/usr/local/Library/Homebrew/extend/ARGV.rb:56:in `block in kegs'
/usr/local/Library/Homebrew/extend/ARGV.rb:55:in `collect'
/usr/local/Library/Homebrew/extend/ARGV.rb:55:in `kegs'
/usr/local/Library/Homebrew/cmd/link.rb:26:in `link'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'

I ran the command:
brew link --force /usr/local/Cellar/openssl/1.0.2h_1/bin/openssl

**Comment by zmwangx** [comment]
To force link openssl (or any other formula), you should have run

```
$ brew link --force openssl
```

instead of

```
$ brew link --force /usr/local/Cellar/openssl/1.0.2h_1/bin/openssl
```

Your command was asking brew to parse the openssl binary as a formula source file.

However, since https://github.com/Homebrew/brew/pull/612 you shouldn't be able to force link openssl:

```
$ brew link --force openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

It was done for a reason and you should probably respect that.

Please let us know if there's anything else we can help with.

**Comment by samkelleher** [comment]
I understand that openssl is being prevented from linking by a deliberate decision, which is great. But I've ended up here because I've hit a wall actually running the latest openssl on a Mac because I can't link it.  All the blog posts and stack overflow for the last several years littered on google all just suggest `brew link openssl` which as of #612 no longer works as expected.

The 'solutions' shared since seem to just indicate creating the link manually, ie doing what brew refuses to do.

Is there an 'official' way to install openssl via brew as I can't locate one. The error message indicates passing arguments to a compiler, but I'm not trying to compile anything - just run an openssl command from the terminal. 😨

**Comment by zmwangx** [comment]
@samkelleher 

```
$ /usr/local/opt/openssl/bin/openssl version
OpenSSL 1.0.2j  26 Sep 2016
$ /usr/local/opt/openssl@1.1/bin/openssl version
OpenSSL 1.1.0c  10 Nov 2016
```

**Comment by dunn** [comment]
@samkelleher you can run the `openssl` binary directly from its unlinked location:
```
$(brew --prefix)/opt/openssl/bin/openssl
```

**Comment by samkelleher** [comment]
Thanks both @dunn and @zmwangx  for the quick responses 👏🏻, just solved half an hour of terminal bashing with your answers! I've made an alias and now openssl running my desired version.  🎉

**Comment by lucy-itjob** [comment]
I have similar issue, please help   
+++++
contegixs-MacBook-Pro:Cellar lucy$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
contegixs-MacBook-Pro:Cellar lucy$ which openssl
/usr/bin/openssl
contegixs-MacBook-Pro:Cellar lucy$ brew link --force /usr/bin/openssl
Error: openssl: /usr/bin/openssl:1: invalid multibyte char (UTF-8)
++++++
 Please advise , thank you for the help in advance

**Comment by zmwangx** [comment]
@lucy-itjob 

1. The syntax of `brew-link` is `brew link --force openssl`.
2. Force linking `openssl` is intentionally prohibited. You should NOT attempt that. Instead, use the full path `/usr/local/opt/openssl/bin/openssl`.

**Comment by lucy-itjob** [comment]
Thanks, issue resolved
