### ISSUE TITLE
TSC Discussion: Type Checking in Homebrew

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/brew#8991]
Extracting TSC discussion from https://github.com/Homebrew/brew/pull/8956

---

I'll start with a summary of events to provide background (feel free to contradict these if you disagree):

- @mistydemeo proposed a GSoC project for summer 2020 to be mentored by her and @issyl0 to add type data using Sorbet to Homebrew. The PR (https://github.com/Homebrew/gsoc/pull/20) was ✅ by @MikeMcQuaid. This was discussed at the Homebrew AGM but the TSC was not all present or their opinion solicited.
- @vidusheeamoli worked this summer on adding type-checking and various commands/CI. This was initially feature flagged but then added to CI to be run by default to ensure the external RBI (type information files) were kept in sync. @vidusheeamoli was made a maintainer as a result of this work.
- @reitermarkus has been continuing this work by adding type-checking to the rest of the Homebrew codebase
  - @MikeMcQuaid and @reitermarkus disagreed on the approach in https://github.com/Homebrew/brew/pull/8781 but eventually came to a compromise and @MikeMcQuaid ✅ the PR.
  - @mikemcquaid was under the impression that RBI files were still being used to keep type information separate
  - @mikemcquaid and @reitermarkus are unable to agree in the path forward in https://github.com/Homebrew/brew/pull/8956
  - An unnamed TSC member had a PR failing due to unadded type information and was unable to figure out from CI output how to resolve their issue so asked in Slack
  - @Homebrew/tsc was solicited for input in Slack but said they are unable to make a decision due to lack of context (hopefully some of which is provided in this issue)

---

My understanding of the decisions for the @homebrew/tsc to discuss (I'll leave my opinions as a comment afterwards):

- Should Homebrew aim to add type information for all Homebrew/brew Ruby files?
- Should Homebrew aim to enable type checking at `brew` runtime?
- Should Homebrew/brew use separate RBI files for storing type information or should these be stored inline?
- Should missing types on new files cause a CI failure which requires them to be added? 

@Homebrew/tsc (and, if desired, @Homebrew/plc, @Homebrew/maintainers and particularly @mistydemeo @vidusheeamoli @issyl0): please leave any comments on this issue or, if you wish to be more anonymous, in a 1:1 message to a @Homebrew/plc or @Homebrew/tsc member in Slack where they can anonymise and paraphrase it here.

**Comment by MikeMcQuaid** [comment]
> * Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

I do not think so. I think adding some type information to some files (e.g. utility classes, perhaps `formula.rb`) would be beneficial but adding typing everywhere will slow down Homebrew development, increase new contributor friction and effectively move Homebrew from being written in "Ruby" to "a Sorbet type-checked version of Ruby".

I do not see any evidence that this will improve overall quality of Homebrew to an end-user.

> * Should Homebrew aim to enable type checking at `brew` runtime?

No, never. This will slow down Homebrew boot and present confusing errors to users with no benefit.

> * Should Homebrew/brew use separate RBI files for storing type information or should these be stored inline?

We should use separate RBI files to ensure that the Ruby code looks like Ruby and the type information (effectively a different language) can live elsewhere and be treated differently.

> * Should missing types on new files cause a CI failure which requires them to be added?

No, I do not think we should require these to be added to new files but we should fail if they are broken or removed from existing files/functions/methods.

**Comment by MikeMcQuaid** [comment]
(locking to restrict this conversation to Homebrew maintainers)

**Comment by claui** [comment]
> Should Homebrew/brew use separate RBI files for storing type information or should these be stored inline?

Pro inlined type information:
- It doubles (in part) as method-level API documentation.
- It’s less prone to get out of sync with the truth. Inlined type info is hard to miss when I change a method signature or delete a method.

Pro out-of-line type information:
- It doesn’t add more cognitive load to code files than we already have.
- Contributors who don’t know Sorbet are free to ignore it.
- It’s easier to get rid of when we realize we’ve made a mistake or when Ruby 3 comes out.

**Comment by claui** [comment]
> Should missing types on new files cause a CI failure which requires them to be added?

They shouldn’t. I don’t think such a CI failure would be actionable for every maintainer.

When I search for Sorbet on the web, I find nothing but dessert recipes.

**Comment by reitermarkus** [comment]
> I do not see any evidence that this will improve overall quality of Homebrew to an end-user.

For what it's worth, so far I have noticed a couple (granted, subtle) bugs which were uncovered by type checking.


> Pro out-of-line type information:
> - Contributors who don’t know Sorbet are free to ignore it.

Unless the contributor changes a type-checked signature leading to a type error, in which case having the signatures in a separate file will be more confusing.

**Comment by jonchang** [comment]
As a maintainer:

If we're going to go down the route of adding type checking in Homebrew, we might as well start inlining the type annotations now so that maintainers and contributors can get used to it.

I've encountered and fixed a few type errors already, and I haven't found it especially difficult: Sorbet tells you there's a type error, you look for the definition in Homebrew/brew, and if you don't know how to fix it, slap some `T::Any` paint over it and see if anyone can help out in Slack. This is as someone who has almost no experience in strongly typed languages.

I haven't seen any additional slowness from runtime type checking (and would like to see actual measurements either way).

More generally, my only complaint so far is that many of these new, large features have not adequately documented; for example, I don't think the [type checking doc](https://docs.brew.sh/Typechecking) has been updated with the details of how to enable runtime type checking (and how it differs from e.g. `brew typecheck`).

As a PLC member:

"Should we have type checking in Homebrew" is exactly the kind of question the TSC has been charged with answering:

> The TSC will also decide the long-term roadmap of Homebrew, including large features or major changes to the Homebrew software.

Maintainers should be more comfortable with calling the TSC to see if a pull request or proposed feature aligns with the direction of the Homebrew. The TSC should be proactive about figuring out what the direction of the project should be in the first place.

It's not within my remit as a PLC member to determine how the TSC goes about this, but one possible path is to write up proposals like I've done in https://github.com/Homebrew/brew/issues/8093 https://github.com/Homebrew/brew/issues/7805 https://github.com/Homebrew/brew/issues/7804.

**Comment by fxcoudert** [comment]
> if you don't know how to fix it, slap some T::Any paint over it and see if anyone can help out in Slack

I did not know any Ruby before I started working with Homebrew, and I still mostly don't know any, really, apart from the very basic subset of the language we're using in formulas (and in some parts of brew itself). I think it's great that the current state of our codebase allows people like me not to have to learn Ruby, really (or Ruby + Sorbet).

Yes you can always find help, get it on slack, ask other maintainers, but it takes time and effort, and it makes the learning/contribution curve steeper. I don't know where the right balance is, but this is an important point to consider.

(For example, _“slap some T::Any paint over it”_ is something I would have no idea how to do in Ruby currently, despite decades working with both strongly typed and untyped languages)

**Comment by claui** [comment]
> (For example, “slap some T::Any paint over it” is something I would have no idea how to do in Ruby currently, despite decades working with both strongly typed and untyped languages)

Thank you @fxcoudert for mentioning that.
I’ve been writing code in strongly typed languages for 25 years, and I wonder how I was supposed to find `T.any` unless I already know it existed.

**Comment by MikeMcQuaid** [comment]
> * It’s less prone to get out of sync with the truth. Inlined type info is hard to miss when I change a method signature or delete a method.

If CI verifies they are sync, that seems like a potential middle ground.

> * It’s easier to get rid of when we realize we’ve made a mistake or when Ruby 3 comes out.

This is a valid thought. As-is it sounds like Ruby 3 will be fine with the path we've taken. Will that be the case indefinitely? I'm not so sure.

> More generally, my only complaint so far is that many of these new, large features have not adequately documented; for example, I don't think the [type checking doc](https://docs.brew.sh/Typechecking) has been updated with the details of how to enable runtime type checking (and how it differs from e.g. `brew typecheck`).

Agreed.


> (For example, _“slap some T::Any paint over it”_ is something I would have no idea how to do in Ruby currently, despite decades working with both strongly typed and untyped languages)

Also agreed (and I've reviewed most Sorbet PRs, too).

**Comment by iMichka** [comment]
> This was discussed at the Homebrew AGM but the TSC was not all present or their opinion solicited.

That's fine for me: if there is a project which I disagree with, I would have voiced my opinion as TSC member. So as long I don't say anything, that's an implicit yes.

> An unnamed TSC member had a PR failing due to unadded type information and was unable to figure out from CI output how to resolve their issue so asked in Slack

That was probably me: I got surprised by the type check error on CI. This happened because I was adding new files, and they did not have the "# typed: false" line. I did not know what was expected from me, but we wera able to solve it quite quickly. It's not that a big deal.

Now to the questions.

FYI as a Python developer, I sort of followed the same path with Python as the one we are following with Ruby. And I am totally in favor to add type checking for production code or for code bases as big as brew.

> Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

Yes

I found so many subtle bugs in my Python code doing the exercise of adding types everywhere. And sometimes it will force you to write cleaner code too.

> Should Homebrew aim to enable type checking at brew runtime?

I guess not. I did even not know that it could be done. Maybe if it's just a flag to switch and we can run some brew code on CI to test it, why not. But if it brings performance issues, surely not.

> Should Homebrew/brew use separate RBI files for storing type information or should these be stored inline?

I prefer stored inline. This is what I did for my Python code, and I am quite happy about it:
- We do not need to keep files in sync
- Having it inline brings readeability: I am often lost with brew's code, because I have no clue about the type of the variables.

> Should missing types on new files cause a CI failure which requires them to be added?

Here, I am a little bit unsure about my anwser. Of course it makes it harder for beginners. But how many beginners are going to make huge changes to brew?
We have been really good at making contributing to homebrew-core easy, but I think this is not so true for brew. The brew code is just hard to read for me.
I think adding types might actually make it easier to read for some people.

Of course it raises the bar at the beginning as you need to add the types; I had a look at #8956 and the syntax looks quite nice. Once you have a few example you can just copy-paste it and work your way through from there.

I guess we can add types step by step at the beginning, until we have typed everything. Then we flip the switch and ask people to type their code.
If we do not do that, this means delegating the type writing to the other maintainers, which is not that fun ...

**Comment by issyl0** [comment]
> [The GSoC project proposal] was discussed at the Homebrew AGM but the TSC was not all present or their opinion solicited.

I was surprised to learn this - I had assumed that the necessary due diligence would have been done before GSoC to confirm that this was definitely a direction that Homebrew as a project wanted to go.

Of course, there was no guarantee that anyone would sign up or get accepted to work on it for GSoC, so the project idea could potentially have been pushed back until next year when Ruby 3 would be around and the Ruby community uptake would have been higher. Luckily we got @vidusheeamoli who's done some awesome work battling through all the discovery of what Sorbet is, how nascent it turned out to be in the Ruby community, and just how complicated Homebrew's codebase is! 🥇

Hence, we are where we are now, and we must try to move forward cohesively to make the effort over the summer worth it and to make developing Homebrew even better for all.

----

Now to the questions in the original post:

> Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

Yes. Though as we learnt in GSoC, that's not easy without a good understanding of Sorbet and, in some cases, refactoring - and fixing bugs in Sorbet itself. Props to @reitermarkus here for all the work he's been doing recently to get the `brew typecheck` errors down to zero for the currently typechecked files (post-GSoC).

> Should Homebrew aim to enable type checking at brew runtime?

I like `brew typecheck` being a separate command for now. But I'm aware of how many "for now"s are in my head and that's not necessarily progressive! If we're worried about performance, some comparative numbers for/against would be good to see.

> Should Homebrew/brew use separate RBI files for storing type information or should these be stored inline?

In-line type definitions make sense for adjustment purposes - seeing type information (in whatever form it takes in later Ruby 3 or Sorbet) is only going to (slowly, over time, admittedly) become more common and I think that, in time, with application, it will be an improvement for Homebrew's codebase. However, I do see the disadvantages that Mike has mentioned a few times: barrier to entry for new contributors. For example, type declarations and comments such as [this](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/PATH.rb#L15-L23) are somewhat impenetrable for the uninitiated.

> Should missing types on new files cause a CI failure which requires them to be added?

Failing to keep track of when new files were added to Homebrew/brew was a problem we saw in the GSoC times - keeping `sorbet/files.yaml` up-to-date with added/removed files took a lot of tedious work. It's better now that the `# typed:` sigils are in the files themselves. For consistency, so we know that Sorbet has knowledge of every new file, we should aim to keep this CI check, I think. Setting files to `false` initially is fine, but we need that `false` baseline so that future improvements are consistent. We can (and should) certainly improve the docs to better indicate to contributors what the problem is with CI. Also as far as I remember `brew style --fix` should add `typed: false`.

----

Now to the comments further on:

> More generally, my only complaint so far is that many of these new, large features have not adequately documented; for example, I don't think the type checking doc has been updated with the details of how to enable runtime type checking (and how it differs from e.g. `brew typecheck`).

Yeah, @fxcoudert, that's a thing we should fixup depending on the outcome of this discussion - times have changed since that document was written!

> But how many beginners are going to make huge changes to brew?

@iMichka Fixing up an allowlist, maybe, or adding a single new feature, but big, sweeping changes where typechecking really comes into its own: probably not.

> I guess we can add types step by step at the beginning, until we have typed everything. Then we flip the switch and ask people to type their code.

Yeah, @iMichka, I'd prefer that too. But will we ever have "typed everything" in an ever-growing codebase? I'm not sure that - like 100% test coverage - is at all an achievable or realistic goal. But we can do "best efforts" for the popular things, I suppose.

----

Thanks for raising this, @MikeMcQuaid. As I said at the end of GSoC, this is a _large_ project that's going to need a concerted effort from more than ~3 people. So, this conversation is great to have started, because we need a cohesive, agreed plan for how to do it.

**Comment by MikeMcQuaid** [comment]
> That was probably me: I got surprised by the type check error on CI. This happened because I was adding new files, and they did not have the "# typed: false" line. I did not know what was expected from me, but we wera able to solve it quite quickly. It's not that a big deal.

@iMichka If you were a new contributor to Homebrew without access to Slack: would the issue template have solved your problem? Would the documentation? If not: I consider that a big deal.

> I found so many subtle bugs in my Python code doing the exercise of adding types everywhere. And sometimes it will force you to write cleaner code too.

"Subtle bugs" or "bugs that affect end-users"? Bugs that are not visible to end-users are not worth dedicating time to fix until you have a 0️⃣ backlog (which Homebrew does not).

> Maybe if it's just a flag to switch and we can run some brew code on CI to test it, why not. But if it brings performance issues, surely not.

Yeh, we're running it at CI time. It will bring runtime performance issues.

> Here, I am a little bit unsure about my anwser. Of course it makes it harder for beginners. But how many beginners are going to make huge changes to brew?

We have people who add new features as their first contribution to Homebrew/brew. Making types mandatory means anyone adding any new files or functions needs to understand and use types for their contributions to be accepted. As the person doing more review of these types of PRs than anyone else: it also means I need to fully learn how to use Sorbet and how to teach first time contributors how to use it. If this is the case, I think it's a bit unfair unless the TSC and others doing Sorbet work are volunteering to spend more time helping new users learn Sorbet and improve documentation.

> We have been really good at making contributing to homebrew-core easy, but I think this is not so true for brew. The brew code is just hard to read for me.

I don't think this is a good reason to make it harder to contribute. If anything I'd be interested in how we can make it easier.

> If we do not do that, this means delegating the type writing to the other maintainers, which is not that fun ...

This is a good argument. I agree for new files/features _if_ we decide the eventual goal is 100% type checking it's not fair to have new code excluded from this indefinitely.

---

> when Ruby 3 would be around and the Ruby community uptake would have been higher.

@issyl0 This is a good point to make: the Ruby community are not widely using types yet. I don't think they ever will, personally. We're taking a relatively niche tool and some of us are pushing for complete adoption far ahead of the Ruby community. Has this come from detailed evaluation of user needs and this being the best way of solving them or just that it seems cool/interesting/fun? 

> As I said at the end of GSoC, this is a _large_ project that's going to need a concerted effort from more than ~3 people.

This is a good point. My issue is: if no-one other than those 3 people (or at least: not everyone) wants to do this: what then?

I appreciate we have a TSC process and that such things are voted but: if I (the person with the [most commits, code changes and longest activity to Homebrew/brew and 10x the activity of all but two maintainers/TSC members](https://github.com/Homebrew/brew/graphs/contributors)) don't want to do this work or, moreso, don't want to use types for the new features I write for Homebrew/brew: do we think it's fair that I'm compelled to do so?

I'm willing to compromise to an extent on this (and anything) and I'm willing to defer to whatever the TSC votes for when we reach the end of this discussion but I would ask that the TSC factors in such things when voting and whether it's likely (as I think it is for me, I'm afraid) to have a chilling effect on new feature development and improvements in Homebrew/brew.

**Comment by fxcoudert** [comment]
> Has this come from detailed evaluation of user needs and this being the best way of solving them or just that it seems cool/interesting/fun?

I believe this is a key point. Are we sure that we are trying to fix something, and what is it? What is our estimate of the benefit/cost ratio?

**Comment by reitermarkus** [comment]
> "Subtle bugs" or "bugs that affect end-users"? Bugs that are not visible to end-users are not worth dedicating time to fix until you have a 0️⃣ backlog (which Homebrew does not).

You cannot really differentiate bugs between subtle and user-facing, some will be in private, some in public APIs. As for it being worth fixing subtle bugs only when there is 0 backlog: No one is obliged to work on the backlog so whether or not it is worth it to fix bugs not on the backlog is irrelevant.

> Are we sure that we are trying to fix something, and what is it?

The main point here I think is that having type-checking will prevent these subtle bugs from being introduced into the codebase in the first place. (Think of pretty much any issue caused by a “method not found for `NilClass`” error, for example.)

> What is our estimate of the benefit/cost ratio?

Maintainers not interested don't have to add annotations except for in files which are already fully typed, in which case they will already have some context by looking at the existing signatures. I also don't think it's a bad thing having to think a bit harder about what exactly you want as parameters and return value for a new method, I think it will be quite beneficial to code quality.

> I think adding types might actually make it easier to read for some people.

I very much agree. Just by looking at the signature you can quickly get an idea of what a method does.

**Comment by MikeMcQuaid** [comment]
> You cannot really differentiate bugs between subtle and user-facing, some will be in private, some in public APIs. 

`@mxcl` stated to me early on in this project "it's not worth fixing speculative bugs in Homebrew" i.e. non-user facing bugs that users aren't hitting when we have large numbers of bugs/issues that users do hit. A private API that never receives invalid input from any calling function could be updated to be stricter but this is generally not a good use to time.

> As for it being worth fixing subtle bugs only when there is 0 backlog: No one is obliged to work on the backlog so whether or not it is worth it to fix bugs not on the backlog is irrelevant.

It's clearly not irrelevant to me, is it? 

@reitermarkus I'm not sure you realise this but to be explicit: both your tone in these conversations and the way in the repeated opportunities to bring others in to override my viewpoints I find offensive and, at this point, hurtful. It's damaging to our working relationship on this project and I'm really not sure what for.

You're correct that no-one is obliged to work on the backlog (although I would question the motivation of maintainers who do not consider it when choosing what to work on). Relatedly, who should be obliged to write typed code? 

> The main point here I think is that having type-checking will prevent these subtle bugs from being introduced into the codebase in the first place. (Think of pretty much any issue caused by a “method not found for `NilClass`” error, for example.)

I am as-of yet unconvinced that either these bugs will be fixed before we have 100% type-checked code or that this would be a better use of time than e.g. better unit tests, fixing these bugs when they appear or writing code more defensively in the first place.

> I also don't think it's a bad thing having to think a bit harder about what exactly you want as parameters and return value for a new method, I think it will be quite beneficial to code quality.

Given Ruby is not a strongly-typed language: I think there's both benefits and overhead to this.

**Comment by MikeMcQuaid** [comment]
It's been a week so I think it would be good to bring this to a vote from each of the @Homebrew/tsc members in the next week. Please reply to each of these with a 👍🏻 or 👎🏻 with an explanation of your position if desired. I'll start in the comment immediately following this.

> * Should Homebrew aim to add type information for all Homebrew/brew Ruby files?
> * Should Homebrew aim to enable type checking at `brew` runtime?
> * Should Homebrew/brew use separate RBI files for storing type information or should these be stored inline?
> * Should missing types on new files cause a CI failure which requires them to be added?

**Comment by MikeMcQuaid** [comment]
> * Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

No 👎🏻 

We should aim to add type checking information only to public, documented methods (e.g. `Formula`, `Utils`) to ensure that we can check these but without adding overhead to improving and refactoring Homebrew internals. Adding them to all files adds overhead to maintainers who do not wish to use types at all (such as myself) and new contributors who aren't used to types or types in Ruby.

> * Should Homebrew aim to enable type checking at `brew` runtime?

No 👎🏻

We should enable it during `brew tests` unit testing but otherwise not. We could provide a documented, opt-in environment variable for maintainers who wish to use it. The potential performance overhead for users is not worth it.

> * Should Homebrew/brew use separate RBI files for storing type information or should these be stored inline?

Yes 👍🏻 

We should use separate RBI files to avoid maintainers or contributors unfamiliar with types in Ruby (or at all) to have to understand and read Sorbet documentation to be able to understand our code. This is even more relevant given that we should not use types at runtime so these definitions are a no-op for all users running this code. Having them in separate files and this enforced by CI allows the benefit of having type information and this being correctly enforced without providing confusion to maintainers and contributors.

> * Should missing types on new files cause a CI failure which requires them to be added?

No 👎🏻 

Given that we should not add type information to all Homebrew/brew Ruby files we should not assume that new files will require types to be added. A compromise could be, if possible, that publicly documented new classes (e.g. helpers to be used in formulae) do require types.

**Comment by iMichka** [comment]
> * Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

Yes 👍🏻

> * Should Homebrew aim to enable type checking at brew runtime?

No 👍🏻

> * Should Homebrew/brew use separate RBI files for storing type information?

No 👍🏻

> * Should missing types on new files cause a CI failure which requires them to be added?

Yes 👍🏻

I gave my opinion above so not writing it again :)

**Comment by fxcoudert** [comment]
> Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

No 👎 
I am concerned that this would greatly increase the barrier to contribution for newcomers, or for maintainers of other "areas" of Homebrew who do not regularly contribute to core. The fact that this is not a standard feature of the language, or dominantly used in existing codebases, makes it likely.

> Should Homebrew aim to enable type checking at brew runtime?

No 👎 
This could be enforced on CI, but definitely not for all users.

> Should Homebrew/brew use separate RBI files for storing type information?

 I am mixed on that one, so I abstain 🙊

 I would tend to be 👎  on this, but I can see that it may end up being a useful middle-ground to build consensus.

> Should missing types on new files cause a CI failure which requires them to be added?

No 👎 
This one is linked to my first vote above (_"add type information for all Homebrew/brew Ruby files"_), I believe whatever choice is made these two should be tied.

**Comment by reitermarkus** [comment]
> It's clearly not irrelevant to me, is it? 

I didn't mean irrelevant to someone personally. I meant it more like: If someone fixes a subtle bug who would not otherwise work on the backlog anyways, that's still beneficial.

> @reitermarkus I'm not sure you realise this but to be explicit: both your tone in these conversations and the way in the repeated opportunities to bring others in to override my viewpoints I find offensive and, at this point, hurtful. It's damaging to our working relationship on this project and I'm really not sure what for.

I apologize, @MikeMcQuaid, none of my comments are intended to be hurtful or disrespectful.

Let me also be explicit: I find it very demotivating when you argument your point on the basis of

- something always having been some way
- being the project leader and 
  > the person with the most commits, code changes and longest activity to Homebrew/brew and 10x the activity of all but two maintainers/TSC members

so I am not sure what else to do other than bring others in to solicit their opinions. I am sorry I offended you by doing so.

> I am as-of yet unconvinced that either these bugs will be fixed before we have 100% type-checked code

The important point is *preventing* these bugs from being introduced in the first place, which will become less likely the more code is type.

**Comment by reitermarkus** [comment]
> * Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

Yes.

> * Should Homebrew aim to enable type checking at `brew` runtime?

No.

> * Should Homebrew/brew use separate RBI files for storing type information?

No.

> * Should missing types on new files cause a CI failure which requires them to be added?

No, at least not until most/all existing files are typed.

**Comment by MikeMcQuaid** [comment]
> I didn't mean irrelevant to someone personally. I meant it more like: If someone fixes a subtle bug who would not otherwise work on the backlog anyways, that's still beneficial.

Cool, ok, yes, that makes sense.

> I apologize, @MikeMcQuaid, none of my comments are intended to be hurtful or disrespectful.
> so I am not sure what else to do other than bring others in to solicit their opinions. I am sorry I offended you by doing so.

Thanks @reitermarkus I appreciate the apology ❤️ 

> Let me also be explicit: I find it very demotivating when you argument your point on the basis of
> * something always having been some way
> * being the project leader and

Thanks for being explicit. I also apologise for demotivating you in this way and will try to do better in future.

> * > the person with the most commits, code changes and longest activity to Homebrew/brew and 10x the activity of all but two maintainers/TSC members

This wasn't intended to be "therefore I should get to decide" but something to weight the decision of the TSC as, if I'm opposed to using types but writing a significant proportion of the code, I think that should be weighed seriously. Regardless, I can see how stating it in the way I did was demotivating so, again, I apologise.

**Comment by mistydemeo** [comment]
> Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

👍 Yes.
As previously mentioned, we've actually caught some real-world bugs via type data and I'm satisfied that it's been a useful way for us to spend time.

> "Subtle bugs" or "bugs that affect end-users"? Bugs that are not visible to end-users are not worth dedicating time to fix until you have a 0️⃣ backlog (which Homebrew does not).

I actually disagree with this point! In my experience with Homebrew (and other software) subtle bugs have a tendency to combine with other subtle bugs to become weirder user-facing bugs. Catching these types of bugs early has been valuable.

When we've had type bugs slip through in the past, some of them have also ended up being pretty obvious and user-facing. Typechecking tooling is valuable for catching those before they reach a user.

> Should Homebrew aim to enable type checking at `brew` runtime?

👎  No.

I don't think this is necessary in order for us to be making the most of type data.

> Should Homebrew/brew use separate RBI files for storing type information?

👍 Yes - probably.

I don't want our type data to be seen as a burden to our users. I want it to be useful. Consequently:

1) If having inline type data makes our code hard to read, or confusing, we should keep type data in sidecar files in order to simplify interacting with it.
2) Conversely, if having sidecar type data makes it harder for developers to reason about it, we should keep type data inline.

These two points are in slight conflict - I want us to optimize for the best case here. My anticipation when we began this project in the experimental phase was that 1 was going to be the bigger blocker here, and so in the experimental phase we focused on separate RBI files.

My reading of the discussion so far is that I was too cautious in my assessment, and many Homebrew developers are willing to accept inline type annotations. As a result, my opinion has flipped: we should see that as being a positive.

> Should missing types on new files cause a CI failure which requires them to be added?

👎 

No. As a part of keeping the impact on developers low, I don't think we should make this a requirement for merging new code. I think we can get a workflow for ensuring we have regular type data in without making this a hard requirement.

**Comment by MikeMcQuaid** [comment]
> As previously mentioned, we've actually caught some real-world bugs via type data and I'm satisfied that it's been a useful way for us to spend time.

@mistydemeo Which ones? Can you link to them?

> 👍 Yes - probably.

It looks like you'll be the deciding vote on this so can I clarify that this is "👍🏻 definitely", "👎🏻 definitely" or "abstain"?

> many Homebrew developers are willing to accept inline type annotations.

I'm a bit confused as to where this comes from. I'm not seeing a clear majority in this issue from Homebrew maintainers in favour of inline type annotations (although, to be clear, if you're 👍🏻 there will be a majority of TSC members) and the majority of https://github.com/orgs/Homebrew/teams/brew members haven't voiced their opinions here (and, as it's locked, no external contributors).

**Comment by maxim-belkin** [comment]
👍 for type annotations
👎 for inline type annotations

👎 for annotating _all_ Ruby files
👎 for type checking at runtime

👍 for checking type annotations in a GitHub action (or a step in an existing action) and/or test-bot/audit with a flag
👎 for CI failures caused by missing types on new files

**Comment by reitermarkus** [comment]
>>> Should Homebrew/brew use separate RBI files for storing type information?

>> 👍 Yes - probably.

> It looks like you'll be the deciding vote on this so can I clarify that this is "👍🏻 definitely", "👎🏻 definitely" or "abstain"?

Just to clarify: This is the most important point for me.

In my point of view, maintaining two sets of files (`.rb` and `.rbi`) is not really feasible. So far the only drawback I have heard for having type information directly in Ruby files is decreased readability, which I cannot agree with because I think you can much more easily get a glance of what a method does by just looking at its signature. Also, type information in separate files is more prone to get out of sync, i.e. by having leftover type information of deleted classes/methods. Also, duplicating the complete class hierarchy in `.rbi` files is not DRY and it's definitely not efficient to work with two sets of files than with only one.

**Comment by scpeters** [comment]
> So far the only drawback I have heard for having type information directly in Ruby files is decreased readability, which I cannot agree with because I think you can much more easily get a glance of what a method does by just looking at its signature.

I haven't chimed in yet on this thread and I think everyone is making good points, but I will say as someone who has learned about ruby primarily through homebrew that on first glance before learning about sorbet I had no idea what the `T` namespace was. By looking at the diff of https://github.com/Homebrew/brew/pull/8956, I was able to see the `extend T::Sig` line was added to many classes. Searching the phrase `extend T::Sig` does mercifully lead to sorbet.org, but many other searches I tried were less helpful. If *readability* depends on one's familiarity with sorbet syntax and that inline type information could improve readability for experienced developers, perhaps we could agree that it is less *discoverable* since it is not an official part of the Ruby language? I think suitable documentation could help mitigate this, though I would recommend that it be reviewed by those with fresh eyes who are perhaps familiar with ruby but not sorbet.

**Comment by MikeMcQuaid** [comment]
> If _readability_ depends on one's familiarity with sorbet syntax and that inline type information could improve readability for experienced developers, perhaps we could agree that it is less _discoverable_ since it is not an official part of the Ruby language?

I strongly agree. 

> I think suitable documentation could help mitigate this, though I would recommend that it be reviewed by those with fresh eyes who are perhaps familiar with ruby but not sorbet.

Even in this case: it seems unusual that reading this documentation would be required before being able to understand the Homebrew codebase.

> I was able to see the `extend T::Sig` line was added to many classes. Searching the phrase `extend T::Sig` does mercifully lead to sorbet.org

Perhaps we should improve the naming here with some of our own aliases to be `Type::Signature`. Yes, it's more to type but it makes what's going on significantly clearer.

**Comment by mistydemeo** [comment]
> It looks like you'll be the deciding vote on this so can I clarify that this is "👍🏻 definitely", "👎🏻 definitely" or "abstain"?

Apologies - I didn't expect to be the tiebreaker.

I vote in favour of inline type information.

> I'm a bit confused as to where this comes from. I'm not seeing a clear majority in this issue from Homebrew maintainers in favour of inline type annotations (although, to be clear, if you're 👍🏻 there will be a majority of TSC members) and the majority of https://github.com/orgs/Homebrew/teams/brew members haven't voiced their opinions here (and, as it's locked, no external contributors).

We are not unanimous, but I am seeing support in this discussion for inline type information *if* we have a) good enough documentation, and b) we ensure that it doesn't substantially harm readability. I'm confident we can get there, and hence I'm in favour of inline type information.

In the original GSOC project, I proposed RBI files as a form of compromise - a way to integrate type information without 100% committing on the level that committing types in our code would. I believe we're now at a time where this is suitable, and if we have buy-in we should do it.

> Perhaps we should improve the naming here with some of our own aliases to be Type::Signature. Yes, it's more to type but it makes what's going on significantly clearer.

I like this. I think it's a good idea.

**Comment by MikeMcQuaid** [comment]
> * Should Homebrew aim to add type information for all Homebrew/brew Ruby files?

👎🏻x2, 👍🏻x3
Final result: 👍🏻 

> * Should Homebrew aim to enable type checking at `brew` runtime?

👎🏻x5
Final result: 👎🏻 

> * Should Homebrew/brew use separate RBI files for storing type information?

👎🏻x3, 👍🏻x2
Final result: 👎🏻

> * Should missing types on new files cause a CI failure which requires them to be added?

👎🏻x3, 👍🏻x2
Final result: 👎🏻

**Comment by MikeMcQuaid** [comment]
> We are not unanimous, but I am seeing support in this discussion for inline type information _if_ we have a) good enough documentation, and b) we ensure that it doesn't substantially harm readability. I'm confident we can get there, and hence I'm in favour of inline type information.

@mistydemeo @reitermarkus @iMichka As those in favour of inline type information: can you prioritise improving the documentation in https://docs.brew.sh/Typechecking. I'll open a dedicated issue for this.

> > Perhaps we should improve the naming here with some of our own aliases to be Type::Signature. Yes, it's more to type but it makes what's going on significantly clearer.
> 
> I like this. I think it's a good idea.

@mistydemeo @reitermarkus @iMichka Similarly, if you agree this is a good idea: please prioritise this alongside the documentation work. 

That's everything, I think. Thanks all for the discussion!

**Comment by MikeMcQuaid** [comment]
@Homebrew/plc @Homebrew/tsc Signal boosting https://github.com/Homebrew/brew/issues/11207 in this thread. TL;DR: we're currently stuck on an outdated version of Sorbet due to using an experimental feature that has since been removed.

Hopefully we can address this but this is one of the things I was worried about when we added Sorbet integration: that it would be a one-off effort that stalls and doesn't receive regular maintenance/progress.

**Comment by Bo98** [comment]
If no progress is made on #11207, I'm happy to look into it once the Perl, Go (and maybe Swift) changes are shipped.

**Comment by MikeMcQuaid** [comment]
@Bo98 Thanks, that'd be great. I'd say get all your current Homebrew/brew PRs finished/merged/closed and then pick this up then if you're still game ❤️

**Comment by Bo98** [comment]
Yep, that's basically the plan.

**Comment by MikeMcQuaid** [comment]
@Homebrew/plc @Homebrew/tsc Bump on #11207 for this thread. TL;DR: we're still currently stuck on an outdated version of Sorbet.

In future I think if you're voting on adopting a tool you should also be voting that you personally are willing to do the work to keep that tool maintained.
