### ISSUE TITLE
Don't auto update without user consent

### ISSUE THREAD

**Issue by mitranim** [Homebrew/brew#9065]
# Feature suggestion

By default, brew should not update packages without user consent.

# A detailed description of the proposed feature

By default, brew should tell you which packages have pending updates, and suggest `brew upgrade`, without actually running it. For users who prefer auto-updates, and I'm sure there are many, there should be a command to enable auto-updates.

# The motivation for the feature

Just ran `brew install fossil`, and in the process, without asking me, it upgraded many of my packages including Postgres, bringing it from 12 to 13 and breaking my workflow. I had to spend significant time looking for ways to roll back the installation (no success yet, partly due to dependencies such as `postgis`, partly due to extension files brew messed with). No, "just update!" is not a good option. Data files are incompatible, I need the same DB version we use at work, and don't want to spend time figuring out side-by-side installations.

# How the feature would be relevant to at least 90% of Homebrew users

An update that breaks your software should be considered a significant downgrade. It may not happen frequently, but when it does, people are angry.

**Comment by iMichka** [comment]
If we update things, it is by design. But we only update the necessary packages.

`fossil` depends on `openssl@1.1`.

`openssl@1.1` got an update, so when you install `fossil`, you will get the latest openssl version. We do not want to leave you with an insecure openssl version.

Of course, now, all other packages using `openssl` are broken; so we update them too (you can check that with `brew uses openssl@1.1`). `postgresql` also gets updated due to that.

So this is by design and not a bug. If this way of doing does not suit you, you can use another package manager :)

**Comment by iMichka** [comment]
Also, you can use `export HOMEBREW_NO_AUTO_UPDATE=1` to avoid the package list to be update when you run `brew install`. We recommend this if you are working in production or on a highly-critical setup you do not want to loose. You can always revert to an older git commit on the project's history, set that flag, and install old unsecured versions from there.

**Comment by MikeMcQuaid** [comment]
This is documented, necessary behaviour.

**Comment by mitranim** [comment]
Thanks for the info. Already found mentions of `HOMEBREW_NO_AUTO_UPDATE` and added it to my shell config, but it's unfortunate that this comes _after_ breakage.
