### ISSUE TITLE
Move python virtualenv dependencies to respective python formulae

### ISSUE THREAD

**Issue by iMichka** [Homebrew/brew#9435]
# Feature suggestion

# A detailed description of the proposed feature

The python.rb code contains the list of dependencies here:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb#L119-L146

This list of dependencies might be different for each python formula we have: we might even struggle one day with the need to have specific versions of these libraries based on the python version we ship.

The idea is to migrate this list of dependencies to the respective python formulae, which lets also our community update them, without us needing to release a new brew version.

The only thing I did not check is how feasible this change is, and how much refactoring it needs. So I have not looked at the real implementation of this.

# The motivation for the feature

It's easier to maintain, and makes it future-proof in case of version mismatches.

# How the feature would be relevant to at least 90% of Homebrew users

Faster delivery of library updates to our users. It's also easier to understand where these dependencies are coming from if they are defined in the formula.

# What alternatives to the feature have been considered

None

**Comment by Rylan12** [comment]
An alternative solution would be to use Python's `venv` module instead of `virtualenv`. This is built into Python versions 3.3 and later. I mentioned this a little bit in https://github.com/Homebrew/brew/pull/8873#issuecomment-704667999, but I'll repost so it's in this issue as well:

According to the [`virtualenv` docs](https://virtualenv.pypa.io/en/latest/) one should use `virtualenv` instead of the `venv` module because `venv`:
> - is slower (by not having the `app-data` seed method),
> - is not as extendable,
> - cannot create virtual environments for arbitrarily installed python versions (and automatically discover these),
> - is not upgrade-able via [pip](https://pip.pypa.io/en/stable/installing/),
> - does not have as rich programmatic API (describe virtual environments without creating them).

---

My responses:

> - is slower (by not having the `app-data` seed method),

Could be a problem, but I don't think it's significantly slower and, frankly, I don't think we're super worried about speed for installs.

> - is not as extendable,

I don't think this is an issue. We don't need lots of extra functionality or extensibility. We just need a virtual environment.

> - cannot create virtual environments for arbitrarily installed python versions (and automatically discover these),

We wouldn't need this as we always know which python version we're using.

> - is not upgrade-able via [pip](https://pip.pypa.io/en/stable/installing/),

No need. It updates along with Python, I believe. Actually, this is a positive because we don't have to manually update it.

> - does not have as rich programmatic API (describe virtual environments without creating them).
Again, I don't think this is needed for our use case.

---

Further benefits:

- No need to update these resources regularly
- Functionality is built-in to Python, so no need to install additionally resources
- No need to worry about where resource blocks live (i.e. it doesn't matter if they're in Homebrew/brew or in the formulae because they don't exist)
- No need for extra clutter in formulae

**Comment by MikeMcQuaid** [comment]
I like this idea in general but don't have anything to offer technically beyond that.



> An alternative solution would be to use Python's `venv` module instead of `virtualenv`.

This seems extremely appealing for the reasons you've stated.

**Comment by Rylan12** [comment]
I'll add investigating this to my to-do list, but it's quite full at the moment so if someone else wants to have a go, please do.

**Comment by iMichka** [comment]
I did not propose a real implementation and did not think about all the technical details. So any implementation proposal is welcome. I also do not plan to work on this in a foreseeable future myself, I have way too many other things to fix right now.

**Comment by dtrodrigues** [comment]
With https://github.com/Homebrew/brew/pull/10039 merged, there are now no `virtualenv` dependencies in `language/python.rb`.

**Comment by iMichka** [comment]
Really cool! Thanks
