### ISSUE TITLE
askpass, github errors on brew update

### ISSUE THREAD

**Issue by diversario** [Homebrew/brew#95]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

Few weeks ago I started seeing this message when running `brew update`:
```
brew update
error: unable to read askpass response from 'false'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Library/Taps/nviennot/homebrew-tmate failed!
Already up-to-date.
```
Updates are still being fetched and I can run `brew upgrade`.

**Comment by mikemcquaid** [comment]
What's your shell? Are you running Homebrew inside a script or `tmux` or over SSH or anything? Thanks!

**Comment by javian** [comment]
https://github.com/nviennot/homebrew-tmate does not seem to exist so there's nothing to download.

**Comment by diversario** [comment]
I untapped the tmate repo and error stopped 😳

**Comment by mikemcquaid** [comment]
@diversario I'd still be interested in the answers to those questions. I'd like to investigate this further even if it's not affecting you. Thanks!

**Comment by diversario** [comment]
Oh, sorry. I was about to answer that but then I deleted the tap and was, like, ¯\_(ツ)_/¯

I was manually running `brew update` in a `zsh` under `tmux`. No SSH.

**Comment by mikemcquaid** [comment]
@diversario Thanks, that'll hopefully help my reproduction; that error is not pleasant.

**Comment by mikemcquaid** [comment]
I've tried to reproduce this and failed unfortunately but will keep an eye out for more stuff like this; could be it's already been fixed accidentally.

**Comment by apjanke** [comment]
Based on the format of the error message, I suspect this is a problem with OP's local `git` configuration.

```
error: unable to read askpass response from 'false'
```

The thing in the `'...'` quotes there is the name of the program that `git` is calling to get a password. It's set by `credential.helper` in `git` configs or by (I think) the environment variable `GIT_ASKPASS`. Looks like it was configured as if it were a boolean variable controlling whether a password is asked for. But since it's actually a string value identifying a program, `git` is running the command `false`, which produces no output and exits nonzero.

I have been unable to reproduce this myself, but I haven't spent too long fiddling with the config files.

If deleting that tap fixed it, I'll bet it was either a local config setting in your cloned repo for that tap, or a `GIT_ASKPASS` env var that got set in one session and disappeared when you logged out.

Don't think this is a Homebrew problem per se.

If this happens again, look at your git config settings (both global and for the repo it happened on) and your `GIT_*` environment variables.

**Comment by UniqMartin** [comment]
> Don't think this is a Homebrew problem per se.

Have you seen [this piece of code in `update.sh`](https://github.com/Homebrew/brew/blob/b0d906f0f8d90c08b0b799d5cf0fd18bf78c30da/Library/Homebrew/cmd/update.sh#L283)? :wink: It's supposed to prevent that interactive password prompts appear during parallel fetch, which would make things very annoying when fetching a bigger number of taps … See also Homebrew/legacy-homebrew#48267.

I can reproduce the issue by simply doing the following:

```
$ git -C $(brew --repo homebrew/core) remote set-url origin https://github.com/Homebrew/homebrew-core-does-not-exist.git
$ brew update
error: unable to read askpass response from 'false'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /opt/brewery/dummy/Library/Taps/homebrew/homebrew-core failed!
Updated Homebrew from 4333bce8 to b0d906f0.
No changes to formulae.
```

This assumes that the GitHub HTTPS credentials are not in your keychain. As GitHub cannot answer whether a repository doesn't exist or is just private, it asks for credentials. If I try to update that repository manually, I'm greeted with the usual prompt:

```
$ git -C $(brew --repo homebrew/core) fetch origin
Username for 'https://github.com':
```

**Comment by apjanke** [comment]
> Have you seen this piece of code in update.sh?

Ha! I was `grep -r`ing through `Library/Homebrew and failed to give it a `-i` I guess. Sorry about that.

```
$ grep -ri askpass Homebrew
Homebrew/cmd/update.sh:  export GIT_ASKPASS="false"
```

Okay, that makes sense now.

I wonder if there's a way to serialize password prompting across the parallel git fetches using the credential helper so we can still prompt but not spew a bunch of warnings. I think I've run in to this before and simply not known what it was - though I use the `osxkeychain` helper, so I'd get spammed with dialogs instead of see spew in the terminal window.

Or maybe we could do a simple check to see if there are any (possibly) non-public repos (maybe with parallel HTTPS HEAD fetches, or just based on the standard official-repo regex pattern but allowing git/SSH transport), and then fall back to a serialized update like you suggested, of only the not-known-public ones?

**Comment by UniqMartin** [comment]
> Or maybe we could do a simple check to see if there are any (possibly) non-public repos (maybe with parallel HTTPS HEAD fetches, or just based on the standard official-repo regex pattern but allowing git/SSH transport), and then fall back to a serialized update like you suggested, of only the not-known-public ones?

I think that would create more damage than good. We nowadays keep a cache of whether a repository is private or not (see #67), but that's not useful at all in finding out whether a prompt will be needed or not. And thanks to Git's `insteadOf` URL rewriting support we can't really rely on inspecting the URLs in the `.git/config` files to make a decent decision.

**Comment by mikemcquaid** [comment]
> Have you seen this piece of code in update.sh?  It's supposed to prevent that interactive password prompts appear during parallel fetch, which would make things very annoying when fetching a bigger number of taps

I suspect this may either be Git-version dependent, just doesn't work or I didn't set it correctly.

**Comment by UniqMartin** [comment]
> I suspect this may either be Git-version dependent, just doesn't work or I didn't set it correctly.

My testing is based on the Apple-provided Git client (the one bundled with Xcode 7.3) as most users are likely to be using that (or the one from the CLTs, but that's the same version). Quite possible its integration with the Keychain and other parts of the system differs subtly from the `git` Homebrew formula I suspect you are using by default.

**Comment by apjanke** [comment]
> I suspect this may either be Git-version dependent, just doesn't work or I didn't set it correctly.

I think it's being slightly misused, or at least used in a nonintuitive way, since that variable takes a command name instead of a boolean value. But `false` is a command, and it causes this behavior. If this is intentional, might be worth putting an explanatory comment where it's being set.

From my reading of the `git` doco, this isn't version-dependent. I think we'll need to set something else if you want to avoid printing out this warning. I don't know what it is, but maybe something related to `credential.helper` instead of askpass-specific stuff. I suspect a lot of `brew` users (including myself) won't see this because they're using the `osxkeychain` credential helper instead of the `askpass` one.

But I think having a warning here, or at least some "skipped updating non-accessible tap repo foocorp/foo" progress message, is a good thing. Because it lets you know that part of the `brew update` command failed (or at least did something a user might not expect).
